### ISSUE TITLE
touch event overlap

### ISSUE THREAD

**Issue by edisonyz** [akiran/react-slick#1000]
touch event overlap, for example:  Carousel in ScorllTab , you should stopPropagation in the event method

**Comment by laveesingh** [comment]
What I get from this description is that you want separate event handler for touch event for inner elements of the carousel and they overlap with the carousel's event handler. I'm looking into that. Please let me know if you meant differently.

**Comment by edisonyz** [comment]
@laveesingh  No, react-slick is included in a scrolling tab panel and triggers the touchMove event of the tab component，Should be added in this method：
swipeMove: function swipeMove(e) { ... e.stopPropagation() }

![img1](https://user-images.githubusercontent.com/3005074/35718728-c95a86a2-0820-11e8-8fa0-0b528cc9d5ec.png)

**Comment by laveesingh** [comment]
I think that should be the way it is. BTW, you should be able to stop propagation in the wrapper of the slider.
