### ISSUE TITLE
Dynamic Sliders not loading until browser resize

### ISSUE THREAD

**Issue by sevagsim** [akiran/react-slick#1001]
I have a Slider with 5 React components.  Each React component renders an image, but it only is passed an ID as a prop, and it is responsible to look in Redux state using that ID to get the image meta data (URL, etc).

Since upgrading to React 16 and React-Slick to a React 16 compatible version, the slider images don't load until I resize my browser and then all of them load at once.

It seems the React Slick slider does not know the number of slides it will have to display before the content loads completely.

A hacky "solution" I have found that makes the images load is doing a `forceUpdate()` in componentDidMount with a setTimeout, but it seems there should be a better solution.

Any help will be appreciated, thank you.

**Comment by laveesingh** [comment]
If you could provide us with the code snippet that you're using, we could be of more help.

**Comment by sevagsim** [comment]
This ended up being a non-issue.  Related to an improper method to use react-slick for SSR.
