### ISSUE TITLE
Default setting for slider isn't aligned left

### ISSUE THREAD

**Issue by jackyef** [akiran/react-slick#1004]
On previous version (`0.16.0`), I could have the `Slider` to align left, but starting from `0.17.1`, it doesn't have the same behavior.

Picture taken from: http://neostack.com/opensource/react-slick

![image](https://user-images.githubusercontent.com/7252454/35802552-1fea752a-0aa3-11e8-9209-dd6e991b4403.png)

On my project:
`v 0.17.1`:
![image](https://user-images.githubusercontent.com/7252454/35802930-91566088-0aa4-11e8-97c1-45f0bb0e00db.png)

`v 0.16.0`:
![image](https://user-images.githubusercontent.com/7252454/35803006-cb0625a2-0aa4-11e8-9282-be11a4c5d8af.png)

Both use the same settings:
```
  const sliderSettings = {
      autoplay: false,
      autoplaySpeed: 5000,
      pauseOnFocus: true,
      pauseOnHover: true,
      dots: false,
      arrows: false,
      infinite: false,
      speed: 500,
      slidesToScroll: 1,
      draggable: true,
      swipeToSlide: true,
      variableWidth: true,
    };
```

It's as if the Slider is forcing the component to align RIGHT instead of the usual LEFT in previous version of `react-slick`. Is this intended or a bug?

**Comment by tracethompson** [comment]
+1

**Comment by rachel-rocks-at-ruby** [comment]
+1

**Comment by AndriiUhryn** [comment]
+1

**Comment by Macrovarius** [comment]
+1

**Comment by duskent** [comment]
+++

**Comment by ilyaskl** [comment]
+

**Comment by ig0rkin** [comment]
+1

**Comment by sandor0213** [comment]
+

**Comment by Shvarts** [comment]
+1

**Comment by sandor0213** [comment]
+1

**Comment by maKSiM89** [comment]
+1

**Comment by SashaKhyzhun** [comment]
+2

**Comment by stas-zozulja** [comment]
+1

**Comment by FullstackJack** [comment]
Tried `rtl: true`, that moved everything to the left, but it reversed the order and some of the items glitched and were missing/hidden.

**Comment by FullstackJack** [comment]
The problem is related to `transform` on the `slick-track`. If you turn off that CSS property, it looks correct.

**Comment by FullstackJack** [comment]
https://github.com/akiran/react-slick/commit/91199e49c2d6b07ead2fa6acef08096057cee133

That definitely has to be the problem. The track transition was rewritten and looks like it didn't account for lists with less than enough slides.

**Comment by FullstackJack** [comment]
I'd recommend rolling back to 17.1 until this is fixed.

**Comment by AdamMcCormick** [comment]
We're seeing this on v0.15.0 when we upgrade to react 16

**Comment by FullstackJack** [comment]
Ok, it's not React 16. Just tested 0.15.0 with React 16 and that looks right. The problem started in react-slick@0.17.1 with the above mentioned PR.

**Comment by tracethompson** [comment]
Also tested 0.15.0 with React 16 and it looks correct. @FullstackJack is correct, i think

**Comment by AdamMcCormick** [comment]
OK, sorry for the false alarm

**Comment by AndriiUhryn** [comment]
If I use version 0.15.0 and up to 0.17.1 I have some extra space after the last item in the slider.
If I use version from 0.17.1 and upper I have some extra space at the start, before the first item.

Is there any way to display it correctly, maybe I'm missing something?)))

**Comment by FullstackJack** [comment]
I haven't had the chance to review to algo written in trackHelper, but the transform calculation is what needs fixing. I'll take a look today if I have some time.

**Comment by AndriiUhryn** [comment]
Hi, I just wanted to ask, how many time approximately do you need to fix this bug? I am writing some new cool stuff and need this on prod.

**Comment by laveesingh** [comment]
On it!

**Comment by laveesingh** [comment]
071a29cea6e1b99f66cc49c20ed2c2e6131e3bb9

**Comment by AndriiUhryn** [comment]
@laveesingh When do you plan to release these updates?

**Comment by laveesingh** [comment]
Probably by Monday

**Comment by jackyef** [comment]
This is still happening even in 0.20.0, can we reopen this?

**Comment by mgiraldo** [comment]
happening in 0.20.0 react 16. downgrading to 0.15.0 fixed the problem.

**Comment by laveesingh** [comment]
I'm not sure if that's happening in version 0.20.0. Could someone create a working demo for this on codesandbox?

**Comment by jackyef** [comment]
@laveesingh sorry for taking so long. Here is a demo for the behavior at 0.20.0
https://codesandbox.io/s/3x7kl81pr5

**Comment by MickeyKay** [comment]
@akiran any update here? Still seeing this issue in 0.23.1

**Comment by jota12x** [comment]
Came up with this problem today. The problem is that slick-track has a margin-left:auto and margin-right:auto by default. Changing those styles to 0 solved it for me.

**Comment by icorne** [comment]
https://github.com/kenwheeler/slick/pull/2966

**Comment by shamseerahammedm** [comment]
So whats the fix for this ? stuck with the same problem ?

**Comment by AdamMcCormick** [comment]
@shamseerahammedm They (@laveesingh) closed it with a "fix" that didn't actually work. You'd probably have to re-file the ticket to get any motion on it

**Comment by rahulmawari** [comment]
.slick-list> div {    
  margin-left:0;
}

This worked for me

**Comment by p8088** [comment]
+1

**Comment by jkang0408** [comment]
+1

**Comment by lewtakm** [comment]
Whole problem is caused by infinite option. If you turn it down it will work fine.

**Comment by kevinbischof** [comment]
Still have that problem with version 0.28.1. 

> [91199e4](https://github.com/akiran/react-slick/commit/91199e49c2d6b07ead2fa6acef08096057cee133)
> 
> That definitely has to be the problem. The track transition was rewritten and looks like it didn't account for lists with less than enough slides.

Like FullstackJack wrote, it seems to be a problem with the transform in slick-track.
