### ISSUE TITLE
Slide layout switches after initial render

### ISSUE THREAD

**Issue by simonabrams** [akiran/react-slick#1005]
I'm a complete React novice, so apologies if I ask something obvious here. I have multiple carousels on a page for a portfolio site. The content is broken down by client, and each client has varying numbers of images associated with it.

When my page loads, the layout of my carousels is not correct - it seems like the `slidesToShow` and breakpoint properties aren't respected. It only corrects itself (or, rather renders how I expect it to), after I either resize the browser, or click on my home button (ie. navigate to the / route). 

Here's my (partial) setup:

```
render() {
...
const sliderOptions = {
    infinite: false,
    className: "thumb",
    slidesToShow: 3,
    slidesToScroll: 1,
    focusOnSelect: true,
    responsive: [
        { breakpoint: 10000000, settings: "unslick" },
        { breakpoint: 1681, settings: { slidesToShow: 3 } },
        { breakpoint: 801, settings: { slidesToShow: 2 } },
        { breakpoint: 414, settings: { slidesToShow: 1 } }
    ]
};

return (
    <li className={styles("container", "row")}>
        <div>
            <Slider {...sliderOptions} >
                {
                    Object.keys(media).map(key => (
                        <div key={key.toString()} >
                        <img src=/path/to/thumbnail/>
                        </div>)
                    )
                }
            </Slider>
        </div>
    </li>
    )
}
```
EDIT: This seems to be an issue in Safari/Chrome, but not in Firefox Quantum. Any suggestions would be greatly appreciated.

**Comment by laveesingh** [comment]
I just tried the same code snippet on my chrome, and it worked perfectly as expected. Please make sure you're latest versions of react-slick and chrome. 
If the issue persists, please regenerate it on codesandbox, and reopen the issue.

**Comment by JetFault** [comment]
I'm having the same issue on IE11
