### ISSUE TITLE
Slider doesn't update width without triggering component rerender.

### ISSUE THREAD

**Issue by GeorgySerga** [akiran/react-slick#1010]
The issue is the same as here pretty much: https://github.com/akiran/react-slick/issues/809 ,- without `resize` event, or any other trigger for components to rerender (modification of the props for example) the images inside slider do not adjust their size. Here is an example:
![2](https://user-images.githubusercontent.com/9346874/35949072-be200fa2-0c3d-11e8-90e6-aef4e9afc805.gif)

I took a look into this and was able to fix this using css `calc()` property, will PR soon.

**Comment by GeorgySerga** [comment]
This one should also fix all of these: https://github.com/akiran/react-slick/issues/600, https://github.com/akiran/react-slick/issues/543 .

**Comment by laveesingh** [comment]
Just add a ref in wrapper:

```
<Slider {...settings} ref={slider => this.slider = slider}> ... </Slider>
```
and doing `this.slider.innerSlider.onWindowResized()` after setting states in wrapper, should take care of the updates.

**Comment by laveesingh** [comment]
Will try to come up with a better js solution for this.

**Comment by laveesingh** [comment]
https://github.com/akiran/react-slick/commit/8591dace983fa1bc103964459ab99eaa34eed8de solves the problem. Changes will be released soon.
