### ISSUE TITLE
fade slider is losing focus, after keypress

### ISSUE THREAD

**Issue by bgaj** [akiran/react-slick#1017]
If I change slide via arrow keys in fade mode, slide changes only once and then the focus is lost.
With option fade: false
![image](https://user-images.githubusercontent.com/22592473/36258981-ff9322ec-125c-11e8-8dfc-1514f93a9a4a.png)
With option fade: true
![image](https://user-images.githubusercontent.com/22592473/36259062-3f139c80-125d-11e8-9d21-050ea5448aeb.png)

**Comment by laveesingh** [comment]
Found a way around: ec4042faf90f26b42be54ddabdf525717eb4ec00
