### ISSUE TITLE
How to center and dynamically scale images to fit slide?

### ISSUE THREAD

**Issue by fractalfrenzy** [akiran/react-slick#1022]
Hello,
I am trying to have images be centered in the slide and also scale to fit in the available space.
I've tried setting the div containing the img to display: flex and using justify-content: center.  For some reason I also need to have a div outside of that one, and then the centering works.  The problem is: when I scale the window's width to less than the image's width, I want the image to shrink and the slide to shrink with it.  Instead, the height of the slide never goes below the original image height. 

Please see this [CodeSandBox](https://codesandbox.io/s/42461o75y9) for a demonstration.  Try making the window less wide than the image to see what the problem is.

Help is appreciated.

**Comment by magicspon** [comment]
not quite right... but should point you in the right direction:
https://codesandbox.io/s/7mmmly0rv1

**Comment by laveesingh** [comment]
I think this should be a manual CSS thing as you're doing in that codesandbox demo and nothing that we should implement internally. And if you tweak a little more with that CSS code, you'll achieve whatever you're trying to.

**Comment by launchriot** [comment]
@fractalfrenzy you can use the className prop to define a custom class and then modify the css accordingly. This is how I achieved make the images smaller so that my custom arrows had more breathing room:
```
.productSlider {
  width: 100%;
  margin: 0 auto;

  .slick-slide {
    padding: 0px 75px;
  }

  .slick-next { right: 25px; }
  .slick-prev { left: 25px; }
}
```
