### ISSUE TITLE
PrevArrow doesn't work with 3 or less items (centerMode: true, slidesToShow: 3 or 2),

### ISSUE THREAD

**Issue by jdonzet** [akiran/react-slick#1025]
With this configuration and 3 or less items PrevArrow doesn't work. However, keyboard arrow do work.

const settings = {
  accessibility: true,
  centerMode: true,
  centerPadding: '0',
  infinite: false,
  variableWidth: false,
  slidesToShow: 3,
  speed: 200,
  focusOnSelect: true,
};

Workaround: I managed to go back using the method slickPrev() with custom arrows

**Comment by laveesingh** [comment]
This has been considered. If slidesToShow >= totalSlides, the slider will be unslick.

**Comment by jdonzet** [comment]
So, why arrows are shown when the the slider is in mode "unslick". That produce a weird behaviour (show 2 arrow buttons but only one works).
I'm pretty confidence there is a bug there. Never mind, the workaround saves me.
Regards.
