### ISSUE TITLE
Remove mounted state

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#1028]
https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L36
Using mounted state is code smell
https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

We should remove this state and clear all the timers in componentWillUnmount

**Comment by laveesingh** [comment]
Removed the state and we are already clearing timeouts and timers in componentWillUnmount.
bbb65e5275c1bd9ea0d99cbd656533cffc1c0208
