### ISSUE TITLE
Rails asset pipeline import doesn't work on CDN file

### ISSUE THREAD

**Issue by CodingAnarchy** [akiran/react-slick#1035]
I am in the process of updating my `react-rails` gem to the most recent version (`2.4.4`) which only supports React 16.  I updated `react-slick` as well, but it wasn't working right away.

The issue appears to be the results of this call in the asset pipeline which loads the javascript obtained from the CDN: `//= require groups/includes/react-slick.min`.

This loaded `Slider` as an object, and I had to include a `var Slider = Slider.default` call before I could use Slider.  This is a breaking change and it took me a while to discover this workaround, so I thought I would bring it up here.

**Comment by laveesingh** [comment]
We were using es5 module.exports for exporting the slider. Now we're using ES6 module export default statement.
You'll be able to use it with any of the following statements:
```
import Slider from 'react-slick'
const Slider = require("react-slick").default
```
