### ISSUE TITLE
the  pauseOnHover doesn't work when I setState in beforeChange

### ISSUE THREAD

**Issue by zhangshuaidan** [akiran/react-slick#1036]
I setState in beforeChange,but I found that the pauseOnHover doesn't work, meanwhile I found that the slickPause() and slickPlay() can't use ,it will throw err, here is my code`  const settings = {

            autoplay:true,
            infinite: true,
            pauseOnHover: true,
            fade: true,
            speed: 1000,
            autoplaySpeed: 6000,
            dots: true,
            // adaptiveHeight:true,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows:false ,// 取消左右导航

            beforeChange:(b,a)=>{
                console.log("b===>",b);
                console.log("a==>",a);
                if(a===0){
                    _this.setState({
                        carousel_title_0: "home_title animated slideInUp"
                    })
                }else{
                    _this.setState({
                        carousel_title_0: "home_title"
                    })
                }
               if(a===1){
                    _this.setState({
                        carousel_title_1:"home_title animated slideInUp",
                        home_banner_img_1:"home_banner_img"
                    })
               }else{
            
                   _this.setState({
                       carousel_title_1: "home_title",
                       home_banner_img_1:""
                   })
               }
               if(a===2){

                   _this.setState({
                       carousel_title_2: "home_title animated slideInUp",
                       home_banner_img_2:"home_banner_img"
                   })
               }else{
                   _this.setState({
                       carousel_title_2: "home_title",
                       home_banner_img_2: ""
                   })
               }

            },
            afterChange:(a)=>{
                // console.log("after_change",a);
            }
        };`

**Comment by laveesingh** [comment]
Could you take a look at this example: [SlickGoTo](https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js)
In this example, I'm setting state in both beforeChange and afterChange hook, and used a wrapper component to decide whether or not I want to update the slider Component. If the slider will update, a several props/states will be reset, so what you can do is avoid unnecessary updates.
If you cannot resolve your issue with the help of this example, please feel free to replicate the issue on codesandbox, and reopen the issue.
