### ISSUE TITLE
It does not work properly in Firefox

### ISSUE THREAD

**Issue by emilioaray** [akiran/react-slick#1037]
You just can not do slide in the browser firefox

**Comment by redhotkid123** [comment]
++1

**Comment by laveesingh** [comment]
Can you regenerate it on code sandbox and give us the link?

**Comment by selrond** [comment]
@laveesingh if the slide item contains `<a />` tag, it behaves weirdly.
https://codesandbox.io/s/7y27y70no1

**Comment by oskvortsov** [comment]
@selrond I found the next solution for this problem
Add for each link `<a href="#" onDragStart={event => event.preventDefault()}`>some text</a>

**Comment by selrond** [comment]
@oskvortsov thx, seems to work, but IMHO this should be a part of the library. 
Btw I've submitted an issue: #1316
