### ISSUE TITLE
remove setState in autoplay and pause

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#1038]
Do we need autoPlayTimer in state ?
https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js#L363

can we just use this.autoPlayTimer instead of this.state.autoPlayTimer and setState calls in autoPlay and pause methods ?

**Comment by laveesingh** [comment]
I don't think we'd need to use a state for autoplay timer. I'll analyze it.

**Comment by laveesingh** [comment]
done
