### ISSUE TITLE
Where is the CSS maintained?

### ISSUE THREAD

**Issue by robcolburn** [akiran/react-slick#104]
For a lot of folks it's probably fine to pull in a 3rd party css sheet, but not for everyone.  If you're already building out a css bundle, it's nice to just add things to the one file.  Can we maintain the css in this module somehow?  Then we can just add a reference in our css file builder.

**Comment by akiran** [comment]
We are only re-writing javascript part of [slick](https://github.com/kenwheeler/slick)
It is better to install original slick to get css. Otherwise we have to update this library every-time css in original project change.

**Comment by robcolburn** [comment]
Too bad npm peerDependencies are going away… oh well.

For others' reference
1. `npm i slick-carousel --save`
2. Add `./node_modules/slick-carousel/slick/slick.css` to css compiling script.

**Comment by vramana** [comment]
@robcolburn I have been wanting to write a flexbox based CSS solution. I will try it out this weekend.
