### ISSUE TITLE
mobileFirst not implemented yet

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#1045]

**Comment by laveesingh** [comment]
Not going to be implemented.

**Comment by macrozone** [comment]
its a petty that this isn't the default in year 2018 :-/

**Comment by pmburov** [comment]
Is this option dead? It's kinda must-have

**Comment by eddietindame** [comment]
No explanation as to why this won't be implemented? What's the deal?

**Comment by shovelend** [comment]
Would be nice to have this feature!

**Comment by tiggeymone** [comment]
Mobile first should be the default behaviour. Why isn't even implemented? Am I missing something?

**Comment by michaelCaleyWhaley** [comment]
It's wild that this isn't implemented
