### ISSUE TITLE
JavaScript warning with auto play carousel, which prevents rest of the page to render.

### ISSUE THREAD

**Issue by Mithula** [akiran/react-slick#106]
When trying to render some dynamic content than image using carousel, most of the times, I encounter following issue.

"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op."

from call stack:
play() and then
this.setState({
        animating: true,
        currentSlide: targetSlide
      }, function () {
        ReactTransitionEvents.addEndEventListener(this.refs.track.getDOMNode().children[currentSlide], callback);
      });

**Comment by vramana** [comment]
This has been fixed in #101

**Comment by akiran** [comment]
Published 0.6.7 version on npm with fix
