### ISSUE TITLE
slickGetOption and slickSetOption methods not implemented yet

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#1063]

**Comment by laveesingh** [comment]
`slickGetOption` has been implemented
`slickSetOption` will not be implemented, those effects be achieved by passing props via state from the wrapper component

**Comment by McGern** [comment]
Hi. Which release has slickGetOption been implemented?

**Comment by entiendoNull** [comment]
Is this feature possible now?

> `slickSetOption` will not be implemented, those effects be achieved by passing props via state from the wrapper component

I have tried this (among other things), but nothing seem to update the slick instance to go with autoplay. The initial values work however. If I hard code autoplay to true it will work.

`<Slider
	dots={true}
	infinite={true}
	speed={500}
	slidesToShow={1}
	slidesToScroll={1}
	autoplaySpeed={2000}
	autoplay={props.autoplay}
>
	{images}
</Slider>`

React Slick version: 0.25.2
