### ISSUE TITLE
Question: Is React Hot Loader working for you?

### ISSUE THREAD

**Issue by kjs3** [akiran/react-slick#107]
If I run my server _without_ webpack hot loading all my sliders look fine but _with_ hot loading the tag styles are off (too big) and images aren't being constrained for the initial render. HTML is rendered server side for what that's worth. 

Nudging the window size causes `initialize` to fire and everything snaps into place 

I'll keep digging into this.

**Comment by akiran** [comment]
Fixed the window resize issue in version 0.6.9.

react-hot-loading is working for our demos.
