### ISSUE TITLE
Demo page is inaccessible

### ISSUE THREAD

**Issue by danilosetubal** [akiran/react-slick#1071]
Hi guys, 
The demo page is inaccessible

> 403 Forbidden
> Code: AccessDenied
> Message: Access Denied
> RequestId: F4530403A2EF890F
> HostId: > puNAx74s7prXV+ev9MhKWw6iXwcQMR0XsxXGbr6c2Ymhb96VdOfOt79KwXDt6uhx+jqv1qSbOVk=

Thanks.

**Comment by akiran** [comment]
check here
http://react-slick.neostack.com/

**Comment by laveesingh** [comment]
The relating PR has been taken in and the change will be out soon.
