### ISSUE TITLE
Custom arrow on image not next to it

### ISSUE THREAD

**Issue by feather-aurelie** [akiran/react-slick#1072]
Hi, I love your project so far but just need help to customize it to fit my needs :)
I've read through the documents but could not find a way... Is there a way to have the nextArrow show on/in front of the image and not on its right? 
See image below for desired result:
<img width="750" alt="screen shot 2018-02-27 at 4 46 15 pm" src="https://user-images.githubusercontent.com/34015195/36756692-c7e328c6-1bdd-11e8-9e67-3797ec3eed9f.png">

**Comment by laveesingh** [comment]
You can tweak css a bit. You'll find class '.slick-next' to customize, just set `right` property.
Something like this should work:
```css
.slick-next {
    right: 25px;
}
```

**Comment by feather-aurelie** [comment]
Great, thanks @laveesingh
