### ISSUE TITLE
immediate method call beaks the slider

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#1074]
Calling `slickNext` method in componentDidMount of wrapper component, breaks the slider. This happens because it uses `slideWidth` state to calculate `trackWidth` while the `setState` statement from initialize mixin hasn't hasn't done setting `slideWidth` state due to its asynchrous nature.
Demo: https://codesandbox.io/s/k5mpm3w2or

**Comment by felixmeziere** [comment]
Hi @akiran ! I'm pretty sure the fix for this now breaks `slickPrev`, `slickNext` and`slickGoTo` methods.
