### ISSUE TITLE
Slider effect breaks when beforeChange is called

### ISSUE THREAD

**Issue by flavioalves** [akiran/react-slick#1075]
Hello Guys!

I'm having a problem with the slider effect when beforeChange event is called.

Take a look on this example:
https://codesandbox.io/s/9jp4v8y32r

If you comment line 11 it goes smooth, but if I set some state the slide transition effect broke. 

How can I get it working properly?

Thanks!

**Comment by laveesingh** [comment]
Refer to #576 and #136
