### ISSUE TITLE
Fade forces focus back to image (scrolls back to image)

### ISSUE THREAD

**Issue by crouman** [akiran/react-slick#1079]
**Issue** 
Setting fade=true will force page to jump back to image if user has scrolled image out of view.

**Repro**
Scroll page so that image is above the fold

**Expected**
Image will continue to change, but window will not move

**Actual**
Window "scrolls back" to image regardless of where user has scrolled to

https://codesandbox.io/s/2vpmnmq5vy

**Comment by laveesingh** [comment]
Thanks for pointing that out. That was some serious issue. The fix will be released soon. For now we will disable forcing to steal focus.

**Comment by crouman** [comment]
In the meantime, is there a fix for this that I can add?

**Comment by laveesingh** [comment]
This issue has already been fixed in version 0.20.0.
