### ISSUE TITLE
Window resize causes 1st slide to show up

### ISSUE THREAD

**Issue by hydrotik** [akiran/react-slick#108]
using "version": "0.6.8" in Safari 7.1.3, when I click to any of the later slides and then resize the window, the 1 slide is then shown.

**Comment by vramana** [comment]
[This commit](https://github.com/akiran/react-slick/commit/13febf4fa200d01e54f185d0c45108724fdca24e) broke things for you. Just roll back 0.6.7 till we find a solution to #100

**Comment by akiran** [comment]
@hydrotik @vramana  I will look into it today

**Comment by hydrotik** [comment]
Happening for me in 0.6.7 as well. Thanks for getting on this so fast!
