### ISSUE TITLE
Slick Children not full width on load

### ISSUE THREAD

**Issue by SCasarotto** [akiran/react-slick#1080]
On occasion, the Slider children will not load full width. Sometimes it works sometimes it loads like below. Any suggestions would be appreciated.

I am creating a portfolio page and loading content from Firebase. The page doesn't render until I have retrieved the data so I know it's not adding children late. Below you will find the Congifs, JSX, Styles used and a screenshot. 

<img width="859" alt="screen shot 2018-03-01 at 1 23 40 pm" src="https://user-images.githubusercontent.com/13336976/36865192-6b28a052-1d54-11e8-8f17-b10936acab85.png">

Configs:
```
const settings = {
	accessibility: true,
	autoplay: true,
	autoplaySpeed: 5000,
	arrows: true,
	dots: true,
	infinite: true,
	speed: 500,
	slidesToShow: 1,
	slidesToScroll: 1,
}
```
JSX:
```
<div style={styles.headerSliderContainer}>
	<Slider {...settings}>
		{images && images.map((image, index) => {
			return (
				<div key={`headerImage_${index}`} style={styles.headerImageContainer}>
					<img src={image.url} alt={`headerImage_${index}`} style={styles.headerImage} />
				</div>
			)
		})}
	</Slider>
</div>
```

Styles (Radium):
```
headerSliderContainer: {
	width: '100%',
	paddingLeft: layout.outerGutter,
	paddingRight: layout.outerGutter,

	'@media (max-width: 1000px)': {
		paddingLeft: layout.outerGutter / 2,
		paddingRight: layout.outerGutter / 2,
	},
	'@media (max-width: 800px)': {
		paddingLeft: layout.outerGutter / 3,
		paddingRight: layout.outerGutter / 3,
	},
},
headerImageContainer: {
	width: '100%',
},
headerImage: {
	width: '100%',
	height: 500,
	objectFit: 'cover',
	objectPosition: 'center'
},
```

**Comment by laveesingh** [comment]
It's most probably the problem to be solved with CSS. If you can create a codesandbox demo for the same, maybe I can help more.

**Comment by SCasarotto** [comment]
It seemed my issue was related to https://github.com/akiran/react-slick/issues/809 and resolved by https://github.com/akiran/react-slick/issues/809#issuecomment-344969721

**Comment by laveesingh** [comment]
This looks like an actual problem. I'll be working on it, please follow #809 for updates.

**Comment by SCasarotto** [comment]
Thank you @laveesingh I will also try to replicate my setup with codebox today to help assist.

**Comment by SCasarotto** [comment]
Demo: https://codesandbox.io/s/m3v7yp6o78

Info:
It looks like the primary cause of the weird render is a delay on rendering. In my setup I am waiting until I have loaded data to display the page. In this demo I simulate that with a timeout in componentDidMount. If you don't see it oddly render try refreshing a few times. 

Let me know if I can provide better information here.
