### ISSUE TITLE
Prevent setting `settings.unslick = true` when slidesToShow > available slides

### ISSUE THREAD

**Issue by silicakes** [akiran/react-slick#1084]
#### Description
In the following [segment](https://github.com/akiran/react-slick/blob/master/src/slider.js#L131) inside slider.js:

settings.slidesToShow = children.length;
```
    } else if (children.length <= settings.slidesToShow) {
      settings.unslick = true;
}
```

This behavior breaks some of the things I'm trying to achieve, however, it can easily be enforced via the configuration:

```
let slidesToshow = 4;
let {items} = this.props; //let's assume it's being updated occasionally;
let sliderConfig = {
  slidesToshow,
  unslick: items.length < slideToShow,
  ...
}
```

Like I said earlier, this shouldn't be forced on users from a point where they can't control it, and it should be removed.
What do you think?

**Comment by laveesingh** [comment]
I think if all the slides fit in a single frame, there's no need for scrolling. The same behavior is reflected by [slick](https://github.com/kenwheeler/slick/)
Anyway, with react you can always get a workaround for whatever you are trying to achieve.

**Comment by silicakes** [comment]
The thing is, you can't, unless you hack it into the source code as it tests for the entire feature with your configuration and its inner children.

I can find numerous cases where this behavior is flawed, especially where you can't promise a specific number of items but still would like to maintain a layout, such as:

![mar-06-2018 16-52-13](https://user-images.githubusercontent.com/1759539/37038973-f5d297d6-215e-11e8-9dbb-64e9e5cf3028.gif)

Currently the gif above is with `settings.unslick = true` being disabled.
If you'll enable it - current version, it won't be possible for you to scroll the first row (4).

**Comment by imornar** [comment]
Guys any update on this? I also believe that this unslick behaviour should not be forced.
