### ISSUE TITLE
Refactor to remove these lifecycle methods when possible componentWillMount, componentWillReceiveProps, and componentWillUpdate

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#1085]
componentWillMount, componentWillReceiveProps, and componentWillUpdate lifecycle methods might be deprecated in react 17
https://github.com/reactjs/react-lifecycles-compat

Try to refactor the code to prevent using these lifecycle methods when possible

**Comment by developer-lindner** [comment]
![bildschirmfoto 2018-03-07 um 09 24 48](https://user-images.githubusercontent.com/5435866/37081346-6a0b7a16-21e9-11e8-9d98-9aa5e4d5571b.png)

**Comment by laveesingh** [comment]
@developer-lindner could you elaborate a bit on this?

**Comment by akiran** [comment]
https://github.com/reactjs/react-lifecycles-compat
this polyfill make the new lifecycles work with older versions of React

**Comment by tompere** [comment]
@akiran ,
it's common and preferred for devs to wrap their app with `<StrictMode />`. Currently, my app's console log is bloated with errors in dev mode. thus making it hard to see other warnings/errors.

**Any plan on migration the effected 3 functions to new lifecycle methods?**

From briefly looking into the source it seems like there's much stateful logic (e.g. accessing `this.x`, invoking `this.setState()`, etc)... 😿
