### ISSUE TITLE
centerMode regression

### ISSUE THREAD

**Issue by python1981** [akiran/react-slick#1088]
centerMode not working in 0.20.0, fixed by reverting to 0.19.0

Instead of keeping the selected slide centered, in version 0.20.0 if less slides than slidesToShow the slides would be streched across the screen. e.g. If only 2 slides with slidesToShow=3 the two slides would each take up 50% of the screen. When selected they should highlight but not move to the center.

**Comment by laveesingh** [comment]
That is not a bug that is just a feature. We believe if all the slides are visible in a single frame, there's no point in scrolling and the [slick](https://github.com/kenwheeler/slick) reflects the same behavior.

**Comment by MichaelCastelbuono** [comment]
I had a similar issue in v0.20.0 with `slidesToShow`. I think what we're both experiencing is that are UI has drastically changed, and now the slides scale to take up more space.

**Comment by laveesingh** [comment]
We're retaining the 'unslicked' class in version 0.21.0 so you can override slides to fit your needs.
