### ISSUE TITLE
slickPause example errors 'slickPause is not a function'

### ISSUE THREAD

**Issue by goldandsilver** [akiran/react-slick#1091]
Hello,

We are really enjoying your wonderful product!

I am trying to use slickPause like you have in your example here - https://github.com/akiran/react-slick/blob/62fd5907a8ae252ebe292651ce835378cdc5019f/examples/AutoPlayMethods.js
but I am getting an error 'slickPause is not a function'.

What can I do to get it to work?

**Comment by goldandsilver** [comment]
I found that if I use this.slider.innerSlider.slickPause() it does work. Is that a proper solution?

**Comment by goldandsilver** [comment]
Actually with innerSlider it doesn't error but it also doesn't pause the auto play.
Does anyone have a solution? Or an idea of how I can troubleshoot?

**Comment by laveesingh** [comment]
If you could show us what you are trying to do, maybe a codesandbox demo, we'd be able to help more.

**Comment by laveesingh** [comment]
I guess you have resolved your problem. So I'm closing the issue.
