### ISSUE TITLE
When unslick setting is active, the slides should not receive the style.

### ISSUE THREAD

**Issue by DenisFrezzato** [akiran/react-slick#1092]
When 'unslick' setting is active, I expect that the slides won't receive the style.

Here the example: https://codesandbox.io/s/ll0kk6qooq

**Comment by DenisFrezzato** [comment]
My PR: https://github.com/akiran/react-slick/pull/1093

**Comment by laveesingh** [comment]
I don't think we're gonna do that. Slick carousel reflects the same behavior so we're gonna stick with it.

**Comment by DenisFrezzato** [comment]
Slick carousel doesn't reflect this behaviour. When unslick is active, there is no style setted to the slides. To me, it doesn't make sense that the slides would have the width calculated by Slick.

**Comment by DenisFrezzato** [comment]
So this is it? Just close this issue?

**Comment by laveesingh** [comment]
In the next release, we're retaining the 'unslicked' class for the slider. So you can override the styles in that case.
