### ISSUE TITLE
Wrong .slick-track translate on start

### ISSUE THREAD

**Issue by jedlikowski** [akiran/react-slick#1094]
Hi,
I've noticed that when using `variableWidth=true` and `infinite=false`, the position of `.slick-track` is not calculated properly. You can see on the screenshot below that the "Residential tenancy agreement" slide starts almost in the middle of the slider. I have `centerMode=false`, `slidesToShow=1`, `slidesToScroll=1`.

![image](https://user-images.githubusercontent.com/9341608/37144954-d903af84-22bf-11e8-9d3f-68cd264f899f.png)

I've identified this part of `trackHelper.js` as the source of the problem:
```
if (spec.infinite === false && targetLeft < max) {
  targetLeft = max;
}
```
This code sets the `targetLeft` to the `max` value when it should be `0` in my case. Of course `0` is less then `max`, and `max` is `399` in my case.

**Comment by laveesingh** [comment]
Commit 8b8b42c67704e855f1f907e9e256f9f8d0e75e8b should be able to resolve your issue. Changes will be released soon.

**Comment by jedlikowski** [comment]
Hi @laveesingh, any idea when this will be released? Sorry, the client is pushing quite hard.
