### ISSUE TITLE
Slider Syncing goes out of sync on continuous key press

### ISSUE THREAD

**Issue by Oliphaunte** [akiran/react-slick#1095]
Thanks a lot for this plugin, it's great work! I know the slide sync is a new feature, but just wanted to bring attention to one issue that was found. 

This issue can be tested out in the react-slick demos for Slider Syncing. If you hold down the left or right arrow keys to continuously scroll through the slider, one of the sliders will eventually go out of sync. It may need to run through the slide several times before the issue appears.

**Comment by laveesingh** [comment]
A similar issue is there, but it's not about slider syncing. If you keep pressing an arrow key on slider long enough, the second frame after the initial cycle goes in the different direction.
Please follow #1116.
