### ISSUE TITLE
Continous scrolling stops 

### ISSUE THREAD

**Issue by jmelendev** [akiran/react-slick#1096]
First and foremost, great plugin!

I am trying to achieve a continuous scrolling element like the one below

http://coolcarousels.frebsite.nl/c/23/

When i do this it starts to work with your plugin but then it stops. Here's what i mean:

https://codesandbox.io/s/1v5q7ox9oj

Any idea whats causing this and how I can fix it? Thanks

**Comment by laveesingh** [comment]
Make speed equal to autoplaySpeed and use `cssEase='linear'`.

**Comment by xnog** [comment]
it doesn't work for me, can you send me an example?

**Comment by BadMachine** [comment]
> it doesn't work for me, can you send me an example?

Same here
