### ISSUE TITLE
Slick track initial transform value incorrect. 

### ISSUE THREAD

**Issue by WinfredMa** [akiran/react-slick#1099]
The carousel settings:
    settings = {
      className: 'slider variable-width',
      infinite: false,
      variableWidth: true
    }

CodeSandBox link: https://codesandbox.io/s/ovnrkj00j9

Expectation: providing option to set initial transform value as translate3d(0px, 0px, 0px);

**Comment by ItIsMyAccount** [comment]
I have the same problem when I use 16+ version of react-slick. WIth 0.16.0 it works fine

**Comment by WinfredMa** [comment]
Yeah, I found the new issue after updating the latest version.

**Comment by laveesingh** [comment]
This problem was apparently there in version 0.20.0, but it has been fixed in dev branch.
The changes will be released soon.

**Comment by WinfredMa** [comment]
Great. Thanks.

**Comment by pmbednarczyk** [comment]
Make sure you have centerMode props set to the false. It may cause wrong slick-track position.

**Comment by veronika-martinovich** [comment]
Still reproduces for me
