### ISSUE TITLE
How to build correctly

### ISSUE THREAD

**Issue by mfclarke** [akiran/react-slick#11]
Hi,

I'm relatively new to React so this might be a stupid question, but I can't get react-slick to compile/build.

I installed with `npm install react-slick` and `bower install slick-carousel`. I've successfully installed other node components, and never had to do anything more than `npm install <component>`

I'm using gulp to build, which in turn uses webpack to build the js/jsx. The error is as follows:

`
ERROR in ./~/react-slick/lib/slider.jsx
Module parse failed: /Users/.../app/node_modules/jsx-loader/index.js!/Users/.../app/node_modules/react-slick/lib/slider.jsx Line 46: Unexpected token <
You may need an appropriate loader to handle this file type.
|     }
|     return (
|       <InnerSlider {...settings}/>
|     );
|   }
 @ ./~/react-slick/index.jsx 1:17-40
`

My webpack config is as follows:

```javascript
var webpack = require('webpack');
var UglifyJsPlugin = require('webpack/lib/optimize/UglifyJsPlugin');
var config = require('./build.configs.js');
module.exports = {
    context: __dirname + '/src',
    watch: false,
    entry: './index.jsx',
    output: {
        path: __dirname + '/' + config.targetDirectory + '/www/js',
        filename: 'bundle.js',
        publicPath: '/',
        chunkFilename: '[chunkhash].js'
    },
    resolve: {
        root: [
            __dirname + '/assets-src/bower/',
            __dirname + '/assets-src/js/',
            __dirname +'/node_modules/'
        ],
        extensions: ['', '.js', '.jsx'],
        modulesDirectories: ['assets-src/bower', 'node_modules'],
        alias: {'snapjs': __dirname + '/assets-src/bower/snapjs/snap.js',
                'spinjs': __dirname + '/assets-src/bower/spinjs/spin.js'}
    },
    module: {
        loaders: [
        { test: /\.jsx$/, loaders: ['jsx'] }
        ],
        noParse: /\.min\.js/
    },
    externals: {

    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
    ]
    };
```

Normally I need `/** @jsx React.DOM */` at the top of my jsx files, and I see react-slick doesn't have these at the top of theirs. Is this the issue? How do I get around it?

**Comment by akiran** [comment]
Which version of react are you using ?
For react 0.12,   /** @jsx React.DOM */ is not required.

react-slick requires react 0.12

**Comment by mfclarke** [comment]
My package.json lists `"react": "^0.12.1",`

**Comment by akiran** [comment]
@mfclarke react-slick uses es6/harmony features.
you have to use harmony flag with jsx loader
```js
{ test: /\.jsx$/, loaders: ['jsx?harmony'] }
```

**Comment by mfclarke** [comment]
Unfortunately that hasn't fixed it. Is there somewhere else I need to specify es6/harmony?

**Comment by akiran** [comment]
You webpack config seem ok. I couldn't find the problem.

Are you seeing this error only when you import react-slick ?

Can you try babel-loader instead of jsx-loader  and see if it works ?

On Tue, Feb 17, 2015 at 7:24 PM, Maximilian Clarke <notifications@github.com

**Comment by akiran** [comment]
I added umd wrapper to dist files and made release now (0.3.2)

If you still have issues with build, you can use pre-bundled file

var react = require('react'); // This should be before importing slick 
var Slider = require('react-slick/dist/react-slick);

**Comment by mfclarke** [comment]
Yep, the error only happens if I import react-slick

babel-loader seems to work, thanks!
