### ISSUE TITLE
Unslick Feature Request

### ISSUE THREAD

**Issue by MichaelCastelbuono** [akiran/react-slick#1101]
After upgrading to v0.20.0 it seems that a few of us have encountered breaking changes in how `unslick` and `slidesToShow` works. I believe the way it's working now is that `unslick` is set to `true` if `slidesToShow > totalSlides`. So if you're wanting to list a carousel of 4 but only have 2, then your carousel will now stretch to show 2—increasing the width and height of each slide. This presents some problems for us, because we're dealing with hundreds of pages where 90% of the time we have 4 slides (so it works great), but the other 10% we have anywhere from 1 to 3 slides. So in those scenarios the layout/design drastically changes.

I have two suggestions:

1. Can we override `unslick: false`? I've tried setting that in the options but it doesn't seem to make a difference. If we could set `unslick` to `false` and allow the old behavior that would be perfect.
2. Can you provide css classes when `unslick` is `true` on the main wrapper? That way we could provide a css solution and force the slides to be the height we need.

Here are a few other issues that reference this problem:
https://github.com/akiran/react-slick/issues/982
https://github.com/akiran/react-slick/issues/1088
https://github.com/akiran/react-slick/issues/1084

**Comment by laveesingh** [comment]
In the next version(0.21.0), we're retaining the 'unslicked' class for the slider, so that you can override styles as per your needs. But the [slick](https://github.com/kenwheeler/slick) reflects similar behaviour so we can't actually disable it.
