### ISSUE TITLE
Not Scrollable when the number of slides is less than slidesToShow

### ISSUE THREAD

**Issue by miketamis** [akiran/react-slick#1102]
When the number of slides is lower than slidesToShow it no longer scrollable this means that centerMode stops working. I want the slide that is selected to be in the Center. Is there a way to make it so that it still scrolls to the so the selected slide is in the center? even when there is fewer that or equal slide to show? (In my case I have 5 slides always and want to show all 5 slides always, but with the selected one in the middle)

Here is my settings:
```js
{
            arrows: false,
            infinite: true,
            speed: 300,
            slidesToShow: 5,
            slidesToScroll: 1,
            focusOnSelect: true,
            centerMode: true
        }
```

[CodeSandBox](https://codesandbox.io/s/6w92p65vyk)

**Comment by laveesingh** [comment]
This is not a bug. This is a feature.
The slider will be `unslicked` if the `slidesToShow` >= `slideCount`.

**Comment by imornar** [comment]
This is perfectly fine, but there is no more `unslicked` class, when slider is actually unslicked

**Comment by Sorcer23** [comment]
@imornar Have you fixed problem with elements cloning?

**Comment by imornar** [comment]
Nope, had to hide it with css
