### ISSUE TITLE
Unable to distinguish between `prev` and `next` if slider has *less than or equal to* two images

### ISSUE THREAD

**Issue by nsaikiran** [akiran/react-slick#1103]
we are using *beforeChangeSlide* callback to capture if user wants to go to next or previous slide. If we have only two images then *beforeChangeSlide* will get `0` and `1` as old and new indexes when user clicks prev *and* next. I was checking the source code. Is there a way we can access *event* parameter of the *changeSlide* function? Or any other way to figure out the buttong click?

Please check the [CodeSandBox](https://codesandbox.io/s/9lq9mxjpw).

**Comment by laveesingh** [comment]
At the moment we only have two events `onSwipe` and `onEdge` which can tell you about the direction which involves swiping and not clicking on arrows. 
To check direction with arrows click, check the custom arrows example, you can temper with the onClick events of nextArrow and prevArrow to keep track of clicks and therefore the direction.
