### ISSUE TITLE
Lazy load one div ahead 

### ISSUE THREAD

**Issue by AnandhaprabhuSp** [akiran/react-slick#1104]
Currently lazy loading for sliders is available properly. But we need to **load one div ahead of current div,** means, if first div is in view port, i want to keep the second div loaded and ready to view. Same should be happen for all, if third div is in view port, fourth should get loaded. Because, Images in div are downloading after coming to view port, so for time being we are showing place holder, to avoid this, if we implemented **how much div ahead we need to lazy loading**, it will be useful.

**Comment by laveesingh** [comment]
We currently don't support such lazy offset. But commit: e0dfd32a6b88e0bcc555f243148f7383d5fc9eb5 implements progressive lazyloading as reflected by [slick](https://github.com/kenwheeler/slick).
These changes will be released soon.

**Comment by Ashkas** [comment]
That looks great. Any idea of ETA?

**Comment by laveesingh** [comment]
probably today

**Comment by laveesingh** [comment]
Progressive Lazyload has been implemented.

**Comment by timm-aym** [comment]
@laveesingh Is there any interest to support the requested feature? I am currently looking into implementing the exact same thing for a gallery in a mobile website.

There is would be wasteful to load all the images immediately.

**Comment by vaibhavi3t** [comment]
@laveesingh I think still the feature requested by @AnandhaprabhuSp is not implemented. 
I also want the same feature. I want to load the next two images from the current one which is in viewport. I didn't find any solution in the latest version 0.23.1

**Comment by bondom** [comment]
@AnandhaprabhuSp Did you switch to other library in order to be able to implement this feature?

**Comment by AnandhaprabhuSp** [comment]
@bondom  - Check this https://github.com/chidanandan/react-slick.git - Here it is working as expected.

**Comment by AnandhaprabhuSp** [comment]
> @laveesingh I think still the feature requested by @AnandhaprabhuSp is not implemented.
> I also want the same feature. I want to load the next two images from the current one which is in viewport. I didn't find any solution in the latest version 0.23.1

@vaibhavi3t  - Try this https://github.com/chidanandan/react-slick.git

**Comment by idangozlan** [comment]
Is there anyway to preload the next 1 or even 2 images ?

**Comment by AnandhaprabhuSp** [comment]
@idangozlan   - Try this https://github.com/chidanandan/react-slick.git
