### ISSUE TITLE
Previous arrow not showing

### ISSUE THREAD

**Issue by LoriKarikari** [akiran/react-slick#1105]
Hi,

First I had some issue with both arrows not showing,  but I found issue #167 and tried the suggested solutions. I ended up editing the CSS but now I can only see the next arrow. When I inspect elements or lower the opacity of the image I can see the previous arrow too but it's not clickable.

I've replicated the issue here https://codesandbox.io/s/l7l1170rz

**Comment by Mr-Chilly** [comment]
This seems to be a z-index issue:

```
.slides .slick-prev,
.slides .slick-next {
  position: absolute;
  top: 50%;
  z-index: 1;
}
```

**Comment by LoriKarikari** [comment]
Thanks it works now @Mr-Chilly
