### ISSUE TITLE
Dynamic Slides positioning breaks when switching from many slides to few

### ISSUE THREAD

**Issue by bbrooks** [akiran/react-slick#1109]
Scenario: You have two sets of slides that you can filter between using a button, just like this demo:
https://react-slick.neostack.com/docs/example/dynamic-slides, but unlike the demo imagine the second set of slides now only contains 2 slides.

When you're viewing slide 6 of Set 1, if you hit the button and switch to Set 2, Set 2 will appear for a second and then move off the screen to the left.

This only happens when you switch to a set which doesn't have a slide to match the slide from the previous set while at the same time dropping the number of slides below the number of `slidesToShow`, which in the demo is 3.

To replicate:
1. Go to https://codesandbox.io/s/0x1mj6x380
2. Advance the slideshow so that you're seeing slides 4,5,6
3. Click the 'Click to change slide count'
4. Watch as slides 1 and 2 appear, and then disappear off to the left a split second later.

Note that https://codesandbox.io/s/0x1mj6x380 is nearly identical to https://react-slick.neostack.com/docs/example/dynamic-slides with just the second set of slides changed from `[1, 2, 3, 4, 5, 6, 7, 8, 9]` to `[1, 2]`

**Comment by laveesingh** [comment]
Apparently, this was a problem in the last version. The problem has already been fixed in upcoming release. You can try it with dev branch.
