### ISSUE TITLE
Custom arrows?

### ISSUE THREAD

**Issue by abdelav** [akiran/react-slick#111]
What is the correct way to use custom arrows ?

thanks

**Comment by vramana** [comment]
I think that you need write your own css class `.slick-arrow` that will do the job I guess or your can pass  your custom react components as `prevArrow` and `nextArrow` . I think it should work, I haven't tried it though. If you have face any problems, we will help you.

**Comment by abdelav** [comment]
passing a custom component as parameter change the style pretty well, but the next event handler doesn't work

**Comment by vramana** [comment]
Can you write an example so I have something to debug on?

**Comment by danielbuechele** [comment]
This works for me:
```
const nextArrow = React.createClass({
    render() {return <div>next</div>}
});
const prevArrow = React.createClass({
    render() {return <div>prev</div>}
});

const settings = {
    nextArrow: nextArrow,
    prevArrow: prevArrow
};

<Slider {...settings} />
```

**Comment by brennanerbz** [comment]
Any update on custom arrows?

**Comment by vramana** [comment]
@abdelav The next Event handler works just props of your Custom arrow component to the actual DOM element.  

@brennanerbz Custom arrows works. Just need to declare it correctly.

**Comment by chemoish** [comment]
Do you have an example of this @vramana. 

I haven't been able to configure it correctly. https://github.com/akiran/react-slick/pull/32

**Comment by vramana** [comment]
@chemoish Let's say your custom arrow component is `CustomPrevArrow` then pass it as
`<Slider prevArrow={CustomPrevArrow} >`. This should work.

**Comment by chemoish** [comment]
Did you have a chance to read the discussion of #32?

Unless I am missing something drastic, I don't believe it works.

The end goal is to add a simple `slick-arrow` class to the buttons.

**Comment by vramana** [comment]
@chemoish Have you tried this or you are believing that it doesn't work? If it doesn't work, I can tell a fix for this.

**Comment by chemoish** [comment]
I have tried a bunch of different implementations, including but not limited to…

```jsx
var settings = {
  nextArrow: React.createClass({
    render: function () {
      return (
        <button {...this.props}></button>
      );
    }
  })
};

<Slider {...settings}></Slider>

var settings = {
  nextArrow: React.createClass({
    render: function () {
      return (
        <button class="slick-arrow" {...this.props}></button>
      );
    }
  })
};

<Slider nextArrow={...settings}></Slider>

var settings = {
  nextArrow: React.createClass({
    render: function () {
      return (
        <button class="slick-arrow"></button>
      );
    }
  })
};

<Slider {...settings}></Slider>

var nextArrow = React.createClass({
  render: function () {
    return (
      <button class="slick-arrow"></button>
    );
  }
});

<Slider nextArrow={nextArrow}></Slider>

var nextArrow = React.createClass({
  componentDidUpdate: function () {
    this.refs.next.getDOMNode().className += ' slick-arrow';
  },
  
  render: function () {
    return (
      <button ref="next" {...this.props}></button>
    );
  }
});

<Slider nextArrow={nextArrow}></Slider>

<Slider nextArrow={<button class="slick-arrow"></button>}></Slider>
```

I even copied the entire code for the `export default NextButton` inside `arrows.jsx`. No avail.

---

However, if you look at the code for...

https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx
https://github.com/akiran/react-slick/blob/master/src/arrows.jsx

> Unless I am missing something drastic, I don't believe it works.

**Comment by vramana** [comment]
> var nextArrow = React.createClass({

The name of the component has to start with a capital letter. React differentiates dom elements and React elements using this strategy. I have read about this somewhere. That may be the problem.

**Comment by msalli** [comment]
The click event wasn't working for me at first as well, but figured out that you need to pass this.props.onClick to your custom component. I think that's what @vramana was trying to say, but I didn't understand. (You can also pass {...this.props} and it works just the same.)

My code looks like this and the event is working!
```
var ProductSlider = React.createClass({

  propTypes: {
    items: React.PropTypes.array,
    slidesToShow: React.PropTypes.number,
    slidesToScroll: React.PropTypes.number,
  },


  render() {
    var settings = {
      dots: false,
      infinite: true,
      speed: 500,
      prevArrow: CustomPrevArrow,
      slidesToShow: this.props.slidesToShow,
      slidesToScroll: this.props.slidesToScroll,
      responsive: [{breakpoint: 768, settings: {slidesToShow: 1, slidesToScroll: 1}}, {breakpoint: 1024, settings: {slidesToShow: 3, slidesToScroll: 3}}]
    }

    return (
      <Slider { ...settings } >
        {this.props.items.map(i => <div>{i}</div>)}
      </Slider>
    )
  }

})

var CustomPrevArrow = React.createClass({
  render() {
    return (
      <button type="button" className="slick-prev" onClick={this.props.onClick}>What</button>
    )
  }
})
```

**Comment by chemoish** [comment]
Thats what `this.props` was doing. I was trying to override the className. Everything else is fine.

**Comment by Pave91** [comment]
What if I want to add new functionality to onClick event of arrows? Does it exist any way how to keep functionality of arrow and at the same time add my own on the top of it?

**Comment by blairanderson** [comment]
@Pave91 you can probably get away with something like this:

```javascript
var CustomPrevArrow = React.createClass({

  newFunctionality(e) {
    this.doMoreStuff()
    this.props.onClick(e)
  }

  render() {
    return (
      <button type="button" className="slick-prev" onClick={this.newFunctionality}>What</button>
    )
  }
})
```

**Comment by hafeez1042** [comment]
+1

Please add an example

**Comment by bhuten** [comment]
It worked for me finally and here is what I did:
`<Slider {...settings} prevArrow={PrevArrow}>
</Slider>`

Make sure to import your **PrevArrow** component. And in your **PrevArrow** component, return the following:
`<IconButton className="slickArrowPrev" onClick={this.props.onClick} iconClassName="fa fa-chevron-circle-left" />`

Similarly you should have **NextArrow** component. Styling the arrows is little bit of work but it should be fairly easy.

_Note: I am using font awesome for the next and prev icon_

**Comment by tuxjs** [comment]
I have tried diferent implemtations without any results,here is my code

`import React from 'react';
import Slider from 'react-slick';

const CustomArrow= React.createClass({
  render: function(){
    return(<span className="icon-angle-left"></span>)
  }
});

export default class Gallery extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {

    const sliderSettings = {
      speed: 500,
      dots: false,
      fade: true,
      arrows: true,
      prevArrow: CustomArrow,
      infinity: true
    };

    return (
      <div className="row-fluid">
        <div className="col-xs-12 gallery">
          <Slider {...sliderSettings}>
            {this.props.pictures.map((pic) => {
              return(
                  <img src={"images/" + pic.src}/>
              );
            })}
          </Slider>
        </div>
      </div>
    );
  }
};`

The browser console return this error

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

Any  Ideas???

**Comment by kasperkronborg** [comment]
@tuxjs I'm getting the same thing, and I'm following the example given by the author in the README.

A clear working example would be great.

**Comment by akiran** [comment]
Check this https://github.com/akiran/react-slick/blob/master/docs/demos.jsx#L447-L485

**Comment by miketrexler** [comment]
I had to pass in the component as JSX, rather than the component name. That is what caused the "Element type is invalid" error for me.

See the example below:

```
const NextArrow = function(props) {
  return (
    <div {...this.props}>
      <img src="/images/arrow_next.png" />
    </div>
  );
};

const PrevArrow = function(props) {
  return (
    <div {...this.props}>
      <img src="/images/arrow_prev.png" />
    </div>
  );
};

...

And in the component which renders <Slider />:

const settings = {
  arrows: true,
  nextArrow: <NextArrow />,
  prevArrow: <PrevArrow />
};

<Slider
  className="Slider"
  {...settings}>
</Slider>
```

I did not need to add an onClick handler to the arrows, that was taken care of by {...props}.

**Comment by Axelest** [comment]
Dude Cannot read property 'props' of undefined why?

**Comment by mnishiguchi** [comment]
```
function SampleNextArrow(props) {
  const {className, style, onClick} = props
  return (
    <div
      className={className}
      style={{...style, display: 'block', background: 'red'}}
      onClick={onClick}
    ></div>
  );
}

function SamplePrevArrow(props) {
  const {className, style, onClick} = props
  return (
    <div
      className={className}
      style={{...style, display: 'block', background: 'green'}}
      onClick={onClick}
    ></div>
  );
}
```

**Comment by phtn** [comment]
```
import React from 'react-slick'
import Slider from 'react-slick'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

// import custom arrow
import Next from '../assets/chevronRight.svg'`

// declare component
const Right = props => (
  <div>
    <img src={Next} onClick={props.onClick}  className='slick-next' />
  </div>
)

// slider settings 
const settings = {
  arrows: true,
  nextArrow: <Right/>
}

// main component
export default props => (
  <div>
    <Slider {...settings}>
      <div>1</div>
      <div>2</div>
    </Slider>
  </div>
)

**Comment by mustkeom** [comment]
Unfortunately It seems i am missing something.

My code looks like this

function SampleNextArrow(props) {
    const { className, style, onClick } = props;
    return (

      <div
        className={className}
        style={{ ...style, display: "block", background: "red" }}
        onClick={onClick}
      >whattt</div>
    );
  }

/*** inside default class **/
//constructor 
 this.settings = {
            customPaging: (i) => {
                return (
                  <div className="thumb">
                    <img alt="thumb" src={this.props.sliderData.slider[i].thumbnail.src} />
                  </div>
                );
            },
            dots: true,
            infinite: true,
            speed: 500,
            slidesToScroll: 1,
            slidesToShow: 1,
            nextArrow: <SampleNextArrow onClick={this.sliderHandler.bind(this)} />
        };

// and handler //
sliderHandler(dir) {
      console.log("slide moved")
    }
 
I am not getting in this sliderHandler.  

Code seems all good. Am I missing something....

**Comment by annjawn** [comment]
It's 2019 and the Arrows still cannot accept React components.

**Comment by blairanderson** [comment]
@annjawn nobody owes you anything. read through this ticket and you'll figure it out.

**Comment by annjawn** [comment]
@blairanderson Never said that anyone owed me anything, just pointing out the fact that it still doesn’t accept React components and documentation isn’t that clear. But thanks for the nice reply. I can come down to your level and respond to your hostility, but then there’d be no difference between you and me. Have a nice day!

**Comment by dharmveer97** [comment]
import React, { Component } from 'react';
import Slider from 'react-slick';
import styled from 'styled-components';

const Section = styled.div`
  background-color: #e2e3e4;
  .slick-prev:before,
  .slick-next:before {
    color: black;
  }
`;

export default class CalendarSlider extends Component {
  render() {
    const settings = {
      className: 'center',
      centerMode: true,
      infinite: true,
      centerPadding: '30px',
      slidesToShow: 3,
      speed: 500,
      rows: 1,
      slidesPerRow: 2,
    };
    return (
      <Section className="section is-normal">
        <div className="columns is-centered">
          <div className="column is-10">
            <div>
              <h1 className="title is-1 has-text-centered"> ARCHIVE </h1>
              <Slider {...settings}>
                <div>
                  <img src="/images/blog/1@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/1@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/1@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/1@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/3@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/3@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/3@2x.png" alt="" />
                </div>
                <div>
                  <img src="/images/blog/3@2x.png" alt="" />
                </div>
              </Slider>
            </div>
          </div>
        </div>
      </Section>
    );
  }
}

**Comment by xNOVA2** [comment]
still not fucking working spend 6 hours on this shit library
