### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the InnerSlider component.

### ISSUE THREAD

**Issue by fabdarice** [akiran/react-slick#1110]
Keep seeing this error in my log console when autoplay: true,

Using v0.20

**Comment by laveesingh** [comment]
If you could give us a codesandbox demo, it would be highly helpful.

**Comment by DRL9** [comment]
I encountered the problem too.  The reproduce steps is as follows:

1. Mount react-slick component on parent component, and set the `autoplay=true`
2. Unmount the parent compoent

The version is *0.20.0*

**Comment by laveesingh** [comment]
Apparently, this problem was there in version 0.20.0, but it has been fixed with the conversion of autoplay from setTimeout to setInterval. I tried it with dev branch and it works fine.
Changes will be released soon.
Thanks!

**Comment by hasankhalid** [comment]
I am getting the same error on version 0.23.1.

**Comment by mahmoudsaeed** [comment]
> I am getting the same error on version 0.23.1.

Same here. Did you manage to fix it?
