### ISSUE TITLE
[bug] unable to change slides on Infinite=false + variableWidth=true

### ISSUE THREAD

**Issue by believer-ufa** [akiran/react-slick#1111]
If you set `infinite` option to `false` and `variableWidth` to `true` - we getting unable to change slides.

Example in Codesandbox with editor: https://codesandbox.io/s/9y1w60x6po.

Just example: https://9y1w60x6po.codesandbox.io/

Reproduces at least on Google Chrome on mobile & desktop.

React-slick versions with that error: 0.19.0 & 0.20.0.

Version 0.18.1 and below works fine on my tests :)

**Comment by believer-ufa** [comment]
Also another issue in same example: on first load we see an empty space on left of first slide:

![image](https://user-images.githubusercontent.com/801727/37514354-86e6d9b8-2929-11e8-8f49-f054d33e88a1.png)

**Comment by 7thDimension** [comment]
Moreover centerMode doesn't work correctly with infinite=false + variableWidth=true (slides are not centered, last slide is sticked to right) . Version 0.16.0 and below works correctly.

**Comment by laveesingh** [comment]
PR https://github.com/akiran/react-slick/pull/1087 fixes several issues regarding variableWidth, and as I tested your code snippet on dev branch, it certainly seems to solve yours.
Changes will be released soon.
