### ISSUE TITLE
IE 11 : Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by padupuy** [akiran/react-slick#1112]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/zzloxr09mp) and provide a link to it along with the issue description

React slick does not work with IE11, when you open the website https://react-slick.neostack.com/docs/example/multiple-items/ there is a popup with an error `Object doesn't support property or method 'assign'`

<img width="1680" alt="capture d ecran 2018-03-19 a 11 13 50" src="https://user-images.githubusercontent.com/715255/37590103-84cad9e6-2b67-11e8-8c7f-a30ad8619705.png">

On CodeSandBox there is also an issue, the slider does not work too

<img width="1680" alt="capture d ecran 2018-03-19 a 11 20 39" src="https://user-images.githubusercontent.com/715255/37590147-aae7d552-2b67-11e8-88ea-aaca271a44c3.png">

**Comment by laveesingh** [comment]
The referenced commit should fix the mentioned problem.
Changes will be released soon.

**Comment by mnemanja** [comment]
I still see that error.
In effect, the slider doesn't work.
