### ISSUE TITLE
Touch Event Listener attached even if not needed

### ISSUE THREAD

**Issue by emphaticsunshine** [akiran/react-slick#1114]
Hi All, 

I have used following options:

```
touchMove: false,
swipeToSlide: false,
draggable: false,
swipe: false,
```

After these options, I still see in chrome devtools that touch event listener are attached. Is there something I am missing or it wasn't considered?

**Comment by laveesingh** [comment]
The referenced commit should resolve the issue.
Changes will be released soon.

**Comment by emphaticsunshine** [comment]
Thanks @laveesingh for fixing it.
