### ISSUE TITLE
creating a simple instafeed-carousel seems more difficult with react-slick vs. the original slick

### ISSUE THREAD

**Issue by KasperOlesen** [akiran/react-slick#1119]
I am trying to create a simple instagram-feed-carousel using instafeed.js and your library. When looking at the documentation for the original slick library (for jquery) this seems pretty straight forward by utilizing the after() function like this:

var imgFeed = new Instafeed({
      get: 'user',
      userId: '',
      clientId: '',
      accessToken: '',
      resolution: 'standard_resolution',
      template: '<img src="{{image}}" />',
      sortBy: 'most-recent',
      limit: 8,
      links: false,
      after: function () {
        $('#instafeed').slick({
          infinite: true,
          slidesToShow: 4,
          slidesToScroll: 4
        });
      }
    })

Is there a similar easy way to do it when using react and your library? I've found multiple sources online stating that "It's very easy" and "The 2 libraries work so well together" but they all lack any documentation as to how it was solved, and when I looked into "dynamic-slides" it didn't help me much.

**Comment by laveesingh** [comment]
I'm not 100% sure what you're trying to do here, but I'm assuming that you want to initialize the slider with the `after` hook of Instafeed.
Well, in a simple way, you can manage a slider state in your wrapper component. Something like the following should do:
```javascript
state = {
  sliderInitialized: false
}
renderSlider = () => {
  if (this.state.sliderInitialized) return <Slider {...settings}></Slider>
  else return <div />
}

// after hook contains a setState statement
after: this.setState({ sliderInitialized: true })
```

**Comment by KasperOlesen** [comment]
I figured that i actually dont need instafeed.js at all. Feel free to close the issue.
