### ISSUE TITLE
Webpack CSS

### ISSUE THREAD

**Issue by pagrawl3** [akiran/react-slick#112]
Hello I'm a little new to the field, and was trying webpack. Is there anyway to require the css files for the slick-slider through webpack ?

Any help would be appreciated.

Thanks!

**Comment by vramana** [comment]
What is your webpack setup? You can import css directly through your js file via https://github.com/petehunt/webpack-howto#5-stylesheets-and-images I use it all the time. (This may not be suited for production but depends on your use case though)

**Comment by vinicri** [comment]
what is the recommended for production?

**Comment by aperkaz** [comment]
Hello @vramana, any recommendation for a production environment?
Thanks :slightly_smiling_face:
