### ISSUE TITLE
Cant call setState, forceUpdate on an unmounted Component

### ISSUE THREAD

**Issue by hasankhalid** [akiran/react-slick#1124]
Hi. 

I am using React Slick along with React Bootstrap for a website and its working perfectly. However once i navigate to some other page from the page using the react slick slider, i get an error saying 

"Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the InnerSlider component"

I thought the issue was caused because when i navigated to another page, the component was unmounted but its timeout remained and tried to make an update to it's state. I thought this was caused by autoplay so i created a componentWillUnmount method to set the state of autoplay to false. The method looks like this. 

  componentWillUnmount() {
    this.setState({
      autoplay: false,
      infinte: false
    });
  }

I still am getting the error though. Can anyone help with how i should go about fixing this?

**Comment by laveesingh** [comment]
Did you take a look at #1110 ?

**Comment by hasankhalid** [comment]
Yeah its the same problem. Thanks for the help
