### ISSUE TITLE
Need to pass my class to slick-track

### ISSUE THREAD

**Issue by psingh157** [akiran/react-slick#1125]
hi, thanks for your component, but according to my requirement so I need to pass my class to slick-track component (parent component to slick-slide), is there any way to do so?

**Comment by laveesingh** [comment]
I'm afraid there's not a direct way to do that. However, you can use the className prop to pass a custom class to the slider component and then can apply styling with CSS children selectors.

**Comment by jmayergit** [comment]
> I'm afraid there's not a direct way to do that. However, you can use the className prop to pass a custom class to the slider component and then can apply styling with CSS children selectors.

using style in jsx but when passing a className prop I see the class in html but corresponding styles are not visible
