### ISSUE TITLE
Is there a way to hide the prev and next buttons with passing custom empty buttons to the component?

### ISSUE THREAD

**Issue by RoshanRIshav** [akiran/react-slick#1126]

**Comment by laveesingh** [comment]
There are several ways to hide the arrows:
Props solution
 ```javascript
arrows: false
```

CSS solution
```css
.slick-arrow {
  display: none;
}
```

But the one that you're looking for can be:
```javascript
nextArrow: <br />,
prevArrow: <br />,
```

**Comment by Augustine-cudjoe** [comment]
const settings = {
        dots: true,
        infinite: true,
         arrows:false,
        className: "center",
        centerMode: true,
        centerPadding: "60px",
        speed: 500,
        slidesToShow: 4,
        slidesToScroll: 1,
        responsive: [
            {
              breakpoint: 1024,
              settings: {
                slidesToShow: 3,
                slidesToScroll: 3,
                infinite: true,
                dots: true
              }
            },
            {
              breakpoint: 767,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 2,
                initialSlide: 2
              }
            }
            
          ]
      };
just asign false to arrows like the above code
