### ISSUE TITLE
None clear setTimeout may cause error

### ISSUE THREAD

**Issue by popo1221** [akiran/react-slick#1127]
Hi @akiran ,

I found the code on [line 111 of inner-slider.js](https://github.com/akiran/react-slick/blob/75ce01b0048ceee4d822bdb5c30f3dbfe14a46c3/src/inner-slider.js#L111)
```js
        image.onload = () => setTimeout(() => this.update(this.props), this.props.speed)
```
cause errors. If the component destroyed before the images loaded.

![image](https://user-images.githubusercontent.com/4590675/37748705-d0d71426-2dbf-11e8-9e37-3a078946ecf2.png)

**Comment by laveesingh** [comment]
f704b92477023a89813d1593da3821d834673ff7 takes care of it.
