### ISSUE TITLE
Very long slide

### ISSUE THREAD

**Issue by JikkuJose** [akiran/react-slick#1129]
Is there a way to scroll through a very long slide? Right now it bounces back to the initial position not showing the end of it thats getting clipped.

**Comment by laveesingh** [comment]
Use `touchThreshold` prop. The default value is 5, the more the value of touchThreshold, the lesser you'll have to drag to complete the swipe.

**Comment by tklkalok** [comment]
@laveesingh Is it really work? Even I have set to 10000, the slick bar still very sticky and hard for scroll.
