### ISSUE TITLE
creating slick-tab-nav

### ISSUE THREAD

**Issue by eraneran70** [akiran/react-slick#113]
I am trying to create a slick-tab-nav with costume titles. I was able to extend a carouselTab.jsx but I am not sure how the onItemClick will call the functionality  to switch slide?

carouselTab.jsx

```
    import styles from './_CarouselTab.scss';
    import React from 'react';

    let { Component, PropTypes } = React;

    export default class CarouselTab extends Component {

      static propTypes = {
        item: PropTypes.object.isRequired
      };

      onItemClick = (e) => {
        e.preventDefault();
         changeSlide('2');
      }

      render() {

        var divStyle = {
          backgroundImage: 'url(' + this.props.item.src + ')'
        };

        return (
          <div className={styles.carouselTab}  >
            <div onClick={this.onItemClick} className={styles.carouselTab__carousellink}>
                <h2>{this.props.item.tab_title}</h2>
            </div>
          </div>
        );
      }
    }
```

Thanks for any insight on this issue.

**Comment by vramana** [comment]
@eraneran70 Are you using your `CarouselTab` component as inside the `Slider` component ? I think whatever you wrote should work,  see [this example](https://github.com/akiran/react-slick/blob/master/docs/demos.jsx#L25). Can you give me more info? Can you make JSfiddle or JSBin ??

**Comment by eraneran70** [comment]
I tried placing it inside slider then I get each tab inside each slide instead in it own div. so i am publishing as follow which I guess making it outside of the scope of slider.

            render() {
              	var settings = {
              		arrows : true,
              		dots: true,
              		infinite: true,
              		speed: 300,
              		slidesToShow: 1,
              		centerMode: true,
              		tabMenu : true
                };

                return (
                  <div className={styles.carousel}>
                    <Slider {...settings}>
            		    {this.props.slides.map((item) => {
            	          return (<div>{/*Workaround for issue https://github.com/akiran/react-slick/issues/29#issuecomment-126169829*/}
            	          			<CarouselItem item={item} />
            	          		</div>);
            	        }, this)}
            	      </Slider>

            	      <div class="slick-tab-nav" id="slick-tab-menu">
            	         {this.props.slides.map((item) => {
                      	          return (
                      	          	<CarouselTab item={item} />
                      	          );
                      }, this)}

            	      </div>
                  </div>
                );
              }

**Comment by eraneran70** [comment]
Eventually used the dotsClass to control the dots as tabs. but i hop it will a feature to add to slick-react the tabs.
