### ISSUE TITLE
No longer compatible with IE 11

### ISSUE THREAD

**Issue by nihlton** [akiran/react-slick#1132]
this commit broke support for IE 11.

https://github.com/akiran/react-slick/commit/23fa13e535111d3f27d18f992579009d259b69d8#diff-84b66437c6b7a9ed244642c3423bee13

IE does not provide the method 'forEach' for object type NodeList (and indeed, this method is not part of the NodeList spec:  https://dom.spec.whatwg.org/#interface-nodelist)

I suggest converting the node list to an array, then continuing.

I see there is already a pull request to address this same issue in earlier version of Chrome:  https://github.com/akiran/react-slick/pull/1118

however, this will still present an issue in IE.

**Comment by laveesingh** [comment]
Commit: 46b10ce should fix that. This change will be released soon.

**Comment by nihlton** [comment]
Array.from isn't supported by IE (except edge)

**Comment by jmschlmrs** [comment]
Also reported in https://github.com/akiran/react-slick/issues/1138

**Comment by nihlton** [comment]
my bad.  closing as a duplicate
