### ISSUE TITLE
The introduction of less files does not work.

### ISSUE THREAD

**Issue by xiaowangmm2** [akiran/react-slick#1134]
Hello, because my project was introduced with less.
So my way of introducing it is this.
@import "~slick-carousel/slick/slick.less";
@import "~slick-carousel/slick/slick-theme.less";
but Don't work ；I checked and found a missing pattern.
.slick-initialized .slick-slide {
        display: block;
    }

**Comment by akiran** [comment]
This could be an issue with your build system.
Not a problem with this library
