### ISSUE TITLE
Is there a way to dynamically add slides to the beginning of the slides. 

### ISSUE THREAD

**Issue by Tzikas** [akiran/react-slick#1135]
I couldn't get the `onEdge` event to be fired, so I wrote my own using `beforeChange`, and was able to add more slides to the end of the slide show when I reached the right edge.  It worked nicely.  But I would also like to add more slides to the "beginning" of the slide show when I reach the left edge, but than it indexes all the way to the left and doesn't transition smoothly.  I have `infinite:false`.  Any ideas on how to do this?

**Comment by laveesingh** [comment]
You could use slickGoTo method for achieving this.
You can also use dontAnimate parameter for slickGoTo (which is in dev branch and will be released soon).

**Comment by ConneXNL** [comment]
@laveesingh I tried adding items at the beginning using this method but I get flashes most likely because of the async rendering.

**Comment by duongthienlee** [comment]
> I couldn't get the `onEdge` event to be fired, so I wrote my own using `beforeChange`, and was able to add more slides to the end of the slide show when I reached the right edge. It worked nicely. But I would also like to add more slides to the "beginning" of the slide show when I reach the left edge, but than it indexes all the way to the left and doesn't transition smoothly. I have `infinite:false`. Any ideas on how to do this?
Can you share your solution to add more slides to the end of the slide show ?
In my case, I have an array fetch from the server which creates slides through map function. 
So when I reach the right edge, swipe to the next slide or click next button, it should fetch and update the array. But the carousel doesn't move to the next slide.

**Comment by neginbasiri** [comment]
I have the same issue, I add to previous slide on fly (on click prevArrow which is a custom arrow). The slide is showing correctly however I am not getting nice slide animation when adding previous slides on fly. I'd appreciate if you have a solution to get the slide effect working for adding previous slides on fly
