### ISSUE TITLE
Create more row in Carousel

### ISSUE THREAD

**Issue by komcal** [akiran/react-slick#1137]
Is this possible to create more than 1 row in carousel ? Do you have any suggestion?
Example
![s__10264579](https://user-images.githubusercontent.com/11961997/37837253-562f7406-2ee7-11e8-9477-568beb1edf61.jpg)

When press next button move to next 4 image

**Comment by laveesingh** [comment]
This feature is not yet supported, but soon this should be implemented.

**Comment by laveesingh** [comment]
Follow #1049
