### ISSUE TITLE
TypeError: images.forEach is not a function - <InnerSlider> component

### ISSUE THREAD

**Issue by fjeansilva** [akiran/react-slick#1138]
Hi everyone, I'm getting the following error when I run my application on the ipad:

**_TypeError: images.forEach is not a function. (In 'images.forEach', 'images.forEach' is undefined)
InnerSlider_componentDidUpdate_**

Debugging the code it renders the component in the view, but when it executes this function it throws the error.

Only on the iPad does this happen, anyone have any idea what it could be?

![screen shot 2018-03-23 at 12 35 37](https://user-images.githubusercontent.com/8744031/37839003-238b47ae-2e98-11e8-8b2e-effd716c11b8.png)

![screen shot 2018-03-23 at 12 36 09](https://user-images.githubusercontent.com/8744031/37839028-33e9894e-2e98-11e8-9f62-41e0b111ce12.png)

**Comment by jmschlmrs** [comment]
This is the same issue as https://github.com/akiran/react-slick/issues/1132.

Some (older) browsers do not provide the method 'forEach' for NodeLists, which is the return value of document.querySelectorAll().

**Comment by fjeansilva** [comment]
Thanks @jmschlmrs, i'll close this issue.

**Comment by nihlton** [comment]
Heh, we both closed our issues.  Oops.

**Comment by laveesingh** [comment]
Although the problem should have been fixed by the latest verson 0.22 3.

**Comment by nihlton** [comment]
Are you referring to changes here? 


 https://github.com/akiran/react-slick/commit/46b10cec38df95a53dab6234e59fde1b46fc9cdb

Array.from is not supported by IE (less than edge).  This will continue to be an issue unless you've polyfilled .from()

**Comment by laveesingh** [comment]
Could you tell me if either of the following would work:
Converting to an array by spreading the NodeList object
```javascript
[...images].forEach
```
Converting to an array by the slice method from Arrays:
```javascript
Array.prototype.slice.call(images).forEach
```

**Comment by jmschlmrs** [comment]
@laveesingh, can confirm that Array.prototype.forEach.call(images, function(e){}); worked for me on IE11.

On a related note, looks like react-slick is using babel-polyfill. I'm assuming NodeList.forEach() is set to be added to that after core-js (which babel-polyfill uses) releases their V3: https://github.com/zloirock/core-js/issues/329.

**Comment by laveesingh** [comment]
The referenced commit should take care of it, the changes will be released soon.

**Comment by nihlton** [comment]
thanks :D
