### ISSUE TITLE
autoplay not working on mobile device.

### ISSUE THREAD

**Issue by puja1234** [akiran/react-slick#1139]
autoplay not working in any browser on mobile device until i click on next/previous.

* It is working fine in desktop.
* "react-slick": "0.14.11"

**Comment by laveesingh** [comment]
Please upgrade react-slick to the latest version 0.22.2.

**Comment by mataoct** [comment]
It doesn't work on mobile devices with  0.23.2

**Comment by Dailyscat** [comment]
I didn't work in version 0.25.2, but I work in version 0.22.2.
