### ISSUE TITLE
How can I move the dots at the bottom of the gallery?

### ISSUE THREAD

**Issue by only-style** [akiran/react-slick#114]
Hi, please tell me how to do move dots in the top of the gallery?

**Comment by vramana** [comment]
You can use `dotsClass` props to change the postion the dots. The default value of dotsClass is `slick-dots`. If you inspect `slick-dots` class in CSS, You can see the rule `bottom: -45px;`. You change that to `top: -45px;` now the dots will appear on top.

**Comment by Alihaider168** [comment]
Working in React
`"& .slick-dots": {
                bottom: "45px",
              },`
