### ISSUE TITLE
[iPhone Safari] Can not scroll down page when finger is on image

### ISSUE THREAD

**Issue by rousseautechnology** [akiran/react-slick#1145]
On iPhone8 and iPhone X (Safari),

Scrolling down does not work if finger is swiping down on the image area.

This is new with version 0.21.0. Rolling back to 0.20.0 fixes this issue.

**Comment by imornar** [comment]
Having same issue, using multiple carousels and scrolling is broken if finger is on carousel

**Comment by laveesingh** [comment]
Are you talking about vertical scrolling here?

**Comment by imornar** [comment]
Yes, that is correct. I have multiple vertically aligned sliders, and if you try to scroll when touching carousel image nothing happens.

**Comment by wszhi** [comment]
Having same issue too. I add a carousel in home page, but I can not scroll down this page on mobile browser:(

**Comment by laveesingh** [comment]
I am looking into it and will try to come up with something asap.

**Comment by laveesingh** [comment]
The referenced commit should take care of it, the changes will be released soon.

**Comment by corey-tock** [comment]
This is still broken for me in 0.23.1

**Comment by immyweb** [comment]
This is also broken for me. Using 0.23.1

**Comment by CreatiCoding** [comment]
OK, I found solution at another issue. #1190. thx.

**Comment by schuylr** [comment]
@laveesingh This is also broken for me in v0.23.1. Do we need to file a new issue? The other solutions are hacky.

**Comment by bsturdivan** [comment]
For those still looking for a solution to this, setting `pointer-events: none` on the `img` fixes this.

**Comment by YuChungWang** [comment]
This issue also happened in Redmi Note 3 too, by using v0.25.2
Thanks for @bsturdivan solution, it's work for me
