### ISSUE TITLE
Dependency create-react-class error

### ISSUE THREAD

**Issue by jeshio** [akiran/react-slick#1148]
After install and import react-slick I getting this error:

![2018-03-27_09-31-02](https://user-images.githubusercontent.com/1515657/37946956-d951bc60-31a1-11e8-9695-2cc0531dd02e.png)

I go to `node_modules/create-react-class/index.js` and see that's empty with 2 space strings.
If clear this strings, all good works.

What is it? 

My package react-slick version is `^0.22.3`

**Comment by laveesingh** [comment]
We don't depend upon `create-react-class` anymore. This will be removed from the dependency list. However, this should not be a concern related to the library itself.
