### ISSUE TITLE
Dynamically Animation

### ISSUE THREAD

**Issue by maxval94** [akiran/react-slick#1149]
Hi,
I want to change animation (fade & vertical) dynamic with select live demo https://codesandbox.io/s/qqp206758q
When select fade or other option the slider is crash.
How i fix this problems?
Thanks!

**Comment by laveesingh** [comment]
I don't think the slider crashes at all. It's just that we just discovered that we have a bit of a problem in vertical scrolling with images. We are looking into it and will try to come up with a solution asap.

**Comment by maxval94** [comment]
Sorry, it don't crash, but the image is hide hire is the record http://jmp.sh/eYqrxMF

**Comment by laveesingh** [comment]
The Referenced commit takes care of it and changes will be released soon.

**Comment by maxval94** [comment]
Good work, thanks!
