### ISSUE TITLE
In iOS v8 safari iPhone 6 images is not a function 

### ISSUE THREAD

**Issue by Xurma2** [akiran/react-slick#1151]
I think need to add something like this 
`var images = document.querySelectorAll('.slick-slide img');
  if(images) {
        images.forEach(function (image) {
          if (!image.onload) {
            image.onload = function () {
              return setTimeout(function () {
                return _this3.update(_this3.props);
              }, _this3.props.speed);
            };
          }
        });
      }`

**Comment by laveesingh** [comment]
The referenced commit takes care of similar issues.
