### ISSUE TITLE
Does it can continue autoplay when hover on slides?

### ISSUE THREAD

**Issue by wszhi** [akiran/react-slick#1153]
Step: 
1. I created a carousel and set it autoplay.
2. I hover on slides, it will pause autoplay.
3. I mouse out slides, it will continue autoplay.
4. I set pauseOnHover to false, and try step2 again, it will pause autoplay.
Question:
Is there any way to make slides always autoplay? Even if I hover on the slides.

**Comment by laveesingh** [comment]
I'm not sure if that's the case. I just checked again and it works as expected. Could you give a demo snippet, probably on codesandbox to justify your statement?

**Comment by laveesingh** [comment]
The latest version doesn't have the mentioned issue.

**Comment by wszhi** [comment]
I'm sorry, it works.

I use react, and set pauseOnHover="false" which it the wrong way to set value.
I change code to pause OnHover={false}, it works.

**Comment by Harshit9456** [comment]
> Step:
> 
> 1. I created a carousel and set it autoplay.
> 2. I hover on slides, it will pause autoplay.
> 3. I mouse out slides, it will continue autoplay.
> 4. I set pauseOnHover to false, and try step2 again, it will pause autoplay.
>    Question:
>    Is there any way to make slides always autoplay? Even if I hover on the slides.

yes you should to add another property in your object autoplay: true
instead of pauseOnHover
