### ISSUE TITLE
Removed a line of code from track.js in your release.

### ISSUE THREAD

**Issue by virajs07** [akiran/react-slick#1155]
Hey guys,

In your 0.15 version there was an issue with fade property and it was fixed in 0.18. But a line of code has been removed from 0.20 version from track.js file which is:

   style.visibility = (spec.currentSlide === spec.index) ? 'visible' : 'hidden';

Due to this the fade property fix has not been proper. Please add that as we are using your component on our website and currently we have to modify node_modules before the build.

**Comment by laveesingh** [comment]
@virajs07  that code was causing issues related to focus loss. But you can use some styling in the wrapper to achieve the same functionality.
