### ISSUE TITLE
Issue with using variableWidth and centerMode

### ISSUE THREAD

**Issue by ankit-casaone** [akiran/react-slick#1156]
Hello React Slick Team

I must say that this is a great slider and I really appreciate all the hard work that you guys have done to build this amazing product. But right now I am facing a strange issue while using the variableWidth.

I have a slider with the following options:
        {
            arrows={false}
            centerMode
            infinite
            slidesToShow={1}
            slidesToScroll={1}
            variableWidth
        }

There are 9 divs in the slider. On the initial load the 1st div is in the center, the 9th partially hidden on the left and the 2nd on the right. The slider works fine until you reach the last div.
When the 8th slide is in the center and 9th is on the right, and you click on the next button, the slider jitters a little to shift the 9th div to the left and bring the 1st div in the center.

You can check this out at
https://staging.casaone.com/

Scroll to the section with the heading **Recent CasaOne Deliveries**

Please help me with this and let me know if you need some more information.
Thanks

**Comment by laveesingh** [comment]
Which version of react-slick are you using?

**Comment by ankit-casaone** [comment]
I am using version 0.19

**Comment by laveesingh** [comment]
Please update to the latest version 0.22.3. It has been fixed in the latest version.
