### ISSUE TITLE
Big number or wasted renders, performance optimisation

### ISSUE THREAD

**Issue by imornar** [akiran/react-slick#1157]
Hi guys, I noticed bad performance when rendering 30+ slick carousels on my web.
Using Perf I noticed big amounts of unnecessary/wasted render triggers:
<img width="1218" alt="screen shot 2018-03-28 at 22 40 21" src="https://user-images.githubusercontent.com/9463015/38055453-0ac17aae-32da-11e8-8fb6-8fc791a2e954.png">

It might be good idea to add couple `shouldComponentUpdate` methods or use `PureComponent` where applicable.

Thanks so much for this great library.

**Comment by laveesingh** [comment]
Referenced commit solves the problem.
