### ISSUE TITLE
it doesn't work in IE browser, don't support Array.from methods?

### ISSUE THREAD

**Issue by ipip2005** [akiran/react-slick#1161]
Open this as an re-open of #1142 

react-slick doesn't work in IE and it complains about Array.from

**Comment by laveesingh** [comment]
This should be fixed in release 0.23.0, which is expected to happen anytime today.

**Comment by akiran** [comment]
Released 0.23.0

**Comment by franjohn21** [comment]
Looks like we are still using `Array.from` here which breaks IE11. https://github.com/akiran/react-slick/blob/5591aab45d6c9fdc62e25fdfcf81d0c84d60764c/src/utils/innerSliderUtils.js#L520

Should this issue be reopened?
