### ISSUE TITLE
Running into problems when trying to get hundreds of slides / or dynamic slides to work

### ISSUE THREAD

**Issue by ConneXNL** [akiran/react-slick#1168]
I am trying make a react-slick with a couple hundred children and running into problems.

I tried using the lazyload but it seems to create hundreds of empty divs making the intial mounting very slow (an improvement could be to only render a single div with the combined with of all 'yet-to-be-loaded' divs).

Additionally, lazyload doesn't seem to unload items which makes the HTML to slide bigger and bigger once you start sliding in one direction.

After giving up on lazyload, I tried to make things performant by only passing the children of the 2 left and right items of the current item (using centered mode). I made a listener for the afterChange event and re-render the component with the children. 

Since it might add slides before and after the initial 5 children, I have to reset the current active frame to frame '2' (the middle frame) at the same time I am passing the new children.

I am trying to do this with slickGoTo(2, true) in the afterChange (which also causes the re-render for the children). However, the result is a flickering slide. It seems that react-slick re-renders with the `previous transform` still there, before slickGoTo actually kicks in and resets the slider to the new start axis.

Another problem seems to be that slickGoTo(2, true) does trigger beforeChange/afterChange etc. What I really need is a way to **reset** Slick to its initialSlide without any animation or triggers.

Are there any ways to get this to work?

If it's possible to truly work with dynamic children than a working example would be awesome!

**Comment by baharev** [comment]
@ConneXNL Having the same issue here. Did you manage to resolve it? Or did you give up on `react-slick`?

**Comment by ConneXNL** [comment]
Sadly I gave up and built something specifically for my use case.

**Comment by baharev** [comment]
@ConneXNL Sorry to hear that. :( Apparently that's what I will have to do too... In any case, thanks for the info!

**Comment by hariria** [comment]
I would be very interested in a solution to this. If there's a way to lazy load the component and then unload the component after its been viewed, it would significantly improve the performance of my use-case. (ie. imagine having 100s of images on a carousel)
