### ISSUE TITLE
Initial slide always off by one error

### ISSUE THREAD

**Issue by rossPatton** [akiran/react-slick#117]
What I mean by this is that when the component initially mounts, the translate value is always negative equal to the width of one slide, showing the cloned slide and not the actual slide.

I have some css animations I want to do for each slide as a user swipes through, but because of this error it's always one off. The 'slick-active' slide is not the one that is visible.

![offbyone](https://cloud.githubusercontent.com/assets/2379901/9742633/51444ba8-5616-11e5-90ca-effa80c2ff01.png)

In the above screenshot, the slick-cloned slide is visible, not the slick-active slide.

**Comment by vramana** [comment]
@rossPatton It's not an error. As you can see the cloned is your last slide before your actuall first slide and it is hidden with -negative translate. Which is used while `infinite` prop is set to `true`. Just set to `false`, you will not see the cloned slide. You will exactly see slides you have passed.

What version are you using? This might be an error caused by some css styling. Can you give more info??

**Comment by rossPatton** [comment]
I see that setting infinite to false 'fixes' the issue, but that is not how slick.js works. I use slick.js often, with infinite set to true, and I do not get this behavior, nor would I ever expect it.

I would expect that the carousel should start on the first slide by default regardless of whether it was infinite or not. 

What is the logic behind having it start any other way?

**Comment by vramana** [comment]
To create the illusion that there is an infinite carousel. This works rougly like this, let's say we are at slide 1 and then we press back then the track is translated to show the cloned slide with an animation which runs smoothly. Then right as the animation ends, we translateX value to show the last slide this time without any animation. So, when the next time use press back button we do translation from last slide to before last slide. 

I think there is something wrong with your settings. Can you clone this repo do `npm i && npm start` and open `localhost:8000` and report if you see any unexpected behaviour on your side? If everything works properly then your Slider is not configured properly. Everything works as expected on my system.

**Comment by webfolkcreative** [comment]
I was experiencing this same issue. I added `initialSlide: 0,` and it seemed to have corrected the issue. The initialSlide is supposed to default to 0, but with infinite set to true it seemed to ignore it and default to the first slide (-1). 

Not sure if that will be helpful to anyone, but it seems to have corrected my issue.
