### ISSUE TITLE
double items showed

### ISSUE THREAD

**Issue by AndriiUhryn** [akiran/react-slick#1171]
SliderProps: {
      slidesToShow: 2,
      infinite: true,
}

With these props if you pass to the slider only 1 item, it will show cloned one under the first slide.

![screenshot 21](https://user-images.githubusercontent.com/22635238/38370956-0428397e-38f4-11e8-96bf-68ad260ac96d.png)

**Comment by AndriiUhryn** [comment]
Hi, when can I wait for the react-slick npm update according to these issue?)

**Comment by JelenaRasic** [comment]
Is there any workaround until you update this?

**Comment by matejm91** [comment]
I'm having the same issue, @SnowDiamond's solution helped, but to give more info about this issue, I belive it happens if item number is smaller then slidesToShow
In my opinion there should be a trigger that sets infinite to false if item number is smaller than slidesToShow

**Comment by tinmar33** [comment]
You can create a state for infinite, and check if your array is enough big to put infinite on true:

`      infinite: this.state.infinite,`

```
if (yourarray.length <= 2) {
    this.setState({infinite: false})
} else {
    this.setState({infinite: true})
}
```

**Comment by michaelCaleyWhaley** [comment]
I am experiencing this problem but finding that it occurs unless the slides to show number is smaller than the item length

**Comment by tevdi** [comment]
> I am experiencing this problem but finding that it occurs unless the slides to show number is smaller than the item length

The solution provided by SnowDiamond should work.

**Comment by narendersaini32** [comment]
infinite false can do the job

**Comment by radscheit** [comment]
> infinite false can do the job

A potential quick-fix, but not a solution for the problem.

**Comment by yashas123** [comment]
I have something like this for the workaround:

```
import Slider from "react-slick";

export default function Carousel({ children }) {
  const settings = {
    dots: true,
		infinite: children.length > 4,
		slidesToShow: 4,
  };

  return <Slider {...settings}>{children}</Slider>;
```

**Comment by ImSolitude** [comment]
It's 2020 already, just fix it.

**Comment by gada121982** [comment]
I got the same problem . :(.

**Comment by MalvinJay** [comment]
Got this error and it took me precious nights to see this quick workaround provided by SnowDiamond. @React-Slick

**Comment by MarkAPhillips** [comment]
If you are using typescript and defining the type of children as ReactNode you will get an error when using `length.`

I solved this by using the following:

```
const MAX_SLIDES = 7; 
const infinite = children ? React.Children.count(children) > MAX_SLIDES : false;
  const settings = {
    dots: true,
    arrows: true,
    infinite,
    speed: 500,
    slidesToShow: MAX_SLIDES,
    slidesToScroll: MAX_SLIDES,
  };

return(<Slider {...settings}>{children}</Slider>)
```

But agree surely a fix can be put in for this?

**Comment by ashkan-pm** [comment]
This problem is there for me even with `infinite: false`. (I'm using Ant's Carousel component which uses React Slick)
This is the third unresolved issue I have run into in a single night for the simplest use case using this library :(

**Comment by LauraBeatris** [comment]
There's also another problem - What happens if there's a different value for ``slidesToShow`` for each device breakpoint? 

We would have to verify the current breakpoint and then access the ``responsive`` array settings to grab the ``slidesToShow`` value.

**Comment by SigitaD** [comment]
> There's also another problem - What happens if there's a different value for `slidesToShow` for each device breakpoint?
> 
> We would have to verify the current breakpoint and then access the `responsive` array settings to grab the `slidesToShow` value.

@LauraBeatris did you happen to find a workaround for this specific problem?

**Comment by fderen-dev** [comment]
Information about `slidesToShow` in current `responsive` is stored deep down in slick guts.
`slickRef.current.innerSlider.track.props.slidesToShow`

**Comment by samirarezai** [comment]
infinite: items.length > 3
it's the great way

**Comment by pdhung197** [comment]
> I faced with same bug, my temporary fix:
> 
> `infinite: items.length > 3`

I have to sign in to like your comment. LoL. It saved my time. `infinite = items.length > slidesToShow` (y)

**Comment by raulbarriga** [comment]
I tried implementing the items.length solution but it didn't work on my end; the .slick-cloned div still repeated the items. Thus, I just added `display: none !important;` to .slick-cloned css class which is the class that has the repeated items.

**Comment by odunet** [comment]
> > I am experiencing this problem but finding that it occurs unless the slides to show number is smaller than the item length
> 
> The solution provided by SnowDiamond should work.
```
infinite = items.length > slidesToShow
```
Thanks everyone, **SnowDiamond**'s solution above worked for me. Does anyone know when we would be getting a permanent fix to this.

**Comment by Michael-pi-max** [comment]
I was facing this issue but using map function of the same data fixed the issue for me
![image](https://user-images.githubusercontent.com/57192317/160295997-98c47c94-3a83-4389-80b4-9ed9b8e8b52f.png)

![image](https://user-images.githubusercontent.com/57192317/160295966-7232f935-91f7-4dd3-9551-d055eef13bdb.png)

**Comment by amIToan** [comment]
I also have the same problems above , just fix it !!! please

**Comment by coderguy2000** [comment]
> I have something like this for the workaround:
> 
> ```
> import Slider from "react-slick";
> 
> import Slider from "react-slick";
> 
> export default function Carousel({ children }) {
>   const settings = {
>         dots: true,
> 	infinite: children.length > 4,
> 	slidesToShow: 4,
>   };
> 
>   return <Slider {...settings}>{children}</Slider>;
> }
> ```

Thanx its work

**Comment by neharadialcode** [comment]
not working

**Comment by Nagibaba** [comment]
In my case, it was due to dynamically changing data. 
```
  <Slider {...settings}>
    {data.map((item, index) => (
      <HomeDropProxy item={item} key={index} />
    ))}
  </Slider>
```

So I added a condition:
```
{data.length > 0 && (
    <Slider {...settings}>
      {data.map((item, index) => (
        <HomeDropProxy item={item} key={index} />
      ))}
    </Slider>
)}

**Comment by johnnyrwest** [comment]
2023 and still running into this issue—thank you @SnowDiamond for the workaround!

**Comment by derikhunt** [comment]
Hi. I am running into a similar problem. If you set infinite to true it is duplicating the slides. The issue is making it to where I am unable to make a video play when it is shown without a duplicate copy playing in the background. The id/ref/index used are duplicated with the originals which causes the shown video to play as well as the one that is hidden and never seen. 

Is there any fix yet to prevent duplicate slides from being created when infinite scroll is true? I've tried everything to work around the issue.

**Comment by miltonbolonha** [comment]
2024

**Comment by 7Luke7** [comment]
const settings = useMemo(() => {
        return {
            speed: 200,
            infinite: productImage.length >= 7 ? true : false,
            slidesToShow: productImage.length >= 7 ? 7 : productImage.length,   
            swipe: false,
            adaptiveHeight: true,
            slidesToScroll: 1,
            arrows: false,  
            lazyLoad: true,
            responsive: [
                {
                  breakpoint: 768,
                  settings: {
                    speed: 200,
                    swipe: false,
                    infinite: productImage.length >= 3 ? true : false,
                    slidesToShow: productImage.length >= 3 ? 3 : productImage.length,   
                    adaptiveHeight: true,
                    slidesToScroll: 1,
                    arrows: false,
                    lazyLoad: true,
                  }
                },
            ]
          
        }
    })
    
    this will help set infinite and slides to show according to amount of images or items you server for example if you have less items than what you had intended to show just show all of it this way it will be less and work perfectly do the same for the infinite, this should work.(worked for me).

**Comment by Noushad-web** [comment]
I faced with same bug. Thanks @SnowDiamond for the work around.

**Comment by madhurgang** [comment]
Add - adaptiveHeight: true in sliders settings.

**Comment by MshengYang** [comment]
faced with same bug
