### ISSUE TITLE
Page scrolling doesn't work

### ISSUE THREAD

**Issue by bul-dog** [akiran/react-slick#1173]
Hi,

I installed latest version (0.23.1) on my project, slider is working perfectly but i can't vertical page scroll over the slider on IOS chrome and safari.

**Comment by danilozangari** [comment]
Same here!

**Comment by laveesingh** [comment]
The page is not supposed to be scrollable vertically when your finger is on the slider and verticalSwiping is true. Let me know if your case differs the situation.

**Comment by bul-dog** [comment]
I solved,

first of all i moved "react-slick folder" from "node_modules" to my custom folder that is name "helper" because we will update a file in that folder so it must be prevent from override by npm  update.

open "/helper/react-slick/lib/utils/innerSliderUtils.js"
and remove or comment out line 300 **"e.target.tagName === "IMG" && e.preventDefault();"**

now we must change used places 
old using:  import Slider from 'react-slider'
new using: import Slider from '/helper/react-slider'

i hope it helps you too

**Comment by imranismail** [comment]
Just chiming in that it's happening on my repo as well.

**Comment by Mrtcndkn** [comment]
For my case, I have a slider on top of my page and details on the bottom. But my image is almost getting the full width and height of the page. Therefore when you open the page from a phone on safari all viewport is almost image and then I want to be able to perform vertical scrolling on the image and still have my horizontal slider as well. Briefly when I put the horizontal slider on my page that page should be scrollable from anywhere.

**Comment by Mrtcndkn** [comment]
I'm still having this problem and couldn't find any solution besides of @bul-dog's solution. But I don't want to do that will there be a fix for this issue?

**Comment by pmgmendes** [comment]
@Mrtcndkn Check if the approach presented at [#1190](https://github.com/akiran/react-slick/issues/1190#issuecomment-390802656) fits your needs.

**Comment by bestjsguru** [comment]
Yeah, it doesn't work on my mobile phone (23.1)
How can I fix this issue? It is urgent for me.
Thanks
