### ISSUE TITLE
More consistent way for release process

### ISSUE THREAD

**Issue by maciekmpintive** [akiran/react-slick#1176]
Hey, I am working with this lib everyday. Idea behind it is awesome and I appreciate all of work especially in few last weeks. But I am missing more frequent release notes to catch the moment when and what kind of bugsfixes/changes was made. Can I ask for update on this? I promise to donate few bucks for coffee :)

**Comment by laveesingh** [comment]
I'm gonna update the changelog markdown file and draft a release.

**Comment by twgraham** [comment]
I've got to agree, I noticed there hasn't been many release notes the past version, and when I went to upgrade I noticed the entire styling for my sliders broke. At a minimum, tagging releases would be greatly appreciated!
