### ISSUE TITLE
sometimes update is called before initialize

### ISSUE THREAD

**Issue by Yuripetusko** [akiran/react-slick#118]
Sometimes `update` is called before `initialize` and `this.refs.list` in `update` function is still `undefined` resulting in javascript error cannot call `getDomNode() of undefined`. Need to add guards around update something like `if (!this.refs.list || !this.refs.track) return`

**Comment by vramana** [comment]
Can you give an example?

**Comment by Yuripetusko** [comment]
"react-slick": "^0.7.0",

```
const carouselSettings = {
      dots: false,
      infinite: false,
      centerMode: false,
      speed: 400,
      lazyLoad: false,
      slidesToShow: 1,
      slidesToScroll: 1
    };

....

<Slider {...carouselSettings}>
       <div><span>Jan 2015</span></div>
       <div><span>Feb 2015</span></div>
       <div><span>Oct 2015</span></div>
       <div><span>Nov 2015</span></div>
       <div><span>Dec 2015</span></div>
</Slider>
```

**Comment by vramana** [comment]
Are you resizing the slider or changing props?

**Comment by Yuripetusko** [comment]
I am not. what do you mean? I just refresh my page. render() fires with Slick in it, I put console lot in initialize and update in helpers.js. I can see that update is called first and initialize after

**Comment by vramana** [comment]
Can you show a screen shot of your console?? this.update is only either on componentWillRecieveProps or on window resize event.  Look [here](https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L58) and [here](https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L64) . Can you put a complete example on jsbin or js fiddle that I can work with? I am a bit lost from where exactly the problem is coming.

**Comment by Yuripetusko** [comment]
![screenshot 2015-09-09 11 22 05](https://cloud.githubusercontent.com/assets/666169/9759450/0bbc5920-56e5-11e5-9941-70a3985c73c0.png)

![Uploading Screenshot 2015-09-09 11.22.36.png…]()

**Comment by Yuripetusko** [comment]
![screenshot 2015-09-09 11 22 36](https://cloud.githubusercontent.com/assets/666169/9759468/36bacd82-56e5-11e5-954d-6f79a92abbeb.png)

**Comment by Yuripetusko** [comment]
The working setup is too complex to put on jsbin, but I will copy snippets later either here or jsbin

**Comment by vramana** [comment]
Are you using react-0.14 ? not that it matters just asking. Hey Can you clone the repo and write you example there and upload it on github. I will clone it and work on it.

Basically I want to isolate the problem. I am not able to do that on top of my head.

**Comment by vramana** [comment]
`this.initialize` and `this.update` are the shady areas of react-slick. I want to write re-everything from group up. There is too much state and imperative manipulations all over the place.
