### ISSUE TITLE
Styles overwritten on application-owned div elements

### ISSUE THREAD

**Issue by nihlton** [akiran/react-slick#1180]
demo: https://codesandbox.io/s/7yvq357xz6

for the given markup:  
```
<Slider {...settings}>
  <div style={slideStyle}>
    <img style={imageStyle} src="http://placekitten.com/g/400/200" />
  </div>
  ...
</Slider>
```
{slideStyle} will be ignored / overwritten.

**Comment by mihauko** [comment]
Are those inline styles connected to additional div wrapper like on screenshot? What is the purpose of this div?

![selection_0961](https://user-images.githubusercontent.com/15020674/38719746-d6175f3c-3ef3-11e8-98ad-abe426c2e1ef.png)

It can be also visible on @nihlton demo.

I have this structure on 0.23.1 version

**Comment by ViacheslavBurlaka** [comment]
@nihlton  have the same problem

**Comment by nihlton** [comment]
@mihauko - was wondering that as well.

I suspect that they *intended* to apply those styles to the additional div wrapper, and are applying them to the application div instead.

**Comment by nihlton** [comment]
any update on this issue?

**Comment by dhruvramdev** [comment]
Facing Same Issue.

**Comment by mopilo** [comment]
same here

**Comment by charliedavison** [comment]
+1

**Comment by tetogomez** [comment]
useful component but it's so hard to use with custom styles. :(

**Comment by charliedavison** [comment]
Ended up wrapping an extra div around everything so we could prevent our styles from being overwritten. Would be nice if this was fixed properly though.

**Comment by remingtonchan** [comment]
@charliedavison Hi, how was your approach in "wrapping everything"? I still can't get around this. 😅

**Comment by pinglinh** [comment]
Any updates on this issue? 😭

**Comment by goriverna** [comment]
As a workaround, you can use className on your div and define css class, in this way you can override css rules.
```
<Slider {...settings}>
  <div style={slideStyle} className='slick-custom'>
    <img style={imageStyle} src="http://placekitten.com/g/400/200" />
  </div>
  ...
</Slider>

```
and then create css rule on you css style:
```
.slick-custom{
    display: flex !important;
    justify-content: center;
}
```

**Comment by akiran** [comment]
Fixed in react-slick@0.25.2

**Comment by chrisneal** [comment]
@akiran We're still experiencing this issue in 0.25.2.

**Comment by manuelgomezo** [comment]
same here

**Comment by noobG** [comment]
yep still broken

**Comment by rphly** [comment]
still broken

**Comment by rphly** [comment]
Hi guys, I found a workaround for this although it's less than ideal.

You can wrap your application div with `<ul>` and the styles won't be overwritten.

Example:
```
return (
    <ul key={i}>
        {...your component here}    
    </ul> 
)
```

**Comment by abhishekashyap** [comment]
Any follow-ups? Still experiencing on 0.27.0

**Comment by tazcarper** [comment]
Still occurring in 0.27.0. Any ETA on fix?

**Comment by tazcarper** [comment]
Could this issue be because React used to require you wrapping lists with a <div> or something similar? We can use <React.Fragment> instead now and it wont add the unnecessary empty <div> within the slides. Seems like the root is around the logic creating rows per slide. Even if you have one row, it still executes this.

**slider.js**
Replace this:
`newSlide.push(<div key={10 * i + j}>{row}</div>);`

With this:
`newSlide.push(<React.Fragment key={10 * i + j}>{row}</React.Fragment>);`

**Comment by tazcarper** [comment]
Sounds like the author wants to wait until a future major change to implement this.

**Comment by templateio** [comment]
Create a component for slide and use Hooks to pass style:
Slide.js  <Slide/> : 
`
function Slide() {
  const [style, setStyle] = useState({
    backgroundImage: 'url(' + process.env.PUBLIC_URL +'/img/url.jpg)',
    backgroundRepeat: 'no-repeat'
  });

return (
    <div 
      className="..."
      style={style}
    >
        ...content...
    </div>
)
`
Hook logic will ensure that your component always stays up to date with state! https://reactjs.org/docs/hooks-state.html
if using redux global state you can use useSelector
PS inside <Slider {...settings}> you can map <Slide/>'s with Slide list component for extra fancy points

**Comment by c-jain** [comment]
I am still facing this issue with version 0.28.0. I want my `div` to have `display: flex;` but it is not working. Did anyone get the solution? currently, I am adding `!important` to fix the situation but a cleaner solution would be great. Please someone help!

**Comment by performautodev** [comment]
> I am still facing this issue with version 0.28.0. I want my `div` to have `display: flex;` but it is not working. Did anyone get the solution? currently, I am adding `!important` to fix the situation but a cleaner solution would be great. Please someone help!

You can change on node_modules\react-slick\lib\slider.js L 251

 newSlide.push( /*#__PURE__*/_react["default"].createElement(**"div"**, {
            key: 10 * i + j
          }, row));

By :
  newSlide.push( /*#__PURE__*/_react["default"].createElement(**_react["default"].Fragment**, {
            key: 10 * i + j
          }, row));

**Comment by AgainPsychoX** [comment]
Still experiencing the same issue, sadly, we need to wait for major update I guess, since `bReAkInG cHaNgEs` :C

**Comment by easyrun32** [comment]
A work around this without messing with inline-block is to just wrap it again
 ```
<Slider {...settings}>


        <div className={styles.dont_touch_wrapper}>
          <div className={styles.container_flex}>
            <div className={styles.a}>A</div>
            <div className={styles.b}>B</div>
          </div>
       </div>

</Slider/>
```

**Comment by mz3r0** [comment]
Somehow used to work, moved files to another location and suddenly got this issue. Easiest temporary fix for me was to use !important on my css.
