### ISSUE TITLE
Problem in importing Slider

### ISSUE THREAD

**Issue by mishra1947** [akiran/react-slick#1181]
### Issue

* import Slider from "react-slick"; on importing below error is coming
* Uncaught TypeError: Super expression must either be null or a function, not undefined

**Comment by glivera** [comment]
I have the same issue.
http://prntscr.com/j39ytu

**Comment by mishra1947** [comment]
I think it is happening due to cicular dpendency or due to ordering issue.

**Comment by laveesingh** [comment]
Which version of react-slick are you using?

**Comment by pluong** [comment]
I also have the same issue.  I'm using 0.23.1
