### ISSUE TITLE
Props for disabling click event on dots

### ISSUE THREAD

**Issue by sumzer** [akiran/react-slick#1186]
Is there any way of disabling dots being clickable i.e i just need dots as page indicators not allowing users to click on them to change pages.

Best regards
Sumi

**Comment by 1412108** [comment]
+ 1

**Comment by paulcredmond** [comment]
How about with CSS.

```
.slick-dots li button{
    pointer-events: none;
}
```

**Comment by 1412108** [comment]
I solved it ! thanks <3

**Comment by Dobby89** [comment]
> I solved it ! thanks <3

Care to share *how* you solved it?
