### ISSUE TITLE
Breakpoint does not re-trigger when hitting it exactly

### ISSUE THREAD

**Issue by ChrisChong** [akiran/react-slick#1188]
* Code is the same as in the [React Slick Documentation](https://react-slick.neostack.com/docs/example/responsive) and is also copied over in [CodeSandBox](https://codesandbox.io/s/qvmpr0xp74).

I was playing around with the react-slick documentation example since I need to implement breakpoints in my code and wanted to see where the breakpoint would trigger.

Steps to replicate:

1. I had my browser initially set at a width greater than 1024.
2. I shrunk my browser width to exactly 1024 and triggered the breakpoint to go from showing 4 slides to 3 slides.
3. I then re-expanded the browser back to a width greater than 1024, but the settings of showing 3 slides persisted, as shown in the screenshot below.

![react-slick-bug](https://user-images.githubusercontent.com/3466812/38745607-02445b86-3f13-11e8-9ebb-1128a24f6035.png)

I also tried this in the reverse direction (browser with of less than 1024, hit 1024 exactly, shrink browser again to less than 1024), and the settings of showing 4 slides instead of 3 persisted.

**Comment by marzelin** [comment]
This only happens at the widest breakpoint
