### ISSUE TITLE
Support for react-0.14

### ISSUE THREAD

**Issue by tarkanlar** [akiran/react-slick#119]
I am using React 1.4 
Getting this error
```Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `InnerSlider```

**Comment by vramana** [comment]
Thanks for the bug report! I'll fix it shortly.

**Comment by vramana** [comment]
@tarkanlar This issue will be fixed in #120. So, I am closing this.
