### ISSUE TITLE
focusOnSelect(true) + infinite(false) = a strange interaction

### ISSUE THREAD

**Issue by zquancai** [akiran/react-slick#1193]
When I use the following configuration, I find a strange interaction that scrolls out of range when I click to the last few.
```js
const settings = {
      focusOnSelect: true,
      infinite: fasle,
      slidesToShow: 3,
      slidesToScroll: 1,
      speed: 500
    };
```
In addition, it is the same behavior if you use keyboard events.

What I want is not to go beyond the scope so as not to cause strange interactions.

[Just like this.](https://codepen.io/anon/pen/OZLRBe)

**Comment by laveesingh** [comment]
I don't see anything strange in the given demo, it just shows the intended functionality. 
BTW, your `infinite` mode should be `false` and not `fasle`.

**Comment by zquancai** [comment]
Thank you very much for your response.
I'm so sorry, I misspelled the word. 

But I still have a little doubt, please look at the following state changes.

Initialization state.
![image](https://user-images.githubusercontent.com/8609783/39081586-a45b8fc0-4576-11e8-8b03-9e5c23ef1a8d.png)

Then I clicked 5 times reached the last state.
![image](https://user-images.githubusercontent.com/8609783/39081618-59abd0d8-4577-11e8-8027-7110f464a134.png)
The red box range is two blanks,  is this condition normal? 

I think the following state may be normal as the last state, and it feels better.
![image](https://user-images.githubusercontent.com/8609783/39081664-01b42424-4578-11e8-9db6-03902e0e86b8.png)
