### ISSUE TITLE
Styling inner divs in react-slick

### ISSUE THREAD

**Issue by HamzaAhmad932** [akiran/react-slick#1194]
I want to custom style the inner divs inside the <Slider></Slider> tag of react-slick.
Actually i want to add some margin between the inner divs of product listing slider .
if we add custom style file and give the ".slide-slick" a margin of 5px than the whole width of slider disorder.

**Comment by jedlikowski** [comment]
@HamzaAhmad932 just add padding inside these divs. Also, I suggest using your own CSS class for this and not overwriting styles from default .slide-slick class.
