### ISSUE TITLE
Warning: React does not recognize the `slideCount` prop on a DOM element.

### ISSUE THREAD

**Issue by kirill-konshin** [akiran/react-slick#1195]
Because of this line https://github.com/akiran/react-slick/blob/master/src/arrows.js#L35 I get errors with React 16.

![image](https://user-images.githubusercontent.com/1530410/38920602-7bd50f66-42a8-11e8-9b77-0e2a6152d4b1.png)

What is the purpose of this? How it will help with a config like this:

```
    nextArrow: (
        <span>
            <IconButton>
                <FA icon={faChevronRight} />
            </IconButton>
        </span>
    ),
```

**Comment by laveesingh** [comment]
Don't pass down all the props that you receive for custom arrows. 
```js
nextArrow: ({ firstProp, secondProps, ...otherProps }) => (
  <element {...props that you want} />
)
```
Something like this should work.

**Comment by kirill-konshin** [comment]
Any progress?

**Comment by Pushplaybang** [comment]
would be great to solve this.

**Comment by kirill-konshin** [comment]
You may use this as workaround:

```js
const SlickButtonFix = ({currentSlide, children, ...props}) => <span>{children}</span>;

const SETTINGS = {
    prevArrow: (
        <SlickButtonFix>
            <IconButton>
                <ChevronLeft />
            </IconButton>
        </SlickButtonFix>
    )
};
```

**Comment by akashmdkml** [comment]
@kirill-konshin  thanks this worked well  👏, react-slick custom arrows help to make arrow accessibility. https://codesandbox.io/s/myqq0yz54y

**Comment by bohehe** [comment]
> ```js
> <SlickButtonFix>
>             <IconButton>
>                 <ChevronLeft />
>             </IconButton>
>         </SlickButtonFix>
> ```

Thank you, man! you saved my life!

**Comment by codfish** [comment]
@bohehe @kirill-konshin I'm running into seeing the button appear along my custom arrow with this fix, did you run into this at all?

![image](https://user-images.githubusercontent.com/1666298/102720674-b5bc3b00-42c3-11eb-905d-f6ec23462686.png)


```jsx
const SlickButtonFix = ({ currentSlide, slideCount, children, ...props }) => (
  <span {...props}>{children}</span>
);
```

```jsx
prevArrow={
  <SlickButtonFix>
    <img src="/chevron-left.svg" alt="previous quote" width="12" height="20" />
  </SlickButtonFix>
}
nextArrow={
  <SlickButtonFix>
    <img src="/chevron-right.svg" alt="next quote" width="12" height="20" />
  </SlickButtonFix>
}
```

When i do the following I **don't** see the issue:
```jsx
prevArrow={<img src="/chevron-left.svg" alt="previous quote" width="12" height="20" />}
nextArrow={<img src="/chevron-right.svg" alt="next quote" width="12" height="20" />}
```

**Comment by minbelapps** [comment]
Why is it closed? It's a workaround, but not the solution. Why the library is injected props directly into the function's/component's output?

**Comment by ray-silicon-rhino** [comment]
This doesn't work with Next.js  12 and typescript as slickButtonFix doesn't know what it should be getting as propperties. dissapointing to see that this issue has not been resolved, I will look for an alternative package

**Comment by xiaojiudev** [comment]
> 

use just do the same above, then adding 'use client' on the top, there no more error (i still don't know why)

**Comment by xiaojiudev** [comment]
> This doesn't work with Next.js 12 and typescript as slickButtonFix doesn't know what it should be getting as propperties. dissapointing to see that this issue has not been resolved, I will look for an alternative package

use just do the same above, then adding 'use client' on the top, there no more error (i still don't know why)

**Comment by shakilcse25** [comment]
can anyone give me the typescript solution?

**Comment by kajikentaro** [comment]
If you use typescript, following example worked for me.
```typescript
    const SlickButtonFix = (props: { children: JSX.Element }) => {
      return props.children;
    };

    return (
      <Slider
        prevArrow={
          <SlickButtonFix>
            <button>prev</button>
          </SlickButtonFix>
        }
        nextArrow={
          <SlickButtonFix>
            <button>next</button>
          </SlickButtonFix>
        }
      >
        {/* your components */}
      </Slider>
    );
```

**Comment by AdamJednacz** [comment]
const settings = {
        dots: true,
        arrows: true,
        infinite: true,
        speed: 600,
        slidesToShow: 1,
        slidesToScroll: 1,
        prevArrow:<SlickButtonFix><FontAwesomeIcon   icon={faAngleLeft}/></SlickButtonFix>,
        nextArrow: <SlickButtonFix><FontAwesomeIcon  icon={faAngleRight}/></SlickButtonFix>,
        initialSlide: 0,
        autoplay: true,
        autoplaySpeed: 10000,
        cssEase: "linear",
        responsive: [
            {
                breakpoint: 768, 
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    arrows: false, 
                    dots:false
                }
            },
            {
                breakpoint: 480, 
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    arrows: true, 
                    dots:false
                }
            }
        ]
    };I pass it like this but the css doesn't work
