### ISSUE TITLE
Slider image streching when slider counter is smaller than the slidesToShow

### ISSUE THREAD

**Issue by ajeemaw** [akiran/react-slick#1196]
I have put 7 slides to show in 1366px screen. but the thing is, sometime the slider count is smaller than the amount of "slideToShow". In this scenario, If there is 3 slide, It will divide the width into 3. But Actually I want this to divide into 7 and display the 3 slides in that respective widths.

### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/zzloxr09mp) and provide a link to it along with the issue description

**Comment by laveesingh** [comment]
This issue was fixed in previous releases. Could you replicate this issue with codesandbox demo?

**Comment by twgraham** [comment]
Sounds related to #1182

**Comment by binary-moon** [comment]
@ajeemaw In your CSS, add the following to achieve what you want:
`slick-slide: {
  max-width: 14.2857%
}`

This will always make slide span 1 / 7 of available space, and will solve your problem

**Comment by ajeemaw** [comment]
Ya I've solved this with the new version. Thank you all.

**Comment by MickeyKay** [comment]
@ajeemaw I'm still seeing this issue. Can you confirm where this was fixed (e.g. commit link)? This is definitely something I'd like to solve.

**Comment by ajeemaw** [comment]
@MickeyKay Sorry actually i dont remember the code, but for me it was **not working** in "react-slick": "^0.20.0", but it is **working fine** after upgrading the version to "react-slick": "^0.22.0"

Please check with that version.

**Comment by MickeyKay** [comment]
@ajeemaw that this works if `variableWidth` is set to true.

**Comment by GoutamShanbhag** [comment]
I am still having this issue i am currently using version  ^0.29.0. 
It would really help if anyone can tell me how you fix it
