### ISSUE TITLE
CenterMode issue when upgrading from v0.15.4

### ISSUE THREAD

**Issue by darrylsepeda** [akiran/react-slick#1197]
Hi,

`I still don't know if this is a bug from react-slick or not.`

Currently Im trying to upgrade my react-slick version from 0.15.4 to 0.23.1.
I have make sure that I use react v16.0.0 and react-dom v16.0.0 like the one used in codesandbox.

I realised some of my slider are broken while some aren't, after further investigation, it happens because of responsive prop, to be precise it is centerMode prop, so if I remove centerMode from the responsive prop, it works fine.

Another issue is about custom arrows, it doesn't appear so we can have dots but not the arrows.

Does anyone ever experience something like this before?
Sorry I can't give the example on pen because it works fine if we only have react, react-dom, and react-slick. I just want to know if someone has ever experienced something like this, how do they solve it.
Thank you

**Comment by laveesingh** [comment]
Would you mind creating a codesandbox demo for the same issue?

**Comment by darrylsepeda** [comment]
Thanks for your response @laveesingh.

After further investigation, the bug appeared not from react-slick.
Sorry for this misleading issue.
