### ISSUE TITLE
Performance issues caused by innerSliderUtils.js

### ISSUE THREAD

**Issue by vertic4l** [akiran/react-slick#1204]
![bildschirmfoto 2018-04-24 um 11 02 05](https://user-images.githubusercontent.com/1771763/39177232-fb394da2-47ae-11e8-8c32-e5b62c2bef88.png)
![bildschirmfoto 2018-04-24 um 11 02 18](https://user-images.githubusercontent.com/1771763/39177236-fd8d88ac-47ae-11e8-9f79-a5ff039e8d4a.png)

**Comment by vertic4l** [comment]
Same goes for inner-slider.js

![bildschirmfoto 2018-05-08 um 10 01 00](https://user-images.githubusercontent.com/1771763/39745185-d50f2112-52a6-11e8-9c5a-91cf0f4f6c67.png)

**Comment by MohammadHasham** [comment]
Same issue.
