### ISSUE TITLE
Once React Slick is rendered I get "Cannot call a class as a function" error

### ISSUE THREAD

**Issue by BradyEdgar94** [akiran/react-slick#1206]
I have recently moved a site over to a new repo which is using next.js for routing and SSR. However now whenever I render my React slick slider I get a `Cannot call a class as a function` error and it breaks the sites entirely. 

I have tried my own react component, a very basic implementation and the example one on the playground page provided from this page when first creating this ticket, none of them work. It seems any instance of React Slick breaks on my site now.

I also don't get much detail on the issue other than the Cannot call a class as a function message.

Does anyone know a way to fix this!!

**Comment by BradyEdgar94** [comment]
Fix was to downgrade to 0.14.6 😦😢

**Comment by netizer** [comment]
Same here. Just to give more context - in my case, it happened with react version 15.5.4
