### ISSUE TITLE
Custom classes for dots based on slides being in the past, present and future.

### ISSUE THREAD

**Issue by paulcredmond** [akiran/react-slick#1207]
Is there a way to add classes to the dots so we can see:

- Slides that have been passed already
- Current slide (yes, we have a class for this: `slick-active`)
- Slides not yet viewed

The dots could then be styled to give this effect:

![screen shot 2018-04-26 at 14 38 49](https://user-images.githubusercontent.com/2063873/39309317-95cc371a-495f-11e8-835c-2990b387fc38.png)

I've been thinking about it but can't think of an easy solution for this.

**Comment by chicgeek** [comment]
You should be able to use the existing classes to help select these for styling.

Past: `.slick-dots li`
Present: `.slick-dots .slick-active`
Future: `.slick-dots .slick-active ~ li`

The selector specificity is a little high for my preference, but it will help you achieve what you're after.

**Comment by chicgeek** [comment]
Sounds like a fairly custom use case. You should be able to add these fairly easily with Slick's `afterChange` event.

**Comment by paulcredmond** [comment]
Yep that's exactly how I got it, thanks.
