### ISSUE TITLE
Slick fails on iPad after the 1st action

### ISSUE THREAD

**Issue by aiia** [akiran/react-slick#121]
Hi,
Just tried demo page with iPad2 iOS 8.4.1, Safari and Mercury browsers.

Strange situation: sliders permit just one slide move and that's all - after that they do not react on any sliding or button touching - like they freeze.
After reload situation repeats.

And thank you for your work!
Iho

**Comment by akiran** [comment]
Demos on the website are outdated and will update this weekend

Current version of react slick is working well on iOS devices
