### ISSUE TITLE
oldIndex parameter is always undefined in beforeChange function

### ISSUE THREAD

**Issue by CMOW5** [akiran/react-slick#1216]
version:
0.23.1

description: 
the parameter oldIndex in function beforeChange(oldIndex, newIndex) is always undefined 

example : https://codesandbox.io/s/x7x1jp6pnp

What is expected?
oldIndex should be equal to the current slide number

What is actually happening?
oldIndex is always undefined

**Comment by andy14312** [comment]
Anything on this issue? Even I'm facing this issue

**Comment by yoyo837** [comment]
Same issue...

**Comment by rttmax** [comment]
It's already fixed here: #1272

**Comment by rttmax** [comment]
It's already fixed [here](https://github.com/akiran/react-slick/pull/1272/commits/b8b261e2127e16d3cd33fc146aca84964ff690a1)!

**Comment by yoyo837** [comment]
This commit was not merged and published.

**Comment by clairefritz** [comment]
Same issue here!

**Comment by jmikrut** [comment]
I am also having this issue.

**Comment by imorar** [comment]
Same issue here. Please merge the commit.

**Comment by AndreiSDumitrescu** [comment]
Same issue here
