### ISSUE TITLE
Next slide method 

### ISSUE THREAD

**Issue by mmichelli** [akiran/react-slick#122]
Expose next + prev methods or setIndex 
Use case 
Use the keyboard to navigate the slides.

**Comment by vramana** [comment]
@mmichelli You can achieve it like this. Add a `currentSlide` variable to the state of the component wrapping you slider which is passed as `intialSlide` prop to the `SlickSlider` component. Now add an  EventListener for keyboardDown on your top level component and invoke a setState change on it changing the currentSlide according to keyCode.  

I am not working on this library at the moment. I have started working on this [new slick library][slick]. With a lot cleaner architecure by using Flexbox underneath. It allows for features like vertical scrolling and custom pages almost trivial and which I found hard to do here because I was fighting the CSS where I just couldn't make it work. It is pretty bare minimum at the moment. I'll make it better in the coming days. If you are interested in using it and found some feature you are missing, just file a issue and I'll try to implement them sooner.      

[slick]: https://github.com/vramana/react-flex-slick

**Comment by kuc2477** [comment]
+1

**Comment by vramana** [comment]
@mmichelli  @kuc2477 I think this is anti-pattern in react. Child components shouldn't expose methods that indirectly do setState. Wrap the slider in a parent component and pass the what ever slide you want as a `initialSlide` prop. You can listen to keyDown events from your parent component.

**Comment by mmichelli** [comment]
ah ok. Will it behave the same when the user presses one of the arrows?

**Comment by dptoot** [comment]
While I agree exposing is an anti-pattern, has anyone actually got this to work?  I have an example where a parent component is setting the initialSlide index of an react-slick instance to a parent state value but upon a setState to update that value nothing happens.

**Comment by vramana** [comment]
@dptoot Your method wont't work because currently one of the problems with `react-slick` is it does a lot of imperative manipulations behind the scenes. And you should never do setState of child from the parent component.

You have to pass the your currentSlide value as `initialSlide` prop to the Slider component which will trigger [this line](https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L58). Then the state of your Slider updates properly.

**Comment by dptoot** [comment]
@vramana Please forgive but I believe that is what I am doing.  Or at least trying to do.  Parent has state value of slide index that it passes to child slider component as initialSlide value.  I am just not seeing any effect on update of Parent state.  If this has been validated as possible and working then I am sure it must be something on my side, I am just not sure what.

**Comment by vramana** [comment]
@dptoot Sorry I misread your comment I guess. Let me check.

**Comment by dptoot** [comment]
@vramana Much appreciated.  :)

I have boiled it down to a pretty basic scenario of a button updating my parent state and I can verify that I am passing a new intialSlide index prop to the slider.  But it does not seem to be updating.  My hope is that you find an issue as I can't see where I might be going wrong on my end.

Thanks again for the quick response!

**Comment by dptoot** [comment]
@vramana I took a look this morning and I think you are right about everything although in the update method I am not seeing any assignment of currentSlide to props.initialSlide here[Github](https://github.com/akiran/react-slick/blob/011dc2b0c0eecd8756511c184afd6a0e866672f4/src/mixins/helpers.js#L46).  My assumption would be just updating that as is done in init method would do the trick... right? 

I am a little new to the world of contributing or I would submit a pull request myself. :)

**Comment by dptoot** [comment]
I have submitted a [pull request](https://github.com/akiran/react-slick/pull/133) with a new demo addressing this functionality.  First contribution... be easy on me! :)

**Comment by xizhao** [comment]
There should be an option to manage current slide in the parent, and pass it down as a prop instead of having it tracked as state inside of the slider

**Comment by akiran** [comment]
yes, I will try to get this feature working this weekend

**Comment by dptoot** [comment]
@akiran My pull request does allow the current slide to be updated via passing a new initialSlide prop.  I of course defer to you guys as to whether it was the correct implementation.  Originally I had it just updating current slide on update but in my opinion users are going to expect to see some animation to that slide as they would any control based interaction.

**Comment by matthewkesler** [comment]
+1. Programmatically changing the slide with ```initialSlide``` does work but we lose the ability to use transitions. A ```currentSlide``` prop would be great!

**Comment by dptoot** [comment]
Any update on this.  I am not convinced that my pull request properly addresses the  issue but we are running into a lot of issues around this behaviour.

**Comment by rkoberg** [comment]
I had tried using the initialSlide, but as mentioned, it is no longer slick. I also needed the buttons outside of the slick container. Apparently with slick slider outside of react you can pass selector options for the the buttons and they can exist outside of the slick container (at least that is what my designer has given me).

To work around this I use the slick buttons, but they are display:none and triggered by my custom buttons:
```
  handleBtn(prevOrNext, btn, hiddenBtn) {
    if (hiddenBtn.className.includes('disabled')) {
      btn.className = prevOrNext + '-button-slick slick-arrow slick-disabled';
      btn.setAttribute('disabled', 'disabled');
      btn.setAttribute('aria-disabled', 'true');
    } else if (hiddenBtn.hasAttribute('disabled')) {
      btn.className = prevOrNext + '-button-slick slick-arrow';
      btn.removeAttribute('disabled');
      btn.removeAttribute('aria-disabled');
    }
  }

  handleBtnStates() {
    this.handleBtn('prev', this.prevTrigger, this.hiddenPrev);
    this.handleBtn('next', this.nextTrigger, this.hiddenNext);
  }

  prev(e) {
    this.hiddenPrev.click();
  }
  next(e) {
    this.hiddenNext.click();
  }

  componentDidMount() {
    const featuredWays = ReactDom.findDOMNode(this.refs.featuredWays);
    const sliderNav = ReactDom.findDOMNode(this.refs.sliderNav);
    this.hiddenPrev = featuredWays.querySelector('.slick-prev');
    this.hiddenNext = featuredWays.querySelector('.slick-next');
    this.prevTrigger = sliderNav.querySelector('.prev-button-slick');
    this.nextTrigger = sliderNav.querySelector('.next-button-slick');
  }
```

**Comment by dptoot** [comment]
This seems like a possible workaround for nextSlide but what we really need is a prgmatic way to assign the currentSlide.  My use case can't assume the control is only requesting the next slide but is assigning the currentSlide based on its index.  Having it animate to that location would make sense.

**Comment by wmf23** [comment]
I am seeing the same issue. I do set the initialSlide to a different index than 0 but the component does not slide.

**Comment by akiran** [comment]
Now you can use slickGoTo  prop for this use case

**Comment by tnrich** [comment]
@akiran , does the slickGoTo prop still have a smooth transition between slides? From what I can tell, it does not..

**Comment by wmf23** [comment]
Yes, I also notice that. The transition is not smooth.

**Comment by revolution42** [comment]
There seems to be a problem when you change the props of the parent before the animation has finished. 

My use case is the person press next and I fire of a ajax request and update the state to allow it to start moving, when the ajax request comes back I update the state however do not change any props in react slider, it then jumps
