### ISSUE TITLE
"rtl: true" puts slides out of place

### ISSUE THREAD

**Issue by mcfoton** [akiran/react-slick#1227]
Opening new issue since #952 was closed but does not contain a proper solution.

I tried playing with the source and have further narrowed the issue. Didn't succeed in fixing it, but hope the info will help. All applies to *rtl: true* prop and 'direction=rtl' in the html.

Initial load and first click places first slide off due to incorrect calculation of slidesToOffset here
> src/sandbox/react-slick/mixins/trackHelper.js:138

Demo [here](https://codesandbox.io/s/13vpk5zmr4) Initial load should show slides 1, 2 and 3.

**Comment by sag1v** [comment]
It's not only the initial load, i think any calculation taking place when rtl is set to true are off.
for example afterChange gives a wrong index.

**Comment by sag1v** [comment]
@mcfoton why did you close it?

**Comment by mcfoton** [comment]
@sag1v oops. wild clicking. thanks for pointing out.
also agreed, the miscalculation of slidesToOffset affect all other states as well.

**Comment by mcfoton** [comment]
also I believe calculations should be fixed here
> /react-slick/utils/innerSliderUtils.js:99
`spec.currentSlide >= spec.slideCount - spec.slidesToShow`
otherwise after we click 'prev' once the 'next' arrow would be disabled
problem is that canGoNext method doesn't seem to receive 'rtl' prop in the 'spec' parameter.

**Comment by sag1v** [comment]
Shame there is no much of activity for issues and PR reviews for this component :/

**Comment by mcfoton** [comment]
@sag1v attached PR. maybe it'll help you in the meantime

**Comment by mohamedragaey** [comment]
any news about this issue?
