### ISSUE TITLE
After upgrading to ios 11.3, the swipe becomes very slow and not smooth

### ISSUE THREAD

**Issue by ethfoo** [akiran/react-slick#1243]
### React-Slick is very slow and not smooth in ios 11.3

I guess this is the reason why  https://github.com/atlassian/react-beautiful-dnd/issues/413

Is  there any way to fix this problem? Thanks.

**Comment by simon-online** [comment]
Yes, it seems like react-slick isn't working in Safari on iOS 11.3 along with a number of other packages that use dragging / swiping behaviours.

There is a pending fix for Safari that will eventually be released as detailed here:
https://bugs.webkit.org/show_bug.cgi?id=184250

In the meantime https://github.com/atlassian/react-beautiful-dnd/issues/413 details a work around that fixes the issue.

**Comment by HelKyle** [comment]
#1291
