### ISSUE TITLE
Problem with fixed positioned elements on android chrome

### ISSUE THREAD

**Issue by tomhai** [akiran/react-slick#1247]
I'm experiencing a problem where a page with a (horizontal) react-slick carousel breaks the correct handling of fixed positioned elements when interacting with the carousel. 

This problem started to appear only on android chrome some time ago and is related to the toggling address bar. I believe that usually the `window.innerHeight` value should change based on the status of the address bar. However, when the problem occurs the `window.innerHeight` is fixed to either of the values independent of the visibility of the address bar. Due to this, any fixed positioned element will be handled wrongly. Interestingly, the elements are still visually rendered correctly, but e.g. click events wont work half of the time as they will "miss" their target.

The problem can be reproduced even with the default demo on the https://react-slick.neostack.com/. One has to simply scroll the **react-slick** carousel back and forth a few times, sometimes requiring multiple attempts. Problem can be detected by inspecting the `window.innerHeight` value to see if it updates when scrolling the page up-and-down, i.e. toggling the address bar.

Any hints on potential causes and workarounds would be much appreciated. I've been able to reproduce the problem even with other carousel implementations, so it doesn't seem to be related only to **react-slick**. However, having them on the site and interacting with them is required for the bug to appear, so there is a high correlation. Currently my best hypothesis is that there might be a browser bug.

I'm using a recent chrome version 66.0.3359.158 and android version 7.0.0 for testing.

**Comment by socker210** [comment]
Same problem. Anyone can help?

**Comment by tomhai** [comment]
This was indeed a browser bug and is now fixed in chrome version 68.

https://bugs.chromium.org/p/chromium/issues/detail?id=848122

I can verify that my original reported issue does not exist anymore on a version 68, so I'm closing this. It was also not caused by react-slick. There doesn't seem to be any good workarounds for the older chrome versions, but its good that it got fixed relatively quickly.

**Comment by socker210** [comment]
@tomhai I can solve this problem to easy way as your response! Thank you!!
