### ISSUE TITLE
Strange Behavior on production build - initialSlide not at the same place 

### ISSUE THREAD

**Issue by rdhox** [akiran/react-slick#1248]
When I use react-slick in development with hot-loader, no problem react-slick behave like it supposed to behave, the image of the bike match the description (in center mode):
![local](https://user-images.githubusercontent.com/36813150/40653302-03cabbc0-633b-11e8-8d06-cbe036506959.png)

When I build my site (with react-static), in production the image doesn't match any more the description. 
![production](https://user-images.githubusercontent.com/36813150/40653317-0d9e24f2-633b-11e8-94ef-084b0475217e.png)

As far as I can say, the problem might be that in development, the initialSlide is place on the left in the gallery of slide, and in production, on the right. So when I go in responsive mode and I tell that below 992px, I want 'SlideToShow:1' and not 3, the slide in focus is on the right and out of sight.

I got back to the same settings of the responsive demo, and no problem, so it's the option 'center' that create the problem.

Any suggestions?

Thanks

**Comment by ekryski** [comment]
Seeing the exact same issue. I thought I was going crazy!

**Comment by alalfakawma** [comment]
Did you guys manage to solve this? I have a weird bug in production too, the rendering of slides is completely different than that of the development build.
