### ISSUE TITLE
react-slick stacks slides vertically

### ISSUE THREAD

**Issue by davidshare** [akiran/react-slick#1252]
import React from 'react';
import Slider from 'react-slick';

const settings = {
    arrows: false,
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
};

const generateSlides = ({slides}) => {
    if(slides){
         return (
            <Slider {...settings}>
            <div>
                {slides.map(function(item){
                    return (
                        <div key={item.id} className="item_slider" 
                            style={{background:`url(/images/covers/${item.cover})`}}>
                            <div className="caption">
                                <h4>{item.topic}</h4>
                                <p>{item.title}</p>
                            </div>
                        </div>
                    )
                })}
                </div> 
            </Slider>
        )
    }
}

const Featured = (props) => {
    return(
        <div>
            {generateSlides(props)}
        </div>
    )
}

export default Featured;

**Comment by Sailias** [comment]
@davidshare did you import the slick css?

**Comment by davidshare** [comment]
Yes I did

**Comment by Sailias** [comment]
@davidshare please include a sandbox, such as: https://codesandbox.io/s/k98w7v4r43

**Comment by Sailias** [comment]
@davidshare the sandbox has everything you need to demo your code.

Anyway, the problem is you have

```
<Slider>
  <div>
     { slides.map }
  </div>
</Slider>
```

This means you have a single slide, with divs inside of it, which probably are going to stack vertically.
Remove the first div in your slider.

**Comment by davidshare** [comment]
@Sailias I did that. But instead, the whole page comes out blank. It is like the space for the image is still occupied yet blank. Sorry about the Sandbox, still have not figured out how to imlement my code there. The data I am using is from an offline json file.

**Comment by Sailias** [comment]
@davidshare it's probably because your slide data hasn't loaded when you render the slider.

```
this.state = {
  home: {
    slider: []
  }
}

... 

{ this.state.home.slider.length > 0 && <Featured slides={this.state.home.slider} /> }
```

**Comment by neemssoni** [comment]
@Sailias I am also facing the same issue, I tried hard coded slide data, still that coming same.

**Comment by zflopez** [comment]
@neemssoni @Sailias I'm not sure I'm really helpful at this point, but have you tried importing "slick-carousel" styles in your app? Such as:  

```
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
```

**Comment by jakub-musik** [comment]
For anyone arriving at this from google: 

It may be because the container in which you have your Slider has a non-compatible display mode, try display: block
`<DivWithBlockDisplay>
  <Slider>
    <div />
    <div />
  </Slider>
</DivWithBlockDisplay>
`

**Comment by marlongichie** [comment]
I am also experiencing this issue, anyone found a solution?

**Comment by Yvad60** [comment]
I was having the same issue and  The issue was that I didn't import CSS which is installed separately and that is mentioned in the docs Include the CSS section https://react-slick.neostack.com/docs/get-started

To add CSS you run `npm install slick-carousel --save` 
and after import CSS where you are using the coursel as 
```
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
```

**Comment by EarlPappi** [comment]
This worked, thank you!

I have react slick in two different components, it worked well in the first component without importing the css, but I had to import the css to solve the vertical stacking. Is there any reason this happened?

**Comment by estoylive** [comment]
for me it was the issue mentioned above (thanks jakub-musik) about having the slider inside a Flex so i added a div with display block and voi-lah! it worked

**Comment by Crimson-keep** [comment]
I had the same issue, then I tried to add a div enclosing the slider component and limit its width, then the problem is resolved.

**Comment by Shashank729** [comment]
> @neemssoni @Sailias I'm not sure I'm really helpful at this point, but have you tried importing "slick-carousel" styles in your app? Such as:
> 
> ```
> import "slick-carousel/slick/slick.css";
> import "slick-carousel/slick/slick-theme.css";
> ```

This worked for me. Thanks for the solution!

**Comment by shefali12-ab** [comment]
I was also having the same issue, I am using Tailwindcss for stylling my webapp. setting the div className enclosing the slider componet to "container" works for me.

**Comment by cmahmadalitariq** [comment]
> I was also having the same issue, I am using Tailwindcss for styling my webapp. setting the div className enclosing the slider componet to "container" works for me.

Thanks @shefali12-ab

**Comment by Sochuks** [comment]
I just spent over an hour with this problem, till I stumbled on this. I am using Tailwindcss for styling my webapp. Just as @jakub-musik suggested I removed flex from the div enclosing the slider and it worked. Thanks for the help
