### ISSUE TITLE
React-slick doesn't slide

### ISSUE THREAD

**Issue by iCantWriteCode** [akiran/react-slick#1253]
Hey guys, i am trying to make react slick to work but it doesn't slide.
I havent installed JQuery.We use Server Side Rendering and we want to avoid using JQuery.
Is it necessary to install JQuery or there is another way.

I use react  version 16.4.0
I installed react-slick with npm. version 0.23.1.
I install slick-carousel  with npm. version 1.8.1
I added external css files from cdn for the styles.
I copy pasted a simple example from the page and it doesn't slide.

**Comment by UniBen** [comment]
Can you show us your settings object?

**Comment by iCantWriteCode** [comment]
![screen shot 2018-06-04 at 10 49 05](https://user-images.githubusercontent.com/26002264/40904902-f050a600-67e4-11e8-8f74-c01ba9e35f9f.png)
 my code looks like this

**Comment by UniBen** [comment]
Hmm, that all looks good.

To answer your question: "Is it necessary to install JQuery or there is another way."
No it's not. I have a reactql project and like you I'm using server side rendering and pulled the css from the CDN without requiring jQuery so it should work for you too.

Sorry I couldn't help you fix your problem.

**Comment by Sailias** [comment]
@iCantWriteCode please include a sandbox, such as: https://codesandbox.io/s/k98w7v4r43

**Comment by iCantWriteCode** [comment]
You guys where right it was my fault. Sorry for the inconvenience

**Comment by julian-gargicevich** [comment]
@iCantWriteCode hey mate, how did you get it to work? I'm having the same issue
Thanks

**Comment by mbhat94** [comment]
I am not getting proper output with react-slick please help me
my code is:
function Slick(): JSX.Element {
  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };
  return (
    <div className={styles.mainContainer}>
      <Slider  {...settings}>
        {data.map(data => (
          <div className={styles.card}>
            <h5>{data.name}</h5>
          </div>
        ))}
      </Slider>
    </div>
  );
}
export default Slick;

and output is  
![image](https://user-images.githubusercontent.com/41264365/83253034-e6bf0c00-a1c9-11ea-90e7-1fa7b838e91e.png)
