### ISSUE TITLE
react-slick going backwards with infinite and autoPlay - help

### ISSUE THREAD

**Issue by dantt775** [akiran/react-slick#1258]
I have a react-slick component like on the link and its fine, but sometimes when i go to other tabs on chrome and return to my page, the component is going in other direction....already tested alot of the default props and nothing.

Here is my settings
https://codesandbox.io/s/znpk6nxznx

**Comment by anshul-pinto0410** [comment]
> I have a react-slick component like on the link and its fine, but sometimes when i go to other tabs on chrome and return to my page, the component is going in other direction....already tested alot of the default props and nothing.
> 
> Here is my settings
> https://codesandbox.io/s/znpk6nxznx

Hey did you ever get this fixed? Facing this same issue, have tried playing around with the settings as much as I can but could not fix the issue
