### ISSUE TITLE
There's no ref.

### ISSUE THREAD

**Issue by vince1995** [akiran/react-slick#1261]
Hi

when I do:

```
<Slider
    ref={slider => (this.slider = slider)}                
>
    {this.props.children}
</Slider>
```

there's no ref in my component.

I've noticed that the ref function is never called. When I do

```
<Slider
    ref={slider => {this.slider = slider; console.log("test");}}    
>
    {this.props.children}
</Slider>
```

the console never outputs "test".

**Comment by akiran** [comment]
Check this example 
https://github.com/akiran/react-slick/blob/master/examples/AutoPlayMethods.js
It works
