### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by havok89** [akiran/react-slick#1263]
Cant get my issue up in codesandbox but gonna ask,

Im including react via script tags for react and react dom development v16.4.0

When including my react-slick.js that has been created via script tag and loading my site I get the message 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

on the <Slider> component. All works fine with it removed. any ideas?

Edit: just to add that I cant include on this project like the previous answer for a similar question. I have to load it as a script so its available globally

**Comment by hlolli** [comment]
Getting the same error, with typescript + webpack + react dom dev(or min) 16.4.1, it's in a stateless react component, just the presence of `Slider` throws this same error. Did you solve it @havok89?

**Comment by emaillenin** [comment]
Thanks @hlolli, stumbled across the same issue and your solution worked for me too 👍
