### ISSUE TITLE
Slick isn't working with react 16.2

### ISSUE THREAD

**Issue by rv-psilveira** [akiran/react-slick#1264]
It happens because slick uses setState on WillMount :(

**Comment by devcosta** [comment]
+1 up ;)

**Comment by eternalsky** [comment]
+1

**Comment by mpint** [comment]
+1

**Comment by ShockiTV** [comment]
+1

**Comment by adorum** [comment]
Try to wrap slick to `PureComponent`.

**Comment by ndaybreak** [comment]
+1

**Comment by MickeyKay** [comment]
Any updates on this one? I just ran into this as well.

**Comment by vaibhavi3t** [comment]
Any update on this? I have same issue,  not working with 16.6.
