### ISSUE TITLE
sliding bug in centerMode:true, infinite:false

### ISSUE THREAD

**Issue by baomastr** [akiran/react-slick#1278]
there is no ability to slide to last slides in centerMode if infinite: false.

code example:
https://codesandbox.io/s/oorn1q75lz

short screencast of bug:
http://take.ms/TJnyR

**Comment by Sailias** [comment]
duplicate of #1251

**Comment by webattitude** [comment]
also, how to avoid first slide offset ?
I'd like the first slide not to be empty...
https://codepen.io/anon/pen/mKKveZ

**Comment by Sailias** [comment]
Try `initialSlide: 1`

Also, this thread is for the specified issue, not a general help thread as you posted a usage question not a bug. 

Please try to stay on topic.

**Comment by randallreedjr** [comment]
I believe this should be fixed by #1232.

**Comment by randallreedjr** [comment]
Also duplicate of #1230 as well
