### ISSUE TITLE
Slider does not go to first slide when changing route with react-router

### ISSUE THREAD

**Issue by chemoish** [akiran/react-slick#128]
SEE: https://github.com/akiran/react-slick/issues/85

I am changing the route using `<Link>` (provided by react-router), but when doing so it keeps the slider on the currentSlide (Even though the slider's data changes).

SEE: https://github.com/akiran/react-slick/issues/100
1. Navigate to item A page
2. Show a list of related items in the slider
3. Click on related item B
4. Navigate to item B page
5. Show a list of related items in the slider (They may or may not be the same items in step 2—The current page will reflect the previous list in step 2)

Perhaps there is a middle ground between all of these related issues to enable reseting `currentSlide: 0`?

**Comment by donnguyen** [comment]
Yep, I am facing the same issue here.

**Comment by TylorShin** [comment]
+1
is there no one still solve this problem?

**Comment by gabriellim** [comment]
+1 
imo currentSlide should reset to 0 when the Slider component updates
