### ISSUE TITLE
Last slider can be scrolled left side under variable width mode

### ISSUE THREAD

**Issue by WinfredMa** [akiran/react-slick#1282]
there is no ability to slide the last slider anymore under old version. but now user can slide the last slider to left side.

code example:
https://codesandbox.io/s/n7r138n5mj

**Comment by diegopamio** [comment]
See PR #1334 and if you like it, please vote to get it into the main component.

**Comment by andreobriennz** [comment]
Any updates? 

I have the same issue, except for me it is an issue when there are fewer items in the slider. For example if there is space in the slider for 5 divs and I only have 3, I can drag the items to the left and all but one will disappear

**Comment by MickeyKay** [comment]
Bump - this is the #1 issue we've run into and would love to see a fix on.
