### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by jvaloria** [akiran/react-slick#1283]
It seems like the [Playground](https://codesandbox.io/s/ppwkk5l6xx) is not working as expected:
![image](https://user-images.githubusercontent.com/4265837/41814590-76153e7a-7728-11e8-87f9-f4ac4718ded4.png)

Dependencies:
- react: 16.0.0
- react-dom: 16.0.0
- react-slick: 0.23.1

**Comment by ronanmccoy** [comment]
I'm having the same issue with the [playground](https://codesandbox.io/s/ppwkk5l6xx) not working. 

It loads, but with a blank view except for the "previous" button. Clicking on the previous button gives a flash of the 4 kitten images, then they disappear. From that point on any subsequent clicks on "previous", or scrolling left to right, shows nothing.

**Comment by jvaloria** [comment]
Thank you @antandev, this does indeed solve the issue in the Playground. I wonder if this issue should be closed or kept open until the playground is corrected, as it is linked in the [docs](https://github.com/akiran/react-slick):
![image](https://user-images.githubusercontent.com/4265837/41929610-07b18898-794f-11e8-8418-d490ffdbc6b7.png)

**Comment by ronanmccoy** [comment]
Confirmed on my end too... It does work when using the "Add Dependency" button to add the slick carousel CSS files instead of directly linking to them in index.html.

Also, I'm agreeing with @jvaloria, till the playground is updated this should be kept open.

**Comment by a-m-dev** [comment]
also if you getting arrows out of view , just cut container style from index.html to styles.css file , you will get nicer look at least , 



i'm just wondering how to import these styles with react ????? doc really confused me with styles ....

**Comment by akiran** [comment]
Playground is working now

**Comment by jvaloria** [comment]
Thank you!
