### ISSUE TITLE
React hot reload breaks with react-slick

### ISSUE THREAD

**Issue by Drafter500** [akiran/react-slick#1285]
Can't reproduce it with sandbox because it uses react-scripts, but on the configuration with react-hot-loader, the issue is reproducible. If you put the slick to the page, HMR stops working. Browser catches change signals but does not rerenders the components even those not related with the slider.

Has anyone else experienced that?

**Comment by jklipton** [comment]
I think I'm having the same issue as well.

**Comment by Drafter500** [comment]
This has to be fixed
