### ISSUE TITLE
IE9 and IE10 errors

### ISSUE THREAD

**Issue by ruchijn** [akiran/react-slick#1286]
I was trying to see if react-slick works with IE9. I tested the link https://react-slick.neostack.com/ in Windows 7/IE 9 and Windows 7/IE10 and I got below errors:

IE9 - SCRIPT5022: matchmedia not present, legacy browsers require a polyfill

IE10 - SCRIPT438: Object doesn't support property or method 'assign'

So I was wondering if this is supposed to work in those browsers? 

http://kenwheeler.github.io/slick/ does work in those browsers though.

**Comment by arongreen0501** [comment]
Any updates on this? Having the same issue after going from version 0.19.0 to 0.21.0.

"Object doesn't support property or method 'forEach'"

**Comment by Dogtiti** [comment]
same issue, so it already supports IE9?

**Comment by zzswang** [comment]
any update? same issue

**Comment by zhuber** [comment]
This is still not working in IE 9, by the way. Any plans to support this?

**Comment by HolyZheng** [comment]
In my case, I solve this issue by include the following polyfills for matchMedia and MutationObserver.
1. firstly, include this polyfill in your project
```
window.matchMedia = window.matchMedia || function () {
    return {
        matches: false,
        addListener: function () { },
        removeListener: function () { }
    };
};
```
2. and then include the following polyfill 
https://github.com/googlearchive/MutationObservers/blob/master/MutationObserver.js
