### ISSUE TITLE
Settings = { dots: true } raised an error: Uncaught TypeError: Array.apply is not a function

### ISSUE THREAD

**Issue by fzingg** [akiran/react-slick#1288]
Works well until you use the settings :

this.settings = {
      dots: true
}

An error is raised: 

```
Uncaught TypeError: Array.apply is not a function, dots.js: 71
```
Works if you remove the `Array.apply` and change this line in `dots.js`:

```
var dots = Array.apply(null, Array(dotCount + 1).join("0").split("")).map(function (x, i) {
```
By this line:
```
var dots = Array(dotCount + 1).join("0").split("").map(function (x, i) {  
```

React-slick 0.22.0
React 16.4.0

**Comment by dm-randy** [comment]
`dots: true` works for me. How many slides are in your carousel?

**Comment by fzingg** [comment]
7 slides
