### ISSUE TITLE
on mobile and ipad - sliding to finger touch speed  possibility (similar to what instagram has for their instagram stories)

### ISSUE THREAD

**Issue by esloewe** [akiran/react-slick#1289]
Hi I would like to know if there is a way in which the sliding on mobile is similar to what the instagram stories slide like. I have added  ` swipeToSlide` and it does improve the experience but it would be nicer if it would slide a bit smoother. Is there way to do this?

**Comment by diegopamio** [comment]
See PR #1334 and if you like it, please vote to get it into the main component.
