### ISSUE TITLE
Blank slide when using lazyLoad

### ISSUE THREAD

**Issue by coyaniv** [akiran/react-slick#129]
When I use lazy load, if I first click is to the left arrow, i'm getting white blank slide.

**Comment by jordansexton** [comment]
+1. It also affects swiping to the right (to reveal the items to the left).

**Comment by i8ramin** [comment]
+1

**Comment by rfarine** [comment]
+1!

**Comment by cotwitch** [comment]
+1

**Comment by akiran** [comment]
This issue is fixed in latest release.
