### ISSUE TITLE
Slider renders two rows of identical items if the number of items within the slider < slidesToShow

### ISSUE THREAD

**Issue by JHolah** [akiran/react-slick#1296]
I have a slick slider that renders dynamic items.

If the number of items returned is greater than the setting "slidesToShow", it works as expected.
If the number of items returned is equal, then it displays a row of items without nav, as expected.
If the number of items returned is lower, the slider renders two rows of identical items - the 'normal' items, and also a row of cloned items.

I can work around this quite simply by hiding the cloned row if the number of items returned is less than "slidesToShow", but I would rather that this wasn't rendered at all, obviously.

Is this a known issue?
Is there a setting or common fix that I have missed?

Demo here: https://codesandbox.io/s/5ko83z1kzn

**Comment by asela-wijesinghe** [comment]
+1

**Comment by Mrebai** [comment]
i worked around it by setting a fixed width and set overflow-y to hidden but it's so annoying behavior.

**Comment by feimosi** [comment]
Another workaround is to set `slidesToShow` dynamically:
```js
slidesToShow={Math.min(images.length, 4)}
```

**Comment by tttt-conan** [comment]
I worked around by setting adaptiveHeight to true but there is still a glitch at first load

**Comment by shyam528** [comment]
> Math.min(images.length, 4

But it is increasing the width of the slide.
I am getting one image from api and it is occupying the complete div area and I can't fix width because image size can be vary for different resoution.

**Comment by JHolah** [comment]
> > Math.min(images.length, 4
> 
> But it is increasing the width of the slide.
> I am getting one image from api and it is occupying the complete div area and I can't fix width because image size can be vary for different resoution.

I also had the same issue. Got around it by creating invisible, empty items to fill the remaining space.

**Comment by uragecz** [comment]
Same problem, someone is working on solution.. ? Dynamic size of slideToShow changes width.. And playing with css around is kinda annoying / unreal if you want to have those items align to center right next to each other

**Comment by dj-neza** [comment]
Same problem - what is going on with this? why does Slick add some "cloned" elements?

**Comment by leo-khramtsov** [comment]
is there a fix for this?

**Comment by topolanekmartin** [comment]
Please review this bug. Same problem here :(

**Comment by hector4213** [comment]
my heart weeps for a fix

**Comment by mymoto23** [comment]
Hope this gets fixed. as shyam528 explained, doing so automatically resizes each item which looks pretty bad in a designer's perspective. A workaround I can think of is to add dummy elements if the length of the items are less than the slidesToShow option- but this is annoying for developers to deal with  if they're using custom elements or reusable components.

> > Math.min(images.length, 4
> 
> But it is increasing the width of the slide.
> I am getting one image from api and it is occupying the complete div area and I can't fix width because image size can be vary for different resoution.

**Comment by sourav-ojha** [comment]
@JHolah   After  using slidesToShow to Max.min(element.length, 4), cards are placed in center
Any solution so the card should align to left not in center

**Comment by tr1Wox** [comment]
The issue still exists, could you fix it ? Because there are no proper solutions to patch the problem.

**Comment by tr1Wox** [comment]
> The issue still exists, could you fix it ? Because there are no proper solutions to patch the problem.

After some research, it comes from the infinite attribute in my case.

**Comment by jovenlumaas** [comment]
> ```js
> Math.min(images.length, 4)
> ```

This solves my problem. Thanks

**Comment by liked95** [comment]
Has this issue been resolved yet?

**Comment by HeinOrangeCollarMedia** [comment]
I had the same problem. I'll let you know If I find any viable solution.

**Comment by TimotijevicVlada** [comment]
I have the same problem, when I try to use slider as a reusable component in the react, the slider getting crazy with styling and I can't fix it long time...

**Comment by nelsonct7** [comment]
I have the same problem, are there any solution available, that can be used with reusable components, where the number of slides are coming from the back end ?

**Comment by jaykch** [comment]
Setting infinite conditionally solves this.

For my particular usecase I am doing something like this -

```
<Carousel ref={slider} {...settings} infinite={data.length > 4}>
```

**Comment by nx-kevinbischof** [comment]
> Setting infinite conditionally solves this.
> 
> For my particular usecase I am doing something like this -
> 
> ```
> <Carousel ref={slider} {...settings} infinite={data.length > 4}>
> ```
> 
> This only sets it infinite when the data is more than 4 (my slidesToShow value). If you have a different slidesToShow value you should use that.

The infinite value fixed that bug for me. Thank you!!
It's annoying that this bug still exists since 5 years...

**Comment by liyan-yida** [comment]
make dummy item. if slidesToScroll is less than item length. add dummy items that is inactive for mouse input

for example, (react)

 const addDummySubBooks = (subbooks, slidesToShow) => {
    const dummyCount = slidesToShow - subbooks.length;
    if (dummyCount > 0) {
      for (let i = 0; i < dummyCount; i++) {
        subbooks.push({
          id: `dummy-${i}`,
          name: "",
          image: null,
          isDummy: true,
        });
      }
    }
    return subbooks;
  };

  return (
    <Container>
      {posts.length > 0 && (
        <Carousel indicators={true} className="main-carousel">
          {posts.map((post) => (
            <Carousel.Item key={post.id}>
              <div className="carousel-image-wrapper">
                <img
                  className="d-block w-100"
                  src={post.image || defaultImage}
                  alt={post.title}
                />
              </div>
              <Carousel.Caption className="carousel-caption-custom">
                <h3>{post.title}</h3>
                <p>{post.content}</p>
              </Carousel.Caption>
            </Carousel.Item>
          ))}
        </Carousel>
      )}
      {books.map((book) => (
        <div key={book.id} className="book-section">
          <h2>{book.name}</h2>
          <Slider {...settings}>
            {addDummySubBooks(book.subbooks, settings.slidesToShow).map(
              (subBook) => (
                <div
                  key={subBook.id}
                  className={`subbook-card ${subBook.isDummy ? "dummy" : ""}`}
                >
                  <Card
                    style={{
                      borderRadius: "10px",
                      overflow: "hidden",
                    }}
                  >
                    <div className="subbook-image">
                      {subBook.image && (
                        <img
                          src={subBook.image || defaultImage}
                          alt={subBook.name}
                          onError={(e) => (e.target.src = defaultImage)}
                        />
                      )}
                    </div>
                    <Card.Body>
                      <Card.Title>{subBook.name}</Card.Title>
                    </Card.Body>
                  </Card>
                </div>
              )
            )}
          </Slider>
        </div>
      ))}
    </Container>
  );

**Comment by liyan-yida** [comment]
make dummy items if slideToShow is more than item length. 

for example, (react)
 const addDummySubBooks = (subbooks, slidesToShow) => {
    const dummyCount = slidesToShow - subbooks.length;
    if (dummyCount > 0) {
      for (let i = 0; i < dummyCount; i++) {
        subbooks.push({
          id: `dummy-${i}`,
          name: "",
          image: null,
          isDummy: true,
        });
      }
    }
    return subbooks;
  };

  return (
    <Container>
      {posts.length > 0 && (
        <Carousel indicators={true} className="main-carousel">
          {posts.map((post) => (
            <Carousel.Item key={post.id}>
              <div className="carousel-image-wrapper">
                <img
                  className="d-block w-100"
                  src={post.image || defaultImage}
                  alt={post.title}
                />
              </div>
              <Carousel.Caption className="carousel-caption-custom">
                <h3>{post.title}</h3>
                <p>{post.content}</p>
              </Carousel.Caption>
            </Carousel.Item>
          ))}
        </Carousel>
      )}
      {books.map((book) => (
        <div key={book.id} className="book-section">
          <h2>{book.name}</h2>
          <Slider {...settings}>
            {addDummySubBooks(book.subbooks, settings.slidesToShow).map(
              (subBook) => (
                <div
                  key={subBook.id}
                  className={`subbook-card ${subBook.isDummy ? "dummy" : ""}`}
                >
                  <Card
                    style={{
                      borderRadius: "10px",
                      overflow: "hidden",
                    }}
                  >
                    <div className="subbook-image">
                      {subBook.image && (
                        <img
                          src={subBook.image || defaultImage}
                          alt={subBook.name}
                          onError={(e) => (e.target.src = defaultImage)}
                        />
                      )}
                    </div>
                    <Card.Body>
                      <Card.Title>{subBook.name}</Card.Title>
                    </Card.Body>
                  </Card>
                </div>
              )
            )}
          </Slider>
        </div>
      ))}
    </Container>
  );
