### ISSUE TITLE
Carousel breaks if I Click on one image

### ISSUE THREAD

**Issue by jmgarciamari** [akiran/react-slick#13]
I'm trying it with demo page and I can drag but if I click on one of images suddenly dragging is disabled, dots don't respond.

**Comment by akiran** [comment]
can you post your demo code snippet ?

**Comment by jmgarciamari** [comment]
emmm I try it in this web http://webrafter.com/opensource/react-slick and if I click one element dragging is disabled, seems like #5 issue but with the click event, sorry for my English

**Comment by akiran** [comment]
#5 issue is fixed. I don't see that issue on demo page.

Can you point me to the element which is causing problem with click? 
Which browser and device are you using ?

**Comment by jmgarciamari** [comment]
I'm using chrome with linux and chrome on android. And whatever of elements
cause this problem. I'm stuck because i want a callback when I click an
element, but if dragging is disabled for me when I click I have a problem.

**Comment by akiran** [comment]
Yes,  Now  I could see the issue.
I will fix it soon.

**Comment by akiran** [comment]
Fixed this issue and made a new npm release (0.3.4)

Thanks for reporting issue.

**Comment by jmgarciamari** [comment]
thanks a lot! Now Works Great!!
