### ISSUE TITLE
error on npm install (error react-slick@0.7.2 prepublish....)

### ISSUE THREAD

**Issue by playtocrazy** [akiran/react-slick#131]
I got the error messages when npm install, would you please give some tips?

>128505 error Windows_NT 6.1.7601
128506 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
128507 error node v0.12.4
128508 error npm  v2.10.1
128509 error code ELIFECYCLE
**128510 error react-slick@0.7.2 prepublish: `babel ./src --out-dir ./lib && ./node_modules/.bin/gulp dist`
128510 error Exit status 1**
128511 error Failed at the react-slick@0.7.2 prepublish script 'babel ./src --out-dir ./lib && ./node_modules/.bin/gulp dist'.
128511 error This is most likely a problem with the react-slick package,
128511 error not with npm itself.
128511 error Tell the author that this fails on your system:
128511 error     babel ./src --out-dir ./lib && ./node_modules/.bin/gulp dist
128511 error You can get their info via:
128511 error     npm owner ls react-slick
128511 error There is likely additional logging output above.
128512 verbose exit [ 1, true ]

**Comment by akiran** [comment]
@playtocrazy  How did you try to install ?

Have you run this command in your project ?
```
npm install react-slick
```

**Comment by playtocrazy** [comment]
@akiran 
I just clone this project and run `npm install`.
Does it have to run `npm install react-slick` before `npm install` ?
thank your reply.

**Comment by akiran** [comment]
@playtocrazy 
Can you install babel globally and then run `npm install` in the cloned repo
```
npm install -g babel
npm install
```

**Comment by playtocrazy** [comment]
I tried your instructions, but it still give me the same error messages.

**Comment by playtocrazy** [comment]
@akiran 
Hi, I give up to find the solution for this error,
Instead, I build one new project and run `npm install react-slick`,
and do some test code with *require react-slick*, now it works fine!

thanks for your support.

**Comment by carrington-115** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: daily-planner-app@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.1 || ^16.0.0 || ^17.0.0" from react-slick@0.28.1
npm ERR! node_modules/react-slick
npm ERR!   react-slick@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
PS C:\Users\Tosh7\Desktop\daily-planner-app> npm i react-slick --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: daily-planner-app@0.1.0  
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.1 || ^16.0.0 || ^17.0.0" from react-slick@0.28.1
npm ERR! node_modules/react-slick
npm ERR!   react-slick@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
PS C:\Users\Tosh7\Desktop\daily-planner-app> npm install react-slick
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: daily-planner-app@0.1.0  
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.1 || ^16.0.0 || ^17.0.0" from react-slick@0.28.1
npm ERR! node_modules/react-slick
npm ERR!   react-slick@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.     
npm ERR!
npm ERR! See C:\Users\Tosh7\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tosh7\AppData\Local\npm-cache\_logs\2022-04-06T10_14_55_281Z-debug.log

This is the error I get while installing react-slick
