### ISSUE TITLE
Wrap slider elements inside `<ul>`

### ISSUE THREAD

**Issue by vijayranghar** [akiran/react-slick#1318]
Hi,

First of all, thanks for creating this wonderful plugin. I am facing a problem which I think a lot of other people have faced. 

I want to wrap all of my slides which are `li` inside `ul`. I went through the documentation and found that `slide` prop can be used for changing the `container` element. `Slide` takes an element name as string. The `default` is  `div`, I changed it to `ul` but still I'm getting `div` as container div.
https://codesandbox.io/s/0xjlvkp9jl

**Comment by howieweiner** [comment]
Looks like the element is hard-coded?
https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L722

**Comment by vijayranghar** [comment]
Yeah, I figured out the same. It's strange there is a prop for container div.

**Comment by tusharshuklaa** [comment]
I think this issue got closed without any resolution. Any update on this?? I'm porting my website from plain jQuery to React and I can't seem to have this functionality which I already have in jQuery Slick.

**Comment by tusharshuklaa** [comment]
> Hi,
> 
> First of all, thanks for creating this wonderful plugin. I am facing a problem which I think a lot of other people have faced.
> 
> I want to wrap all of my slides which are `li` inside `ul`. I went through the documentation and found that `slide` prop can be used for changing the `container` element. `Slide` takes an element name as string. The `default` is `div`, I changed it to `ul` but still I'm getting `div` as container div.
> https://codesandbox.io/s/0xjlvkp9jl

@vijayranghar  Were you able to fix this?

**Comment by vijayranghar** [comment]
Nope @tusharshuklaa no way to do it :(

**Comment by gorfadvijay** [comment]
> I think this issue got closed without any resolution. Any update on this?? I'm porting my website from plain jQuery to React and I can't seem to have this functionality which I already have in jQuery Slick.

@tusharshuklaa have you find any solution mate ??
