### ISSUE TITLE
Thumbnails mode

### ISSUE THREAD

**Issue by dmitry** [akiran/react-slick#132]
Does someone interested to accomplish something like that:
https://github.com/kenwheeler/slick/pull/648

Another solution is to make two slicks connected, so every state change in one will be automatically transfered to the other.

**Comment by akiran** [comment]
Custom Pagging is already implemented. 

asNavFor will implemented soon and is tracked in the issue #47

**Comment by heshamelmasry77** [comment]
its actually xx and not working properly
