### ISSUE TITLE
Pass slide index as a prop to a nextArrow or prevArrow component

### ISSUE THREAD

**Issue by s1100h** [akiran/react-slick#1321]
Hello, I have a quick questions is it possible to pass the slide index as a prop to a custom nextArrow and prevArrow component? Ultimately I was to update the route when the user clicks on each on of the arrows. I am currently using afterChange to handle that, but the routes get mixed up quickly if I click the arrows to fast.

This is a sample of the code. I want to take the ```this.setCurrentSlideUrl(event)``` and pass it as a prop to the ```NextArrow``` and ```PrevArrow``` components.
```
const NextArrow = (props) => {
  const { onClick } = props;
  return <FaAngleDoubleRight className={'FeaturedPhotos-toggle right'} onClick={onClick} />;
};

const PrevArrow = (props) => {
  const { onClick } = props;
  return <FaAngleDoubleLeft className={'FeaturedPhotos-toggle left'} onClick={onClick} />;
};

```
```
setCurrentSlideUrl(id) {
  EventPhotos.getSinglePhoto(id).then((data) => {
    history.push(`/${data[0].title}`);
 });
}
render() { 
const settings = {
    dots: true,
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    nextArrow: <NextArrow />,
    prevArrow: <PrevArrow />,
    afterChange: (event) => this.setCurrentSlideUrl(event)
   }

return ( 
     <div className="FeaturedPhotos">
        <Slider {...settings}>
          {
            (gallery) ? (
              gallery.map((value, index) => (
                <img key={value.title} src={value.medium} alt={value.title} onClick={(event) => openLightbox(index, event)} />
              )
            )) : ""        
          }
        </Slider>
      </div>
   );
}
```

**Comment by Mr-Chilly** [comment]
sorry! late to the party....

fo anyone else search this, if consider your settings object calls a component for the arrows:

```
const settings = {
    nextArrow: <Arrow />,
    prevArrow: <Arrow />,
}
```

you Arrow component's props already contain the current index:

```
const Arrow = (props) => {
   console.log(props);
   return <div>Arrow</div>
}
```

in the above example - the prop is lost in the destruture: `const { onClick } = props`, adding `currentSlide` to the destrucuture or adding rest props:

`const { onClick, currentSlide } = props`
or
`const { onClick, ...restProps } = props`
`restProps.currentSlide`

should do the trick
