### ISSUE TITLE
why initialIndex not working with dynamic image list?

### ISSUE THREAD

**Issue by jun-hyeok** [akiran/react-slick#1325]
Hi, i'm using react-slick in my project.
I have a question in initialIndex.

My process likes this.
1. images URL load from server with axios
2. `return this.state.imageURL.map((image, index) => <Img key={index} src={image} />)`
3. and render it.

and i give a setting 
` initialSlide: 3,  `

but carousel not start at index 3.

How can i start index 3?

**Comment by myaskevich** [comment]
Maybe because the prop name is `initialSlide`?

**Comment by jun-hyeok** [comment]
@myaskevich no, it's my mistake move code from my IDE to github.
I wrote `initialSlide: 3` in my code.

**Comment by sergiubologa** [comment]
@jun-hyeok I can't find in docs any property called `initialSlide`. What is it? Where have you found it?

**Comment by jun-hyeok** [comment]
@sergiubologa https://react-slick.neostack.com/docs/api#initialSlide this one?

**Comment by maddhruv** [comment]
@jun-hyeok is your issue resolved?
or need some help?

**Comment by jun-hyeok** [comment]
@maddhruv Oh, I didn't realize this issue not closed.
It was just my mistyping :(
