### ISSUE TITLE
slickGoTo isn't working while already in animation

### ISSUE THREAD

**Issue by danielrea** [akiran/react-slick#1336]
[CodeSandBox replication]( https://codesandbox.io/s/1zmrn8wzy3)

Sorry if this has been posted elsewhere I couldn't find something similar when searching.

I am trying to get animation working when using slickGoTo on hover of an item ( represented by the coloured boxes ). To demonstrate the issue you can move mouse back and forward across the boxes, most of the time the colour you land on will not represent the image it is linked to.

It seems like when slickGoTo is called while it is currently in an animation it will not be registered, is there a way to force an override to ensure that where you land on the boxes, will update the carousel to the relevant slide.

Any help would be greatly appreciated, ofcourse this all works fine when animation is off, but if possible I would like to have it animated.

Thanks

**Comment by MocanuMarius** [comment]
This issue has been going on for a full half year, it's strange it still hasn't been fixed. It's such an obvious and big problem.

**Comment by laurentiu-dancu** [comment]
Leaving this here for the next poor soul that finds this thread: https://github.com/akiran/react-slick/blob/master/src/default-props.js
Setting `waitForAnimate` to false will skip the animation if there's already an ongoing slickGoTo animation.
