### ISSUE TITLE
any desire or work in progress for autoplay on screen?

### ISSUE THREAD

**Issue by do917** [akiran/react-slick#1341]
i used react-slick recently for a project but had to implement autoplay only when the carousel was on screen.  Ie. if the carousel is later down the page and not visible on the first load, autoplay should not start until the user scrolls down and carousel is in view. 

i was wondering if this is a commonly requested feature and would be willing to put in the time to create a pr.

**Comment by akiran** [comment]
You can auto play method to implement this functionality

Check this example
https://github.com/akiran/react-slick/blob/master/examples/AutoPlayMethods.js
