### ISSUE TITLE
Replication of a slick

### ISSUE THREAD

**Issue by vivekverma1993** [akiran/react-slick#1342]
https://codesandbox.io/s/31z8rvmmyp

**Comment by akiran** [comment]
Can you describe about issue and reopen

**Comment by vivekverma1993** [comment]
https://codesandbox.io/s/kw0pol2v97

Sorry i have missed adding  a param in the code i.e  slidesToShow. So the issues is i am trying to display a set of images with react-slick and i want two slicks at a time present on the view. so i passed 
slidesToShow = 2 in Slider Props. This issue appears when only one is displayed with slidesToShow set to 2. Since data i am fetching is dynamic, so i have no control over the number of images fetched.
