### ISSUE TITLE
Mobile issue. Window Scroll broken on mobile devices after selecting an item from slider.  

### ISSUE THREAD

**Issue by AndriiUhryn** [akiran/react-slick#1350]
Simply touch on mobile or tablet slide item in the vertical Slider and then try to scroll the page, getting this error.

<img width="421" alt="screenshot at aug 29 16-26-22" src="https://user-images.githubusercontent.com/22635238/44790582-5e50a900-aba8-11e8-919c-db5264730e41.png">
<img width="557" alt="screenshot at aug 29 16-26-02" src="https://user-images.githubusercontent.com/22635238/44790583-5ee93f80-aba8-11e8-8e67-6816c0acbb3a.png">

**Comment by rostyslavP** [comment]
The same story
