### ISSUE TITLE
setState in beforeChange disables slider

### ISSUE THREAD

**Issue by mikhuang** [akiran/react-slick#136]
I'm trying to call setState on the parent component in the beforeChange callback. This seems to disable the slider. However, calling setState in the afterChange callback works fine. Any ideas? Also, is there a jsfiddle that has a barebones setup of react-slick in it? I couldn't quite get one working.

**Comment by amoenk** [comment]
I can corroborate this. Any setState call from within the beforeChange will cause the slider to update exactly once without animating. No further clicks to the next or previous buttons will change the current slide. This occurs even if the changed state property is not related to the slider.

**Comment by jjalonso** [comment]
here the same bug.

**Comment by tvogels** [comment]
Did anyone solve this? I have the same problem, but this also happens sometimes when setting the state on the parent component on a button click.

**Comment by andfaulkner** [comment]
Having the same issue, and have noticed it also occurs if you re-render the slider on prop change (e.g. when using redux's mapStateToProps after a new store is returned following a dispatched action)

**Comment by ivliag** [comment]
+1

**Comment by jjalonso** [comment]
I found this problem about 6 month ago. I think the project is dead. It
need a fork or something :-/

**Comment by bsadecki** [comment]
+ 1

**Comment by 3em** [comment]
is smbody solved it ?

**Comment by jjalonso** [comment]
I guess this project is dead? Im sending this from my mailbox but anyway...
is long time since that and I didnt see an answer here.

**Comment by akiran** [comment]
Setting state of parent component in beforeChange is not a good idea, because it cause slider to render and effects animation

Can you replicate you usecase with this. I will try a work around
https://jsfiddle.net/kirana/20bumb4g/

**Comment by akiran** [comment]
I welcome PR's.

**Comment by VentroArt** [comment]
Has anyone found any solution?

**Comment by Grsmto** [comment]
The workaround I found for this is to avoid triggering a re-render by having whatever element you want to access the `beforeChange` parameter as a separate component.
For example I needed to have access to the active slide from a `<SliderTabs>` component. I attached a ref to it from my parent component `this.sliderTabs` and I did:
```
beforeChangeHandler(_, nextIndex) {
    this.sliderTabs.setState({ activeTab: nextIndex });
}
```

**Comment by silicakes** [comment]
Any news on this?

**Comment by stevemao** [comment]
Even with `afterChange` and `setState()` is buggy. When it's rerendered my slider just scroll to the right automatically. Have to use @Grsmto workaround.

**Comment by yantakus** [comment]
Another workaround is to wrap the slider into a separate component and add
```
shouldComponentUpdate() {
  return false;
}
```
to it.

**Comment by RuslanYurchenko** [comment]
+1

**Comment by eggzon** [comment]
I had the same problem with refreshing the page, what i did was sending the event.preventDefault(); then calling the next.slickNext();

It works!

**Comment by ClintonMorrison** [comment]
It seems like setState from parent components causes problems from either beforeChange or afterChange.

**Comment by Trolleymusic** [comment]
Just want to +1 to @yantakus 's solution - I'm now using the main component to control rendering of slides and exciting other stuff and then having a simple slider container component.

**Comment by laveesingh** [comment]
@yantakus's solution seems to handle the use case. In case anyone has a different opinion, please feel free to reopen the issue.

**Comment by ClintonMorrison** [comment]
@laveesingh I think calling setState from those hooks is a valid use case. 

I found that anything which trigger the component to re-render (for example forceUpdate), as well as changing the state or props, also breaks the carousel.

You shouldn't have to wrap the slider in a special component that ignores all updates anyway. What if you need to change the contents of the slider, or any of the settings? 

I think this is something that needs to be fixed, or the library will seem broken to people who try it. It's a great slider; it should support being re-rendered. Earlier versions of this library didn't have that problem. 

Can you reopen the issue?

**Comment by laveesingh** [comment]
@ClintonMorrison did you check this SlickGoTo [example](https://github.com/akiran/react-slick/blob/dev/examples/SlickGoTo.js). I am setting state in afterChange hook, and that works just fine.

**Comment by yantakus** [comment]
@laveesingh afterChange doesn't fit in most cases, when action is required immediately when a slide changes.

**Comment by silicakes** [comment]
I completely agree with @ClintonMorrison and @yantakus - having setState inside beforeChange is an extremely valid case: be it analytics or changes/updates you want to trigger simultaneously.

**Comment by laveesingh** [comment]
Guys, I have managed to effectively use both `afterChange` and `beforeChange` in this [example](https://github.com/akiran/react-slick/blob/dev/examples/SlickGoTo.js) to set state in parent component. I had to create another wrapper to give space for `shouldComponentUpdate` hook. This [commit](https://github.com/akiran/react-slick/commit/b08119fe6f9e4fa730d2db86a67ef6c2c634ca13) should help you, let me know if it doesn't.

**Comment by silicakes** [comment]
@laveesingh - great example!
Essentially, I reckon you can toggle your `shouldComponentRender` prop (updateCount) between true and false, to get the same effect.

However it does forces your components to share and be aware of the short circuiting state.
The more complex state you have, the more props you'll need to pass into your SliderWrapper.

On the other hand, you'll need to update a single prop that will decide on whether it should be updated or not - rather than having react do it for you.

From your knowledge of the code, how hard it would be to prevent the slider from breaking from within the library itself?

**Comment by laveesingh** [comment]
@silicakes as long as my knowledge is concerned, here are the points that I'd like to state...
First of all the slider is not breaking, by setState statement, it's just that the animation is gone during the slide change.
Secondly, if the Slider re-renders, the animation is supposed to go away. 
Please correct me, if I'm wrong or you have something to suggest.

**Comment by silicakes** [comment]
@laveesingh You're right with the fact that only the animation is affected, however it is never restored (after the update is finished).

That's why I'd go with looking weather the slider is being animated at the moment, if so, I'll push the update to a queue and will invoke it on transitionEnd.
For that, You'll still need to create another wrapping component - however this will be done internally:

```
class Wrapper extends React.Component {
  constructor(props) {
    super(props);
   this.state = {
    sliderProps: props
   }
   this.transitioning = false;
  }

  componentWillReceiveProps(nextProps) {
    if(this.transitioning) {
     // store the update in a queue during the animation
      updateQueue.push({sliderProps: nextProps});
    } else {
      // dispatch the update immediatly
      this.setState({sliderProps: nextProps});
   }
  }

  // short circuit the entire update cycle just in case the react team will decide to change its behavior (again)
  shouldComponentUpdate() {
    return !this.transitioning;
  }

// releasing all the accumulated states
  onTransitionEnd = () => {
       while(this.updateQueue.length) {
        let {sliderProps} = updateQueue.shift();
        this.setState({sliderProps});      
      }
  }

 // child component will receive this function and will invoke it on every start/end of transition 
  onTransition = (isTransitioning) => {
    if(isTransitioning !== this.transitioning) {
      if(isTransitioning === false) {
        onTransitionEnd();
       } else {
         //...you can do onTransitionStart here
       }
    } 
     this.transitioning = isTransitioning;
  }

  render() {
      let {sliderProps} = this.state;
      return <Slider {...sliderProps} onTransition={this.onTransition}>
  }
}
```

What do you think?

**Comment by jmschlmrs** [comment]
This was fixed for me in the recent V0.21.0 release

**Comment by obedparla** [comment]
no it wasn't. Still having that put on V.0.23.1 @jmschlmrs

**Comment by dixoncheng** [comment]
There is another workaround, not sure if this will work for everyone. Call `setState` inside a `setTimeout`:

```
beforeChange: (oldIndex, newIndex) => {				
	setTimeout( () => { this.setState({ var: value }); }, 10 );			
}
```

**Comment by max-arias** [comment]
The above fix with the setTimeout worked for me. Thanks @dixoncheng

**Comment by zverexe** [comment]
Thanks, @dixoncheng your workaround worked for me as well

**Comment by zhangyanling77** [comment]
maybe you should use useRef store your state or data, not useState.
in fact, it works!

**Comment by twobyte** [comment]
This bug is still an issue.

It seems impossible to change the slider’s currentSlide state within the beforeChange and afterChange callbacks without also reloading ALL the slide components. This is causing GatsbyImages to disappear and reappear on every slide action.

 I have tried using both functional components and classes, changing ref, context and useState, and no matter how I manage state, every-time the state is changed within the callbacks, even when using a setTimeout, all the slides are reloaded and the images briefly disappear.

Here is a minimal reproducible example, if you view the console you should see what I mean, 
https://codesandbox.io/s/beforechange-afterchange-react-slick-forked-lhgyxj?file=/src/components/slickCarousel.js

I haven’t been able to get the wrapping component workaround to work for me yet. Any tips appreciated. Thanks.

**Comment by benjaminbenais** [comment]
I solved the issue by wrapping the Slider with React.memo in its own file:

```
// CustomSlider.js
import React from 'react';
import Slider from 'react-slick';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const CustomSlider = React.memo(({ data, beforeChange }) => {
  const settings = {
    // your settings here
  };

  return (
    <Slider
      {...settings}
      beforeChange={beforeChange}
    >
      {data.map((item) => (
        <img key={item.id} src={item.thumbnail} />
      ))}
    </Slider>
  );
});

export default CustomSlider;
```

And then using it like this:

```
import { useEffect, useState, useMemo, useCallback } from 'react';

import CustomSlider from './CustomSlider';

const Press = () => {
  const [data, setData] = useState([]);
  const [currentSlide, setCurrentSlide] = useState(null);

  useEffect(() => {
    const getData = async () => {
      try {
        const response = await fetch(some-url`).then((res) =>
          res.json()
        );

        setData(response);
      } catch {
        return null;
      }
    };

    getData();
  }, []);

  const currentQuote = useMemo(() => {
    return data[currentSlide]?.quote || '';
  }, [currentSlide, data]);

  const beforechange = useCallback((_, newIndex) => {
    setCurrentSlide(newIndex);
  }, []);

  return (
    <div>
        <CustomSlider data={data} beforeChange={beforechange} />
        {currentQuote && <p>{currentQuote}</p>}
    </div>
  );
};

export default Press;
```

The important part is to wrap the beforeChange method in the useCallback hook. That way, the CustomSlider component wrapped with React.memo won't re-render :) Hope it helps.
