### ISSUE TITLE
Infinite scroll not working proper

### ISSUE THREAD

**Issue by bipsBro** [akiran/react-slick#1362]
Hello there, 

I got issues on focusOnSelect, Infinite scroll and centerMode not working proper while slider is less or equal to three.
It need to scroll infinitely.
Here is the sandbox link
https://codesandbox.io/s/4jpqprrxy7

**Comment by ramojej** [comment]
@bipsBro were you able to solve the scroll infinite? It's true that it's not looping infinitely when slide items are only 3.
