### ISSUE TITLE
[Feature request] Switch off lazy loading after first swipe

### ISSUE THREAD

**Issue by kenNg1** [akiran/react-slick#1364]
Hi, thanks for creating this great library.

I have a list of cards using the carousel to render images and I've implemented lazy loading to improve page load times. However, images loaded lazily take around 2 seconds to appear.

Is it possible to turn off lazy loading (and load the necessary images in the background) after the user has swiped right once? I feel this would enhance the user's experience as subsequent swipes would have no (or less) delay. Thanks!

### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by flieks** [comment]
any update ?

or a way to always preload the next picture...

**Comment by flieks** [comment]
ok lot's of people made a PR but nothing approved yet:
https://github.com/akiran/react-slick/pull/1495
https://github.com/akiran/react-slick/pull/1516
https://github.com/akiran/react-slick/pull/1494
https://github.com/akiran/react-slick/pull/1496

**Comment by kenNg1** [comment]
Closed due to inactivity
