### ISSUE TITLE
Slider crashes while swiping concurrently with viewport scrolling

### ISSUE THREAD

**Issue by zulkamal** [akiran/react-slick#137]
Having this issue on: 
- Chrome iOS.
- A single item slider

Steps to reproduce:

1. Swipe (left or right) on a slider.
2. Swipe up or down to concurrently scroll the viewport
3. Continue swiping to the end of the slider.
4. The slider moves to the next slide but now all touch, button mechanisms are lost. Slider is effectively crashed until page is refreshed.

The simple fix I did was to exit swipeMove when viewport is scrolling:

```javascript
swipeMove: function swipeMove(e) {
    ...
    // Also move this higher up in swipeMove
    var swipeDirection = this.swipeDirection(this.state.touchObject);
    if (swipDirection === 'vertical') { return; }
    ...
```
Not sure if this fix affects anything else though. I can do a PR if this is acceptable.

**Comment by akiran** [comment]
this issue is fixed in latest release
