### ISSUE TITLE
how to custom arrows?

### ISSUE THREAD

**Issue by leeseean** [akiran/react-slick#1374]
I want to change the styles of prev button and next button, how to custom?

**Comment by firestar300** [comment]
**Index.js(x)**
```javascript
import React, { Component } from 'react'

import Slider from 'react-slick'

import SliderArrow from '../components/Global/SliderArrow'

class Index extends Component {
  render() {
    const sliderSettings = {
        dots: true,
        infinite: true,
        prevArrow: <SliderArrow to="prev" />,
        nextArrow: <SliderArrow to="next" />,
        slidesToShow: 1,
        slidesToScroll: 1
    }

    return (
      <div className="main">
        <Slider {...sliderSettings}>
           <div>
              <h2>1</h2>
           </div>
           <div>
              <h2>2</h2>
           </div>
           <div>
               <h2>3</h2>
           </div>
        </Slider>
      </div>
    )
  }
}

```

**SliderArrow.js(x)**
```javascript

import React from 'react'

import Icon from './Icon'

export default ({to}) => (
  <button type="button" className={`button button--text button--icon slick-arrow slick-${to}`} aria-label={to}>
    <Icon className="icon" icon={to} />
  </button>
)
```

**Comment by maddhruv** [comment]
@leeseean is your issue resolved with the above code?
I am closing this as of now
Feel free to reopen :smile:

**Comment by yasin749** [comment]
You can try this way

render() {
    const ArrowLeft = (props) => (
        <button
            {...props}
            className={s.prev}/>
    );
    const ArrowRight = (props) => (
        <button
            {...props}
            className={s.next}/>
    );

    const settings = {
        arrows: true,
        prevArrow: <ArrowLeft />,
        nextArrow: <ArrowRight />,
    };

    return (
        <Slider {...settings}>
            {/* items... */}
        </Slider>
    )
}

**Comment by yasin749** [comment]
You can try this way

    render() {
        const ArrowLeft = (props) => (
            <button
                {...props}
                className={s.prev}/>
        );
        const ArrowRight = (props) => (
            <button
                {...props}
                className={s.next}/>
        );

        const settings = {
            arrows: true,
            prevArrow: <ArrowLeft />,
            nextArrow: <ArrowRight />,
        };

        return (
            <Slider {...settings}>
                {/* items... */}
            </Slider>
        )
    }

**Comment by ondrejrohon** [comment]
imho this should be mentioned in README

**Comment by golestanirad** [comment]
why cannot i find that `prevArrow` or`nextArrow` in the doc? are they still valid?

**Comment by Nikhil-devloper** [comment]
try this code it works for me :100: 
adjust left-right position's according to your need.


.slick-prev:before{
    /* background-color: blue !important; */
    width: 46px;
    height: 46px;
    content: '' !important;
    position: absolute;
    top: -11px;
    left: -31px;
    background-image: url('http://lorempixel.com/50/50');
}


.slick-next:before{
    /* background-color: blue !important; */
    width: 46px;
    height: 46px;
    content: '' !important;
    position: absolute;
    top: -11px;
    left: 0px;  
    background-image: url('http://lorempixel.com/50/50');
}

**Comment by mecharmor** [comment]
Does the slider render react components??
When I try `prevArrow={<FontAwesomeIcon icon={faChevronLeft} />}`
the slider will break. but when I use `prevArrow={<img src={some_svg} />}` it works.

I see that this library itself is a port to the jQuery slick slider so perhaps that is the issue?

**Comment by Hahlh** [comment]
@mecharmor 

You could try to remove the { }:

![image](https://user-images.githubusercontent.com/45669613/108630416-16532a00-7465-11eb-9a10-1fe9a6c203e3.png)

**Comment by luming63** [comment]
hello! Lao Ming.

**Comment by ZaidKhan144** [comment]
@Nikhil-devloper Thanks man, After so much time tweaking around, your solution works for me.

**Comment by rever96** [comment]
Can u add an example that uses image instead of symbol of arrow?

**Comment by muskanbhatnagar16** [comment]
> @Nikhil-devloper Thanks man, After so much time tweaking around, your solution works for me.

Can you share a snapshot of how you made it work?

**Comment by ZaidKhan144** [comment]
@muskanbhatnagar16 Sure, no worries! Below I have my whole component of Events where I have used the carousel.

```
import React from 'react'
import './styles.css'
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import EventCards from './EventCards'

const Events = (props) => {

    const image = props.data.image,
          groupName = props.data.groupName,
          date = props.data.date,
          time = props.data.time,
          eventName = props.data.eventName,
          numOfAttendees = props.data.numOfAttendees;

    return (
        <div className="event-card-container">
            <div className="event-card">
                <img className="event-card-image" src={image} alt={eventName}/>
                <div className="event-card-main">
                    <p>{date} {time}</p>
                    <p>{eventName}</p>
                    <p>{groupName}</p>
                    <p>Attendees: {numOfAttendees}</p>
                </div>
            </div>
        </div>
    )
}

const EventInfo = (props) => {

    var data = props.data;
        var newsTemplate;
        var settings = {
            dots: false,
            infinite: false,
            accessibility: true,
            slidesToShow: 4,
            slidesToScroll: 1,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 700,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                    }
                }
            ]
        };

        if (data.length > 0) {
            newsTemplate = data.map(function(item, index) {
                return (
                    <div key={index}>
                        <Events data={item} />
                    </div>
                );
            });
        } else {
            newsTemplate = <p>Please add some GroupCards</p>;
        }

    return (
        <div className="news">
        <h1 className="text-6xl font-bold">upcoming events</h1>
            <Slider {...settings}>{newsTemplate}</Slider>
        </div>
    );
}

const EventCarousel = () => {
    return (
        <div className="carousel">
            <EventInfo data={EventCards} />
        </div>
    );
}

export default EventCarousel
```
