### ISSUE TITLE
We can add a prop so that Slick does not add width: 100%; display: inline-block; ?

### ISSUE THREAD

**Issue by CharlyJazz** [akiran/react-slick#1378]
Slick is adding those styles to the Slider items and I must use important in the original styles to not lose them. This would be a very good idea, this is not the first time this has happened with Slick.

![untitled](https://user-images.githubusercontent.com/12489333/46584765-2c4b2600-ca35-11e8-8d9b-c7bdd46389e6.png)

``` JSX 
import React from 'react'
import ImageCircle from '../ImageCircle';
import Slider from "react-slick";
import './styles.scss'

export default ({ images, isAvatar }) => {
  const settings = {
    dots: false,
    infinite: true,
    autoplaySpeed: 2000,
    slidesToShow: 5,
    slidesToScroll: 5,
    autoplay: true,
    responsive: [],
    arrows: false,
    centerPadding: '100px',
    accessibility: false,
  };
  return (
    <div className='GalleryImages'>
      <Slider {...settings}>
        {
          Array.isArray(images) && images.map((img) => (
            <div className='BlockImage' key={img.url} >
              <div className='BlockOverlary' />
              {
                isAvatar ? (
                  <ImageCircle
                    style={{
                      width: '100px',
                      height: '100px',
                      margin: 'auto'
                    }}
                    img={img.url}
                    alt={img.alt}
                  />
                ) : (
                    <img
                      src={img.url}
                      alt={img.alt}
                    />
                  )
              }
            </div>
          ))
        }
      </Slider>
    </div>
  )
}

```

If you allow me, I can do a PR. But we should discuss the name of the prop.

**Comment by wenisy** [comment]
any updates here?

**Comment by CharlyJazz** [comment]
No

**Comment by Romcol** [comment]
Hi, I found that if you move the rendered div (here the one with class BlockImage) to a external function, slick doesn't add those props. Not sure it can help though

**Comment by intelligence** [comment]
> Hi, I found that if you move the rendered div/component (here the one with class BlockImage) to an external function, slick doesn't add those props. Not sure it can help though

Could you elaborate what you mean?

**Comment by mimiqkz** [comment]
Any solution to this yet? I need to change the width so that in mobile, it won't show just 1st card on load, but a bit of the 2nd card so that user knows this is a slider

**Comment by Romcol** [comment]
> > Hi, I found that if you move the rendered div/component (here the one with class BlockImage) to an external function, slick doesn't add those props. Not sure it can help though
> 
> Could you elaborate what you mean?

```
     <Slider {...settings} className={classes.slider}>
        {items..map(item => (
          <MyComponent
            key={item.position}
            otherProp={item.otherProp}
          />
        ))}
      </Slider>
```

I think that if you separate your code like this, the inline style won't be added. Other solution is you override the inline style. Hope it helps

**Comment by alexfromesper** [comment]
To anyone still looking for a solution..

Try wrapping your list components in a react fragment.
This worked for me.

`<React.Fragment key={id}>
 <Item>
 </Item>
</React.Fragment>`

**Comment by McGern** [comment]
@alexfromesper Brilliant, that worked for me. No idea why it should work, but it does.

**Comment by socker210** [comment]
@alexfromesper This solution is the best. Thank you.

**Comment by brunoborta** [comment]
By using fragments around an arrow component, the functionality is gone :(
