### ISSUE TITLE
In infinite carousal centeMode and focusOnSelect the direction of slide animation is not Correct

### ISSUE THREAD

**Issue by ddaspodder** [akiran/react-slick#1380]
In infinite circular carousal with centerMode and focusOnSelect set to true, if I select any slide, it comes to the center but the direction in which the animation takes place is not according to the shortest number of slides to scroll.
Please go through the image to understand it.
![reactslick](https://user-images.githubusercontent.com/43873636/46593591-e2247c00-caea-11e8-9576-a11686ef4203.png)

The solution is to modify some code in the **innerSliderUtils.js** file under **utils** folder.

1. Replace line no. **202** and **203** with the following code
**animationSlide = infinite ? animationSlide : slideCount - 1;
finalSlide = infinite ? animationSlide % slideCount : slideCount - 1;**

2. Modify the siblingDirection function in line no. **769** with this one..

**var siblingDirection = (exports.siblingDirection = function siblingDirection(
  spec
) {
  if (!spec.centerMode) {
    if (spec.targetSlide > spec.currentSlide) {
      if (spec.targetSlide > spec.currentSlide + slidesOnRight(spec)) {
        return 'left';
      }
      return 'right';
    } else {
      if (spec.targetSlide < spec.currentSlide - slidesOnLeft(spec)) {
        return 'right';
      }
      return 'left';
    }
  }
  else {
    if (spec.targetSlide > spec.currentSlide) {
      if (
        spec.targetSlide - spec.currentSlide <
        spec.slideCount - spec.targetSlide + spec.currentSlide
      ) {
        return 'right';
      }
      return 'left';
    } else {
      if (
        spec.currentSlide - spec.targetSlide <
        spec.slideCount + spec.targetSlide - spec.currentSlide
      ) {
        return 'left';
      }
      return 'right';
    }
  }
});**

**Comment by ddaspodder** [comment]
please let me know if there is any update regarding this issue.

**Comment by maddhruv** [comment]
@ddaspodder would you like to make a PR?

**Comment by ddaspodder** [comment]
@maddhruv  yes please do so. Thank you. Please let me know if anything is required from my side.

**Comment by ddaspodder** [comment]
@maddhruv  please let me know if there is any update regarding this issue. I am waiting for your response.

**Comment by maddhruv** [comment]
@ddaspodder I was asking if you want to make a Pull Request regarding this

we (team) will take a little more time to resolve this issue
planning for an upgrade and some promising changes in the core

**Comment by ddaspodder** [comment]
yes @maddhruv  i want to make a pull request. Please provide me access for the same.

**Comment by maddhruv** [comment]
I think you dont need a permission to do that!
Just simply fork this repo
Create your branch
Push your code to your branch
And make a pull request

**Comment by ddaspodder** [comment]
ok thanks. I will do that.

**Comment by juansalvatore** [comment]
I'm still having this issue, was there any solution added to the repo?

**Comment by BossBele** [comment]
Having this issue
