### ISSUE TITLE
React slick - text-align center or justify-content-center makes disappear texts 

### ISSUE THREAD

**Issue by SemihKoc** [akiran/react-slick#1382]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by maddhruv** [comment]
@SemihKoc Please provide more info into this!
either share your screenshot or code

**Comment by CharlesFJWilliamson** [comment]
Judging by the title, I think I've experienced the same issue. To add further information:

When wrapping <Slider> in a div with the following CSS:
```
display: flex

justify-content: center
```

the Slider appears on Render and then disappears immediately after.
