### ISSUE TITLE
update gulp to ^4.0.0 to fix npm vulnerabilities warnings

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#1390]
updating the gulp and webpack-dev-server packages and get the build and dev server working

**Comment by maddhruv** [comment]
should we also update webpack?

**Comment by akiran** [comment]
@maddhruv Yes, Lets update webpack to latest version

**Comment by maddhruv** [comment]
Can we do webpack stuff separately in a new issue & PR?

**Comment by maddhruv** [comment]
Doing webpack in #1394
