### ISSUE TITLE
[Question] How would I go about implementing an animation when my component is shown?

### ISSUE THREAD

**Issue by daydream05** [akiran/react-slick#1395]
Is there a props that allow animation to trigger when the component is the main focus?

For example, I'm using slick as a carousel slider and I would like text animation to show up whenever it transitions to the next slide. I'm using [react-reveal](https://www.react-reveal.com/examples/) for reference.

**Comment by akiran** [comment]
Checkout https://github.com/akiran/react-slick/blob/master/examples/CustomSlides.js example.

Implement a custom component that animates based on `active` prop change
