### ISSUE TITLE
A way to change drag sensitivity/amount

### ISSUE THREAD

**Issue by cloudsociety** [akiran/react-slick#1401]
Is there a way to change the drag sensitivity/amount? Currently, I find I have to drag slides a fair amount (30-50% of their width, average image width is 600+ px wide) for the switch to take. If I "flick" the slide a tiny amount (100ish px), the slider doesn't go to the next slide; it bounces back to the current slide. This feels like bad UX to me.

I'd like to be able to "flick" slides and have them progress to the next slide.

Possible in the current code base? Feature request?

**Comment by kamac** [comment]
You can increase sensitivity with a higher touchThreshold value (eg. touchThreshold: 1000 makes it very sensitive).

From slick carousel's documentation:

> To advance slides, the user must swipe a length of (1/touchThreshold) * the width of the slider

**Comment by tklkalok** [comment]
After increase sensitivity with a higher touchThreshold value, there is no effects and still very sticky, why?

**Comment by gabriel3iri** [comment]
still happens at the date, touchThreshold has no effect whatsoever
