### ISSUE TITLE
React 16.6 StrictMode: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by apepper** [akiran/react-slick#1406]
First of all, thanks for your package. It's quite a help to have it.

I just checked out the latest `react` `16.6.0` release. They extended APIs in `StrictMode`, that are now considered deprecated. `findDOMNode` is now considered deprecated.  See https://reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode for the full list.

If you add `React.StrictMode` around `Slick` you'll get the following console warning:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Track which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Track)
    in Track (created by InnerSlider)
    in div (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
    in Slider (created by ReactSlickDemo)
    in div (created by ReactSlickDemo)
    in StrictMode (created by ReactSlickDemo)
    in ReactSlickDemo

Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node
```

See it live on https://codesandbox.io/s/8j39k1pq8. Also see https://fb.me/react-strict-mode-find-node for how to get rid of the warning.

**Comment by akiran** [comment]
Thanks @apepper 

Can you raise a PR to fix this issue ?

**Comment by apepper** [comment]
> Can you raise a PR to fix this issue ?

Sorry, but no.

**Comment by andreytrofimov** [comment]
Hi @akiran 
Could you check PR #1442 to fix this issue?

**Comment by NasKadir123** [comment]
> Thanks @apepper
> 
> Can you raise a PR to fix this issue ?

Hi, @akiran! Is this issue still unsolved?
I'm getting the same error in react 16.10.0.
Thanks in advance.

**Comment by stahlmanDesign** [comment]
I think this PR could be safely accepted as it won't break any of the slider functionality, it's just a react maintenance issue.
