### ISSUE TITLE
centerPadding is not getting applied for centerMode slick slider.

### ISSUE THREAD

**Issue by nutank** [akiran/react-slick#141]
Hi, 

We are using slick react component for displaying slides in the center mode. And we needed to apply center padding for the slides. I am assuming this is not supported by the react-slick component yet.

It would be great if this could be supported anytime sooner.

@akiran Could this feature be added at the earliest please?

Thanks a lot!

**Comment by ankur0890** [comment]
Yes this is not working. If I am adding margin manually to slick-slide container height is increasing abruptly. Any work arounds?

**Comment by whitebeatle** [comment]
+1

**Comment by joshuarh** [comment]
+1

**Comment by alenb** [comment]
+1

**Comment by prrraveen** [comment]
+1

**Comment by selfagency** [comment]
+1 and not a fan of abandonware

**Comment by lukedar** [comment]
+1 Any plans to support this in the near future?

**Comment by akiran** [comment]
Yes, I welcome PR's

**Comment by renddiyeh** [comment]
hi guys, my [PR](https://github.com/akiran/react-slick/pull/396) is just been merged.
centerMode with centerPadding should be working now with the latest version `v0.12.3`.

**Comment by ajgilzean** [comment]
Seems to work but I had to use a negative pixel count.
