### ISSUE TITLE
Slider autoplay timer can be reset by changes to enclosing react DOM

### ISSUE THREAD

**Issue by greeble31** [akiran/react-slick#1414]
https://codesandbox.io/s/yvllj853oj

The slider will never advance, even though it's set to autoplay.

Explanation: The interval timer (bottom) causes a state change every 1000ms. This interferes with the InnerSlider's autoplay timer, even though the state change is to a parent of Slider, and the state change that has no bearing on Slider's state.

It seems this is being caused by repeated invocations of InnerSlider.componentWillReceiveProps(), but I am unsure of what the correct fix it. If you'd care to point me in the right direction, I'll file a PR.

**Comment by JaccoGoris** [comment]
I have this issue, When I change state with a react hook, the autoplay resets, only when no state changes happen anymore, does the autoplay resume. this doesn't make any sense..
