### ISSUE TITLE
asNavFor skipping certain items 

### ISSUE THREAD

**Issue by peltos** [akiran/react-slick#1416]
So I'm having a problem that I can't seem to solve.

I'm using the asNavFor variable to make 2 sliders move together while sliding. the first slider is the navigation showing 3 items and the second slider is the content. 

When I slide the slider left or right, it doesn't seem to react. When I slide again it will skip the first slide and goes straight to the second. 

This is the way I set it up.
https://codesandbox.io/embed/ox9k97my0y

I'm not sure if I'm doing something wrong or that the slick slider is doing something wrong. Could someone help me with this?

**Comment by sniperyork** [comment]
I have exactly the same problem. Not too sure what causes the issue here

**Comment by celdrake** [comment]
Hi all.

I have submitted a PR which should fix this issue. 
It would be great if you could check if this works for you as well.

https://github.com/akiran/react-slick/pull/1423

**Comment by jubskurian** [comment]
hi 

This is not working as expected, This commit  is reflecting in version 0.23.1 aswell, please take a pull from the below url and run, In asNaFor demo  alternate images are loading on carousel arrow click event.

Downloaded files from this url :https://github.com/akiran/react-slick

**Comment by jubskurian** [comment]
hi 

This is not working as expected, This commit  is reflecting in version 0.23.1 aswell, please take a pull from the below url and run, In asNaFor demo  alternate images are loading on carousel arrow click event.

Downloaded files from this url :https://github.com/akiran/react-slick

**Comment by ruhaise** [comment]
i can reproduce this issue

**Comment by brittonwalker** [comment]
I am also having this issue where it only activates next slide on every other slide. I removed my code and used the example, same issue.

**Comment by j4mesjung** [comment]
For those that need a quick fix, I reverted back to `0.23.1` and it is working normally.

**Comment by piovischioh** [comment]
> For those that need a quick fix, I reverted back to `0.23.1` and it is working normally.

Or you could use patch-package, I demo it in [the PR]( https://github.com/akiran/react-slick/pull/1423#issuecomment-481072707).
