### ISSUE TITLE
Allow Overflow on mobile 

### ISSUE THREAD

**Issue by andrew-oko-odion** [akiran/react-slick#1419]
on Mobile screens, there is no way to indicate to the user that there are more slides. 
how can I fix this? 

`current view on mobile.`
![screenshot from 2018-11-03 19-01-35](https://user-images.githubusercontent.com/4202928/47955691-ec2b8480-df9b-11e8-9252-776835be6b32.png)

`expected View on Mobile`
![screenshot from 2018-11-03 19-03-40](https://user-images.githubusercontent.com/4202928/47955699-036a7200-df9c-11e8-8868-e05e22928070.png)

**Comment by shaohaolin** [comment]
Follow up on this. +1
