### ISSUE TITLE
Codesandbox demo is broken

### ISSUE THREAD

**Issue by ummahusla** [akiran/react-slick#1420]
This looks broken to me - https://codesandbox.io/s/zzloxr09mp

**Comment by finppp** [comment]
This is how my page looked when I tried using react-slick

**Comment by mherodev** [comment]
It's broken because codesandbox wants the external CSS files to be added as External Resource Dependencies rather than manually referenced inside the HTML.

Here's a fixed version:

https://codesandbox.io/s/483zzj5po9
