### ISSUE TITLE
BUG WITH SCSS WHEN IMPORT THE STYLES

### ISSUE THREAD

**Issue by Wilmerj** [akiran/react-slick#1433]
Hi! I'm use this library with sass but when I import de styles of slick-carousel the carousel dont read the styles.

I import the files with sass from node modules with
`@import './slick.scss';
@import './slick-theme.scss';`

but the carousel dont take the styles

![captura de pantalla 2018-11-23 a la s 10 32 59 a m](https://user-images.githubusercontent.com/19375953/48951111-51272a00-ef0b-11e8-80af-c5f58ec60a4d.png)
![captura de pantalla 2018-11-23 a la s 10 33 10 a m](https://user-images.githubusercontent.com/19375953/48951112-51272a00-ef0b-11e8-9340-474507bcad30.png)

I take the styles of library in my project but dont execute.

Sorry for mi english, I dont domain this language

**Comment by seanwhudson** [comment]
This could be an issue with webpack or whatever you use to package your app. If one of your loaders changes the css class names but react-slick doesn't get updated, then it will not have any styles applied.

You want to exclude the css from being changed by webpack, which you can do one of two ways:
A) Somehow exclude the react-slick css from being loaded and transformed in your webpack loader
or B) Remove your import statement and just load it in your index.html using `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />`

**Comment by JasonTangJun** [comment]
Because you use css modules,all class names in css files are transformed.
