### ISSUE TITLE
When click the item, it will get focused and show the default border of the browser

### ISSUE THREAD

**Issue by YusongLiu** [akiran/react-slick#1439]
Repro in https://codesandbox.io/s/ppwkk5l6xx

In Chrome, for example, when we click the item
![image](https://user-images.githubusercontent.com/15144072/49138425-1ae21400-f32a-11e8-92e0-40bf6f798108.png)

Actual:
It shows the default border of the browser.

Expected:
Not show the default border of the browser. (outline: none;)

**Comment by alexmarmon** [comment]
Try this:
```
.slick-slide div {
  outline: none !important;
}
```

**Comment by feRpicoral** [comment]
I was having the same issue but @alexmarmon's solution didn't work.

What did the trick was adding

```css
div.rec * {
    outline: none !important;
}
```
