### ISSUE TITLE
Removing usage of deprecated React lifecycle hooks

### ISSUE THREAD

**Issue by tompere** [akiran/react-slick#1444]
Description:
Using React >= 16.3.x in StrictMode, deprecation warnings are thrown.
```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (created by ReactSlickDemo)
    in ReactSlickDemo

componentWillMount: Please update the following components to use componentDidMount instead: InnerSlider, Slider

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: InnerSlider

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Impact:
Other than not corresponding to react best practices, and bloating the console with errors in dev mode, this is effectively means react-slick will break in version 17.x.

[CodeSandBox reproduction](https://codesandbox.io/s/n3l6yvj3q0)

🌟 I've created a PR to remove usage of `componentWillMount` (#1443)
BUT, removing `componentWillReceiveProps` seems much more complicated...

**Comment by dlong500** [comment]
@akiran Now that React 16.9 is out the console gets littered with warnings even without enabling strict mode.  At the very least there needs to be a new release that renames the deprecated lifecycle functions to the `UNSAFE_*` variants.  After that I think its time to start figuring out how to refactor to best fit the newer React recommendations.  Note that I understand it can be difficult to find time to maintain projects, so I'm really just hoping to catch your attention to see what your plans are.

**Comment by akiran** [comment]
@dlong500 I Agree.

we can prefix deprecated lifecycle methods with  UNSAFE_*  until we refactor those components

**Comment by akiran** [comment]
Released react-slick@0.25.0 with this fix

**Comment by vertjs** [comment]
I have installed "react-slick": "^ 0.25.2", and here the same error

**Comment by vthanh6494** [comment]
same error here

**Comment by Emmanx** [comment]
> I have installed "react-slick": "^ 0.25.2", and here the same error

Likewise

**Comment by Xama-Dev** [comment]
same error here to

**Comment by theshashiverma** [comment]
0.25.2 wokring fine, have issues with current version

**Comment by douglasrcjames** [comment]
Bumping this issue

**Comment by williamjingo** [comment]
Same here

**Comment by jessicaariessa** [comment]
"react-slick": "^0.26.1" having the same issue

**Comment by NicolasHz** [comment]
Still same error.
![image](https://user-images.githubusercontent.com/23178565/87441625-ad036280-c5c9-11ea-9ef5-f90e51a92019.png)

**Comment by akiran** [comment]
I am working on it.

Will make a release with the fix this week.

**Comment by lowpolyfox** [comment]
> I am working on it.
> 
> Will make a release with the fix this week.

Did this fix come with version 0.27.0? I'm still seeing the error.

**Comment by SoyDiego** [comment]
Same error here! :(
![imagen](https://user-images.githubusercontent.com/19764334/89110484-50b69480-d44b-11ea-8002-940fb52fb2f0.png)

**Comment by meinu-chan** [comment]
> Same error here! :(
> ![imagen](https://user-images.githubusercontent.com/19764334/89110484-50b69480-d44b-11ea-8002-940fb52fb2f0.png)

is this bug or what?
bcs i catch same error

**Comment by buzzfair** [comment]
same here

**Comment by maxizhukov** [comment]
I have same error on 26.1

**Comment by akiran** [comment]
@maxizhukov use 27.12
