### ISSUE TITLE
Not using all slides, not updating tags

### ISSUE THREAD

**Issue by salientknight** [akiran/react-slick#1454]
I cannot recreate this off site because it relies on a data pull. Otherwise I would be happy to.

I have 23 slides rendering ranging from -4 to 19.  The page loads with slides 0 through three active. The first time I click next slides 4 through 7 are active. The second time I click next slides 6 through 9 and showing but slides 6 and 7 don't have the slick-active class and aria-hidden is still set to true. The third time I click next, slides 0 through 3 and shown The slides never advance past 9. In the HTML all slides are rendering correctly just not being shown and on the second click not being updated. 

With a 3 slide view, there is a similar problem where out of 50 slides only 23 are ever used. Also it's set to scroll by threes but it's only scrolling 1 at a time.

**Comment by maddhruv** [comment]
@salientknight thanks for coming up
can you share your code for reproduction
It would be very helpful for us to solve this

**Comment by salientknight** [comment]
So, it looks like when you create the slide show there are n+n-1 slides created and then the slide show loops through the first half of the slides and not the full set. So the slide show appears to be functioning, I just don't understand the need for the extra slides.

**Comment by salientknight** [comment]
It winds up with some rather wonky data issues. Sometimes moving through the slides the visible slide has aria-hidden="true" and doesn't have an "active" class. The next slides are set correctly. This causes issues with trying to add css to the active slide either by slick-active or aria-hidden="false".
