### ISSUE TITLE
InitialSlide

### ISSUE THREAD

**Issue by jmgarciamari** [akiran/react-slick#15]
Are InitialSlide enabled? I need it, is on defaultProps but I don't know if there is implemented.

**Comment by akiran** [comment]
Not yet implemented. I will do it soon

**Comment by jmgarciamari** [comment]
;) Ok Thanks a lot

**Comment by PapaMufflon** [comment]
:+1:

**Comment by steroberts89** [comment]
I've submitted a pull request which adds this functionality in
