### ISSUE TITLE
as-nav-for not working properly in react

### ISSUE THREAD

**Issue by akbar-pyt** [akiran/react-slick#1503]
> I have created the as-nav-for with the reference for the below example,
> https://react-slick.neostack.com/docs/example/as-nav-for/

But when i try this, that one is not working properly. 
The slider has been work only in odd times. that means when I navigate the first time it's work second time not navigated than the third time it has been worked.

Example Sample: https://codesandbox.io/s/32m323y9w5

But, it(https://react-slick.neostack.com/docs/example/as-nav-for/) has been shown like worked. So, I have checked that GitHub on that sample even that same issue has been reproduced.. can you please look into this. and provide some guidance to achieve this requirement?

**Comment by asgeirfri** [comment]
Had the same issue. Downgraded to 0.23.1 and it works.

**Comment by tiggem1993** [comment]
Yes, I am also getting error with version 0.23.2. Example code is : [https://yjyzm7yk71.codesandbox.io/](https://yjyzm7yk71.codesandbox.io/)

**Comment by akiran** [comment]
This is working with react-slick@0.29

**Comment by KaziMuneeb** [comment]
Finally got the solution
https://stackblitz.com/edit/react-nkwgpt?file=src%2FApp.js
