### ISSUE TITLE
Problem with installing react slick through github

### ISSUE THREAD

**Issue by vasupol11** [akiran/react-slick#1515]
Please excuse my inexperience, I have just started using npm along with react-slick and I have some minor changes I have to make in the react-slick source code. It requires me to fork and I wish to use the repo I forked for my npm package instead of
npm install react-slick --save
what I have tried so far
npm install git+https://github.com/akiran/react-slick.git --save (just to see)
npm install git+https://github.com/vasupol11/react-slick.git --save (my repo)

Thank you for having a look at my problem.

**Comment by virtuexru** [comment]
You need to commit the `dist` and `lib` folders to your forked repo in order for the forked version to work. Remove them from `.gitignore`, run a `npm run build` then commit the folders after that try `npm install` of your fork again.
