### ISSUE TITLE
hide next-Arrow and prev-Arrow when first/last slide is active.

### ISSUE THREAD

**Issue by MaheshK02** [akiran/react-slick#1517]
how to hide arrow based on first and last images.

**Comment by eballeste** [comment]
the buttons get a `slick-disabled` class whenever they can't do anything else

**Comment by xwillmadeit** [comment]
@eballeste  There is no slick-disabled class when i pass custom prevArrow and nextArrow

**Comment by eballeste** [comment]
when doing a custom prevArrow nextArrow, I would try to figure out the internal state of the slider, maybe by tapping into the `beforeChange` method which has the following fingerprint `(oldIndex, newIndex)` and then compare that to the length of your slide array

**Comment by akiran** [comment]
you can add some css like this
```css
.slick-disabled {
  display: none;
}
```

**Comment by golakjena** [comment]
> when doing a custom prevArrow nextArrow, I would try to figure out the internal state of the slider, maybe by tapping into the `beforeChange` method which has the following fingerprint `(oldIndex, newIndex)` and then compare that to the length of your slides array

in the following scenario it's not working

const beforeChange = (prev, next) => {
        setSlideIndex(Math.floor(next));
    }

    const settings = {
        dots: false,
        infinite: false,
        arrows: true,
        speed: 500,
        slidesToShow: 4.5,
        slidesToScroll: 4.5,
        beforeChange: beforeChange
    };

    const next = () => {
        slider.current.slickNext();
    }
    const previous = () => {
        slider.current.slickPrev();
    }

**Comment by xu3u4** [comment]
> you can add some css like this
> 
> ```css
> .slick-disabled {
>   display: none;
> }
> ```

Hi @akiran 
I found there is `display: "block"` inline CSS on [prev and next button props](https://github.com/akiran/react-slick/blob/master/src/arrows.js#L31):
```
let prevArrowProps = {
      key: "0",
      "data-role": "none",
      className: classnames(prevClasses),
      style: { display: "block" },
      onClick: prevHandler
};

let nextArrowProps = {
      key: "1",
      "data-role": "none",
      className: classnames(nextClasses),
      style: { display: "block" },
      onClick: nextHandler
};
```
With inline CSS, class style has lower priority. https://codesandbox.io/s/react-slick-playground-forked-05k9j?file=/index.css
![image](https://user-images.githubusercontent.com/6767433/106847875-2643dd80-66f3-11eb-8cfd-9fee976e4696.png)

Do you think we can remove the `style: { display: "block" }` here?

**Comment by dalalRohit** [comment]
If you are using custom arrows with react, the custom arrow function receives additional `props` with these properties.

```
className: "slick-arrow slick-prev slick-disabled"
currentSlide: 0
data-role: "none"
onClick: null
slideCount: 20
style: {display: "block"}
type: "prev"
```

One way is to check `display=props.onClick === null ? "none" : "block" `

**Comment by NataliaLinnik** [comment]
@dalalRohit thank you for the idea to check for onClick function!

**Comment by minbelapps** [comment]
> you can add some css like this
> 
> ```css
> .slick-disabled {
>   display: none;
> }
> ```

Why it's closed?

**Comment by hridoy01-hash** [comment]
very good

**Comment by jestrade** [comment]
For custom arrows, it worked for me to validate when `onClick` is not null. 

```
const Arrow = ({onClick}) =>  onClick && <button>click</button>;
```

**Comment by Mir-Labib-Hossain** [comment]
only this worked for me as simplicity
```
.slick-arrow.slick-disabled {
  display: none;
}
```

**Comment by khamid4575** [comment]
.slick-arrow {
  display: none;
}
