### ISSUE TITLE
bug in slick dots

### ISSUE THREAD

**Issue by sandeepsirodia** [akiran/react-slick#1523]
hey when we switch swiping from slick dots to slick list or vice versa, it shows 2 slick dots activated ( black color )

**Comment by jaisonka91** [comment]
In autoplay mode, if one dot is clicked by the user then it's showing as active always. So it will show two active dots.

**Comment by filip4428** [comment]
I'm experiencing the same problem.

**Comment by akiran** [comment]
Duplicate of #1432
