### ISSUE TITLE
As nav for skips elements

### ISSUE THREAD

**Issue by lule23** [akiran/react-slick#1526]
When i use as nav for its skips one slide, nothing happens, then when i click again its scrolls to the next slide. Here is my code:
https://codesandbox.io/s/ko7rwj89r5

**Comment by lule23** [comment]
Fixed by this: https://github.com/akiran/react-slick/pull/1423/commits/0e348f665c22a13b5d285f283fb3b2369e8fc128

**Comment by radneran** [comment]
I was just about to open this issue. Thanks for posting the answer.

**Comment by gcosgreave-us** [comment]
Can this issue now be closed? Something should be said in the docs about using at least 0.24.0 if you want to use nav for. I had the same issue and thought it was my code

**Comment by lule23** [comment]
@gcosgreave-us  U can use solution I posted earlier, it ain't implemented in library itself.
