### ISSUE TITLE
Unable to render elements from props.children

### ISSUE THREAD

**Issue by RyRy79261** [akiran/react-slick#1531]
## Expected outcomes

Passing custom styled components as children to a slider component with all custom settings, styling and buttons to render each custom styled component in a grid layout based on the slider settings

## Issues
All child elements rendered by `this.props.children` are rendered in a single slide stacking all said elements on top of each other

[Reference CodeSandBox](https://codesandbox.io/s/n026oovv7j)

**Comment by akiran** [comment]
You have to forward props to your CustomSlide

Check this example
https://github.com/akiran/react-slick/blob/master/examples/CustomSlides.js
