### ISSUE TITLE
bug: ‘unslick’ setting incorrectly rendered

### ISSUE THREAD

**Issue by AlecTheseus** [akiran/react-slick#1532]
I tryed to update react-slick from 0.15.4 to 0.23.2, a bug happened.
This is my old code, which works correctly:
`responsive: [
    { breakpoint: Breakpoint.Mobile, settings: { slidesToShow: 1 } },
    { breakpoint: Breakpoint.Desktop, settings: { slidesToShow: 2 } },
    { breakpoint: 100000, settings: 'unslick' },
  ],`

But after updating, something went wrong. 

settings: 
` { breakpoint: 100000, settings: { 'unslick' } },`
result: There will be nothing to show except the 'regular slider' div
`<div class="regular slider "><div></div></div>`

settings: 
`{ breakpoint: 100000, settings: { unslick: true } },`
result: It will render a messy one, which cannot use
![`4SJ DVC@6N@@P56ABN06LL](https://user-images.githubusercontent.com/22948771/55935961-7e306b00-5c67-11e9-8651-8c9320f09408.png)

**Comment by akiran** [comment]
Fixed the issue in react-slick@0.26.0
