### ISSUE TITLE
Duplicate slides when items less that slidesToShow

### ISSUE THREAD

**Issue by Fi1osof** [akiran/react-slick#1553]
For example, slidesToShow: 3, real items 2 or 1.
https://codesandbox.io/s/93n7pvqmr

**Comment by mayday7** [comment]
I have the same problem,did you solve it？
 slidesToShow: 5，
the real items was 1，the page shows 3

**Comment by Fi1osof** [comment]
@mayday7 i just add items calculating: https://github.com/prisma-cms/front-editor/blob/bcb1ad37e884f12d62eef4fd47dee363c8e49e88/src/components/App/components/public/Slider/index.js#L179

**Comment by akiran** [comment]
Duplicate issue #1569

**Comment by narendersaini32** [comment]
infinite false can do the job

**Comment by mohammadghomizadeh** [comment]
@narendersaini32 

thank you it's work...

**Comment by muhammadNaveedWarraich** [comment]
i have the same issue but i solve this 

https://github.com/akiran/react-slick/issues/1623#issuecomment-1891567384
