### ISSUE TITLE
React slick importing CSS

### ISSUE THREAD

**Issue by schecter22107** [akiran/react-slick#1554]
If i import the css files using 
@import "~slick-carousel/slick/slick.css";
@import "~slick-carousel/slick/slick-theme.css";
the carousel shows vertically and no css is applied to the carousel. However if I use the cdn it works perfectly fine but when I deploy my app to the server it doesnt apply the css to the carousel. Is there a reason to why importing the css doesnt apply the css? Can anyone help? 
Thank you

**Comment by schecter22107** [comment]
i found the fix 
@import url("https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css");
@import url("https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css");
add this to your main css file

**Comment by ScoutsOut** [comment]
yeah I had the same issue today. Your solution is more of a workaround than an actual fix though. We should be able to import the files directly. I'm going to keep digging for a few minutes to see what I can find. :)
