### ISSUE TITLE
Not show proper amount of items on initialSlide setting

### ISSUE THREAD

**Issue by TotallWAR** [akiran/react-slick#1558]
Hello!
First of all - perfect package!

However i found an issue. When i set slidesToShow to 3 and initialSlide to the last but one - it's shown 2 items instead of 3.
Here i have created an example:

https://codesandbox.io/s/zen-dhawan-ulr5y

**Comment by wgolledge** [comment]
You may just need to set `initialSlide: activeSizeIndex - 1`

https://codesandbox.io/s/admiring-architecture-d1g1n

Is that the result you're looking for?

**Comment by TotallWAR** [comment]
@wgolledge Yes, i'm. You are right. i feel stupid...
