### ISSUE TITLE
Hi @awitherow, in an earlier version of https://farbenmeer.de we also used [Next.js](https://github.com/zeit/next.js) with [Next-CSS](https://github.com/zeit/next-plugins/tree/master/packages/next-css). React-Slick requires fonts and icons in it's default-theme that webpack does not resolve by default. That's likely where your error comes from.

### ISSUE THREAD

**Issue by Mhmdabed11** [akiran/react-slick#1559]
Hi @awitherow, in an earlier version of https://farbenmeer.de we also used [Next.js](https://github.com/zeit/next.js) with [Next-CSS](https://github.com/zeit/next-plugins/tree/master/packages/next-css). React-Slick requires fonts and icons in it's default-theme that webpack does not resolve by default. That's likely where your error comes from.

You can "fix" this by adding [URL-Loader](https://github.com/webpack-contrib/url-loader) for these files to webpack in `next.config.js` like this:

```js
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    })
    return config
  }
})
```

and of course install url-loader: `$ yarn add --dev url-loader`.

_Originally posted by @pex in https://github.com/akiran/react-slick/issues/842#issuecomment-385378629_

When i add  `cssModuled:true`, it stops working

**Comment by awitherow** [comment]
Danke dass ihr habt das mitgeteilt @Mhmdabed11 👍
