### ISSUE TITLE
Empty Space at the end. Custom slick-slide width is not considered for calculating slick-track width

### ISSUE THREAD

**Issue by justin22** [akiran/react-slick#1560]
**Problem**

When giving specific width to items inside slider, even though the same width is given to the `.slick-slide`, the  total width of `.slick-track` is calculated wrong and it creates some **empty space on the end of the slider.** 
When calculating the overall slider width, custom width given for `.slick-slide` is not considered.

<img width="1133" alt="Screenshot 2019-05-23 at 2 57 43 PM" src="https://user-images.githubusercontent.com/3507241/58241926-7e924a80-7d6b-11e9-824d-d86effaf4b66.png">

[Codesandbox URL is included](https://codesandbox.io/embed/react-slick-playground-hci70)

**Comment by triblood** [comment]
Same problem here

**Comment by dozen1488** [comment]
Same problem. I'm thinking about dynamic slidesToScroll so the last swipe will shift to correct slide

**Comment by justin22** [comment]
I couldn't figure out a solution. Ended up using a different [library](https://github.com/YIZHUANG/react-multi-carousel)
