### ISSUE TITLE
Bug in asNavFor: Dosen't work when infinite is set to false

### ISSUE THREAD

**Issue by creatorisback** [akiran/react-slick#1562]
I was trying to make eCommerce image slider using asnavFor.
But the problem is that when I try to set infinite false. asnavFor feature stops working, 
**Need help!**

Here is a link to working code
https://z7u59.codesandbox.io/

**To replicate issue try to remove infinite from the first sider and everything will work**

**Comment by hoc-ht** [comment]
Me too!!! :(

**Comment by raymondsze** [comment]
Got same issue.

**Comment by akiran** [comment]
Code is here
https://codesandbox.io/s/react-slick-playground-2gzb3

**Comment by nikhilasrani** [comment]
Hi Kiran, I would like to work on this issue.

**Comment by kramerkm** [comment]
Using the Code Sandbox link above, if you were to switch both sliders to infinite={false}, the active class on the thumbnail slider doesn't ever change.  

I'm running into this issue on my site where I will show 5 thumbnails out of 10 total, and it'll switch the active class until I get to 6th thumbnail, from then on the active class on the thumbnails never changes. Currently using 0.25.2.

**Comment by iamzifei** [comment]
I'm also experience this issue
