### ISSUE TITLE
Text below the dots

### ISSUE THREAD

**Issue by derrysukrie** [akiran/react-slick#1568]
Hi, can i make the text below the dots?
Because the default setting, Text appear above the dots.

Pls check my UI

![E4B4C076-A8F4-4FD1-AEFE-CD65F9D76A30](https://user-images.githubusercontent.com/43488373/59150637-7f57fb80-8a50-11e9-9599-86288054266b.jpeg)

**Comment by lavaxun** [comment]
@derrysukrie may I know how you solve this issue?

**Comment by kivervinicius** [comment]
`.slick-dots li button::before {
    z-index: -1;
}`

Is ugly but resolve...
