### ISSUE TITLE
Not working with React 0.14 with version 0.9.0-rc1

### ISSUE THREAD

**Issue by alexander37137** [akiran/react-slick#157]
failing with such error on initialisation
```
Warning: React can't find the root component node for data-reactid value `.0.2.3.0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.warning @ react-slick.js:2484ReactMount.findComponentRoot @ react-slick.js:3347ReactMount.findReactNodeByID @ react-slick.js:3314getNodeFromInstance @ react-slick.js:2827findDOMNode @ react-slick.js:10952initialize @ react-slick.js:18937componentDidMount @ react-slick.js:245assign.notifyAll @ react.js:868ON_DOM_READY_QUEUEING.close @ react.js:12853Mixin.closeAll @ react.js:15679Mixin.perform @ react.js:15626batchedMountComponentIntoNode @ react.js:10870Mixin.perform @ react.js:15613ReactDefaultBatchingStrategy.batchedUpdates @ react.js:8443batchedUpdates @ react.js:13689ReactMount._renderNewRootComponent @ react.js:11064wrapper @ react.js:12336ReactMount._renderSubtreeIntoContainer @ react.js:11133ReactMount.render @ react.js:11153wrapper @ react.js:12336Application.render @ app.js:497OverviewController.index @ app.js:1233ApplicationRouter.dispatchToController @ app.js:381apply @ director.js:517_every @ director.js:298Router.invoke @ director.js:522updateAndInvoke @ director.js:480Router.dispatch @ director.js:492Router.init @ director.js:195Application.run @ app.js:487(anonymous function) @ (index):125fire @ jquery.js:3148self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503
react-slick.js:3350 Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

When I replace internal _reactDom2['default'].findDOMNode with global function ReactDom.findDOMNode it works ok

**Comment by alexander37137** [comment]
Actually it seems problem that react-slick use react dom integrated inside lib. It have version 0.14.0-rc1 and it do not work well with external react 0.14. Why it do not use React dom is external dependency?

**Comment by missrhyme** [comment]
I have the same problem, so I have to use the version 0.8.0.

**Comment by websilone** [comment]
Hi,
I'm using React 0.14.0 and it's working fine with react-slick 0.9.0-rc1 (except a little issue I logged yesterday).

At least there is no warning anymore.

**Comment by akiran** [comment]
Merged #161

**Comment by alexander37137** [comment]
I updated to 0.9.0 and It is still not working with same error

React dom inside react slick still 0.14.0-rc1

![image](https://cloud.githubusercontent.com/assets/5341567/10886070/71648eba-8191-11e5-9335-217bd8a61e37.png)

**Comment by akiran** [comment]
#164 might fix this issue.

I will review and merge it

**Comment by akiran** [comment]
@alexander37137 Can you checkout react-slick@0.9.1 and see if your issues are resolved

**Comment by alexander37137** [comment]
@akiran There is error when importing react dom from window object. 
now it looks like this
```	else
		root["Slider"] = factory(root["React"], root["react-dom"]);
```
but should be 
```
	else
		root["Slider"] = factory(root["React"], root["ReactDOM"]);
```

I manually changed it and it start working. Can you please fix it

**Comment by akiran** [comment]
Yes, It is fixed in master. Need to make a npm release.


On Thu, Nov 5, 2015 at 12:04 PM, Alexander Andreev <notifications@github.com

**Comment by mmmurf** [comment]
@akiran excellent

**Comment by alexander37137** [comment]
@akiran When do you plan release it?

**Comment by akiran** [comment]
Its already released

On Tue, Nov 10, 2015 at 6:26 PM, Alexander Andreev <notifications@github.com

**Comment by ChrisCinelli** [comment]
@akiran if this is solved can you close it?
