### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by thebiltheory** [akiran/react-slick#1573]
CHANGELOG.md shows changes up until 0.22.0. Package.json shows version: 0.24.0.
We use this plugin on a huge production site. Does anyone knows what changed? 

Can we update the log files?

Thanks!

**Comment by akiran** [comment]
yes. We will update

**Comment by MickeyKay** [comment]
I see this is closed, but I'm not seeing the changelog actually bumped. Can you please confirm @akiran?

**Comment by nubs** [comment]
It would be great to get some changelog/release info somewhere. The last couple releases haven't had GitHub tags or releases and no updates to the CHANGELOG.md which makes it more difficult to judge whether we should update to the newest version.
