### ISSUE TITLE
slick track overflow body element

### ISSUE THREAD

**Issue by amishPro** [akiran/react-slick#1576]
I know how to solve this problem what I wanted to open an issue anyway because maybe somebody is having the same problem and because I think is a bug.
If you create a slider without any style it overflows the body (and the container if any).
You fix this by adding padding. I finded the solution in the playground codesandbox provided in the readme file.

### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

https://codesandbox.io/s/3msrb

**Comment by uragecz** [comment]
Same problem... however i can't make work around like you did with setting overflow-x: hidden...   Soo any other solution ?

**Comment by aehm-dacrea** [comment]
Also worked for me
`.slick-initialized {
  overflow: hidden;
}`

**Comment by diegosaul402** [comment]
For me, were the arrows that are displayed by default outside the slide, the overflow worked but also overriding the `right` property for `.slick-next`

**Comment by dmmello1989** [comment]
> .slick-initialized { overflow: hidden; }

this worked liked a charm, thank you!

**Comment by mf-7** [comment]
> For me, were the arrows that are displayed by default outside the slide, the overflow worked but also overriding the `right` property for `.slick-next`, or set `arrows: false`

The same problem for me. Thanks.
