### ISSUE TITLE
Bunch of warnings using with react 0.14

### ISSUE THREAD

**Issue by collinwu** [akiran/react-slick#158]
ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `InnerSlider`.

<img width="555" alt="screen shot 2015-10-27 at 10 13 12 am" src="https://cloud.githubusercontent.com/assets/6867357/10766168/62023cfe-7c93-11e5-8db5-53029d8bbd52.png">

**Comment by laxplaer** [comment]
Use 0.9.0-rc1 version with 0.14 react..
