### ISSUE TITLE
Trying to contribute

### ISSUE THREAD

**Issue by evanderson** [akiran/react-slick#1585]
Hello @akiran 

I would like to contribute some accessibility features to this project however I am having trouble getting this repo to build & compile locally for development. 

I have done the following steps:

1. Forked and cloned the repo locally
2. Ran the available build scripts `npm run build` & `npm run prepublish`
3. Pointed my NextJS project to this local install `import Slider from '../../../../../react-slick/dist/react-slick';`

But I get this error when building my application `Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/from' in '/Users/evanderson/Projects/react
-slick/dist'`

Also the files that get added to my `node_modules` directory when performing `npm install react-slick --save` are not the same as the files produced from the build commands. 

Could you please clarify?

**Comment by YIZHUANG** [comment]
Hi,

I built a better version of the carousel https://github.com/YIZHUANG/react-multi-carousel 
Would you like contribute?

**Comment by evanderson** [comment]
I was able to figure this out by running `npm install ../react-slick` to use a local build on my project for testing incase anyone runs into this problem.
