### ISSUE TITLE
Slider childrens classNames are not merged anymore in 0.9.0-rc1

### ISSUE THREAD

**Issue by websilone** [akiran/react-slick#159]
I know 0.9.0-rc1 is still under development but here is a little issue.

Having className on slider children elements (which will become the .slick-slide), it seems these classNames are not merged anymore with the new ones.

From what I saw in the changes between 0.8 and 0.9, in track.jsx, line 70, 0.9 is using React.cloneElement where 0.8 was using cloneWithProps.
So it's probably an intern change in these methods but it would be nice to find a way to keep these classNames on the child elements.

Thanks.

**Comment by akiran** [comment]
yes, I will look into this

**Comment by websilone** [comment]
if this can help, here is what I came up with.

In track.jsx, in the renderSlides method, line 69 : 

var slickClasses = getSlideClasses(assign({index: index}, spec));
    var cssClasses;

    if (child.props.className) {
        cssClasses = classnames(slickClasses, child.props.className);
    }
    else {
        cssClasses = slickClasses;
    }

    slides.push(React.cloneElement(child, {
      key: index,
      'data-index': index,
      className: cssClasses,
      style: Object.assign({}, child.props.style || {}, childStyle)
    }));

It is actually due to React.cloneElement not merging styles and classNames anymore for us.

**Comment by dfala** [comment]
@websilone +1 -- classNames not merged

**Comment by akiran** [comment]
It is fixed with #161
