### ISSUE TITLE
Dot number issue

### ISSUE THREAD

**Issue by cyyeh** [akiran/react-slick#1591]
issue code demo:
https://codesandbox.io/embed/react-slick-playground-zdbqj

The dot number will be equal to the images number, right? Then if there are many images, how do I deal with dots rendering issue? I would like dots number can be configurable, and it will rotate automatically when I click dots. Thank you!

**Comment by akiran** [comment]
Dots is not idle for this case. 

You can use custom paging feature
https://github.com/akiran/react-slick/blob/master/examples/CustomPaging.js

You can write the custom logic and make dots appear the way you want

**Comment by vadimsviridov** [comment]
@cyyeh 
Found solution, use beforeChanges() and useState for calculation and saving dots quantity, and appendDots() for write it.
`{dots.map((dot,index) => {
                            if(index<dotsQuantity){
                                return <Dot {...dot.props} onClick={dot.props.children.props.onClick} />
                            }
                            return
                        })}`
