### ISSUE TITLE
Incorrect slide position on initial load when using centerMode on mobile

### ISSUE THREAD

**Issue by nahmadic** [akiran/react-slick#1607]
I am using the carousel on a Gatsby site deployed to Netlify. The carousel is showing 5 slides with center mode active which works fine on desktop. On tablet screen sizes is goes down to 3 and on mobile it goes down to 1. When initially loading the site on tablet size or smaller it shows the wrong slide in the center but without the slick-active class. 

![Screenshot 2019-07-31 at 19 47 45](https://user-images.githubusercontent.com/8457885/62239081-1f386280-b3cc-11e9-86df-ff28c79b8d7f.png)
Expected behaviour

![Screenshot 2019-07-31 at 19 48 02](https://user-images.githubusercontent.com/8457885/62239098-28293400-b3cc-11e9-819d-7614ccc1b25a.png)
Actual behaviour - You can see the quotation marks to right showing where the slick-active class slide is.

If I go into another page and reload the page with the carousel it works fine.

![Screenshot 2019-07-31 at 19 21 44](https://user-images.githubusercontent.com/8457885/62239196-53ac1e80-b3cc-11e9-94b5-549e8aa95a25.png)
The issue appears to be caused by this padding problem. When the page is reloaded it looks like this:

![Screenshot 2019-07-31 at 19 23 01](https://user-images.githubusercontent.com/8457885/62239236-6888b200-b3cc-11e9-9500-ba364f2e6eb0.png)
The settings I am using are what is requested in the documentation as shown below:

![Screenshot 2019-07-31 at 19 50 47](https://user-images.githubusercontent.com/8457885/62239288-83f3bd00-b3cc-11e9-9760-4252cfe9fa99.png)

The site in question is https://airvat-gatsby.netlify.com/ if you want to try and replicate. Another point of interest is that the same issue does not happen locally.

Thanks in advance for any help anyone offers

**Comment by reachtokish** [comment]
Hi @nahmadic can you reproduce this same issue on codesandbox? I just tried using your same settings but I am not getting this issue.

**Comment by nahmadic** [comment]
Hey @reachtokish, thanks for getting back to me. I've set it up in codesandbox and just like you the issue doesn't persist, both in a new project using the same settings and actually using the repo for the project itself. Could this be something to do with the Netlify build process?

**Comment by reachtokish** [comment]
I am not exactly sure about Netlify build process that it could create issues but just check the version of this package you have used for Netlify build.

**Comment by nahmadic** [comment]
Ok well lets close this for now then, I think we can assume it's not the package causing the problem. I'll post an update if I get to the bottom of it. Thanks for the help!

**Comment by nahmadic** [comment]
@reachtokish I sorted it, I managed to replicate it locally by using gatsby build -> gatsby serve and from there did some reading into what the production build does and from my reading it seems to have something to do with the window object or lack of it? Either way, forcing slick to wait until the component mounts sorts it. Thanks again for your help!

**Comment by SamIngram96** [comment]
Hello @nahmadic Could you tell me more about what it means to force slick to wait until the component mounts? I think something similar is happening on my site, slick is getting a 50px padding added to it, but only when I use gatsby build -> gatsby serve, the bug doesn't occur in gatsby develop

**Comment by SamIngram96** [comment]
@nahmadic 
<img width="1680" alt="Screen Shot 2019-09-10 at 2 36 59 PM" src="https://user-images.githubusercontent.com/54552986/64640691-7d4b6300-d3d8-11e9-882c-3e41da95db26.png">

**Comment by nahmadic** [comment]
Hey @SamIngram96,

I'm not sure if this will help your situation but I'm happy to try and help. Have a look at the following file in my repo:

[https://github.com/nahmadic/airvat-gastby/blob/master/src/components/homepage-carousel.js
](url)

You can see that I set a variable in state called render to false and then after the component is rendered (using the componentDidMount() lifecycle method) I then change it to true. The outputted markup is wrapped in a conditional based on that variable.

There is most likely a cleaner way to get that to work but in this instance it worked perfectly so I'm happy to leave it for now.

Hope this helps!

**Comment by SamIngram96** [comment]
Hello @nahmadic unfortunately, this did not solve our problem, but I really appreciate your advice! the search continues!! (were just injecting css into the document now to force override the padding 😄 )

**Comment by RhyG** [comment]
Hi @nahmadic just letting you know you saved me from a very stressed out PM, thanks a lot!

**Comment by nahmadic** [comment]
> Hi @nahmadic just letting you know you saved me from a very stressed out PM, thanks a lot!

Glad to help!

**Comment by miikEe13** [comment]
For me works just adding a 100vw in the wrapper of the slider and it works
