### ISSUE TITLE
UNSAFE_componentWillUnmount

### ISSUE THREAD

**Issue by bvaughn** [akiran/react-slick#1616]
Looks like some of the components in this lib declare a lifecycle, `UNSAFE_componentWillUnmount`, that does not exist. Despite having "will" in its name, `componentWillUnmount` is a commit phase lifecycle meant for cleaning up (e.g. removing event listeners). It's not "unsafe".

Read about side effects here if you're curious:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

This means that these components will not clean up after themselves and may cause leaks:
* https://github.com/akiran/react-slick/blob/97988e897750e1d8f7b10a86b655f50d75d38298/src/slider.js#L70
* https://github.com/akiran/react-slick/blob/97988e897750e1d8f7b10a86b655f50d75d38298/src/slider.js#L70

**Comment by afc163** [comment]
Fixed in https://github.com/akiran/react-slick/pull/1615

**Comment by akiran** [comment]
Thanks @bvaughn @afc163 

Resolved this issue
