### ISSUE TITLE
React-Slick not showing images on Chrome

### ISSUE THREAD

**Issue by danomov** [akiran/react-slick#1625]
I have 4 slides created with react-slick and one of them is image slider.
Now the issue is that on Firefox for example it's showing that images but on Chrome no.

I have attached screenshots bellow for greater understanding(left - chrome, right - firefox)

![Screenshot (37)](https://user-images.githubusercontent.com/39675086/63948057-16998180-ca89-11e9-925c-6b6d30105307.png)

How i can solve this issue?

**Comment by Toyocodes** [comment]
Hello, how were you able to solve this?
