### ISSUE TITLE
React Slick implementation of slickGoTo not working

### ISSUE THREAD

**Issue by rajatrao777** [akiran/react-slick#1639]
I have gone through this 
https://react-slick.neostack.com/docs/example/slick-go-to.
My code snippet is as below
var settings = {
dots: false,
      infinite: false,
      autoplay: false,
      speed: 500,
      arrows: true,
      slidesToShow:2.7,
      afterChange:()=>{
      React.findDOMNode(this.slider).slickGoTo(2);
     }
}
<Slider {...settings} ref={slider=>(this.slider = slider)} >
child elements of carousel</Slider>
My requirement is as soon as user clicks last slide it should return to first slide...so trying by using slickGoTo function ,but its not working and error is shown as slickGoTo is not a function

**Comment by VincentCharpentier** [comment]
try `this.slider.slickGoTo(2);`
React.findDOMNode returns a DOM Node (eg. div).
You want to call slickGoTo on a slick instance

**Comment by akiran** [comment]
The solution mentioned by @VincentCharpentier is correct.

Closing this issue.
