### ISSUE TITLE
Padding between slide item

### ISSUE THREAD

**Issue by futurify-ydang** [akiran/react-slick#1655]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

I want to add spacing between the slider item like [responsive example](https://react-slick.neostack.com/docs/example/responsive/) but it seems like there is an issue with the padding.
Can you help me in this case?
Thanks
![image](https://user-images.githubusercontent.com/44663784/66796015-8b892380-ef30-11e9-82b4-35dd2902072c.png)

https://codesandbox.io/s/react-slick-playground-pl0o5

**Comment by sscaetite** [comment]
Same mistake here

**Comment by spvalencia** [comment]
I solved as below

`& .slick-list {
    margin: 0 -7px;
    & .slick-slide > div {
      padding: 0 10px;
    }
  }`

**Comment by akiran** [comment]
yes, this should be solved with custom css

**Comment by AhmadRaza9** [comment]
@akiran @sscaetite @futurify-ydang @jeffh @spvalencia 
It's not working in tabs mega menu, Also when open tabs mega menu, all slides width is 0px, 
Let me know how to resolve 0px width issues and proper way to add gap between slides.
![image](https://github.com/akiran/react-slick/assets/85168169/c8306c10-86a7-4c3e-8fbd-8acd871c6bf5)

**Comment by qiutian00** [comment]
> I solved as below
> 
> `& .slick-list { margin: 0 -7px; & .slick-slide > div { padding: 0 10px; } }`

Works for me
