### ISSUE TITLE
Is there any way to remove the additional slides that are generated when i have two slide elements?

### ISSUE THREAD

**Issue by SAGARACH65** [akiran/react-slick#1656]
I have two elements in the slider. I noticed that it actually creates 5 other slides. They have data-index varying from -1 to 3. 
![Screenshot from 2019-10-18 21-36-11](https://user-images.githubusercontent.com/24357040/67109075-77bf1500-f1ef-11e9-81cd-b178be3ef795.png)

The component I am rendering is in position 1.

Is there any way to remove the clone slide elements in the DOM?

The problem I am having is that the slides at position -1 and 3 have a div with the same id.

Now when I do `document.getelementbyId()` , I do not get the properties of the actual component in view.
`

**Comment by SAGARACH65** [comment]
Looks like you can just pass `{infinite:false}` prop in the slider option.

**Comment by realamirhe** [comment]
Is there a way to have the infinite animation and remove some extra attributes.

Imaging this scenarios;
You have some banner images which you want to collect clicks analytics via google gtag.
but images are infinity rotate and has their animation.
