### ISSUE TITLE
how can I make slider like hotel.com?

### ISSUE THREAD

**Issue by keung7251** [akiran/react-slick#1657]
how can I make slider like hotel.com?

https://ibb.co/72YDsV1

https://www.hotels.com/ho806701504/?pos=HCOM_ASIA&locale=en_HK&pa=3&q-check-out=2019-11-21&tab=description&q-room-0-adults=1&YGF=14&q-check-in=2019-11-13&MGT=7&WOE=4&WOD=3&ZSX=0&SYE=3&q-room-0-children=0

**Comment by tainefreitas** [comment]
So, to do this, you may need to follow 3 examples:
* First, use asNavFor to make the first and big photo connects with the miniatures.
https://react-slick.neostack.com/docs/example/as-nav-for
* Second, use Multiple rows to make thumbs (https://react-slick.neostack.com/docs/example/multiple-rows) or just use a function to call the right slide on click, is more simple. (a example: https://react-slick.neostack.com/docs/example/resizable)
* Third, to make the arrows, you can modify then (https://react-slick.neostack.com/docs/example/custom-arrows)....

**Comment by akiran** [comment]
Thanks @tainefreitas for answering the question.
