### ISSUE TITLE
Markup change from v0.22 to v.25

### ISSUE THREAD

**Issue by vertic4l** [akiran/react-slick#1660]
What was the reason to change the markup between these version?
Seems to be worse than before and got to give fixed heights for the inner content.

Or did i miss something?

The changelog.md is also out of sync for no reason...

And why the fuck is there an additional div with inline style now:
`style="width: 100%; display: inline-block;"`

which fucks up the correct rendering of the dots and everything else?

**Comment by akiran** [comment]
There is no markup change from 0.22 to 0.25

**Comment by jaredkotoff** [comment]
I'm also seeing my inline style being overwritten with `style="width: 100%; display: inline-block;"` after updating to `0.23.1` from `0.22.3`
