### ISSUE TITLE
Unslick is not working

### ISSUE THREAD

**Issue by jorgefernandes** [akiran/react-slick#1663]
I'm trying to set 'unslick' for desktop responsive, but slick is just erasing content inside slick wrapper

https://codesandbox.io/s/react-slick-playground-ylelk

**Comment by cryptic022** [comment]
Hi, @jorgefernandes @akiran I have raised a PR for this issue. Please review.

**Comment by akiran** [comment]
Thanks @cryptic022. Your PR fixed the issue.

Made a release react-slick@0.26.0 with the fix.
