### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by vabatta** [akiran/react-slick#1672]
As title says, is this repo still maintained? I can see tons of issues reported dated back to 2018 with 63 open pull requests. Do you guys needs help to maintain this?

**Comment by ecfaria** [comment]
I'm available to help as well!

**Comment by tainefreitas** [comment]
So, the last update is from August, and if need some help to maintain, I help too!

**Comment by soren121** [comment]
At this point, a fork might be the best option. I'm not able to lead a fork at the moment but if someone else takes it up, I'd certainly contribute to it.

**Comment by tainefreitas** [comment]
@soren121 Hi, I can help on weekends!

**Comment by tainefreitas** [comment]
@soren121 @ecfaria @vabatta I made a fork, so I can manage the project, just need some help

**Comment by vabatta** [comment]
I actually opted out from this to a simpler (and lighter) implementation.

**Comment by jbromberg** [comment]
@vabatta mind sharing?

**Comment by vabatta** [comment]
@jbromberg here: https://www.npmjs.com/package/react-pure-carousel
