### ISSUE TITLE
AutoPlaySpeed not resetting on changing the slide manually

### ISSUE THREAD

**Issue by sahilvicesoftware** [akiran/react-slick#1673]
If i have autoplaySpeed set as 10 seconds and i move to next slide after 6 seconds, the seconds slide auto moves to third slide after 4 seconds but it should move after 10 seconds

**Comment by rvvpatel** [comment]
suffering same issue, any updates ?

**Comment by akiran** [comment]
This issue is fixed in react-slick@0.27
