### ISSUE TITLE
useRef react hooks  syncing issue.

### ISSUE THREAD

**Issue by eagle3y3** [akiran/react-slick#1682]
I'm having trouble syncing two sliders together with react hooks. I'm not able to use this.slider and I'm not able to use the useRef hook properly. Does anyone have a workaround solution to this using React Hooks?

**Comment by naingoted** [comment]
Hi, @eagle3y3 did you manage to get it working using hooks ?

**Comment by hrafaelveloso** [comment]
I'm facing this same issue. I want to sync two sliders, but I'm not able to sync them... I'm trying with useRef.

**Comment by hrafaelveloso** [comment]
@eagle3y3 @naingoted I have this codesandbox working with hooks: 
https://codesandbox.io/s/react-slick-playground-9kfgv

**Comment by joshua-isaac** [comment]
> @eagle3y3 @naingoted I have this codesandbox working with hooks:
> https://codesandbox.io/s/react-slick-playground-9kfgv

Thank you so much for this, been looking for AsNavFor using hooks for a while now! Going to implement this in a project when i get home :)
