### ISSUE TITLE
Will slickGoTo be fixed?

### ISSUE THREAD

**Issue by FootyNumb3rs** [akiran/react-slick#1685]
I'm trying to save the state of my slider when moving between different pages of my react app. 

Tge slickGoTo example on the site doesn't seem to work. 

To my best of knowledge what's required to get things working is:
```
<Slider
          ref={slider => (this.slider = slider)} />
```
Then I've tried: 
```
onInit: () => {
        this.slider.slickGoTo(0); 
      },
```
'0' being whatever the state is. The thing is, I've tried putting `this.slider.slickGoTo ` at various places throughout the app and I always get the same error:

TypeError: Cannot read property 'slickGoTo' of undefined

**Comment by FootyNumb3rs** [comment]
Setting initialSlide to the desired state is buggy, for some reason whenever I change the slide the transition is deactivated.

**Comment by erikswed** [comment]
Is the a fix for this? I see the same thing!

**Comment by AceBerry924** [comment]
@FootyNumb3rs , this issue is fixed?
