### ISSUE TITLE
onClick events on children all fire on mount and never fire again after

### ISSUE THREAD

**Issue by Patricknew** [akiran/react-slick#1689]
Hey y'all

I'm on v0.25.2. I have onClick events on each child image. But they all get fired on load. After that they can never fire again when I click on them. I see some similar issues but no solution has worked for me.

Link to sandbox with this issue: https://codesandbox.io/s/react-slick-playground-unh8y?fontsize=14&hidenavigation=1&theme=dark

I need to update another component based on which child gets selected (clicked). Is there any workaround?

Thank you!

**Comment by tibonl** [comment]
<div onClick={alert(1)}>
If you pass any function like this or call anything directly on onClick it will get executed as soon as the component mounts. Instead you should pass the function without () or bind it using .bind. In your case you should have passed the alert inside a function  and then to onClick below given examples will help you understand the ways you can pass a function to onClick.
import React from "react";
import ReactDOM from "react-dom";
import Slider from "react-slick";
import "./index.css";

class ReactSlickDemo extends React.Component {
  onClickHandler(val) {
    alert(val);
  }
  render() {
    var settings = {
      dots: true
    };
    return (
      <div className="container">
        <Slider {...settings}>
          <div onClick={ alert(1)}>//Your way of calling function
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div onClick={() => alert(2)}>//correct way of calling function
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div onClick={() => this.onClickHandler(3)}>//correct way of calling function
            <img src="http://placekitten.com/g/400/200" />
          </div>
          <div onClick={this.onClickHandler.bind(this, 4)}>//correct way of calling function
            <img src="http://placekitten.com/g/400/200" />
          </div>
        </Slider>
      </div>
    );
  }
}

https://reactjs.org/docs/faq-functions.html -> This will guide you in a much better way.

**Comment by Patricknew** [comment]
Thank you very much for the explanation and the useful link!
