### ISSUE TITLE
Arrows not showing upon production but in local environment work fine.

### ISSUE THREAD

**Issue by horaleon1** [akiran/react-slick#1702]
I used this classes to modify the default settings.

.slick-next, .slick-prev{
  height: 21.5px;
  width: 21px;
  border-radius: 50%;
  background-color: #e63976;
}
.slick-next::before, .slick-prev::before{
  color: white;
  font-size:30px;
  opacity: 1;
  margin-left: -3px;
  line-height: 0.95
}
.slick-arrow:hover{
 background-color: #e63976 !important;
}
.slick-arrow:focus{
  background-color: #e63976 !important;
 }
.slick-next{
  right: 15px;
}
.slick-prev{
  left: 28px;
  z-index: 1;
}

**Comment by akiran** [comment]
This could be your project build setup issue.
