### ISSUE TITLE
CSS etc is not part of the dist ?

### ISSUE THREAD

**Issue by dcsan** [akiran/react-slick#1708]
I created a new simple app with `create-react-app`
but the CSS can't be found.

checking in the built `/dist` folder there are indeed no css files there.

So I copied them from the docs folder into my app
https://github.com/akiran/react-slick/blob/master/docs/slick-theme.css

But now getting this error

> ./src/components/KwGame/slick-theme.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/components/KwGame/slick-theme.css)
Module not found: Can't resolve './ajax-loader.gif' in '/Users/dc/dev/rnd/trax/kws/src/components/KwGame'

and yeah all that stuff isn't in the dist either

So am I doing something wrong, or do I actually have to go in and eject the project and tweak the webpack config to get this to work with create-react-app?

**Comment by dcsan** [comment]
oh it requires another project

> npm install slick-carousel

**Comment by akiran** [comment]
yes
