### ISSUE TITLE
Not seem to be working with images from Shopify

### ISSUE THREAD

**Issue by arhoy** [akiran/react-slick#1717]
I'm using React Slick in a Gatsby - Shopify site and have trouble rendering the images like I normally would using React Slick and Gatsby.

Here is my repo if you could take a look. Basically, the images come thru for a instant and then I get a flash and the images disappear :(

Here is the repo and the file of the source code. Please advise!

https://github.com/arhoy/aquasarcafe/blob/master/src/templates/Shopify/ShopifyProductPage.js

**Comment by akiran** [comment]
Do you still have this issue ?

If so, provide steps to reproduce the issue
