### ISSUE TITLE
getBoundingClientRect disables CSS transitions

### ISSUE THREAD

**Issue by pattard** [akiran/react-slick#172]
If used inside CSSTransitionGroup react-slick prevents the transition from happening. The issue seems to only happen in Chrome.

Apparently (maybe) React has an issue with getBoundingClientRect (https://github.com/facebook/react/issues/3672) and it is used in initialize method here https://github.com/akiran/react-slick/blob/c6b612fa5c05e49572db97c13ab0af9c50aaa702/src/mixins/helpers.js#L65

Wrapping the entire body of the initialize method into a 0 settimeout seems to fix the problem.

**Comment by akiran** [comment]
This issue is fixed in latest release.
Can you check.
