### ISSUE TITLE
useRef react hooks syncing with typescript issue

### ISSUE THREAD

**Issue by krupasavadiya** [akiran/react-slick#1728]
import Slider from 'react-slick';

function SliderSlick() {
    const [state, setState] = useState({ nav1: undefined, nav2: undefined });
    const slider1 = useRef();
    const slider2 = useRef();
  
    useEffect(() => {
        setState({
          nav1: slider1.current,
          nav2: slider2.current
        });
      }, []);

      const { nav1, nav2 } = state;

    return(
        <Slider
            asNavFor={nav2} 
            ref={slider => (slider1.current = slider)}
        >
             <div>
          <h3>1</h3>
        </div>
        <div>
          <h3>2</h3>
        </div>
        <div>
          <h3>3</h3>
        </div>
        <div>
          <h3>4</h3>
        </div>
        <div>
          <h3>5</h3>
        </div>
        <div>
          <h3>6</h3>
        </div>
        </Slider>
      <div>
                <Slider
                   asNavFor={nav1}
                    ref={slider => (slider2.current = slider)}
                    slidesToShow={3}
                    swipeToSlide={true}
                    focusOnSelect={true}
                >
                     <div>
                        <h3>1</h3>
                        </div>
                        <div>
                        <h3>2</h3>
                        </div>
                        <div>
                        <h3>3</h3>
                        </div>
                        <div>
                        <h3>4</h3>
                        </div>
                        <div>
                        <h3>5</h3>
                        </div>
                        <div>
                        <h3>6</h3>
                        </div>
                </Slider>
</div>   
)
  }

> Facing an issue "Type 'Slider | null' is not assignable to type 'undefined'.
  Type 'null' is not assignable to type 'undefined'."  when assign ref to slider.

Can any one suggest?? where i miss something? May be it's a problem of type mismatch..

**Comment by inquiztr** [comment]
I had trouble using Refs and Functional components myself. This is what I got working:
````
import React, { useEffect, useState, useRef } from 'react';
import Slider from 'react-slick';

const SliderSlick = () => {
    const [nav1, setNav1] = useState();
    const [nav2, setNav2] = useState();
    const slider1 = useRef();
    const slider2 = useRef();

    // i dont seem to need this
    //useEffect(() => {
    //    setNav1(sliderEl1);
    //    setNav2(sliderEl2);
    //  }, []);

    return (
        <>
            <Slider asNavFor={nav2} ref={slider1 => setNav1(slider1)}>
                <div>
                    <h3>1</h3>
                </div>
                <div>
                    <h3>2</h3>
                </div>
                <div>
                    <h3>3</h3>
                </div>
                <div>
                    <h3>4</h3>
                </div>
                <div>
                    <h3>5</h3>
                </div>
                <div>
                    <h3>6</h3>
                </div>
            </Slider>

            <Slider
                asNavFor={nav1}
                ref={slider2 => setNav2(slider2)}
                slidesToShow={3}
                swipeToSlide={true}
                focusOnSelect={true}
            >
                <div>
                    <h3>1</h3>
                </div>
                <div>
                    <h3>2</h3>
                </div>
                <div>
                    <h3>3</h3>
                </div>
                <div>
                    <h3>4</h3>
                </div>
                <div>
                    <h3>5</h3>
                </div>
                <div>
                    <h3>6</h3>
                </div>
            </Slider>
        </>
    );
};

export default SliderSlick;
````

**Comment by Freelancerwebiots** [comment]
@inquiztr 
Thank you for quick response :) 
It's work for me but have an issue with first item means bottom slider sync to top slider for all item except first. when i click any item from bottom slider it sync and that item displayed in top slider but when i go to first item it can't sync to top slider. Don't know why?
any idea about that?

**Comment by krupasavadiya** [comment]
@inquiztr
Thank you for quick response :)
It's work for me but have an issue with first item means bottom slider sync to top slider for all item except first. when i click any item from bottom slider it sync and that item displayed in top slider but when i go to first item it can't sync to top slider. Don't know why?
any idea about that?

**Comment by inquiztr** [comment]
Hmm I didnt notice that. I am only just got mine working with sample images and still hooking mine up to connect to an api to get the proper images. I will check to see if my first images are not synched as well and see what is going on.  Does un-commenting the useeffect section I commented, have any improvment?

**Comment by krupasavadiya** [comment]
No when i un-comment that useEffect section got another issue of 
**Cannot read property 'slideHandler' of undefined**

**Comment by inquiztr** [comment]
I placed my code in codesandbox and it seems to be working (top and bottom slider are synchronized) and i dont seem to need the useffect.  https://codesandbox.io/s/react-slick-demo-mshh4
Do you see the issue here?

**Comment by inquiztr** [comment]
Ok I think I have it working without errors now : https://codesandbox.io/s/react-slick-demo-27z23
Please try this one and ignore the other one.

**Comment by krupasavadiya** [comment]
> Ok I think I have it working without errors now : https://codesandbox.io/s/react-slick-demo-27z23
> Please try this one and ignore the other one.


Yes, It work now as expected. Thank you so much @inquiztr

**Comment by pnghai** [comment]
> I had trouble using Refs and Functional components myself. This is what I got working:
> 
> ```
> import React, { useEffect, useState, useRef } from 'react';
> import Slider from 'react-slick';
> 
> const SliderSlick = () => {
>     const [nav1, setNav1] = useState();
>     const [nav2, setNav2] = useState();
>     const slider1 = useRef();
>     const slider2 = useRef();
> 
>     // i dont seem to need this
>     //useEffect(() => {
>     //    setNav1(sliderEl1);
>     //    setNav2(sliderEl2);
>     //  }, []);
> 
>     return (
>         <>
>             <Slider asNavFor={nav2} ref={slider1 => setNav1(slider1)}>
>                 <div>
>                     <h3>1</h3>
>                 </div>
>                 <div>
>                     <h3>2</h3>
>                 </div>
>                 <div>
>                     <h3>3</h3>
>                 </div>
>                 <div>
>                     <h3>4</h3>
>                 </div>
>                 <div>
>                     <h3>5</h3>
>                 </div>
>                 <div>
>                     <h3>6</h3>
>                 </div>
>             </Slider>
> 
>             <Slider
>                 asNavFor={nav1}
>                 ref={slider2 => setNav2(slider2)}
>                 slidesToShow={3}
>                 swipeToSlide={true}
>                 focusOnSelect={true}
>             >
>                 <div>
>                     <h3>1</h3>
>                 </div>
>                 <div>
>                     <h3>2</h3>
>                 </div>
>                 <div>
>                     <h3>3</h3>
>                 </div>
>                 <div>
>                     <h3>4</h3>
>                 </div>
>                 <div>
>                     <h3>5</h3>
>                 </div>
>                 <div>
>                     <h3>6</h3>
>                 </div>
>             </Slider>
>         </>
>     );
> };
> 
> export default SliderSlick;
> ```
Thank, your solution worked smoothly. Anyway, those lines will be never used in the logic,
```
    const slider1 = useRef();
    const slider2 = useRef();
```
as the slider1 variable inside `ref={slider1 => setNav1(slider1)}` is just local scoped to the inline function

**Comment by jagruti-turtlemint** [comment]
<Slider ref={slider=> (slider? slider.slickGoTo(+props.slideToIndex || 0) : '')}  > ....  This worked for me in case of jumping to the particular slide

**Comment by hoektoe** [comment]
> Ok I think I have it working without errors now : https://codesandbox.io/s/react-slick-demo-27z23
> Please try this one and ignore the other one.

Exactly what I was looking for, thanks you so much

**Comment by MarekChoinski** [comment]
@akiran can you update this section in documentation with this solution? Now everyone uses hooks

https://react-slick.neostack.com/docs/example/as-nav-for/

**Comment by brianecook** [comment]
@inquiztr Thanks for the solution, but there's one thing that I don't think is quite right. Your calls to useRef don't seem to have any actual functionality here. All that matters is that the nav elements live in state and are set using their corresponding setter in the ref attribute callback. Basically, I'm just saying you can remove these lines:

```
const slider1 = useRef();
const slider2 = useRef();
```
