### ISSUE TITLE
how to set custom width

### ISSUE THREAD

**Issue by sambhav2612** [akiran/react-slick#1738]
I'm building a website @ https://fh-web.qa.xencov.net/, the `react-slick` has been used a many places within this page. If you scroll to **Shop by category** section as: 

![Screenshot from 2020-03-02 11-36-19](https://user-images.githubusercontent.com/19583619/75649750-16698100-5c7a-11ea-8ab5-745760410dda.png)

It's just fine, does what we wanted, however when you go a little down to **Fantastic stories** section, there's margin from left and width set to `# of items inside slider * 286px`:

![Screenshot from 2020-03-02 11-38-09](https://user-images.githubusercontent.com/19583619/75649902-7c560880-5c7a-11ea-9722-ecbd722b2f55.png)

I need help with 2 scenarios:
- To skew the entire slider container to left regardless of internal props or custom styles.
- To change the width of individual slider elements using settings and/or props, as in:

![Screenshot from 2020-03-02 11-41-31](https://user-images.githubusercontent.com/19583619/75650022-c5a65800-5c7a-11ea-96fd-67e35fe3b7ff.png)

In the above picture, all slider elements have a width of `286px`.

Please help.

**Comment by sambhav2612** [comment]
@akiran

**Comment by MykhailoKondrat** [comment]
@sambhav2612 have you figured that out?

**Comment by sambhav2612** [comment]
> @sambhav2612 have you figured that out?

@MykhailoKondrat I think we were able to fix it via CSS
