### ISSUE TITLE
slider translate3d X going crazy after leave it running in a chrome tab behind other tabs

### ISSUE THREAD

**Issue by JianGuo222** [akiran/react-slick#174]
the slick-track transfrom:translate3d(x,y,z)

the x keeps accumulating after leave the chrome tab running in the behind, once come back to the chrome tab, the slider is completely gone to the left, like -12312454px.

**Comment by JianGuo222** [comment]
tried to solve it by reset the translate3d of .slick-track to (0,0,0), but seems there is a hidden internal variable that remembers the accumulated value, and still slides to blank after the reset

**Comment by JianGuo222** [comment]
probably need a static function that can easily reset the whole slider

**Comment by JianGuo222** [comment]
one solution is hack the trackHelper.js, use these 2 lines instead:

WebkitTransform: 'translate3d(' + (spec.left % trackWidth) + 'px, 0px, 0px)',
transform: 'translate3d(' + (spec.left % trackWidth) + 'px, 0px, 0px)',

hopefully, this can be built into the next release

**Comment by laxplaer** [comment]
+1

**Comment by easga** [comment]
I experience it too. i also see that, if i click too fast, x is accumulating in a similar fashion and my items get lost. if i click slowly, there is no problem but if i click fast every single click moves it to an X which gets the items off screen instead of resetting in the end of the cycle. However, the first example in demo seems to work fine. It ignores consecutive clicks as it should. Does any know why would that be?

**Comment by JianGuo222** [comment]
yeah, @easga , I had the same issue. my fix is add a disabled classname to the carousel in beforeChange event, then remove the disabled classname in afterChange event. and just use pointer-event: none on the disabled class.

**Comment by JianGuo222** [comment]
also the translate3d hack above does have minor issue as well, which is after a slide slides in, the slide might flick into a different slide.

**Comment by ChrisCinelli** [comment]
@JianGuo222: I see the flickering even without the hack. That is not introduced by your "hack". I would actually put in a pull request.

**Comment by kidwm** [comment]
Ref: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by Cunha44** [comment]
+1

**Comment by HuarenYu** [comment]
+1
