### ISSUE TITLE
Dragging from left to right breaks the carousel on Chrome

### ISSUE THREAD

**Issue by YBostelaar** [akiran/react-slick#1743]
Hi all,

When dragging from left to right on Chrome the carousel breaks and the slides keep hanging somewhere in between. It also happens in the Playground of react-slick: https://codesandbox.io/s/ppwkk5l6xx

It doesn't happen in other browser such as Firefox and Safari.

Does anybody have a solution for this issue?

**Comment by mayinghan** [comment]
save error

**Comment by jinxin0112** [comment]
I had the same problem

**Comment by JeffreyBouva** [comment]
Having the same issue, @akiran seen this ticket ?

**Comment by gautamz07** [comment]
@YBostelaar seems to work fine , does this issue still exists ?
