### ISSUE TITLE
how to render Slider in map function ?

### ISSUE THREAD

**Issue by mehrdad517** [akiran/react-slick#1744]
{this.props.data.map((list, index) => {
              return(
                <div key={index} style={{position:'relative'}} >
                  <Line title={list.title} link={list.link !== null ? list.link : ''} />
                  <Slider {...settings}/>
                </div>
              );
            })}

but first slider working

**Comment by aminvatanparast** [comment]
بزارش تو مپ رندر میشه

**Comment by SerdarMustafa1** [comment]
Can you elaborate? You want to map multiple sliders or multiple results in a single slider?

My example for the latter is:
```

  <Slider {...settings}>
          {movies.map((element, i) => (
            <div>
              <MovieThumb
                key={i}
                clickable={true}
                image={
                  element.poster_path
                    ? `${IMAGE_BASE_URL}${POSTER_SIZE}${element.poster_path}`
                    : "./images/no_image.jpg"
                }
                movieId={element.id}
                movieName={element.original_title}
              />
            </div>
          ))}
        </Slider>
```
