### ISSUE TITLE
react-slick discussion

### ISSUE THREAD

**Issue by bvasko** [akiran/react-slick#175]
Thoughts on adding a channel for react-slick to reactiflux?

**Comment by tnrich** [comment]
+1 I would love to have somewhere to talk to real-time about new features/configs I'd like to add to react slick

**Comment by tnrich** [comment]
What needs to be done to make a channel? Can anyone do it?

**Comment by bvasko** [comment]
There is a reactiflux channel for new-channel-requests. Based on previous discussions it looks like the request should come from the maintainer. Gitter is also an option. I think anyone can start a gitter room.

**Comment by akiran** [comment]
Let us start using gitter

**Comment by tnrich** [comment]
Gitter sounds good to me

**Comment by bvasko** [comment]
Sounds good to me. @akiran should open it so the room shows up under his github handle

**Comment by mmmurf** [comment]
+1

**Comment by akiran** [comment]
created a gitter room https://gitter.im/akiran/react-slick
