### ISSUE TITLE
appendArrows doesn't work

### ISSUE THREAD

**Issue by rajuahammadfans** [akiran/react-slick#1751]
Hi,
I face a problem when use append arrow. I use custom arrow on my carousel.

`import React, {useState} from 'react';
import {Container, Row, Col} from 'react-bootstrap'
import Portfolio from "../../components/portfolio";
import SlickCarousel from "../../components/SlickCarousel";

const PortfolioDefault = () => {

    const [portfolioData] = useState(require('../../data/portfolio'));

    const carouselSettings = {
        arrows: true,
        autoplay: false,
        autoplaySpeed: 5000,
        dots: false,
        pauseOnFocus: false,
        pauseOnHover: false,
        infinite: true,
        slidesToShow: 5,
        prevArrow: <PrevArrow/>,
        nextArrow: <NextArrow/>,
        responsive: [
            {
                breakpoint: 1199,
                settings: {
                    slidesToShow: 4,
                }
            },
            {
                breakpoint: 991,
                settings: {
                    slidesToShow: 2,
                    autoplay: true,
                }
            },
            {
                breakpoint: 767,
                settings: {
                    slidesToShow: 2,
                    autoplay: true,
                }
            },
            {
                breakpoint: 479,
                settings: {
                    slidesToShow: 1,
                    autoplay: true,
                }
            }
        ]
    };

    return (
        <div className="content-body section">
            <div className="section-wrap section">
                <Container fluid>
                    <Row>
                        <Col className={'p-0'}>
                            <SlickCarousel settings={carouselSettings}>
                                {portfolioData.map(portfolio => (
                                    <div key={portfolio.id} className="col pl-5 pr-5">
                                        <Portfolio title={portfolio.title}
                                                   thumb={portfolio.thumb}
                                                   category={portfolio.category}
                                                   classes={'portfolio-screen-height'}/>
                                    </div>
                                ))}
                            </SlickCarousel>
                        </Col>
                    </Row>
                </Container>
            </div>
        </div>
    );
};

const NextArrow = ({className, onClick}) => {
    return (
        <button className={className} onClick={onClick}>next</button>
    )
};

const PrevArrow = ({className, onClick}) => {
    return (
        <button className={className} onClick={onClick}>prev</button>
    )
};

export default PortfolioDefault;
`

when use appendarrow give a error.

have a any solutions for this?

thanks

**Comment by IBanda** [comment]
Hi
I was reading through your issue. although I'm not very clear but I understand that you're trying to use custom arrows for your carousel. If that's the case you can try this:
1. Get an instance of the slider using a 'ref'
2. Attached to that instance are the methods slickPrev and slickNext which can be used to control the slider. you can access them like this "this.slider.current.slickPrev/Next"
3. Add your custom arrows and make them run those methods when clicked

I hope that helps

**Comment by rajuahammadfans** [comment]
Yes, I want to use custom arrows. I create a ref but my arrows are another component.

that's means carousel and arrows are different components.

So, how can I control this?

Thanks

**Comment by IBanda** [comment]
You can import the custom arrow component into your slider component and pass to `them` the methods as props
` constructor(props) {
    super(props);
    this.slider = React.createRef();
    this.nextSlide = this.nextSlide.bind(this);
    this.prevSlide = this.prevSlide.bind(this);
  }
  nextSlide() {
    this.slider.current.slickNext();
  }
  prevSlide() {
    this.slider.current.slickPrev();
  }
  render() {
    return (
      <div className="slider-wrapper">
        **_<CustomArrow onClick={this.prevSlide} />**
        <Slider ref={this.slider} {...settings}>
        <slide>
        <slide>
        </Slider>
         **<CustomArrow onClick={this.nextSlide} />**
      </div>
    );
  }
}`

**Comment by IBanda** [comment]
You can import the Custom arrows in the carousel component and pass them the methods as props.
Something like this 
```javascript
 constructor(props) {
    super(props);
    this.carousel = React.createRef();
  }
  nextSlide=()=> {
    this.slider.current.slickNext();
  }
  prevSlide=()=> {
    this.slider.current.slickPrev();
  }
  render() {
    return (
      <div className="slider-wrapper">
        <CustomArrowPrev onClick={this.prevSlide} />
        <Carousel ref={this.carousel}>
          <div>
          <Slide1/>
          </div>
           <div>
          <Slide2/>
          </div>
        </Carousel>
        <CutomArrowNext onClick={this.nextSlide} />
      </div>
    );
  }
}
```

**Comment by rajuahammadfans** [comment]
Thanks for the reply.
Actually my carousel is on **Content** Component  and arrows are on **Footer** Component. I create a ref on Content Component. So now, how can I pass this **ref** on **Footer** Component.?

https://prnt.sc/rp8dwk

**Comment by IBanda** [comment]
So in your situation what you could do is create the ref in a parent component that contains the content and footer component.
I created a small example that illustrates how you can do that:
[https://codesandbox.io/s/black-sunset-frys7](https://codesandbox.io/s/black-sunset-frys7)

For a better understanding look at the React DOCs on refs:
[https://reactjs.org/docs/refs-and-the-dom.html](https://reactjs.org/docs/refs-and-the-dom.html)
[https://reactjs.org/docs/forwarding-refs.html](https://reactjs.org/docs/forwarding-refs.html)
[https://reactjs.org/docs/hooks-reference.html#useref](https://reactjs.org/docs/hooks-reference.html#useref)

**Comment by rajuahammadfans** [comment]
@IBanda Thanks, specially for live example.
Problem is solved.
