### ISSUE TITLE
issues in UNSAFE_componentWillMount, UNSAFE_componentWillReceiveProps , findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by karesh** [akiran/react-slick#1752]
React version 16.3.1
react-slick: 0.25.2

I get these warnings.

1.
index.js:1 Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.

2.
Please update the following components: InnerSlider, Slider
console.<computed> @ index.js:1
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

3.
Please update the following components: InnerSlider
console.<computed> @ index.js:1
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Track which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Track)
    in Track (created by InnerSlider)
    in div (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
    ...
    in App (at src/index.js:8)
    in StrictMode (at src/index.js:7)

**Comment by karesh** [comment]
running without strict mode is ok.

**Comment by olasunkanmi04** [comment]
@karesh Please how do you run without strict mode?
