### ISSUE TITLE
Video refs not working

### ISSUE THREAD

**Issue by connoredward** [akiran/react-slick#1754]
Refs for videos inside .map functions aren't working. I'm try to get the next/previous video in the slide to restart from the beginning but the .pause() method for videos doesn't work. I've tested this outside of react-slick and it works as intended.

I've pasted an example below

```
const sliderRef = useRef()
  const videoArrayRefs = useRef(data.map(() => React.createRef()))

  function nextSlide() {
    videoArrayRefs.current[0].current.pause()
  }

  return (
    <div>
      <button onClick={() => nextSlide()}>next</button>
      <Slider {...settings} ref={sliderRef}>
        {data.map(({videoSrc}, index) => <video key={index} src={videoSrc} ref={videoArrayRefs.current[index]} autoPlay muted />)}
      </Slider>
    </div>
  )
```

**Comment by akiran** [comment]
You should pass videoArrayRefs[index] instead of  `videoArrayRefs.current[index]` to ref
