### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by tumdav** [akiran/react-slick#1766]
### Please update the following components: InnerSlider

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Track which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely [here](https://fb.me/react-strict-mode-find-node)`

**Comment by akiran** [comment]
fixed it in react-slick@0.27.0
