### ISSUE TITLE
filtering children and removing slide

### ISSUE THREAD

**Issue by KahyeAhn** [akiran/react-slick#1772]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

I have a list of children and make a div tag looping a children. If a child has a certain type(in this code the types are "ETC" and "BANNER"), I don't want to make a slide and show a user the slide. But in this code, it automatically makes slides as many as children and shows empty slide.
How can I not make a slide in this case?

https://codesandbox.io/s/friendly-goldberg-v14qz?file=/src/App.js

**Comment by akiran** [comment]
filter postAttachments array to exclude objects for which slides are not necessary and then iterate over the filtered array to render slides
