### ISSUE TITLE
Next.js warning: Prop `className` did not match on server and client

### ISSUE THREAD

**Issue by gauravkrp** [akiran/react-slick#1776]
I am developing a next.js react application and used slick slider.
After the first build whenever the page reloads or just hot reloads, I get the following warning in my console::
`Warning: Prop `className` did not match. Server: "slick-slide slick-active slick-current" Client: "slick-slide slick-active slick-center slick-current"`
I also tried using custom babelrc config as follows but nothings helps.
`
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "styled-components",
      { "ssr": true, "displayName": true, "preprocess": false }
    ]
  ]
}
`

Node version: 12.16.2
nextjs version: 9.3.5

**Comment by arun-reddy-g** [comment]
@gauravkrp any other alternatives which would work fine with next.js

**Comment by gauravkrp** [comment]
> @gauravkrp any other alternatives which would work fine with next.js

I am looking to intergrate swiper instead of react slick. I will update when I do test it.

**Comment by cryptic022** [comment]
Hi @gauravkrp This issue is related to nextjs. You can follow this [issue](https://github.com/zeit/next.js/issues/7322) here. Maybe this comment can solve your [problem](https://github.com/zeit/next.js/discussions/12338#discussioncomment-8285)

**Comment by gauravkrp** [comment]
> Hi @gauravkrp This issue is related to nextjs. You can follow this [issue](https://github.com/zeit/next.js/issues/7322) here. Maybe this comment can solve your [problem](https://github.com/zeit/next.js/discussions/12338#discussioncomment-8285)

Hello Pankaj, I have already tried with steps mentioned over there, but nothing helped. This bug with Next.js is still there.

**Comment by gauravkrp** [comment]
**Use nextjs dynamic import and pass ssr option to be false.**
https://nextjs.org/docs/advanced-features/dynamic-import

I just discovered this method and it works in my case as my components has data to load on client side. option SSR needs to be false so that component is loaded on the client side dynamically and is not SSR. 
In my case, the slider components has classes that are initialized and added to elements on client side after the document window is ready. So, the solution will work in all similar cases where the classes are initialized and added on the client side. See my code below.

`
const AGSlider = dynamic(
  () => import('../components/slider'),
  { ssr: false, loading: () => <Loader /> }
)
`

**Comment by simplenotezy** [comment]
@gauravkrp Although that's a workaround, it's still a shame if you won't be able to server side render your content

**Comment by gauravkrp** [comment]
> @gauravkrp Although that's a workaround, it's still a shame if you won't be able to server side render your content

@simplenotezy Are you able to server side render your content using slick-slider in next.js? Can you please provide a snippet here for the issue above? I'm sure your code will be helpful for many developers here :)
