### ISSUE TITLE
Slider loading up as 'unslicked'

### ISSUE THREAD

**Issue by realchriswells** [akiran/react-slick#1777]
I have got a component wrapped by react-slick but for some reason when I render the page the class 'unslicked' is being added to `div.slick-initialized.slick-slider` and none of the `slick-slide` classes are being applied to the content within the track.

https://gist.github.com/realchriswells/9be9c47caca5b81079aedce29f125997

I'm using v0.21.0 as there was an issue with an extra div being added in 0.25.2, and adding `rows: 0` caused Chrome 81 to fall over.

**Comment by cryptic022** [comment]
Hi, @realchriswells I tried to replicate your issue with v0.21.0. I couldn't find any class 'unclicked' in DOM. Here is the [codesandbox](https://codesandbox.io/s/react-slick-playground-jcppe). If you could provide code sandbox with an issue, I might be able to help you.

**Comment by akiran** [comment]
@realchriswells please provide codesandbox to replicate the issue.

Closing it for now since we couldn't replicate the issue
