### ISSUE TITLE
Quick start code sandbox is not working properly

### ISSUE THREAD

**Issue by etasbasi** [akiran/react-slick#1778]
When I navigate to https://codesandbox.io/s/zzloxr09mp mentioned in [quick start](https://react-slick.neostack.com/docs/get-started/). I see a `previous` button and some buttons on bottom left. When I click the previous button some images appear then disappear after ~200ms.
The console doesn't have any errors.
(I also tried to run the example on a local empty project and got the same thing.)

![Annotation 2020-05-02 234601](https://user-images.githubusercontent.com/9984244/80898245-398ecc00-8ccf-11ea-901f-c1e3245f5536.jpg)

![Annotation 2020-05-02 234619](https://user-images.githubusercontent.com/9984244/80898244-398ecc00-8ccf-11ea-8bf1-f8460f64e9d8.jpg)

**Comment by cryptic022** [comment]
Instead of putting external CSS files in index.html, put CSS files in external resources. It will work. Quickstart is also working correctly. I forked your example and fixed it[codesandbox](https://codesandbox.io/s/react-slick-playground-tu1fz)

**Comment by etasbasi** [comment]
Thanks, that works.
