### ISSUE TITLE
How to change currentSlide based on function call from sibling component?

### ISSUE THREAD

**Issue by aadishjain2212** [akiran/react-slick#1788]
Suppose The structure is somewhat like this:
            parentComponent
|__childComponent1(slider)  |__childComponent2(a list of titles of images being displayed in the slider)
currently, the initialSlide is set from ParentComponent's state.
How to change the current slide in the slider, based on selection of a list item in childComponent2?

I tried changing parentComponent's state from childComponent2, thereby updating the initialSlide property of slider. but, this doesn't  change the current slide.
Can anyone help me out?

**Comment by akiran** [comment]
You can use slickGoTo method
https://react-slick.neostack.com/docs/api#slickGoTo

Check this example
https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

**Comment by aadishjain2212** [comment]
Thanks a lot @akiran.

**Comment by maaft** [comment]
I am having a similar problem. How can I call slickGoTo when I don't have access to the object?
```python
export default ({ images, imageIndex, isOpen, setImageIndex, showModal, closeModal}: Props & Actions) => {
    const settings = {
        dots: true,
        lazyLoad: true,
        centerMode: true,
        variableWidth: true,
        infinite: false,
        speed: 500,
        slidesToShow: 2,
        swipeToSlide: false,
        slidesToScroll: 1,
        initialSlide: 0
      };

    return ( 
        <div>
        <Slider { ...settings }>
          {
            images.map((url, index) => (
              <div onClick={() => {setImageIndex(index); showModal();}}>
                <Image size="medium" bordered src={url}/>
              </div>
              )
            )
          }
        </Slider>
      </div>
    );
}
```

**Comment by Dodobrat** [comment]
> I am having a similar problem. How can I call slickGoTo when I don't have access to the object?
> 
> ```ts
> export default ({ images, imageIndex, isOpen, setImageIndex, showModal, closeModal}: Props & Actions) => {
>     const settings = {
>         dots: true,
>         lazyLoad: true,
>         centerMode: true,
>         variableWidth: true,
>         infinite: false,
>         speed: 500,
>         slidesToShow: 2,
>         swipeToSlide: false,
>         slidesToScroll: 1,
>         initialSlide: 0
>       };
> 
>     return ( 
>         <div>
>         <Slider { ...settings }>
>           {
>             images.map((url, index) => (
>               <div onClick={() => {setImageIndex(index); showModal();}}>
>                 <Image size="medium" bordered src={url}/>
>               </div>
>               )
>             )
>           }
>         </Slider>
>       </div>
>     );
> }
> ```

Supposedly you use hooks -> 
```
const [slider, setSlider] = useState(null)

<Slider ref={slider => setSlider(slider)} { ...settings }>
         {
            images.map((url, index) => (
              <div onClick={() => {
                                //Function that goes to slide provided from API
                                slider.slickGoTo(index);
                               //
                                setImageIndex(index); 
                                showModal();
                           }}>
                <Image size="medium" bordered src={url}/>
              </div>
              )
            )
          }
</Slider>
```

Sorry for the bad formatting
