### ISSUE TITLE
Can't mock with jest.mock

### ISSUE THREAD

**Issue by ubotsbr** [akiran/react-slick#1797]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

I'm trying to mock react-slick to unit test my component with jest but the real react-slick is called
jest.mock('react-slick', () => jest.fn(() => null));

How do I mock react-slick?

**Comment by akiran** [comment]
This is not an issue with this library.

Try asking this question on stackoverflow
