### ISSUE TITLE
IE9 not working ("matchMedia")

### ISSUE THREAD

**Issue by zhuber** [akiran/react-slick#1798]
This is not working and all docs seem to point to fixing unit tests. This is actually breaking our app for IE users who are simply loading the app via browser. I think maybe the real issue is being lost along the way due to the fact that the larger issues happen outside of the testing suite.

We've already fixed our test suite with a polyfill, but the much more important issue is that it crashes our app for any users in IE 9 or earlier.

# Steps to replicate:
1. Open Internet Explorer 9
2. View a react-slick gallery
3. Notice the app is broken
4. Inspect console to see issues with matchMedia

# Versions:
- `react`: 16.10.2
- `react-slick`: 0.26.1

**Comment by akiran** [comment]
You can use matchmedia polyfill for IE support

https://www.npmjs.com/package/matchmedia-polyfill
