### ISSUE TITLE
option to temporarily disable forward/back arrows and dots

### ISSUE THREAD

**Issue by tnrich** [akiran/react-slick#180]
I'd like to be able to, based on a prop passed in to the component, disable the forward arrow, the back arrow, or both at the same time. Does anyone know if there is there a way to do that?

Thanks!

**Comment by tnrich** [comment]
Doesn't look like the functionality I want exists yet, so I'll try PRing it. It looks like the test suite isn't totally functional yet, so I hope I'm not breaking anyone else's work...

**Comment by akiran** [comment]
You can use nextArrow and prevArrow for this usecase
