### ISSUE TITLE
Feature: Remaining time on slide?

### ISSUE THREAD

**Issue by Jossnaz** [akiran/react-slick#1801]
I want to have something like this:

an indicator that shows how much time is left in the current slide

![image](https://user-images.githubusercontent.com/2072058/82097647-ece0c300-96c8-11ea-9b02-98fa7a15d14d.png)

is there a simple solution where I dont have to reinvent the wheel with my own hover triggers, then fix mobile  etc?

**Comment by akiran** [comment]
We maintain feature parity with slick carousel 
https://kenwheeler.github.io/slick/

So we can't implement this feature
