### ISSUE TITLE
findDOMNode deprecation warning

### ISSUE THREAD

**Issue by olegzhermal** [akiran/react-slick#1805]
There is a deprecation warning for the react-slick component inside <React.StrictMode>.
**Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Track which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node**

So, perhaps, refactoring is needed.

**Comment by gaston-flores** [comment]
I was looking for the same issue, apparently there's already a PR that fixes this issue: #1442. Previous discussion of the issue is in #1406.

**Comment by akiran** [comment]
Fixed it in react-slick@0.27.0
