### ISSUE TITLE
Carousel not working

### ISSUE THREAD

**Issue by mridulgogia** [akiran/react-slick#1806]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

react-slick not working
Even in the [codesandbox](https://codesandbox.io/s/ppwkk5l6xx?file=/index.js) the carousel does not work 

My code 
  const mapping = data.map((item, index) => (
    <Card className="text-center" key={index}>
        <Card.Header>
          <Link to={`/company/${item.ticker}`} className="magic-link"></Link>
          {item.companyName}
        </Card.Header>
        <Card.Body>
          <Card.Title>{item.ticker}</Card.Title>
          <Card.Text>$ {item.price}</Card.Text>
          <Card.Text
            className={
              item.changesPercentage[1] !== "-" ? "positive" : "negative"
            }
          >
            {item.changesPercentage}
          </Card.Text>
        </Card.Body>
      </Card>
  ));

  const settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 1,
  };

  return (
    <div className="row">
      <div className="col-md-12 carousel_container">
        <h2 className="carousel_title"> {title}</h2>
        <Slider {...settings}>{mapping}</Slider>
      </div>
    </div>
  );

![Screenshot from 2020-05-24 15-16-14](https://user-images.githubusercontent.com/44144128/82750950-8e56cb80-9dd1-11ea-9153-d24810ff500b.png)

**Comment by akiran** [comment]
You might have missed adding css 
Check docs
https://react-slick.neostack.com/docs/get-started
