### ISSUE TITLE
Horizontal Scroll should be hidden by default.

### ISSUE THREAD

**Issue by tbaustin** [akiran/react-slick#1808]
I created a blank CRA (create-react-app) application and installed `react-slick` and imported the styling. There is horizontal scroll with just the basic setup used from the readme. I think this should be hidden by default. 

```js
var settings = {
		dots: true,
		infinite: true,
		speed: 500,
		slidesToShow: 1,
		slidesToScroll: 1,
	}
	return (
		<>
			{/* <Global styles={globalOverride} /> */}
			<Slider {...settings}>
				<div>
					<h3>1</h3>
				</div>
				<div>
					<h3>2</h3>
				</div>
				<div>
					<h3>3</h3>
				</div>
				<div>
					<h3>4</h3>
				</div>
				<div>
					<h3>5</h3>
				</div>
				<div>
					<h3>6</h3>
				</div>
			</Slider>
		</>
	)
```

![Screen Shot 2020-05-27 at 10 24 04 AM](https://user-images.githubusercontent.com/14001400/83039813-3358ea80-a004-11ea-87aa-00e9c983f3bf.png)

**Comment by akiran** [comment]
You should solve this with css
