### ISSUE TITLE
add a custom state for custom arrows

### ISSUE THREAD

**Issue by PBRT** [akiran/react-slick#181]
Could it be possible to add custom props when using custom arrows (like an array/object or something)?  I'd like to animate my arrows on hover. A ```this.props.isVisible```would be perfect for that, transmitted from the ```<Slider>```comp.

I have the following code : 

```
var CarouselArrow = React.createClass({
    displayName: 'CarouselArrow',
    render() {
      return (
        <div {...this.props} style={s.prevArrow} className='slick-arrow'>
          <i className='icon-web_arrow_left'></i>
        </div>
      );
    },
  });

var Slider = React.createClass({
    displayName: 'Slider',
    getInitialState(){
      return {this.state.isVisible: false};
    },
    render() {
      var settings = {
        adaptativeHeight: true,
        arrows: true,
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        dotsClass: 'slick-indicators',
        slickGoTo: 4,
        className: 'inner-slider',
       isVisible: this.state.isVisible,
      };
      return (
          <Slider
            {...settings}
            prevArrow={CarouselArrow}
            nextArrow={CarouselArrow}>
              <div>1</div>
              <div>2</div>
          </Slider>
      );
    },
  });

```

I'd like to pass the ```this.state.isVisible``` in the settings object for reaching the Arrow comp. However, this additional field will be populated only until the ```InnerSlider``` comp where the arrows are instantiate. 

One way to make this work is to add a arrowProps field in the setting object which will be transmitted in the ```InnerSlider``` to the arrow object.

Do you have any idea how to implement that? Exept that everything works like a charm :100:

**Comment by akiran** [comment]
You can get this working without additional option by adding animation logic in custom arrow or with css.
