### ISSUE TITLE
When i using this Slider getting the below attached warnings

### ISSUE THREAD

**Issue by deepankarsen** [akiran/react-slick#1812]
index.js:1 Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: InnerSlider, Slider

**Comment by akiran** [comment]
Fixed in react-slick@0.27.9
