### ISSUE TITLE
OnClick outline

### ISSUE THREAD

**Issue by bashford7** [akiran/react-slick#1817]
I'm trying to remove the black slide outline that appears when clicked or dragged. I've tried 
```
body {
   outline: 0;
   border: 0;
}
```
To no avail.

Thanks!

**Comment by greenimpala** [comment]
https://github.com/akiran/react-slick/issues/1439

**Comment by akiran** [comment]
Solution here
https://github.com/akiran/react-slick/issues/1439#issuecomment-445664432
