### ISSUE TITLE
Width being calculated to a ridiculously large value

### ISSUE THREAD

**Issue by I2obiN** [akiran/react-slick#1836]
![image](https://user-images.githubusercontent.com/7683830/87304121-3a807d00-c50c-11ea-92a4-33a978654778.png)

I have a very basic application using the Kentico Kontent API Sample Application. I have removed all normalize css and any other css I can find from the application. I am just dropping the basic demo html for the most part. I can see the image come up briefly for a moment then disappear completely.

I can place normal elements including images about it with no issue. Within the div elements

Does anyone have an inkling or knowledge of why this is happening?

**Comment by I2obiN** [comment]
Resolved

**Comment by AlexKotov** [comment]
@I2obiN Any suggestions?

**Comment by AlexKotov** [comment]
the reason is flex css

**Comment by MarkPare** [comment]
@I2obiN @AlexKotov what is the fix for this? Having same issue.

**Comment by tannerbaum** [comment]
Also having this. I checked on the issue @I2obiN filed in his other repository, and he had styles from Slick being overwritten. At first glance that doesn't seem to be the case on my end.

**Comment by MarkPare** [comment]
Looks like this happens because an ancestor of slider uses `display: flex`.  I was able to fix it by applying the following css to the nearest ancestor of slider that is a child of an element with `display: flex`: 

```
flex: 1 1 0px;
overflow: hidden;
```

**Comment by tannerbaum** [comment]
I couldn't find the flex that was causing it for us - if it was the same problem at all. What we did to fix it was setting a couple of max-width properties on parents of the slider.
