### ISSUE TITLE
Rendering a component as a seperate slide

### ISSUE THREAD

**Issue by TadasMil** [akiran/react-slick#1841]
This is my Slider and I am trying to render `UserReview` as a seperate Slide. Unfortunately, `UserReview` items are being render all together in one slide.

`<Slider {...settings}>
                    
                        {
                            this.state.users.map(item=>{
                                return (
                                    <div>
                                        <UserReview key={item.id} userReview={item}/>
                                    </div>
                                )
                            })
                        }    
                    
                </Slider>
`

I want to render each of UserReview as a seperate slide. This is the `UserReview` component:

`export default function UserReview(props) {
    const {name, review, img} = props.userReview;
    return (

         <div className='user-review'>
             <h3>{review}</h3>
                <div className='user-review-info'>
                    <h4>{name}</h4>
                    <img src={img} alt='user'></img>
                </div>
            </div>
    )
}`

Does anyone know why the `UserReview` components elements are being rendered on a single slide?

**Comment by gilans** [comment]
Hi ! @TadasMil , it could be the width of each element <UserReview />, react-slick creates each slide depending on the size of the elements.

**Comment by akiran** [comment]
Please provide a codesandbox link with code to reproduce the bug.
