### ISSUE TITLE
🔲 Carousel inside another carousel

### ISSUE THREAD

**Issue by RuellePaul** [akiran/react-slick#1845]
Is there a way with React Slick to have Carousel inside Carousel ?

```
import Slider from "react-slick";

<Slider
    {...settings}
>
        <div/>
        <div>
            <Slider
                {...settings}
            >
                ...
            </Slider>
       </div>
       <div/>
</Slider>
```

I tried this kind of code but it completely messed up both carousels.

I don't need to have swipe, dots or arrow, carousel are fully controlled using `slickGoTo`.

Thank for your help

**Comment by akiran** [comment]
I don't think we can support this usecase
