### ISSUE TITLE
Transform scale style displaces arrows

### ISSUE THREAD

**Issue by justintim3** [akiran/react-slick#1849]
I noticed that applying transform scale styling seems to displace the positioning of custom arrow components which prevents it from being centered. Is there any solution/workaround for this?

Here's a sandbox example:  https://codesandbox.io/s/react-slick-rjcri

**Comment by tazcarper** [comment]
You should be able to apply the transform scale to the psuedo element inside of the arrow instead of the parent arrow.


```
.slick-prev:before {
    position: absolute;
    transform: scale3d(-1, 1, 1);
```

**Comment by justintim3** [comment]
That seems to work thanks!
