### ISSUE TITLE
 "tabbing" between slides breaks carousel 

### ISSUE THREAD

**Issue by tnrich** [akiran/react-slick#185]
Currently if there are multiple input boxes spanning multiple slides, tabbing between them causes the carousel to get stuck halfway between slides. This should definitely not be the default behavior. 

Also, does anyone know if there is a way to prevent "tabbing" between inputs on separate slides altogether?

**Comment by dearsaturn** [comment]
Very late, but to anyone that sees this, you'll probably want to just `lazyLoad: true` to prevent the next slide from even being loaded or `tabIndex=-1` and prevent tabbing altogether.

**Comment by renatho** [comment]
Here's a sample [simulating the problem] (https://jsfiddle.net/mk5nn5mw/).
Try to navigate with tabs and look what happens.
I think the correct behavior would be to go to the slide, but with the correct position without break the slider.

**Comment by renatho** [comment]
Would any of the maintainers have an interest in solving this accessibility / usability problem?
@jeffh @jonathanp @kjs3

**Comment by dearsaturn** [comment]
Just use another library. This issue won't get any attention.

https://github.com/leandrowd/react-responsive-carousel

**Comment by dearsaturn** [comment]
@renatho Just use another library. This issue won't get any attention. No issue here will.

https://github.com/leandrowd/react-responsive-carousel

**Comment by sumeetkate** [comment]
Is there update on this issue ?

**Comment by dnlml** [comment]
Up, I also have this problem

**Comment by vitorolivg** [comment]
...

**Comment by jcowher** [comment]
Just throwing this out there for anyone looking. Seems like this bug applies to more than just Slick. https://wd.dizaina.net/en/internet-maintenance/js-sliders-and-the-tab-key/
