### ISSUE TITLE
How to change dynamically the width of a slide ?

### ISSUE THREAD

**Issue by GeoffreySautieres** [akiran/react-slick#1850]
Hey guys, 

I have one question about `react-slick`, in my slider, I want to display images ! After rendering, I'd like to change the width of the image according to the active one. I'll share with you a quick use case, when image 2 is going to take the place of image 1, it will have a larger width and in this case image 1 will shrink.

![demo](https://user-images.githubusercontent.com/47658009/88858690-af380480-d1f8-11ea-966c-4dd9cdbd612e.png)

By doing this I have a problem with the `slick-track` and the `translate3d`, it can't adapt to the change.
I managed to get the desired behavior, but the slider doesn't work as soon as I want to change slides.

Thank you for your help !

**Comment by akiran** [comment]
Dynamically changing widths can't be supported.
