### ISSUE TITLE
how can implement next prev buttons and indicators together like this image ?

### ISSUE THREAD

**Issue by Moji0098** [akiran/react-slick#1855]
[image](https://cdn1.bbcode0.com/uploads/2020/8/3/bb6f824bba8960dc250ae33a9c6d193b-full.png)

**Comment by saulofilho** [comment]
`  useEffect(() => {
    const queryPagination = document.querySelector('.pagination-home')
    const queryBtnPrev = document.querySelector('.button-prev-home')
    const queryBtnNext = document.querySelector('.button-next-home')
    const appendPaginationPrev = queryPagination.appendChild(queryBtnPrev)
    const appendPaginationNext = queryPagination.appendChild(queryBtnNext)
  }, [])
`

**Comment by saulofilho** [comment]
I've achieved something like that in React:

`
useEffect(() => { 
const queryPagination = document.querySelector('.pagination-home') 
const queryBtnPrev = document.querySelector('.button-prev-home') 
const queryBtnNext = document.querySelector('.button-next-home') 
const appendPaginationPrev = queryPagination.appendChild(queryBtnPrev) 
const appendPaginationNext = queryPagination.appendChild(queryBtnNext) }, 
[])
`

**Comment by saulofilho** [comment]
I've achieved something like that in React:

`
useEffect(() => { 
const queryPagination = document.querySelector('.pagination-home')

const queryBtnPrev = document.querySelector('.button-prev-home') 
const queryBtnNext = document.querySelector('.button-next-home') 
const appendPaginationPrev = queryPagination.appendChild(queryBtnPrev) 
const appendPaginationNext = queryPagination.appendChild(queryBtnNext) }, 
[])
`

**Comment by akiran** [comment]
You have to use custom arrows feature.

https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js
