### ISSUE TITLE
Unnecessary div wrapper on slide items

### ISSUE THREAD

**Issue by n8green** [akiran/react-slick#1868]
Slide items are wrapped in a div which is not necessary.

This is very likely related to this issue - https://github.com/kenwheeler/slick/issues/3110 - the workaround of setting rows: 0 option does resolve the issue with the slick library, but causes a memory leak with react-slick.

**Comment by tazcarper** [comment]
Related: https://github.com/akiran/react-slick/pull/1848

**Comment by akiran** [comment]
Tracking in #1877
