### ISSUE TITLE
draggable should not move slides when fade is on

### ISSUE THREAD

**Issue by darkalor** [akiran/react-slick#187]
When both `draggable` and `fade` are on slides transition with fade, but dragging still changes the horizontal position, so e.g. you can move you slide outside the screen.

**Comment by ChrisCinelli** [comment]
+1 I think this PR would fix it - https://github.com/akiran/react-slick/pull/30 - Not sure why @akiran did not merge it when it was submitted in March..

**Comment by frg** [comment]
+1 For fix. This has really been bugging me lately :/

**Comment by i8ramin** [comment]
Same issue here. Does https://github.com/akiran/react-slick/pull/30 indeed fix the issue? if so, could we get it merged in?

**Comment by laveesingh** [comment]
The issue has been fixed long back. Please feel free to request reopen if someone disagrees.
