### ISSUE TITLE
Slick Track should add line-height: 0 to prevent white space sizing

### ISSUE THREAD

**Issue by tomchentw** [akiran/react-slick#1880]
![ycKIYNv3Pj](https://user-images.githubusercontent.com/922234/91270334-0eaf1300-e7ab-11ea-9d10-df26ce01a762.gif)

## Reproduce Steps

* Go to the demo page, open DevTools
* Select the element `.slick-track` and add `line-height: 20` to its style
* Observed the sizing of it has dramatically increased

## Expected Behavior

The `.slick-track` should set the `line-height: 0` in its inline-style

**Comment by akiran** [comment]
I don't think this is the right solution

**Comment by RZsam** [comment]
I don't think this is a `react-slick` issue. I was trying to make `img` in the slider and parent `div` the same height but I did not find any reason why it's taller. I  found [this](https://github.com/kenwheeler/slick/issues/3509#issue-341991915).
anyway, @tomchentw workaround solved the problem for me.
