### ISSUE TITLE
In Production, The Slider contents are not shown 

### ISSUE THREAD

**Issue by aashishshrestha5532** [akiran/react-slick#1883]
In local development the Slider is working fine but in production the slider is not showing up 

I am using react-slick@0.26.1

### Production
![Screenshot from 2020-08-30 18-05-05](https://user-images.githubusercontent.com/26792137/91658866-a6826900-eaeb-11ea-98ff-f282c769e21a.png)

### Local Development
![Screenshot from 2020-08-30 18-06-52](https://user-images.githubusercontent.com/26792137/91658872-b0a46780-eaeb-11ea-9675-d1bfa0579e02.png)

**Comment by akiran** [comment]
Please provide code to replicate the problem and reopen this issue
