### ISSUE TITLE
Giant width within flex container

### ISSUE THREAD

**Issue by Diegovisk** [akiran/react-slick#1887]
It's quite simple, and straightforward.

I don't know if someone else reported this, I've looked within some issues but didn't found something related.

I've modified the base sandbox and here is the link: [https://codesandbox.io/s/react-slick-playground-forked-dnc0n](https://codesandbox.io/s/react-slick-playground-forked-dnc0n)

It also happens inside children of flex elements.

Came around this while trying to use it in some projects of mine, below is the picture of what happened.

More info:
**react-slick version:** 0.26 (on my projects, default on the sandbox)
**browser:** Firefox 80.0.1 (64-bits)

![image](https://user-images.githubusercontent.com/20441537/91988058-d48ac780-ecfc-11ea-9a3a-d8d017268d5e.png)

**Comment by Diegovisk** [comment]
Found a quick-fix for the children of flex-based elements. Applying `max-width: 100%;` to a non-flex child of a flex container seemed to work for me.

In the above sandbox, I've created a div inside `.container` and applied `.container > div {max-width:100%;}`

**Comment by bkennedyfuture** [comment]
@Diegovisk came across your issue because I the same. Setting `flex-direction: column` on the container will prevent the unwieldy overflow. Hope it helps!

**Comment by liaokaime** [comment]
Here's how I solved it
```jsx
<div style={{
    width:"100%",
    height: "100%",
    position: "relative",
}}>
    <div style={{
        position: "absolute",
        top: 0,
        bottom: 0,
        right: 0,
        left: 0
    }}>
        <Carousel >
            ~~~
        </Carousel>
    </div>
</div>
````

**Comment by netojose** [comment]
@liaokaime , you saved my day!!!
