### ISSUE TITLE
How to set slickCurrentSlide correctly?

### ISSUE THREAD

**Issue by exocode** [akiran/react-slick#1894]
I have a slider where the third slide should be active. I've set `slickCurrentSlide` to 2 in the sliderSettings which are passed to the Slider. But it seems not picking up. When I first click the next slide, the correct slider is active. but the initial state is not correct: 

 

**As it should be:**

<img width="991" alt="Bildschirmfoto 2020-09-18 um 20 52 03" src="https://user-images.githubusercontent.com/1597621/93634602-2b78e800-f9f1-11ea-982e-3e54b32396b7.png">

**As it is:** 

<img width="987" alt="Bildschirmfoto 2020-09-18 um 20 51 56" src="https://user-images.githubusercontent.com/1597621/93634615-2fa50580-f9f1-11ea-9e14-c847a9014b92.png">

These are my current settings: 
```js
    var sliderGallerySettings = {
      infinite: true,
      slidesToShow: 4,
      slidesToScroll: 1,
      dots: true,
      slide: "row",
      arrows: false,
      slickCurrentSlide: 2,
      centerPadding: "0",
      centerMode: true,
      initialSlide: 2,
      beforeChange: (current, next) => {
        this.setState({ activeSlide: next })
      },
```

The `slick-current` className is not attached properly. 

How can I solve that? I tried to change `slickCurrentSlide`, `initialSlide` in all possible ways.

**Comment by akiran** [comment]
use slickGoTo method

https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js
