### ISSUE TITLE
NEXT JS DOESN'T WORK

### ISSUE THREAD

**Issue by matheuskousen** [akiran/react-slick#1895]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

ERROR  >> CAN'T RESOLVE '.@import "slick-carousel/slick/slick.css";

**Comment by akiran** [comment]
you need to install slick-carousel

Also, You should not use @ if you are importing css in javascript.
just 
```import  "slick-carousel/slick/slick.css";```
