### ISSUE TITLE
Only able to slide when an animation has completed?

### ISSUE THREAD

**Issue by steroberts89** [akiran/react-slick#19]
Hey

I've noticed that the navigation buttons only work when the animating state is false, does anyone know the reasoning behind this? you can see what I mean [here](https://github.com/akiran/react-slick/blob/master/lib/mixins/helpers.js#L164)

I've disabled in In my usage by doing this (logic was copied from the further if statement 4 lines down)

``` javascript
if (this.state.animating === true && this.state.currentSlide === index) {
     return;
}
```

Is this by design or is there another reason for this?

Cheers
Stephen Roberts

**Comment by akiran** [comment]
@steroberts89,  This is by design.   

Original slick carousel does the same thing https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1728

**Comment by akiran** [comment]
Do you have a usecase where you need this ?

**Comment by steroberts89** [comment]
Yeah,

so we're using it for displaying various prices/days of flights for instance with the slider operating in centre mode, and the centred item is the item which is being displayed in further details (hence my pull request yesterday for me to get the index out!) 

We're displaying 3 prices at a time, and if the user say wants scroll through all the options, they have to wait for the animation to finish before they go to the next. It could get rather frustrating if the user has to wait to click next! 

Cheers
Stephen

**Comment by akiran** [comment]
Yes, We should fix it then.

slick-carousel has a waitForAnimate option which is not implemented in the react-slick yet.
This address your issue.
waitForAnimate = true, buttons work only  after animation completion
waitForAnimate = false, buttons work before animation completion as well.

**Comment by akiran** [comment]
waitForAnimate = false setting should fix this issue

**Comment by vlafiser** [comment]
Guys thanks for implementing, it's helpful, but it's not in the doc. ;) I found it by check of the component definition. Can you add? Thanks!
