### ISSUE TITLE
Configurable lazy load

### ISSUE THREAD

**Issue by mping** [akiran/react-slick#191]
Hi,

Do you have plans to allow preloading a defined set of images? With lazy load, the image loading is noticeable when you move to the next slide.

Ideally you would supply a param specifying how many components should be prerendered before and after the current slide.

**Comment by mping** [comment]
Any updates on this?

**Comment by akiran** [comment]
Since this is not part of original slick API,  we don't have any plan for implementing this.

I think you should implement  a custom prefetching scheme using beforeChange/afterChange hooks.

**Comment by mping** [comment]
Pity, but fair enough. I'll take a look on the hooks. Thanks

**Comment by bondom** [comment]
@mping Did you implement custom lazy loading using beforeChange/afterChange hooks? If yes, will be glad to take a look at your code :)

**Comment by idangozlan** [comment]
Any solution for it?

**Comment by bondom** [comment]
@idangozlan I implemented solution, it is not ideal(as far as I remember there is some problem when user tries to click left or right arrow very fast, in that case smoothness effect doesn't work) but generally it works: https://github.com/bondom/react-slick/tree/feature/smart-lazy-loading
