### ISSUE TITLE
Released version is higher than Github repo latest?

### ISSUE THREAD

**Issue by dlong500** [akiran/react-slick#1913]
Where is the v0.27.12 release coming from?  The package.json version in master is currently v0.27.11.  Also, I'm assuming since the "experimental" alert was remove for v0.27.x that there is no longer a recommendation to wait for a v0.28 release for production use?  Thanks for your work--just looking for some clarification.

**Comment by akiran** [comment]
removed alert in  v0.27.12 and pushed to github
