### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by apepper** [akiran/react-slick#1918]
`react-slick` currently support multiple react versions:

https://github.com/akiran/react-slick/blob/54188538d503c0f2df0a7c8c399ec03637bae22c/package.json#L96-L99

But it does not yet support [React 17](https://reactjs.org/blog/2020/10/20/react-v17.html). Please add support for the latest react version.

**Comment by apepper** [comment]
@akiran Thank you for the support of react 17 with 4ca610d. Is there any ETA when this change will be available on NPM?

**Comment by akiran** [comment]
@apepper  released 0.27.13 with this change

**Comment by apepper** [comment]
Any ETA for the release of `0.27.13`? https://www.npmjs.com/package/react-slick still lists `0.27.12`.

**Comment by akiran** [comment]
@apepper I already published.

It may be an npm cache issue.
It will appear on npm in sometime.

**Comment by apepper** [comment]
Awesome. Thank you for your work @akiran!
