### ISSUE TITLE
 arrows outside the scope of the carousel

### ISSUE THREAD

**Issue by kkleber1991** [akiran/react-slick#1919]
the sandbox link of the arrows for the next and previous image

https://codesandbox.io/s/funny-hopper-9zyx1

it is like this:
![gif](https://user-images.githubusercontent.com/50781783/97793712-deba2c80-1bac-11eb-9171-c879ba8418e6.gif)

I need it that way
![img](https://user-images.githubusercontent.com/50781783/97793728-175a0600-1bad-11eb-8bc7-f09340a3636d.png)

**Comment by akiran** [comment]
You can accomplish this with custom css for `.slick-arrow` class
