### ISSUE TITLE
Will slickGoTo be fixed? #1685

### ISSUE THREAD

**Issue by AceBerry924** [akiran/react-slick#1921]
I'm trying to save the state of my slider when moving between different pages of my react app.

Tge slickGoTo example on the site doesn't seem to work.

To my best of knowledge what's required to get things working is:

```
<Slider
          ref={slider => (this.slider = slider)} />
```
Then I've tried:
```
onInit: () => {
        this.slider.slickGoTo(0); 
      },
```

'0' being whatever the state is. The thing is, I've tried putting this.slider.slickGoTo at various places throughout the app and I always get the same error:

TypeError: Cannot read property 'slickGoTo' of undefined

I didn't find solution on online..
Hope to help me

**Comment by gautamgoshopmatic** [comment]
where are you saving the ref ?

**Comment by AceBerry924** [comment]
I saved using Hook - `useRef`

**Comment by AceBerry924** [comment]
@gautamgoshopmatic, is it working on your side?

`let sliderRef = useRef();`

I declared like this\

Hope you to help me
Thank you

**Comment by oparizek** [comment]
@AceBerry924 In case you use functional component & hooks you should do it like this:

```js
const sliderRef = useRef();
const onInit = () => sliderRef.current.slickGoTo(0);

return <Slider ref={sliderRef} />
```
