### ISSUE TITLE
Touch scrolling causes console errors with latest version of React

### ISSUE THREAD

**Issue by ifancyabroad** [akiran/react-slick#1924]
With latest version of React (17.0.1), touch event on mobile is causing the following console error:

`Unable to preventDefault inside passive event listener invocation.`

This can be seen by using Chrome devtools and responsive mode in the following link:

https://codesandbox.io/s/react-slick-playground-forked-futdl

**Comment by mauroxdev** [comment]
I have the same issue, with React 17.0.1 and NextJS 10.0.1

**Comment by gary-imotor** [comment]
I have the same error in console after binding an onClick event handler to images inside of the Carousel.
React 17.0.1 and Gatsby 2.27.0.

**Comment by takeItIzzy** [comment]
same issue with react 17.0.1 ande next.js 10.0.3

**Comment by RZsam** [comment]
same here
    "next": "^10.0.0",
    "react": "^17.0.1",

I also tried `touch-action:none` in every class but didn't help

**Comment by mouadlouhichi** [comment]
I have the same issue in console with React 17.0.1

**Comment by Ali72** [comment]
Can you find a way to fix this issue?

**Comment by riimako** [comment]
In the version 0.28 this seems to be fixed.
https://github.com/akiran/react-slick/pull/1971

I updated our version of the library and it works.
