### ISSUE TITLE
Urgent - Change Dots Count

### ISSUE THREAD

**Issue by mosvict** [akiran/react-slick#1937]
Hello. How are you?
I have a problem to use react-slick.
Slider has 10 screen. I set these configuration for slider.
slidesToShow: 6,
slidesToScroll: 1,
I see 10 dots at bottom.
Can I display couple dots?
Please help me.

**Comment by VadimSvirdoff** [comment]
You could use append dot, it's allow you show as mach dots as you need.
https://react-slick.neostack.com/docs/example/append-dots

**Comment by akiran** [comment]
It is expected behavior.

number of dots = number of slides/slidesToScroll

For slidesToScroll = 1, number of dots = number of slides

**Comment by mosvict** [comment]
Thank you
