### ISSUE TITLE
How to make all equal-height slides

### ISSUE THREAD

**Issue by mylesfarm** [akiran/react-slick#1940]
Hello, and thank you for this awesome library!

I'm attempting to have all my slides be the same height, equivalent to the tallest of the slides (from wrapping text growing the element's height), and having some trouble achieving this. I tried toggling the `adaptiveHeight` prop to `true`, but this only adjusts the slick container to the taller height once that taller slide is centered/selected.

I have then added the following custom CSS to the `.slick-track`: `display: flex; flex-direction: row; align-items: stretch` to set the child items to take up the full height. I have also set each child item to `display: flex; flex-direction: column; flex: 1` to have them take up the full height, but it doesn't appear to be stretching them vertically as expected. What's strange to me is that setting `.slick-track`'s `align-items` to either `flex-start` or `flex-end` does indeed align the children appropriately, but setting the value to `stretch` does not take effect.

Any tips on how to handle this would be appreciated. Thank you very much!

**Comment by Cedric-Delacombaz** [comment]
Did this a while ago and it worked for me:

```javascript
const CarouselLayoutContainer = styled.div`
    //// slick-track is the container of all slide items
    .slick-track {
         display: flex;
         align-items: stretch;
    }
    // slick slide is the container of a single slide item. There is also a wrapper div before our custom component
    .slick-slide {
        display: flex;
        align-self: stretch;
        height: unset;
        > div {
            display: flex;
            align-self: stretch;
            width: 100%;
        }
    }
`
```

**Comment by mylesfarm** [comment]
@Cedric-Delacombaz Thanks! I used your solution with `height: 100%` on `.slick-slide > div`, and just had to add `height: 100%` to my custom component inside. Much appreciated.

<img width="833" alt="Screen Shot 2020-12-07 at 9 40 16 " src="https://user-images.githubusercontent.com/46573464/101385356-8c85be80-3870-11eb-825f-ac032106187c.png">

**Comment by ChazUK** [comment]
I feel like this should be an option of the library.

**Comment by fungcheukyin-TeamLab** [comment]
Encountered same issue in my project.
It would be great if the library could include this as an optional setting.
