### ISSUE TITLE
first element not shown as expected after loading

### ISSUE THREAD

**Issue by MZDN** [akiran/react-slick#1941]
I am using following setting:

>  const settings = {
            initialSlide: 0,
            dots: false,
            infinite: false,
            autoplay: false,
            speed: 500,
            arrows: true,
            slidesToShow:2,
            rtl:true,
            afterChange:()=>{
                this.slider.slickGoTo(2);
                }
        };

expected to be shown the first 2 sliderItems. But the last 2 sliderItems are being shown.

**Comment by akiran** [comment]
```
afterChange:()=>{
this.slider.slickGoTo(2);
}
```
might be causing the issue

**Comment by MZDN** [comment]
> ```
> afterChange:()=>{
> this.slider.slickGoTo(2);
> }
> ```
> 
> might be causing the issue

I removed it, but couldn't help.

**Comment by nayararn** [comment]
Any solution to this problem?
