### ISSUE TITLE
Can´t resolve react-slick component with GatsbyJS

### ISSUE THREAD

**Issue by igorgarciaco** [akiran/react-slick#1959]
When Gatsby build a default slick component, it shows this error

> undefined failed
>
> Can't resolve 'react-slick' in '/usr/src/app/www/src/components'
> 
> If you're trying to use a package make sure that 'react-slick' is installed. If you're trying to use a local file make sure that the path is correct.
> 
> For more details see https://gatsby.dev/issue-how-to

![image](https://user-images.githubusercontent.com/36867094/103807185-cf37e380-5034-11eb-803e-b3838689f752.png)

**Comment by akiran** [comment]
Check if react-slick and slick-carousel dependencies are installed
