### ISSUE TITLE
When clicking on a dot, before/afterChange are not fired

### ISSUE THREAD

**Issue by foxeil** [akiran/react-slick#196]
i'm using setState inside beforeChange, and it works perfectly with the autoplay, but when i click on the navigation dots, beforeChange is not fired, and therefore my state stays the same until the next image is displayed by the autoplay

**Comment by kioopi** [comment]
I can't reproduce this.  In a simple setup `beforeChange` is fired when clicking on prev/next as well as when clicking on dots.

**Comment by akiran** [comment]
Thanks @kioopi  for checking this.
