### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by mataps** [akiran/react-slick#2]
Not very easy to use, I had to add ``webpack jsx loaders`` and edit ``after-transition component``. It's just to lengthy process and destructable edits to make this work.

**Comment by akiran** [comment]
I cleaned up some of the issues.

Setting up react-slick requires some steps like copying fonts and css from slick-carousel and building jsx etc. I hope you are using tools like gulpjs or gruntjs

I created a yeoman generator which helps you in setting up quickly
https://github.com/akiran/generator-react-slick

Let me know if it helps

**Comment by akiran** [comment]
after-transition component is no longer needed with latest version of react-slick

**Comment by akiran** [comment]
Added standalone built files (dist folder) in the latest release.
