### ISSUE TITLE
Reactify dependency missing from your package.json

### ISSUE THREAD

**Issue by eriklharper** [akiran/react-slick#20]
Attempting to use your react-slick component and I'm getting a build error, that looks to be because you don't specify "reactify" as a dependency anywhere in your package.json even though you're using it as a browserify transform.  You must have it installed locally, but just forgot to commit that to the package.json?

```
>> Error: Cannot find module 'reactify' from './node_modules/react-slick'
Warning: Error running grunt-browserify. Use --force to continue.
```

**Comment by akiran** [comment]
Fixed it

**Comment by burtyish** [comment]
I'm getting the same error in version 0.4.1

**Comment by vramana** [comment]
@burtyish We use babel-loader as the transformer. What build tool are you using and what is your configuration ?

**Comment by akiran** [comment]
@burtyish  reactify is already added in devDependencies of package.json

**Comment by burtyish** [comment]
@vramana I use [coffee-reactify](https://github.com/jsdf/coffee-reactify)

**Comment by vramana** [comment]
It is not about relevancy. I don't how to setup grunt properly so little bare-bones grunt conf would help me to focus on the issue rather than trying to setup grunt.

**Comment by burtyish** [comment]
I see, you're trying to reproduce the problem. I'll see if I can provide a bare-bones setup like you mentioned.
By the way, if I use the files in the dist folder directly, browserify succeeds, but I run into #40

**Comment by vramana** [comment]
Yes. I want to reproduce the issue. I'll look in that as well.

**Comment by burtyish** [comment]
I used a boilerplate to quickly set it up. You can clone https://github.com/burtyish/grunt-react-boilerplate/commits/master and try it out yourself.
Thanks for the quick reply!

**Comment by vramana** [comment]
I think I found the issue @burtyish. You have to reactify is added as devDependency, so it is not being installed by default. If I add it as dependency, I don't see this anymore.

But the grunt transformer is not properly transforming `App.jsx` So it is giving errors. When I added this 
```
  "browserify": {
    "transform": [
      [
        "reactify",
        {
          "es6": true
        }
      ]
    ]
  }
``` 
To package.json everything compiles.

**Comment by burtyish** [comment]
I'd like to test the fix in my project. Do I have to wait for a release?

**Comment by vramana** [comment]
We just released 0.5 version !! Try it out.

**Comment by burtyish** [comment]
Now I get `Error: Cannot find module 'reactify' from './node_modules/react-slick/node_modules/react-responsive-mixin'`
However, if I require `node_modules/react-slick/dist/react-slick.min` directly, it works fine.

**Comment by vramana** [comment]
@burtyish  That is because of this https://github.com/akiran/react-responsive-mixin/blob/master/package.json#L44 I will clean it up later.
