### ISSUE TITLE
slider show blank screen on Mobile View for the first time in map function.

### ISSUE THREAD

**Issue by Rvi851994** [akiran/react-slick#2007]
`const settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 1,
    initialSlide: 0,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 767,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          initialSlide: 2,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
        },
      },
    ],
  };

<Slider {...settings}>
                {featureCars &&
                  featureCars.length > 0 &&
                  featureCars.map((item) => (
                    <div className="slider-box" key={item.car_id}>
                      <div className="slider-pic">
                        <img
                          src={item.thumbnail_src || placeholder_listing}
                          alt="car"
                        />
                      </div>
                      <div className="slider-info">
                        <Link
                          to={`${t('urls.detail')}/${getStr(
                            lang === 'en' ? item.title_en : item.title_tr
                          )}/${item.model_year}/${item.car_id}`}
                          style={{
                            color: 'inherit',
                            textDecoration: 'inherit',
                          }}
                        >
                          <h3 role="presentation">
                            {item.car_make} 
                            {' '}
                            {item.car_model}
                            {' '}
                            <span>
                              -
                              {item.model_year}
                            </span>
                          </h3>
                        </Link>
                        <span>
                          {item.currency_icon}
                          {item.price.toLocaleString()}
                        </span>
                      </div>
                    </div>
                  ))}
              

> </Slider>

`
https://www.loom.com/share/85b20faaad3f4855b621fb1bee46021c?focus_title=1&muted=1&from_recorder=1

please check the video and let me know why is not working on mobile view properly?

**Comment by hug963** [comment]
I have the same issue, I just updated to the latest version, it was not happening before on 0.26.1
It is not happening consistently on all sliders on the same page.

The slider which has the issue seems to not be initialised properly, and no initial slide is selected (The back arrow is not disabled and the track is offset at load with a css transform)

It might some kind of racing conditions, I have two sliders on the same page, one works intermittently on mobile, the other not at all anymore.

**Comment by hug963** [comment]
I fixed it by placing the whole carousel in a conditional bracket to wait for the data to be fetched.
I realised the sliders with the issue were initialised with no initial data.

**Comment by Rvi851994** [comment]
Yes hug963 you were right I already fixed that but thank you.

**Comment by ekhishigee** [comment]
@Rvi851994 @hug963 
I have faced the same issue on v0.29.0. Is it still working correctly?
