### ISSUE TITLE
An option to set custom button outside the slider component to navigate 

### ISSUE THREAD

**Issue by abhi12123** [akiran/react-slick#2013]
currently the way to customize the arrow is 

    function SampleNextArrow(props) { 
	   return ( arrow properties)
	}
	function SamplePrevArrow(props) {
		return ( arrow properties)
	}
	export default class CustomArrows extends Component { 
		render() { 
			const settings = { 
				nextArrow: <SampleNextArrow />
				prevArrow: <SamplePrevArrow /> 
			}; 
		return ( 
			<Slider {...settings}>
			content
			</Slider>
		 );
		}
	}

it would have been better to use buttons outside the  slider component to navigate through the slides. For example

	export default class CustomArrows extends Component { 
		render() { 
			const settings = { 
				nextArrow: navigatenext()
				prevArrow: navigateprevious()
			}; 
		return ( 
			<button onClick={navigatenext}>Next</button>
			<button onClick={navigateprevious}>Previous</button>
			<Slider {...settings}>
			content
			</Slider>
		 );
		}
	}

**Comment by ArnasJack** [comment]
You can achieve this by adding a ref to the slider and accessing available methods that will allow you to control the slider.

`<Slider>
</Slider>
`

**Comment by abhi12123** [comment]
Yes It works fine. Seems like the same was implemented in https://react-slick.neostack.com/docs/example/previous-next-methods example. Thank you for taking the time out to respond to this. I believe this issue can be closed now

**Comment by mimi-uxui-dev** [comment]
it actually didn't work for me, the problem with this is whenever i refresh the slider disappears, here's my code, could youn tell me what i'm doing wrong : 

`import React, { useState, useEffect, useRef, useCallback } from 'react'
import axios from "axios"
import { SERVICES } from '../../sevices/globalServices'
import { Link } from "react-router-dom"
import Slider from 'react-slick'
import ServicesSliderCard from './ServicesSliderCard'

import i1 from "../../assets/img/Services/i1.png"
import i2 from "../../assets/img/Services/i2.png"
import i3 from "../../assets/img/Services/i3.png"
import i4 from "../../assets/img/Services/i4.png"

import left from '../../assets/img/Services/left.png'
import right from '../../assets/img/Services/right.png'

class ServicesComponent extends React.Component {
     constructor(props) {
          super(props)
          this.next = this.next.bind(this);
          this.previous = this.previous.bind(this);
     }

     next() {
          this.slider.slickNext();
     }
     previous() {
          this.slider.slickPrev();
     }

     state = {
          services: []
     }


     fetchData = async () => {
          const r = await axios.get(SERVICES())
          this.setState({ services: r.data.data })
     }


     componentDidMount() {
          this.fetchData()
          console.log(this.slider)

     }

     s = [i1, i2, i3, i4]


     render() {
          const settings = {
               centerMode: true,
               dots: false,
               autoplay: true,
               infinite: true,
               autoplaySpeed: 2000,
               slidesToShow: 2,
               slidesToScroll: 1,
               arrows: true,
               centerPadding: "12.6%",
          };

          return (
               <div className='services_component__container'>
                    <div className='header'>
                         <div>
                              <h3>Our Best Tours</h3>
                              <h6>We can  take you to more then 400 destination</h6>
                         </div>
                         <div className='cta'>
                              <Link to='/' >View All Tours</Link>
                              <img src={left} onClick={this.previous} alt='' />
                              <img src={right} onClick={this.next} alt='' />
                         </div>
                    </div>

                    <div className="servicesSlider">
                         <Slider ref={slider => this.slider = slider} {...settings}>
                              {
                                   this.s.length === 0 ? <h3>Loading...</h3> : this.s.map(p => <ServicesSliderCard key={p} data={p} />)
                              }
                         </Slider>
                    </div>
               </div >
          )

     }
}

export default ServicesComponent
`
