### ISSUE TITLE
SVG parsing warm

### ISSUE THREAD

**Issue by newadbie** [akiran/react-slick#2018]
Hey! Today i have updated my gatsby packages, after i saw warm 
`warn Css Minimizer Plugin: cssnano: S:\xx\xx-xxxx\styles.276fc0543f
parsing SVG: Non-whitespace before first tag.`, this warm is related with react slick. When i commented my slider, the error does not appear again.

**Comment by akiran** [comment]
I don't think this is an issue with react-slick.

Please provide a repo or codesandbox to reproduce this issue if you are sure that this is an issue with react-slick
