### ISSUE TITLE
Option to convert to List instead of carousel

### ISSUE THREAD

**Issue by showduhtung** [akiran/react-slick#2019]
Hi react slick team, I was wondering if there could be an option to convert the carousel into a list. The features in this library are fantastic, but the option to have multiple items per page, coupled with custom numbered paging feels like the point of having the numbered paging becomes lost. Say you have 31 results and 3 results per page, at the 11th page instead of expecting just 1 result, you'd get the 31st result, and the 1st and 2nd result, which is expected of a carousel, but then comes the confusion of the paging system.

**Comment by akiran** [comment]
You can use infinite: false setting for this usecase.
