### ISSUE TITLE
How do I add a link within slider content? Is there a property to enable click? I have 0.28.1 install via npm.

### ISSUE THREAD

**Issue by nima-dot** [akiran/react-slick#2024]
How do I add a link within slider content? Is there a property to enable click? I have 0.28.1 install via npm.

**Comment by akiran** [comment]
Links in slider  should work.

If you still face this issue, provide a codesandbox to replicate the issue.

**Comment by nima-dot** [comment]
Thanks for the response. It is not working. I am using <a href... is there any property to enable it? Can't find any documentations as well. Any help will be very much appreciated.

Thanks!

**Comment by nguyentrungson97** [comment]
<a href=""><img /></a> only focus the last element in my array, cant focus the current img
