### ISSUE TITLE
Issue with grid and flex

### ISSUE THREAD

**Issue by drfrostongithub** [akiran/react-slick#2026]
Hello I have issue when using with CRA, 

and then Implemented Grid and Flex. 

Suddenly the slider would be bloated. 

### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by akiran** [comment]
Please explain the issue clearly and provide the code sample to replicate the issue.

**Comment by abdulmoizhussain** [comment]
+1
any solution?

here is the snippet:
https://codesandbox.io/s/react-slick-playground-forked-0z8wp?file=/index.css
