### ISSUE TITLE
lack of smooth transition in autoplay

### ISSUE THREAD

**Issue by sagartmg** [akiran/react-slick#2031]
can you add a smooth transition while autoplay?
https://codesandbox.io/s/react-slick-playground-forked-e9pv6?file=/index.js

like this....
![PISuxOBflt](https://user-images.githubusercontent.com/49345528/117850771-5deb9400-b2a5-11eb-918a-14760cb7a3fc.gif)

currently it stucks /pauses  in-between 
![jhK8VxxEWI](https://user-images.githubusercontent.com/49345528/117851016-9c814e80-b2a5-11eb-80d7-ec2c93c22002.gif)

**Comment by sagartmg** [comment]
dots: true,
        infinite: true,
        arrows: false,
        autoplay: true,
        autoplaySpeed: 2000,
        speed:2000,
        slidesToShow: clients_slider.length > 4 ? 4 : clients_slider.length,
        initialSlide: 0,
        **cssEase: "linear",**

**Comment by BadMachine** [comment]
And what it means?
