### ISSUE TITLE
Empty space on the left with centerMode true

### ISSUE THREAD

**Issue by nayararn** [akiran/react-slick#2033]
Hey. I'm having problems with centerMode: true and infinite: false. My carousel has a blank space on the left when I put slidesToShow: 4, if I put slidesToShow: 3 the problem doesn't happen. With infinite: true, the problem doesn't happen either, but I don't want it to be true. Can anyone help?

Problem image:
![carrosel-problema](https://user-images.githubusercontent.com/47114149/117923821-21cb2a00-b2cb-11eb-92d2-ab7af30d8753.PNG)

My settings: 
![carrosel-configs](https://user-images.githubusercontent.com/47114149/117923952-58a14000-b2cb-11eb-80ba-571b5179c803.PNG)

Help me please, I need to implement this! Thanks.

**Comment by akiran** [comment]
Canter mode can't be used with infinite = false
