### ISSUE TITLE
React + Vite - package not working

### ISSUE THREAD

**Issue by MyraxByte** [akiran/react-slick#2035]
Hi, i'm using React + Vite, and react-slick package not working 
![image](https://user-images.githubusercontent.com/22584144/118022032-900ffb00-b364-11eb-8557-853377e4b79a.png)

**Comment by Mirazex** [comment]
For example u can create `yarn create @vitejs/app example-app --template react-ts`
and install `react-slick` from docs.

**Comment by ghernandezr** [comment]
Yes, I have the same issue here. Any solution so far?.
Thanks!!!

**Comment by ghernandezr** [comment]
@Mirazex  In my case. I remove the yarn.lock file, then remove the node_modules folder, then reinstall all again and now all work fine, I hope that's helps.

**Comment by rrfaria** [comment]
same here 

[vite] Internal server error: [postcss] Failed to find '~slick-carousel/slick/slick.css'

**Comment by pratyushbh** [comment]
Hi @Mirazex , can you please provide me the codesandbox link or a repo of your code so that I can replicate the issue

**Comment by web-developer032** [comment]
yea we have to delete node modules and package-lock and yark-lock file then reinstall all the packages

**Comment by vu-innoflex** [comment]
> same here
> 
> [vite] Internal server error: [postcss] Failed to find '~slick-carousel/slick/slick.css'

In my case, change to 'slick-carousel/slick/slick.css' resolve the problem

**Comment by salehahmed20** [comment]
hi i am a beginner in react-vite. how can i run slick carousel in my project. please guide step by step

**Comment by ravishanw** [comment]
Hi, make sure you have installed slick-carousel as well as react-slick

npm install react-slick slick-carousel --save
