### ISSUE TITLE
`centerMode` with `infinite=false` behaves weirdly

### ISSUE THREAD

**Issue by swietektomasz** [akiran/react-slick#2036]
### [Codesandbox link](https://codesandbox.io/s/react-slick-center-mode-7clrv?file=/src/App.js)

It seems that `centerMode` with `infinite` set to `false` doesn't take into account the offset caused by centering. This causes the end slides to be unusable, and `slickGoTo` to cause some other curious effects, most of the time it actually doesn't take `centerMode` into account, moving the slide to the left.

Is this expected behaviour?

**Comment by akiran** [comment]
Yes, You can't use centerMode with infinite = false
