### ISSUE TITLE
How to change color of dots on active class?

### ISSUE THREAD

**Issue by AhmedMalick** [akiran/react-slick#2046]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it 
along with the issue description

Hi, I'm trying to change the colour of the dot on active but it's not working. My code base is: https://github.com/ahmedmalick/My-Portfolio

**Comment by linhtv97** [comment]
Hi @AhmedMalick, You can customize by use style for class `slick active`
<img width="393" alt="Screen Shot 2021-06-25 at 09 46 45" src="https://user-images.githubusercontent.com/48935244/123362095-5b65a500-d59a-11eb-855a-e689917d154d.png">

**Comment by AhmedMalick** [comment]
Thanks for responding I tried your' one but I'm still not getting the result because I'm using modules css so <slick-acitve>  class won't instead this work <styles.slick_active> so how do I achieve this. let me just know.

**Comment by mrviniciux** [comment]
Hey @AhmedMalick I don't think this is an issue, do you tried to use `::before` selector on css?

See: https://codesandbox.io/s/react-slick-playground-forked-pdejb?file=/index.css

If that works I would ask to leave a feedback and close this issue.

**Comment by AhmedMalick** [comment]
Hey, @mrviniciux thanks for replying to me actually the problem is I'm using [Modules CSS](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/) so I need to have a class like {styles.slick-active} but it's done I've another CSS file but if you know how to style in modules CSS so do let me know

**Comment by victorbyttebier** [comment]
@AhmedMalick I was happy with this result. I kept the slick-dots class and then added my scss modules class .dots
<img width="365" alt="Screenshot 2021-07-23 at 00 30 38" src="https://user-images.githubusercontent.com/33923870/126717450-bf624419-27b5-41ed-a4ac-cd3e456c3948.png">
This makes the dots bigger and moves them up over the images. 
<img width="322" alt="Screenshot 2021-07-23 at 00 30 47" src="https://user-images.githubusercontent.com/33923870/126717485-0f4f0d00-5500-4d41-aa5e-34165da7dc86.png">
