### ISSUE TITLE
How to change the color of navigation arrows?

### ISSUE THREAD

**Issue by serzhan181** [akiran/react-slick#2047]
I have a white background on the body, so i can't see arrow navigation button, screenshots below:

![Screenshot_1](https://user-images.githubusercontent.com/67381256/122935068-dad45800-d391-11eb-93a7-0a6e6e6cadde.png)
Can see the arrows, ok 😃.

![Screenshot_2](https://user-images.githubusercontent.com/67381256/122935237-ffc8cb00-d391-11eb-8d94-30322b18b497.png)
Stop hiding arrows, I can't see you 😒.

**Comment by serzhan181** [comment]
label:good-first-issue

**Comment by appukuttan-shailesh** [comment]
Add this to your stylesheet...
```
.slick-prev:before, .slick-next:before {
  color: black !important;
}
```
