### ISSUE TITLE
Updating jquery

### ISSUE THREAD

**Issue by olgunkaya** [akiran/react-slick#2053]
Hi,

Lately our security team prevent the use uf jquery 3.2.1. So that we need to update jquery to a newer version. Is there a way to do this ? Like a webpack trick etc ??

**Comment by akiran** [comment]
jquery is not a dependency of react-slick

You can use `yarn why jquery@3.2.1`  to find out which libraries are depending on this jquery version and update them

**Comment by olgunkaya** [comment]
sorry I thought it comes from devDependencies.

**Comment by SteveEdson** [comment]
Correct, jQuery is a dev dependency - https://github.com/akiran/react-slick/blob/master/package.json#L65

The version being used has a vulnerability, can we remove this dependency if it's not actually being used?

Thanks
