### ISSUE TITLE
Duplicate Slides in FrontEnd

### ISSUE THREAD

**Issue by britocris74** [akiran/react-slick#2059]
Hi, I have this problem, I want to show maximun 3 slides in the same time, but the amount of cards that I recive for backend it's not constant, It can be 1, 2, 3 or more.. When the cards I recive it's menor than 3, its repeat the cards in front. I set "slidesToShow: 3", because I want the size of cards will be always the same, no matther the number of avaibles cards.

![image](https://user-images.githubusercontent.com/83915507/125313278-7874d480-e30b-11eb-89b3-6eb0aeb34d38.png)
I recive 2 cards for backend, and this render a duplicate for this 2 cards, the same happends when I recive only one card.

![image](https://user-images.githubusercontent.com/83915507/125313486-a78b4600-e30b-11eb-95e8-042eddd79e44.png)
This is what I really need.

Anyone have an idea to resolve this problem? 

[CodePen Example](https://codesandbox.io/s/react-slick-playground-forked-eebdc?file=/index.js)

**Comment by huybui-hubt** [comment]
@britocris74 you need set infinite: false.
```
var settings = {
      dots: true,
      slidesToShow: 2,
      slidesToScroll: 1,
      infinite: false
};
```
