### ISSUE TITLE
Eslint and eslint-react-plugin conflict

### ISSUE THREAD

**Issue by PauloE314** [akiran/react-slick#2078]
I followed the development guide to install React Slick locally, for contribution purposes. During the installation, however, this error appeared on the terminal and I just couldn't make it work locally. Someone could help?

 
![Captura de tela de 2021-08-30 13-36-16](https://user-images.githubusercontent.com/58001614/131374023-df4f7e10-d7a0-4f3c-bf37-c800967a86cf.png)

OS: Ubuntu 20.04
Node version: 16.6.0
NPM version: 7.19.1

**Comment by akiran** [comment]
This issue is fixed now.
