### ISSUE TITLE
Question: The slick is not working when the item is less than slidesToShow

### ISSUE THREAD

**Issue by Dityath** [akiran/react-slick#2093]
I dont know why but my slider is not working fine when the slides item less than the slidesToShow, it just became stacked like a css grid, and how to make the slide become just a single slider (or make it into multiple slider that less than slidetoshow) when this happens? or maybe any other tips?

codesandbox: [CodeSandBox](https://codesandbox.io/s/practical-drake-hehn8?file=/src/App.js)

**Comment by gi-batalha** [comment]
I had the same problem here. The slides doubled and stacked upon each other when there's less items than the value set on slidesToShow property

**Comment by Vixy88** [comment]
Any update on this one, we are having the same issue?

**Comment by Vixy88** [comment]
We fixed this now by adding flex:1 to the .slick-list class

**Comment by AlbertRF147** [comment]
The problem persists. I fixed it with:

```
.slick-slide.slick-cloned {
  display: none;
}
```

**Comment by ahmadmustafeen** [comment]
i fixed it by conditionally turning infinite scroll to false

`          <Slider
            dots={true}
            infinite={slides.length >= 3}
            speed={500}
            slidesToShow={3}
            slidesToScroll={1}
          >`

**Comment by akiran** [comment]
Yes, slides can't be less than slidesToShow
You have to fix it with conditional logic as @ahmadmustafeen suggested

**Comment by shoaib-ab** [comment]
> I got a similar problem, when the slides are less than slidesToShow, the slides doubled and stacked upon each other, I tried to remove `infinite: true` but that didn't worked. Also I tired the code from documentation, the same problem occured. Can anyone confirm is it only problem of mine or everyones.

I am also facing the same problem

**Comment by ahmadmustafeen** [comment]
> > I got a similar problem, when the slides are less than slidesToShow, the slides doubled and stacked upon each other, I tried to remove `infinite: true` but that didn't worked. Also I tired the code from documentation, the same problem occured. Can anyone confirm is it only problem of mine or everyones.
> 
> I am also facing the same problem

tried this? https://github.com/akiran/react-slick/issues/2093#issuecomment-1705213915
