### ISSUE TITLE
[FONT] Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by mmgil** [akiran/react-slick#2100]
### Guidelines for posting a new issue
In PageSpeed insights i receive the following message: Ensure text remains visible during webfont load.

How to FIX this situation?

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by Ricardo-Bonin** [comment]
I have the same problem!!!

**Comment by Ricardo-Bonin** [comment]
I add the font-display: swap in font-face of all slick-theme documents in node_modules and solved it by running in localhost

**Comment by nitvirus** [comment]
facing same issue, please advise a way forwad, if CSS is not maintained, please remove the font dependency

**Comment by dharanchit** [comment]
Anything on this?
How do i resolve this?

**Comment by nitish-hogarth** [comment]
we removed the dependency on react-slick and customised the css for slcik carousel

**Comment by Ricardo-Bonin** [comment]
Do not. I tried everything and I couldn't solve it here!

**Comment by dharanchit** [comment]
@Ricardo-Bonin  any way around this?

**Comment by Ricardo-Bonin** [comment]
The solution would be for them to add the font-display: swap; to @font-face straight in the default css! I made the suggestion but they didn't accept it!

**Comment by mrdkzm** [comment]
You should override to your slider button fonts with css.

 .slick-next:before, .slick-prev:before{
        font-family:  (Your project font or anything what you want) !important;
        font-display: swap;
    }
