### ISSUE TITLE
Hide some items

### ISSUE THREAD

**Issue by jaynerdominguez** [akiran/react-slick#2101]
We are using this npm to display the overall items in the web project's carousel but we wanna hide some specific items. Not sure what approach we can use. We are using React, Gatsby. Please let me know

**Comment by juninhokaponne** [comment]
Okay, if you are using Styled-Components, it will be easier to do this, you must pass a className as in the image below, and then simply in your style file call this class and then validate which points you want to hide using Styled- itself Components or Javascript as Styled-Components allows us to use them.
 
There is a props it receives in the settings called className

![code](https://user-images.githubusercontent.com/49099875/150651717-f4e9af5c-55d7-4d18-a3ce-77025953ca24.png)

A hypothetical example of how it would look more or less in your styled-components file, I took the example from the documentation itself.

![code](https://user-images.githubusercontent.com/49099875/150651836-3e8b0996-b45d-4fef-aa37-abb7dade2e04.png)

I hope this helps you or at least gives you some direction.
