### ISSUE TITLE
[feature] add support to free mode

### ISSUE THREAD

**Issue by vczb** [akiran/react-slick#2107]
I would like to make a slide transition and when I stop the slides should keep the position I left

I saw many issues asking for this and I don't understand why they are closed

#1988  #532

**Comment by gsmachado** [comment]
I'm also interested in the free mode feature.

Or at least to know the reasons why issues #1988 and #532 are closed without any apparent reason.

Thanks!

**Comment by pratyushbh** [comment]
Hi, apparently the free mode is not supported by the original jQuery slick carousel on which the react-slick is based on, that's why free mode is not supported by react-slick too.
