### ISSUE TITLE
How we can pause the AutoPlay

### ISSUE THREAD

**Issue by educostachaves** [akiran/react-slick#211]
@akiran 

I'm using your component, and got stuck with a feature that I think is very necessary: how we pause the autoplay of the carousel. I've tried to do this manually and not worked. After taking a good look at your Issues, I saw that had feedback on this feature, and even Pull Requests resolution. I don't know if you've implemented it, but I think it is necessary.

Thanks!

**Comment by ericfowler303** [comment]
Mabye getting https://github.com/akiran/react-slick/pull/142 merged would help. I know I'm looking for something similar and pausing on hover would be good enough for my project. I thought about a button to trigger pause/resume but I wouldn't know which prop/thing? to change.

**Comment by akiran** [comment]
Merged #142

**Comment by kaela** [comment]
You should add pauseOnHover to the property list on the readme
