### ISSUE TITLE
Testing in Jest

### ISSUE THREAD

**Issue by G0TT0N** [akiran/react-slick#2112]
Hello. I am using your react-slick library. Thank you very much.
There is a question: there is an afterChange event. How can it be tested in Jest?
I tried to trigger an event via fireEvent, but since afterChange is a field in a variable (
```
const settingsReserveGoodsSlider = {
    afterChange: (current) => {
      setPrevProduct (current - 1);
    }}
```
)
 , then the event is not called in it.

https://codesandbox.io/s/upbeat-bose-pe1ow?file=/src/App.js

**Comment by akiran** [comment]
You can check this
https://github.com/akiran/react-slick/blob/master/__tests__/afterChange.test.js
