### ISSUE TITLE
React-slick Not Working 

### ISSUE THREAD

**Issue by DevShehabIbrahem** [akiran/react-slick#2118]
When I use the Slider Component To run the slick,,, I got this error in the console 

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at createFiberFromTypeAndProps

**Comment by emripka** [comment]
Bump

**Comment by JamieBradders** [comment]
I've got the same issue here too 😢

**Comment by akiran** [comment]
This could be an issue with your code.  It is work fine for others.

Please provide code to replicate the issue if you think it is a library issue.
