### ISSUE TITLE
Next and Previous Arrow

### ISSUE THREAD

**Issue by edygar** [akiran/react-slick#212]
Could the component have its labels (currently hard-coded to Next and Previous) injectable, by some prop?

I need to translate some buttons.

**Comment by rafaelteixeira** [comment]
You could override the prevArrow and nextArrow props with components of your making, like this:

class NextButton extends React.Component {
  render() {
    return (
      <button {...this.props}><i className={styles.nextbutton} />{this.props.nextText}</button>
    );
  }
}

class PrevButton extends React.Component {
  render() {
    return (
      <button {...this.props}><i className={styles.prevbutton} />{this.props.prevText}</button>
    );
  }
}

sliderSettings = {
      arrows: true,
      prevArrow: PrevButton,
      nextArrow: NextButton
};

<Slider {...sliderSettings}>
  { slides }
</Slider>

**Comment by edygar** [comment]
Oh, now I see, thank you
