### ISSUE TITLE
Cannot find module 'react' from slider.js

### ISSUE THREAD

**Issue by oaraujocesar** [akiran/react-slick#2120]
Hey! 

I'm currently using react-slick with Nextjs 12 and TypeScript.
I was creating the unit test with Jest for a generic Slider when I encountered this error: 

![image](https://user-images.githubusercontent.com/61256606/149043787-99f85db3-9d3e-4adb-93cd-341858a48273.png)

Basically it doesn't find react whatsoever. Inside the lib we have the following line:

```js 
var _react = _interopRequireDefault(require("react"));
```
and the tooltip when hovering the react word says: `module "/home/oaraujocesar/dev/node_modules/@types/react/index"`

**Comment by sayinmehmet47** [comment]
Install these props together

``` js
 "react-slick": "^0.28.1",
    "slick-carousel": "^1.8.1"

```

**Comment by oaraujocesar** [comment]
It worked just fine!!! That is funny because I remember installing react-slick, and I was using it on my storybook. 

After checking the Package.json, it wasn't there. Weird.

I'm just curious now: how did you come to this conclusion?

**Comment by sayinmehmet47** [comment]
@oaraujocesar  I made the same error 1 hour ago. I saw your issue and wanted to answer it :)
