### ISSUE TITLE
Extra div inside every single slide in react

### ISSUE THREAD

**Issue by foridpathan** [akiran/react-slick#2131]
When I use just react Libary on HTML, CSS there not have an extra div but I fount an extra dive in react. Can you help me, please?

`
<div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 153px;">
  <div>
    <div class="step" style="width: 100%; display: inline-block;">
      <h3>1</h3>
    </div>
  </div>
</div>
`

**Comment by foridpathan** [comment]
`
<div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 153px;">
  <div>
    <div class="step" style="width: 100%; display: inline-block;">
      <h3>1</h3>
    </div>
  </div>
</div>
`

**Comment by ardok** [comment]
Need to get rid of this extra div as well. It's messing up with screen reader focus. As in, it adds unnecessary focus.

**Comment by eyupkoc29** [comment]
It puts an extra div so it doesn't have a full height value. How to remove this extra div?

**Comment by akiran** [comment]
duplicate of #1877
