### ISSUE TITLE
react slick partial slide apprears on left instead of right

### ISSUE THREAD

**Issue by sanjipun** [akiran/react-slick#2132]
settings

const settings = {
  dots: false,
  arrows: true,
  infinite: true,
  speed: 500,
  slidesToShow: 4.5,
  slidesToScroll: 1,
};

Output:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/64313011/154202360-a0a05d44-eb24-47d9-af06-25bb96bcd174.png">

expected output:
partial next slide on the right side

**Comment by sanjipun** [comment]
Solved:

change settings = {
infinite:false
}

**Comment by seankim1111** [comment]
Is there any way to expose the next slide part on the right while keeping {infinite: true}?
