### ISSUE TITLE
How to get dots count

### ISSUE THREAD

**Issue by gregg-cbs** [akiran/react-slick#2142]
When you slide more then 1 slide at a time the dots count to that kind of 'grouping'

So if you have 9 slides, you slide 3 at a time, then you will have 3 dots.

I want to get that dot count, the number 3, so I can use it to show a text '1 of 3', '2 of 3', '3 of 3'.

How do I get the dots count from the slider api?

Example of dots here:
https://react-slick.neostack.com/docs/example/multiple-items

**Comment by akiran** [comment]
You can use appendDots for this use case.
dots are passed as an argument to this function.  dots.length will give you the number of dots.
https://react-slick.neostack.com/docs/example/append-dots
