### ISSUE TITLE
Scrolling to left from first slide break animation

### ISSUE THREAD

**Issue by donotcodeit** [akiran/react-slick#2145]
When slider shows multiple items and scrolled from first slide to left, animation stops on invalid slide. Also slide with class name `slick-current` is not in visible area. Please take a look at the demo: https://codesandbox.io/s/react-slick-scroll-left-issue-8v5sz9

**Comment by akiran** [comment]
I tried the demo and it is working as expected.
Can you record a video of the issue and share it?
