### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by VeRJiL** [akiran/react-slick#2146]
Please add react 18 to peerDependencies

**Comment by akiran** [comment]
fixed in react-slick@0.29

**Comment by JohnHeroSaz** [comment]
hi im having problems with react 18.3.1

**Comment by MrOldProger** [comment]
This method solves the problem: https://github.com/akiran/react-slick/issues/2206#issuecomment-1961173249
Just use:
`const SliderComponent = !!Slider.default ? Slider.default : Slider`
