### ISSUE TITLE
What's the 'react' way of accessing the active slides?

### ISSUE THREAD

**Issue by taichatha** [akiran/react-slick#215]
I want to change the width of an active slide based on a class it has, but I first need to grab it. How would you recommend I safely go about this? I tried doing refs, but that's apparently not safe. And I am passing my divs/slides as props. So basiaclly how do I go into <Slider /> and access the active slides.

**Comment by bvasko** [comment]
You probably figured this out already - but use the beforeChange prop
<MySlider beforeChange={this._onChange} />

_onChange:  function( currentSlide, nextSlide ) { }

**Comment by akiran** [comment]
Yes, you can use beforeChange or afterChange methods for this usecase

**Comment by joebanks10** [comment]
I'm having trouble figuring out how to access to current slide *element*. The current slide index is passed into `afterChange`, but how do I use that to get a reference to the current slide element?

**Comment by HelKyle** [comment]
@joebanks10  maybe you can make it by native javascript, like this

```
onChange () => {
    document.querySelector('.slick-current').focus();
}
```

**Comment by nikobenedikt** [comment]
Has anyone found a correct solution to this problem? How do we access the elements within the current Slide without using querySelector since it's considered bad practice ??? Maybe with Refs? Please help.

**Comment by jamesryan-dev** [comment]
+1 for solution - I would like to know which slide is active via a prop maybe?
