### ISSUE TITLE
Mobile view in React 18 

### ISSUE THREAD

**Issue by khenlevy** [akiran/react-slick#2152]
When using it with React 18 it works only for desktop.
The view for mobile is displaying next and prev html buttons and sliding is not working

**Comment by arthur1041** [comment]
I can work on this issue.

**Comment by arthur1041** [comment]
Can you give more details about the issue?
I tested it on a mobile view and the sliding, next and previous buttons worked properly as you can see bellow:

https://user-images.githubusercontent.com/42497300/164785659-c51ece77-5e52-4fd8-93cd-88b00b83dccd.mp4

**Comment by akiran** [comment]
Thanks @arthur1041 for testing it out.

Closing this issue as it is working fine.
