### ISSUE TITLE
Cannot setState within the beforeChange and afterChange callbacks without also reloading ALL the slide components.

### ISSUE THREAD

**Issue by twobyte** [akiran/react-slick#2158]
It seems impossible to change the slider’s currentSlide state within the beforeChange and afterChange callbacks without also reloading ALL the slide components. This is causing unacceptable presentation issues as GatsbyImages disappear and reappear on every slide action.

I have tried using both functional components and classes, changing ref, context and useState, and no matter how I manage state, every-time the state is changed within the callbacks, even when using a setTimeout, all the slides are reloaded.

Here is a minimal reproducible example, if you view the console as the slide runs, you should see what I mean,
https://codesandbox.io/s/beforechange-afterchange-react-slick-forked-lhgyxj?file=/src/components/slickCarousel.js

Other closed issues reference the [SlickGoTo example](https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js), but this example is very basic and does not use components as slides. For my use case I am trying to trigger code within the slide component when the slide becomes active.

I haven’t been able to get the [wrapping component workaround] (https://github.com/akiran/react-slick/issues/576#issuecomment-266243192) to work for me yet. Any tips appreciated. Thanks.

**Comment by akiran** [comment]
SlickGoTo should work for this usecase.

You can try it out and let us know if you run into any problems
