### ISSUE TITLE
Basic code doesnt work for me

### ISSUE THREAD

**Issue by ljs19923** [akiran/react-slick#2160]
Hi,
 I don't understand. I just imported the basic example code in my project, and this is the result.. I searched during few hours without success. If someone have one idea : 
<img width="165" alt="Screen Shot 2022-06-11 at 14 17 45" src="https://user-images.githubusercontent.com/5727223/173187661-8fb13eb4-7d10-4d2a-8f6e-7930655df173.png">

<Slider {...settings}>
            <div>
              <h3>1</h3>
            </div>
            <div>
              <h3>2</h3>
            </div>
            <div>
              <h3>3</h3>
            </div>
            <div>
              <h3>4</h3>
            </div>
            <div>
              <h3>5</h3>
            </div>
            <div>
              <h3>6</h3>
            </div>
          </Slider>

var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

**Comment by GabrielReisSync** [comment]
Hello @ljs19923, I have the same problem, how can you fixed this problem?

**Comment by gusazevedo** [comment]
@ljs19923 You mut import the default CSS files on the component you want use the Slick.
`import "slick-carousel/slick/slick.css";`
`import "slick-carousel/slick/slick-theme.css";`
