### ISSUE TITLE
No overload matches this call

### ISSUE THREAD

**Issue by jonasmarco** [akiran/react-slick#2161]
Someone can help me? I'm facing this error when I try to use React Slick with TS

> "react-slick": "0.28.1"
> "@types/react-slick": "0.23.4"
> "typescript": "4.4.4"

![image](https://user-images.githubusercontent.com/19959770/173200724-7b2691a1-db4d-41b8-88fd-f4ab66f8703f.png)

**Comment by mshakhriyorov** [comment]
> Someone can help me? I'm facing this error when I try to use React Slick with TS
> 
> > "react-slick": "0.28.1"
> > "@types/react-slick": "0.23.4"
> > "typescript": "4.4.4"
> 
> ![image](https://user-images.githubusercontent.com/19959770/173200724-7b2691a1-db4d-41b8-88fd-f4ab66f8703f.png)

maybe, you can try just using `Slide` instead of `SlickSlider`?

**Comment by jonasmarco** [comment]
I can't, `Slider` is already the name of my component

![image](https://user-images.githubusercontent.com/19959770/174507372-0c574b09-c5fc-4a32-8a5f-a53338ea2c5a.png)

**Comment by MauriceAyasse** [comment]
In your example an older @types/react-slick package version is used. This error will disappear if the given version would be increased by at least to version 0.23.6.

**Comment by akiran** [comment]
@jonasmarco Try with latest version of types as suggested by @MauriceAyasse

**Comment by pacehutt** [comment]
> @jonasmarco Try with latest version of types as suggested by @MauriceAyasse

not working with the version 0.23.6.
