### ISSUE TITLE
Special sized scroll containers cause flicker

### ISSUE THREAD

**Issue by canvascat** [akiran/react-slick#2163]
- windows os
- [CodeSandBox](https://codesandbox.io/s/react-slick-playground-forked-oopn1z?file=/index.js) 

![20220628165000](https://user-images.githubusercontent.com/31235016/176136640-fd451997-2316-485f-a29a-6caf38bda9c5.gif)

**Comment by akiran** [comment]
This is happening because container is smaller than slides. 

Slide should fit inside container to avoid scrollbars
