### ISSUE TITLE
Slider not working with MUI row stack

### ISSUE THREAD

**Issue by Nigel-N** [akiran/react-slick#2169]
I was attempting to create a basic image carousel using slider but it does not seem to work when used in a Material-UI stack with direction as row but works when the direction is set to column.  The slider in the row stack also seemed to block/remove the other elements of that stack (right stack content cannot be seen). Is this due to a compatiblity issue or slider size?

**Row**
![image](https://user-images.githubusercontent.com/84008187/181303063-9ca1ef2b-191b-4f72-b497-170317d15cf2.png)

**Column**
![image](https://user-images.githubusercontent.com/84008187/181302859-52363636-e500-4578-bd77-a80b9faa1b36.png)

**MY CODES**
```
<Stack direction={{ xs: 'column', sm: 'row' }}   spacing={5}>
    {/* Left stack */}
    <Stack>
        {/* Big image */}
        <img src={car.Image} alt="car1" width="350"/>

        {/* Small image */}
            <Slider {...sliderSettings}>
                {
                    carImage1.map((item) => (
                        <div>
                            <img src={item} alt="" width={70}/>
                        </div>
                    ))
                }
            </Slider>
        
    </Stack>

    {/* Right stack */}
    <Stack></Stack>

</Stack>
```

**Comment by Nigel-N** [comment]
Nope, it was a dumb mistake. I did not set the width of the div that contained the slider. As a result the slider content overflowed, appearing distorted and blocking other elements from being displayed.

**Comment by willjstevens** [comment]
Thank you @Nigel-N  - I had exactly the same scenario issue and your solution solved it.
