### ISSUE TITLE
Trying to space between the slides without margins/paddings on both sides

### ISSUE THREAD

**Issue by rafaelteixeira** [akiran/react-slick#217]
I can't seen distance the slides without having to create margins or paddings on both sides of each slide.

I need the first slide to start showing exactly at the left of the container, and the last displayed slide to end  at the end of the container. 

That's easy to do, if I don't have any space between the slides, since it's the default behavior.

Is there any way to have a margin only between the displayed slides (slidesToShow)?

**Comment by rafaelteixeira** [comment]
This a very specific use case, so I'm closing this issue.

**Comment by lauterry** [comment]
Hi @rafaelteixeira 

Have you managed to do what you have described ?

Best regards

**Comment by rafaelteixeira** [comment]
Hi @lauterry 

I did, but lost it somehow. It was in an old project, and apparently, not commit in my fork.

The solution was basically adding a prop "slideSpacing" with default 0, that had the number of pixels in between the slides. And in the slide track calculation I added this (slideSpacing * (slides_count - 1)), before calculating the width for each slide (when slidesToShow > 1).

Sorry I couldn't find the source, but hope that this helps.

Best

**Comment by cassianomon** [comment]
I could accomplish it with Styled Components, but I think regular SCSS will do the job too:

```
export const SliderStyles = styled(Slider)`
    .slick-list {
        margin: 0 -4px;
    }
    .slick-slide > div {
        margin: 0 4px;
    }
`;
```

**Comment by blueedgetechno** [comment]
@cassianomon god bless you
