### ISSUE TITLE
Add support for onArrowClick

### ISSUE THREAD

**Issue by JorgeSivil** [akiran/react-slick#2179]
I had to fire an event on arrow click and it wasn't possible, I was able to do what I needed only with beforeChange and it didn't work right because I had a re rendering issue in which upon scrolling vertically and coming up again, the carousel would be shifted to the right.

The workaround was to do a goTo(0) upon scrolling, and had to add a flag in the window scope to prevent the event from firing when doing a goTo(0). It would have been so much easier if I just had a onArrowClick() event.

Thanks a lot!

**Comment by pratyushbh** [comment]
Unfortunately, this feature is not supported by the JQuery Slick carousel on which React Slick is based upon.
