### ISSUE TITLE
More expressive & better documented code

### ISSUE THREAD

**Issue by startupthekid** [akiran/react-slick#218]
There are a lot of places in the code that could be better expressed.

Take the following block (taken from `track.jsx`):

```
React.Children.forEach(spec.children, (elem, index) => {
    if (!spec.lazyLoad | (spec.lazyLoad && spec.lazyLoadedList.indexOf(index) >= 0)) {
      child = elem;
    } else {
      child = (<div></div>);
    }
    var childStyle = getSlideStyle(assign({}, spec, {index: index}));
    var slickClasses = getSlideClasses(assign({index: index}, spec));
    var cssClasses;

    if (child.props.className) {
        cssClasses = classnames(slickClasses, child.props.className);
    }
    else {
        cssClasses = slickClasses;
    }

    slides.push(React.cloneElement(child, {
      key: index,
      'data-index': index,
      className: cssClasses,
      style: assign({}, child.props.style || {}, childStyle)
    }));

    // variableWidth doesn't wrap properly.
    if (spec.infinite && spec.fade === false) {
      var infiniteCount = spec.variableWidth ? spec.slidesToShow + 1 : spec.slidesToShow;

      if (index >= (count - infiniteCount)) {
        key = -(count - index);
        preCloneSlides.push(React.cloneElement(child, {
          key: key,
          'data-index': key,
          className: getSlideClasses(assign({index: key}, spec)),
          style: assign({}, child.props.style || {}, childStyle)
        }));
      }

      if (index < infiniteCount) {
        key = count + index;
        postCloneSlides.push(React.cloneElement(child, {
          key: key,
          'data-index': key,
          className: getSlideClasses(assign({index: key}, spec)),
          style: assign({}, child.props.style || {}, childStyle)
        }));
      }
    }
  });
```

Instead of doing a `forEach`, why not do a map? Then, it's clear that you're transforming and cloning the elements, not just looping and performing a lot of side-effects. Side-effects, which in turn can lead to bugs that are hard to find and fix.

Here's one way you can fix it:

```
const array = React.Children.toArray(this.props.children); // transform to flat array
    const children = array.slice(array.length - this.props.visibleItems, this.props.infinite ? array.length : array.length - this.props.visibleItems).concat(array).concat(array.slice(0, this.props.infinite ? this.props.visibleItems : 0)); // create final array
children.map((child, index, list) => {
    const key = index - (list.length - this.props.visibleItems); // have to shift the index by the amount padding to the front
    return React.cloneElement(child, {
        key: key,
        'data-index': key 
    });
});
```

Here you turn the children into a regular array, then construct the final array (the conditionals inside slice take care of the carousel being infinite), and then map each element to a cloned element. Am I leaving a lot out such as applying styles, etc? Yes, of course, for the sake of brevity in this issue but I think this illustrates my points; why take 60+ lines to write something when it could be done in 15?

Additionally, it's incredibly unclear as to the formula you're using to calculate the number of items in an infinite carousel. Why? Because there's no comments and there should be. Plus, as I said, the infinite items are generated in two separate places instead of one condensed line.

Also, if you're going to make a React port of slick-carousel, which currently sits at 2000+ lines, and I can't stress this enough, writing code in a proper and much more testable manner is imperative. Ultimately, this library will end up being just as big as slick-carousel and when you're dealing with that many lines of code, it is so hugely important to reduce possible failure points. The sole reason I don't use this library is because it's written in such a haphazard and side-effect ridden manner and I can't afford a bug sneaking into my production code. I understand that it's a work in progress but if you're going to release even minor versions, the code quality has to come up.

The reasons to consider re-writing in this manner are:

* decrease the library size (I accomplished the same task in 3 lines that was done in upwards of 50)
* make it easier for consumers of the library to understand what's going on
* less bugs
* better testability which in turn would lead to better adoption
* You have to write less code (less work to accomplish the same task is always good right?)

And side-effects are bad. Pushing elements into an outer array inside a `forEach` makes me shudder. Why not just use `map`? Not to mention, just inside that code block, `React.cloneElement` is repeated 3 separate times, which for 60 lines of code is a LOT of code repetition.

**Comment by rafaelteixeira** [comment]
+1

**Comment by akiran** [comment]
@startupthekid  Can you open PR ?

**Comment by startupthekid** [comment]
@akiran no thanks. I don't have time myself, I just wanted to see this library become great hence the suggestions.

**Comment by robcolburn** [comment]
@akiran,
While I believe @startupthekid's words were lean more critical than helpful. The point about mutating props is valid, I'll try to roll that into an actual PR.

I noticed 4e80d751c06a313c2dc26f024ad9bb272b97b030, let me know what issues came up, and if I can help you out in anyway with the automated testing aspect. It makes it difficult to write PR's without a test suite to validate against.

**Comment by startupthekid** [comment]
@robcolburn being critical of software is a good thing, it helps it become great. We can only call ourselves software engineers when we adhere to engineering methodologies and modes of problem solving.  And in this case, that's needed because there are no good react carousels out there that have the functionality that slick carousel does. This could stand as a great library given some TLC.

To your point about tests, I completely agree. One thing that would really help the library and encourage others to participate is a set of tests. That's probably the most important priority.

**Comment by akiran** [comment]
Nature of the library itself is complex because it need to support wide variety of mode.
I will try my best to refactor and add docs & tests.

**Comment by robcolburn** [comment]
@startupthekid,

So, "critical" is loaded word, it can mean both "expressing or involving an analysis of the merits and faults of a work of literature, music, or art." as well as  "expressing adverse or disapproving comments or judgements.".

The latter can be subtly toxic to an open-source software / community. Bugs are annoying and the pain is shared by many people.  However, as long as there is software there will be bugs, software is hard. Judgmental comments while main with the earnest attempt at solving an issue can harm our emotions, and make us want to give up on personal projects. But, each of us maintaining positivity helps also enjoy the process and our lives a bit better. So, please do try to avoid being judgmental in posting issues. Personally, I am critical and negative often. Perhaps, years of developing software are terrible to my character, but I'm trying to change.
