### ISSUE TITLE
React-slick max height property

### ISSUE THREAD

**Issue by adimchithecreator** [akiran/react-slick#2189]
This is my first time using react slick in my project and i'm unable to set a max height property. 

Can anyone help me with this ?

**Comment by ShedrackGodson** [comment]
Any update on this issue pls?

**Comment by adimchithecreator** [comment]
This was how i fixed it, i'm not sure if it's the most conventional way but it works.

<----to set the max-height of the slick-list container---->
`.slick-list{
    max-height: 14rem ;
}`

<----to set the max-height of the images in the carousel---->
`.slick-list img{
 width: 100%;
height: 14rem;
}`

**Comment by pratyushbh** [comment]
Unfortunately max-height property is not the part of original jQuery plugin from which react-slick is based upon
