### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by nithishj** [akiran/react-slick#219]
**Static content(working):**

```javascript
return( <Slider {...settings}>
             <div><h3>hello</h3></div>
            <div><h3>hello</h3></div>
            <div><h3>hello</h3></div>
            <div><h3>hello</h3></div>
            <div><h3>hello</h3></div>
            <div><h3>hello</h3></div>
          </Slider>)
```

**dynamic content(not working)**
```javascript
var thumbs='';
 for(let i=1;i<=7;i++)
    {
       thumbs = thumbs+'<h1>hello</h1>';
    }
return( <Slider {...settings}>
             {thumbs }
          </Slider>)
```
**getting Error as:**
~~Uncaught TypeError: Cannot read property 'className' of undefined~~

*I am using react@0.14.1, react-dom@0.14.1,  react-slick@0.9.3*

**Comment by li2go** [comment]
i met the same question. how did you do?

**Comment by akiran** [comment]
@nithishj  You are using strings instead of JSX in dynamic content example.
It will work your dynamically generated JSX
