### ISSUE TITLE
Centered item

### ISSUE THREAD

**Issue by grydstedt** [akiran/react-slick#22]
Hi, thanks for the great port.

When I'm using centerMode, with slidesToShow: 5, slidesToScroll: 1, I'm seeing the fourth item selected. Is that working as intended?

![screen shot 2015-02-26 at 5 28 26 pm](https://cloud.githubusercontent.com/assets/782394/6405831/3ef3bdd4-bddd-11e4-9151-4449bc590ac6.png)

**Comment by vramana** [comment]
Once #57 gets merged, your issue will be fixed.
