### ISSUE TITLE
Wrong behaviour with initialSlide

### ISSUE THREAD

**Issue by egorovsa** [akiran/react-slick#2207]
1) infinite=false
2) set InitialSlide 
3) swipe right

Expected result: it goes to the next slide
Actual result: it always goes to slide 2

Reproduced there!

https://codesandbox.io/s/react-slick-playground-forked-8lnxbb?file=/index.js

**Comment by gadanihiman** [comment]
I got the same issue, anyone can fix it?

**Comment by gadanihiman** [comment]
have you got the solution? @egorovsa

**Comment by egorovsa** [comment]
Yes I found a solution, but this is.... how to say . Temp Monkey patching.
But this works for me. Instead of using initialSlide prop I use ref and Slider API.
Check this out

```
 // Since the slider's plugin has an initialSlider property setting issue
  // we set an initial slide using the package API
  // Issue is created https://github.com/akiran/react-slick/issues/2207
  const initSlider = (ref: Slider) => {
    ref?.slickGoTo(initialSlide || 0, true);
  };


//...

<Slider
        ref={initSlider}
        dots={false}
        infinite={false}
        nextArrow={<NavigationButton isNext={true} />}
        prevArrow={<NavigationButton />}
      >
...
```

**Comment by ashutosh887** [comment]
Let me have a look @akiran

**Comment by pratyushbh** [comment]
this issue has been fixed.
