### ISSUE TITLE
Is there a way to change the dots color?

### ISSUE THREAD

**Issue by StasGavrilov** [akiran/react-slick#2215]
![Untitled](https://user-images.githubusercontent.com/89335018/216502979-72301a12-72b8-42be-904c-75204305e6e0.png)

I have tried to change like this:
`    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 2,
        slidesToScroll: 1,
        dotsClass: `slick-dots ${styles.dots}`
    }`

`
.cardsContainer {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 80px 150px;

    .dots {
        color: aqua;
    }
}
`
but it did not change them.
(I'm using sass css)

Thanks :)

**Comment by Jastagar** [comment]
I have solved this issue and have added a new setting that can be used to change the color of the dots.
You can use 'dotsColor' to change to any color you want. Note that this does not also change the opacity of the dots but only their colors.

**Comment by akiran** [comment]
This can be implemented with custom CSS or appendDots/customPagging settings

https://react-slick.neostack.com/docs/example/append-dots
