### ISSUE TITLE
slidesToShow not working

### ISSUE THREAD

**Issue by Sayanism** [akiran/react-slick#2217]
even though i have set the slidesToShow attribute to 3 (or any number) it's still showing only one card/element on the entire screen. Also, i implemented this without using props, so if you any better, should i use props instead? and the dots: true isn't working either but that was not a deal breaker for me so i don't mind if that issue is not solved for me.

the code : 
![image](https://user-images.githubusercontent.com/72667755/218181418-cd090709-b644-4384-a327-755da69f4587.png)

the result :
![image](https://user-images.githubusercontent.com/72667755/218181152-7a0e6d1d-251f-423e-88c7-a907dc20eadf.png)

**Comment by abhishek-sonawane** [comment]
So did you not pass the settings object as prop ? If not you should pass it as a prop to the slider component.

**Comment by Sayanism** [comment]
yeah, i just checked my code and that was the issue. i passed it as a prop initially but made some changes later and forgot to pass the settings to the slider component again. Thanks!

**Comment by abhizuddl** [comment]
@Sayanism Please close this ticket if your issue is resolved.
