### ISSUE TITLE
The item flex-grow on hover effect is not working

### ISSUE THREAD

**Issue by TangoPJ** [akiran/react-slick#2219]
Hello, I have a problem with flex-grow style on hover effect. Works the transform: scale(1.3) only, what am I doing wrong?

https://codesandbox.io/s/infallible-butterfly-mtnmb9?file=/src/components/slider/Slider.css

**Comment by sumitvish20** [comment]
There is no problem with the transform, everything is working fine, for proof, I am attaching some screenshots 

For transfrom: scaleY(1.3)
![1](https://github.com/akiran/react-slick/assets/94473575/9a2c611a-7522-4dd5-bf68-d1cec243725c)

For transform: scaleY(2)
![2](https://github.com/akiran/react-slick/assets/94473575/d5ee8600-25ea-47d9-97d5-1c92eadea2f8)

If you want to zoom from all sides then use transform: scale(1.5(any number))
![3](https://github.com/akiran/react-slick/assets/94473575/4d992a38-03b4-4b6c-93f0-38e3026b92e3)

**Comment by akiran** [comment]
This is not an issue in this library
