### ISSUE TITLE
any idea to implement immediate stop/play ❓❓❓

### ISSUE THREAD

**Issue by Yi-bee** [akiran/react-slick#2229]
How to achieve immediate stop scrolling when the mouse is moved in, and immediate start scrolling when the mouse is moved out ?????

Here are my settings：
```js
const settings = {
  arrows: false,
  autoplay: true,
  speed: 5000,
  autoplaySpeed: 0,
  cssEase: 'linear',
  infinite: true,
  slidesToShow: 4,
  slidesToScroll: 1,
  vertical: true,
  verticalSwiping: true,
  swipeToSlide: true,
};
```

**Comment by pratyushbh** [comment]
Unfortunately, this feature is not supported by the Jquery Slick carousel on which react slick is based upon
