### ISSUE TITLE
demos throw error on npm start

### ISSUE THREAD

**Issue by Gattermeier** [akiran/react-slick#223]
Following instructions in README to run demos locally: 
git clone https://github.com/akiran/react-slick
npm install
npm start

Throws error:

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: docs/docs.scss
Error: It's not clear which file to import for '@import "slick-carousel/slick/slick"'.
       Candidates:
         slick-carousel/slick/slick.scss
         slick-carousel/slick/slick.css
       Please delete or rename all but one of these files.
       on line 8 of stdin >> @import "slick-carousel/slick/slick";
   ^ at options.error

**Comment by akiran** [comment]
Do you slick carousel installed ?

**Comment by zakness** [comment]
I got this too, easily worked around by doing what the error message says...

> Please delete or rename all but one of these files.

...which means going into `node_modules/` and deleting `*.css`, letting gulp-sass use the scss versions.

But it would be nice not to have to do that. Perhaps `docs.scss` can import explicitly?

```sass
@import "slick-carousel/slick/slick.scss";
```

**Comment by akiran** [comment]
fixed it
