### ISSUE TITLE
Problem on install with node 18.16.0

### ISSUE THREAD

**Issue by redd97** [akiran/react-slick#2231]
Hi everybody. I have a problem to install it with node v18.16.0
_Moment when error appear_ https://i.imgur.com/TS8Dasp.png
_Error message:_ Error: error:0308010C:digital envelope routines::unsupported
_Error screenshot:_ https://i.imgur.com/LElVMCR.png

I think this error occurs because when you install the package, it does `npm run build` (started from prepublish scipt in package.json).
As I understand it, this bug is caused by [breaking change on node >=v17](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported),  and on other hand caused from `prepublish` script in **package.json**.

So a solution would be to rename `prepublish` -> `prepublishOnly`.
Because : 
1) `prepublish` is deprecated 
2) when i run 'npm install`, and install dependency i don't want to do build library.

For example most popular libraries from npm ([express](https://github.com/expressjs/express/) or  [grunt](https://github.com/gruntjs/grunt)) don't do build when i install these libraries. He provide from start folder as /lib

**Comment by akiran** [comment]
Fixed it in #2240
