### ISSUE TITLE
With vite (&SWC) Slick Font not loading

### ISSUE THREAD

**Issue by apuatcfbd** [akiran/react-slick#2239]
Font not loading, please checkout this [screenshot](https://i.imgur.com/mFfAfwB.png) & this [screenshot](https://i.imgur.com/uA9vgLd.png)

in `slick-theme.scss` `slick-font-url` is what failing

```
@function slick-font-url($url) {
    @if function-exists(font-url) {
        @return font-url($url);
    }
    @else {
        @return url($slick-font-path + $url);
                    ^^^^^^^^^^^^^^^^^^^^^
    }
}
```

**Comment by pratyushbh** [comment]
Hi, Im unable to replicate the issue , will you please send me a small repo of the code in which the issue is occuring.

**Comment by pratyushbh** [comment]
Hi, Im unable to replicate the issue , will you please send me a small repo of the code in which the issue is occuring.

**Comment by TilW-CEBEX** [comment]
```scss
@function slick-font-url($url) {
    @if function-exists(font-url) {
        @return font-url($url);
    }
    @else {
        @return url("#{$slick-font-path}#{$url}");
    }
}
```

Would solve this problem
