### ISSUE TITLE
overflow-x-auto on react-slick hompage website

### ISSUE THREAD

**Issue by dev-phantom** [akiran/react-slick#2250]
there is currently an overflow on the homepage of react-slick 

i guess this can be fixed by setting the width to 100%
![Screenshot (5)](https://github.com/akiran/react-slick/assets/72051159/4102d711-fdd4-4367-8694-948f1fb50af1)

**Comment by akiran** [comment]
We are rebuilding the docs with Docusaurus. This will be fixed in the new docs
