### ISSUE TITLE
Wrong pixel width

### ISSUE THREAD

**Issue by nicitaacom** [akiran/react-slick#2253]
https://codesandbox.io/p/sandbox/zen-sammet-7hwygv
Wrong width - it doesn't work as here https://react-slick.neostack.com/docs/example/multiple-items/

**Comment by nandavikas** [comment]
I want to work on this as my first open-source contribution.

But when I try to reproduce the issue, I can see a blank page on the Codesandbox.

**Comment by Nicitaa** [comment]
> I want to work on this issue. This would be my first open-source contribution.
> 
> But when I try to reproduce the issue, I can see a blank page on the Codesandbox.

![image](https://github.com/akiran/react-slick/assets/39565703/3a25fe0b-4ef8-4ec2-a28c-b94ea9f28982)
https://7hwygv-8001.csb.app/

![image](https://github.com/akiran/react-slick/assets/39565703/bf152f61-7a9f-4e32-a21d-925d9aaafc2c)
![image](https://github.com/akiran/react-slick/assets/39565703/83865a28-ac17-445a-b27e-1c62d5291889)

**Comment by malakbenr** [comment]
Can I work on this?

**Comment by Nicitaa** [comment]
> Can I work on this?

This question more for slick slider developer - its open source and you may not ask about you may work or no - if you want you can improve smth

**Comment by akiran** [comment]
slick-carousel css is not included in the demo you provided

**Comment by nicitaacom** [comment]
@akiran why its closed?
