### ISSUE TITLE
Element disapears if the user stays in another browser tab.

### ISSUE THREAD

**Issue by abdelouahabb** [akiran/react-slick#226]
If another tab is opened, and the user leaves the tab where the is the carousel, the elements will disapear. must clic on to make them back.
This happens of course when the carousel is played automaticaly `autoplay: true,`

**Comment by vdv73rus** [comment]
+1
I'm waiting for fix!

**Comment by alexeyignatov** [comment]
+1
The same issue!

**Comment by nicoecheza** [comment]
+1

**Comment by akiran** [comment]
Dulplicate of #202
