### ISSUE TITLE
My cards are't centred inside the slider

### ISSUE THREAD

**Issue by starman1999** [akiran/react-slick#2266]
SETTINGS: 

  ```
const settingss = {
    dots: true,
    infinite: true,
    slidesToShow: 1,
    centerMode: true,
    slidesToScroll: 1,
  };
```

HTML: 

  
 ```
<Slider {...settingss}>
          <div>
            <article className="advantages-card">
              <img src={require("../../assets/advantages-icon1.png")} alt="" />
              <h3> {t("Advantages-title1")} </h3>
              <p>{t("Advantages-p1")} </p>
            </article>
          </div>

          <div>
            <article className="advantages-card">
              <img src={require("../../assets/advantages-icon1.png")} alt="" />
              <h3> {t("Advantages-title1")} </h3>
              <p>{t("Advantages-p1")} </p>
            </article>
          </div>

        </Slider>
      </div>
```

RESULT: 
![image](https://github.com/akiran/react-slick/assets/32131811/40fa06f1-e1a0-4f32-b0d0-3a9e4c2e0a00)

when i use H3's instead of cards, it center them with no problems.
Noe that the "advantages-class" in my cards has a width property that i believe is causing the problem:
```
.advantages-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--color-white);
  box-shadow: 0px 0px 4px 0px rgba(11, 117, 51, 0.25);
  border-radius: 20px;
  padding: 2rem;
  width: 28rem;
  color: var(--color-black);
}
```
when I remove the width from the advantages-card class it becomes centered but it's streched : 
![image](https://github.com/akiran/react-slick/assets/32131811/628340e5-604b-4914-a4e4-833cbb147210)

what can I do please to make this work? i want to show a card at a time , centred.
Thank you for taking the time to check this out 😁

**Comment by Shaikhaltamash861** [comment]
assign me

**Comment by kaif001** [comment]
please set the margin auto at the div of card so that it can be centered
margin:0 auto;
