### ISSUE TITLE
[feature request] gaps and padding

### ISSUE THREAD

**Issue by y-nk** [akiran/react-slick#2268]
1. It would be useful that we can set a gap (similar to flex gap) because we can't set margins (it messes up calculation)
2. It would be nice if we could have padding within the carousel which does not influence width/page calculation.

**Comment by bharath090909** [comment]
@y-nk, I would like to address this. Can I take it on?

**Comment by y-nk** [comment]
@bharath090909 i'm not owner of the repo so please go ahead. also, FYI i moved _out_ of this library and implemented my own carousel with flex layout instead, which is better for layout calculation performances. it's a private library until i get clearance to open it.

**Comment by akiran** [comment]
We can't add this feature.
You can add spacing with CSS and CustomSlide feature
