### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by Pierre31415** [akiran/react-slick#2275]
Greetings,

I use the same code as on this page : https://react-slick.neostack.com/docs/example/simple-slider
but I have a width issue, it is always far too wide on smaller screen
It must be very easy to fix it, but I am getting mad at not finding the solution for 2 days

Thanks for your support

![cc1](https://github.com/akiran/react-slick/assets/78741730/b1792bc2-6fb3-4acf-b0c5-fdc4b884f3ca)
![cc2](https://github.com/akiran/react-slick/assets/78741730/c007a453-cf94-48db-8990-a6a4c45fb2e9)

**Comment by Noushad-web** [comment]
@Pierre31415 I'd be happy to help you with that. Can you please provide me with more context? because I can't reproduce this issue. What code snippet are you trying?

**Comment by akiran** [comment]
You can wrap the slider with a div and you can set the width you want on this div
