### ISSUE TITLE
In infinite mode, when slidesToShow equal to the length of slides, infinite functionality is not working

### ISSUE THREAD

**Issue by smurf-ss** [akiran/react-slick#2279]
### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by akiran** [comment]
when slidesToShow is equal to the length of slides, all the slides are already appearing on the screen. So there is nothing to slide.

It is the desired behavior of the library.
