### ISSUE TITLE
Slide with variable width's first slide is not positioned properly.

### ISSUE THREAD

**Issue by alma-socar** [akiran/react-slick#228]
```
let settings = {
      dots: false,
      arrows: false,
      centerMode: true,
      infinite: true,
      slidesToShow: 1,
      speed: 500,
      variableWidth: true,
    };
```

![image](https://cloud.githubusercontent.com/assets/16098076/12709587/fffeec00-c8f0-11e5-897e-15db2474e4e7.png)

Since this is infinite slides last slide should displayed on the left.

`initialSlide: 2` is not working too.

**Comment by foriacus** [comment]
+1

**Comment by lemieux** [comment]
I have this problem too, any idea how to fix that? it seems to fix itself when the page resizes or when you navigate through the slides.

**Comment by bluefoliot** [comment]
+1
Does this mean that variable width is unusable?
