### ISSUE TITLE
How to change the prevArrow and nextArrow button position

### ISSUE THREAD

**Issue by iamdebobrota** [akiran/react-slick#2282]
- [ ] If i want to change the position  of nextArrow and prevArrow, how can I do this?

**Comment by Nitinkumar2905** [comment]
As both buttons are in parent container as image so we can use position absolute to parent which will use relative and consider giving left top bottom or right distance for buttons

**Comment by akiran** [comment]
You can go through the css in [slick-theme.css](https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.css) and override the .slick-prev, .slick-next styles.

Or you can use custom arrows feature
https://react-slick.neostack.com/docs/example/custom-arrows
