### ISSUE TITLE
Type Issues with @types/react 18.2.22

### ISSUE THREAD

**Issue by lx-maxhaslehner** [akiran/react-slick#2284]
When using the latest Version of React Slick combined with @types/react Version 18.2.22, there are type errors when trying to build the project. (When using Version 18.2.21, everything works fine)

![Bildschirmfoto 2023-09-21 um 10 42 29](https://github.com/akiran/react-slick/assets/119567022/d415e8c9-6085-4463-a907-5ad233f7cffa)

**Comment by ericus123** [comment]
I have the same issue as well
<img width="1006" alt="Screenshot 2023-09-21 at 14 54 35" src="https://github.com/akiran/react-slick/assets/58434968/891d213e-8aef-4cb1-b8aa-7ce75377c62e">

**Comment by kjxbyz** [comment]
same issue.

**Comment by Lucasgeg** [comment]
Hey guys, I get the same issue since I've update to 1.18.22,
I fixed it with a `yarn dedupe` and it's all good

**Comment by kjxbyz** [comment]
1. `rm -f yarn.lock`
2. `yarn`
3. `yarn build`

It works for me.

**Comment by Lucasgeg** [comment]
> 1. `rm -f yarn.lock`
> 2. `yarn`
> 3. `yarn build`
> 
> It works for me.

It's quite the same, with this you delete all your yarn.lock,
yarn dedupe will parse your yarn.lock and only delete duplication 👍
