### ISSUE TITLE
how to set the spacing between carousel elements?

### ISSUE THREAD

**Issue by Jairwin-L** [akiran/react-slick#2290]
@akiran @pratyushbh   I have checked the documentation and [demo](https://react-slick.neostack.com/docs/example/multiple-items), but there is no mention of how to set it up. It’s just that the official demo has spacing.

**Comment by Jairwin-L** [comment]
It seems like the only way to solve it
```tsx
<Slider {...sliderSettings}>
  {dataSource.map((item, index) => (
    <Fragment key={index}>
      <div
        style={{ marginRight: "10px" }}
      >
       11
      </div>
    </Fragment>
  ))}
</Slider>
```

**Comment by Enkratia** [comment]
You can go to https://react-slick.neostack.com/docs/example/simple-slider
-> click right mouse button on slider
-> observe css code of page to understand. how css applied for this slider

Or you can use my approach
```
  .slick-slider {
    margin-inline: -30px;
  }

  .slick-slide {
    >div {
      margin-inline: 15px;
    }
  }
```

Do you understand idea of this code?

**Comment by Jairwin-L** [comment]
> Hello, @Jairwin-L
> 
> You can go to https://react-slick.neostack.com/docs/example/simple-slider -> click right mouse button on slider -> observe css code of page to understand. how css applied for this slider
> 
> Or simply do this:
> 
> ```
>   .slick-slider {
>     margin-inline: -30px; //  space between slides * (-1)
>   }
> 
>   .slick-slide {
>     >div { // automatically generated 'div' by 'react-slick'
>       margin-inline: 15px; //  space between slides / 2
>     }
>   }
> ```
> 
> Do you understand idea of this code?

okay, I probably understand
