### ISSUE TITLE
Slider width being set to a larger number?

### ISSUE THREAD

**Issue by medv** [akiran/react-slick#230]
I implemented a slider sometime in the past but now it's broken. It's like the calculation of the slick container takes max-width of the parent element as the width, so it fails to size itself down when its container is sized down.

My parent element is 98% wide and max-width 1600px, and slick does not go below 1600px anymore. It used to scale fine before. I have scoured for any side effects in my css but I fail to find any, this happens no matter what I set as my slides, too, even simple naked div with a string inside it.

**Comment by amitthakkar22288** [comment]
i think this is related to a recent chrome update if using flex layouts,
 try setting min-width:0;min-height:0 

http://stackoverflow.com/questions/35168412/incorrect-flexbox-display-in-chrome-48

**Comment by medv** [comment]
Issue persists, I am not using flex, but it appears further up the ancestor tree. However i break out of flex before the slider depth. Anyhow, setting those to all elements up the tree does not solve the issue.

**Comment by akiran** [comment]
Please provide code snippet to replicate the issue

**Comment by akiran** [comment]
Closing this issue. 
Please reopen if you can reproduce the issue with demo
https://jsfiddle.net/kirana/20bumb4g/

**Comment by nabilfreeman** [comment]
@akiran, I broke it:

https://jsfiddle.net/20bumb4g/128/

Note the purple overlapping colour.

I'm currently suffering from this issue - basically the slider works perfectly until you embed it in a Flex view. Quite difficult to work around in some situations.

**Comment by nabilfreeman** [comment]
I can't reopen the issue so could you?

**Comment by nabilfreeman** [comment]
I updated it here with a check for the pixel width of the `.flex-inner` div.

It comes back as 3080px when it should be 500px

https://jsfiddle.net/20bumb4g/129/ (open your console)

**Comment by amitthakkar22288** [comment]
i had this issue too. temp fix is adding

```
min-width:0;
max-height:0;

```
to .flex-inner class.

**Comment by nabilfreeman** [comment]
@amitthakkar22288, you're a legend man! This worked for me.

I didn't actually need `max-height:0` for my horizontal slider, just `min-width:0;`

You can toggle the fix with a button here:

https://jsfiddle.net/20bumb4g/130/

**Comment by creeperyang** [comment]
I don't use `flex` and slider width is still larger. So any idea?

**Comment by jshado1** [comment]
We're seeing this also (as @creeperyang described). We do use flexbox on the slides, but the min-width + max-height trick just collapses the slides. It appears that the amount by which the slide's width is incorrect is equal to the amount of padding applied to the grandchild of each slide.

**Comment by Randy808** [comment]
I'm still encountering this problem of 'too wide' slides. The slick-slide elements all have styles directly on the div that impose large widths. I even tried setting a fixed width in the settings, but it still refuses to work.

**Comment by TPABHuKOB** [comment]
Guys, i've made vertical gallery like what https://jsfiddle.net/20bumb4g/2709/
In example works fine, but in my app (based on react-redux-universal-hot-example) its looks terrible. I used flexboxgrid and fixes from this thread dont helped me.
What To Do?!

**Comment by TPABHuKOB** [comment]
set width,height in <img> helps me

**Comment by jonnyi** [comment]
The issue as described above still exists for me. Could you possibly reopen this?

**Comment by laveesingh** [comment]
@jonnyi  could you generate a codesandbox demo for the same?

**Comment by chadsteele** [comment]
I had a similar, but different issue where .slick-slide's width was being mis-calculated when I only had one slide in the carousel... when I add settings = { ... variableWidth: true ... } solved it for me.  Perhaps it will help some of you.

**Comment by prasanthd2246** [comment]
guys if u problem with slick slider width even though  without using any flex box or grid and the slide images are appearing if u scroll through large width then you could use overflow:hidden in container having slider  .. it solved my issue ;
