### ISSUE TITLE
Wrong direction when use floating point `slidesToShow`.

### ISSUE THREAD

**Issue by AliBayatMokhtari** [akiran/react-slick#2307]
The live example lives here: [Code Sand Box](https://codesandbox.io/p/sandbox/misty-snowflake-spcwf2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpds7cpq00073p6gij7jiwx7%2522%252C%2522sizes%2522%253A%255B86.96629213483146%252C13.033707865168537%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpds7cpq00033p6gon8j7qzs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpds7cpq00043p6grsh1usu2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpds7cpq00063p6g0v7qmi0b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B59.28735003403346%252C40.71264996596654%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpds7cpq00033p6gon8j7qzs%2522%253A%257B%2522id%2522%253A%2522clpds7cpq00033p6gon8j7qzs%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpds7cpq00063p6g0v7qmi0b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpds7cpq00053p6gmclnga9r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpds7cpq00063p6g0v7qmi0b%2522%252C%2522activeTabId%2522%253A%2522clpds7cpq00053p6gmclnga9r%2522%257D%252C%2522clpds7cpq00043p6grsh1usu2%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpds7cpq00043p6grsh1usu2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A19.569327731092443%257D)

it shows the half one on the left side, but container direction is `ltr` and the half one should be on the right side.

**Comment by akiran** [comment]
`slidesToShow` should be integer
