### ISSUE TITLE
dots

### ISSUE THREAD

**Issue by James4518** [akiran/react-slick#2314]
const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1，
      slidesToScroll: 1
    };

When I change the css on the original basis， see:
![viewfile](https://github.com/akiran/react-slick/assets/55346078/906cb82d-ea87-4497-a310-67f0680721d9)

try to flex,but:
![viewfile(2)](https://github.com/akiran/react-slick/assets/55346078/b864f6a2-e79a-4f0b-80ae-c714d5777389)

**Comment by akiran** [comment]
I couldn't understand issue. Are you using multiple sliders?
Please re-open the issue with codesandbox to replicate the issue
