### ISSUE TITLE
Not able to change size of arrows of Slider

### ISSUE THREAD

**Issue by SoniRe** [akiran/react-slick#2320]
Just want to change the size of god damn arrows. 

-> Its not working even after changing height, width, font size
-> But it changes background color and other stuff

**Comment by akiran** [comment]
You need to change height and width on .slick-prev, .slick-next and fontsize on .slick-prev:before, .slick-next:before

Try this
```
.slick-prev,
.slick-next {
  height: 40px;
  width: 40px;
}
.slick-prev:before,
.slick-next:before {
  font-size: 40px;
}
```
