### ISSUE TITLE
I am using react slick slider on click on colors i have i want to change the image of carousel 

### ISSUE THREAD

**Issue by sahilbisht0602** [akiran/react-slick#2321]
![Screenshot 2024-01-06 at 10 54 07 PM](https://github.com/akiran/react-slick/assets/61845930/8e814193-4d3c-4442-bc83-9871f794374b)

you can refer above image if user clicks on red color the car change to red color car image and same goes with other. how to achieve this. i am not able to change the active index

**Comment by akiran** [comment]
You can use custom paging feature
https://react-slick.neostack.com/docs/example/custom-paging
You can use CSS to place the dots at required position.

If the custom paging doesn't work for your use case, you can try slickGoTo
https://react-slick.neostack.com/docs/example/slick-go-to
