### ISSUE TITLE
May I develop it so that infinite swipe is possible when the values of 'slidesToShow' and 'showElement' are the same, and 'infinite' is set to true?

### ISSUE THREAD

**Issue by rjsdnql123** [akiran/react-slick#2328]
Hello. I'm using the `react-slick` library successfully.

The requirements for my project are to have 9 `items(element),` with `slidesToShow` set to 9 so that all elements are visible on the screen, and `infinite` is set to `true.`

The expected outcome is to have all elements visible on the screen and be able to slide left and right.

However, I've confirmed that it's not currently functioning as expected.

Looking at the issue list, it seems there are others with similar requirements. Would it be okay for me to try making modifications in this regard?

## Related issues

https://github.com/akiran/react-slick/issues/2102

## before
<img width="1258" alt="image" src="https://github.com/akiran/react-slick/assets/61114705/3d5ad882-a508-4794-aa79-003fe62bf8d0">

## after 

<img width="687" alt="image" src="https://github.com/akiran/react-slick/assets/61114705/3382a6e1-f6f3-4c0f-8e5b-641e12715b9a">

### Guidelines for posting a new issue

* Please replicate your issue with this [CodeSandBox](https://codesandbox.io/s/ppwkk5l6xx) and provide a link to it along with the issue description

**Comment by rjsdnql123** [comment]
+ add https://github.com/akiran/react-slick/issues/1813

**Comment by rjsdnql123** [comment]
@akiran 
If you could check, I will summarize and post my changes. Thank you for creating a great library! :)

**Comment by akiran** [comment]
Sure. You can send a PR

**Comment by rjsdnql123** [comment]
https://github.com/akiran/react-slick/pull/2329%20%20%20%20Could%20you%20please%20review%20my%20pull%20request?%20:%20)

**Comment by akiran** [comment]
Merged #2329

**Comment by rjsdnql123** [comment]
Thank you 😄
