### ISSUE TITLE
Can't add default styles

### ISSUE THREAD

**Issue by humanua** [akiran/react-slick#2332]
styles now are broken... can't add default styles
`<head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>`
this variant doesn't work

**Comment by akiran** [comment]
It is working in this playground. 
https://codesandbox.io/s/ppwkk5l6xx

**Comment by humanua** [comment]
didn't work yesterday. can you add styles to the library?

**Comment by humanua** [comment]
> It is working in this playground. https://codesandbox.io/s/ppwkk5l6xx

didn't work yesterday. can you add styles to the library?

**Comment by akiran** [comment]
It had issues yesterday because of some changes in the codesandbox platform. Fixed it today.

We can't add styles to the library at the moment. styles need to be integrated separately .
