### ISSUE TITLE
Can i display all slides while i set slideToShow?

### ISSUE THREAD

**Issue by fzn0x** [akiran/react-slick#2335]
I have some issue with this package

The issue is when I set the slideToShow to 4 (with infinite: true)

Only 4 slides are visible

What I expect is, I want all other than the 4 slides to be visible, so i can use transform and translate for dynamic animation purposes like CSGO gacha

the problem is when i use transform and translate, the other slides are hidden.

How to fix this issue?

**Comment by akiran** [comment]
If you want more slides to appear, set slidesToShow to a higher number.

For example, if you set slidesToShow to 12, slidesToScroll to 4,  12 slides will be visible. When you click on next or previous buttons, 4 slides will shift

**Comment by fzn0x** [comment]
GG thanks @akiran

**Comment by fzn0x** [comment]
Can we do that without `When you click on next or previous buttons, 4 slides will shift` ? @akiran

**Comment by akiran** [comment]
I didn't understand your requirement
