### ISSUE TITLE
Slider shows the wrong number of slides

### ISSUE THREAD

**Issue by yerinSergey** [akiran/react-slick#234]
Set such options: 
- slidesToShow: 2,
- slidesToScroll: 1,
- swipe: true

then, swipe to the end.
Expected result - see 2 last slides.
Actual result - see only one, last slide.
I think the problem in https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js#L142
maybe it should be => (targetSlide >= this.state.slideCount - 1)

**Comment by akiran** [comment]
Couldn't replicate this issue.
Can you provide exact code snippet you are using
