### ISSUE TITLE
Issue with asNavFor Prop in react-slick v0.30.1

### ISSUE THREAD

**Issue by dasun4u** [akiran/react-slick#2344]
Hello,

I've encountered an issue with the asNavFor prop in react-slick version 0.30.1. It seems that the asNavFor functionality is not working in this version, while it functions properly in version 0.29.0.

Link to sandbox where all issues are reproducible [CodeSandBox](https://codesandbox.io/p/sandbox/react-slick-93y92t?file=%2Fsrc%2Findex.js%3A44%2C9-44%2C17)

Could you please look into this matter and provide guidance on resolving the issue?

Thank you,

**Comment by abubakarkhawaja** [comment]
Following issue is also seen on react-slick doc https://react-slick.neostack.com/docs/example/as-nav-for

**Comment by akiran** [comment]
Yes, We are working on it.
Will fix it in the next release
