### ISSUE TITLE
Slider with only one slide item not displaying properly

### ISSUE THREAD

**Issue by andreivictor** [akiran/react-slick#2357]
I have a slider with dynamic number of items. 
At page load, the slider contains only one slide item.
The slider does not display properly.

```ts
const settings = {
    dots: true,
    slidesToShow: 1,
    slidesToScroll: 1
  };
```

React Slick version: **0.30.1**

Stackblitz demo:
https://stackblitz.com/edit/vitejs-vite-zskgbz?file=src%2FImageSlider.jsx

**Comment by wa1kb0y** [comment]
try to set `infinite: false`

```
var settings = {
      dots: true,
      slidesToShow: 2,
      slidesToScroll: 1,
      infinite: false
};
```

**Comment by andreivictor** [comment]
Thank you, using `infinite: false` solved the issue.

```ts
const settings = {
    dots: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    infinite: false,
  };
```
