### ISSUE TITLE
Slider is scrolled to the right when switching to previous on the first item 

### ISSUE THREAD

**Issue by Qrysto** [akiran/react-slick#238]
I have a react-slick slider with 5 items. When I update to 0.10.0, this unexpected behaviour happens. When I'm on the first item and I press the previous button, it's scrolled to the last item, but all the way to the right instead of to the left (naturally). This didn't happen in 0.9.3

My config is as follow
```
<ReactSlick
				dots={false} 
				slidesToShow={1}
				slidesToScroll={1}
				autoplay={false} 
				pauseOnHover={true}
				autoplaySpeed={6000}
				infinite={true}
				draggable={true}
				swipe={true}
				swipeToSlide={true}
			>
```

**Comment by easga** [comment]
Yes, same for me, we discovered it today.
