### ISSUE TITLE
Depends on jQuery

### ISSUE THREAD

**Issue by abhinavrastogi** [akiran/react-slick#240]
This adds 60kb to the webpack bundles. Highly inconvenient!
Would have gladly used it if it was much smaller.

**Comment by akiran** [comment]
It doesn't depend on  jQuery.
It's purely written in react

**Comment by yiminghe** [comment]
please move original slick to dev Dependencies

**Comment by akiran** [comment]
It depends on slick for CSS.

**Comment by yiminghe** [comment]
can you copy slick css to you project?

react-slick causes our build server to download unnecessary code (slick-carousel, jquery ...).

**Comment by ShinyLeee** [comment]
I think slick-carousel is unnecessary too.. 
It depend on jquery and I have to download it.

**Comment by Gervwyk** [comment]
Is there any way to remove the jquery dependency? Looks like it really adds unnecessary content to the bundle size.

**Comment by akiran** [comment]
jQuery is never added in the bundle.  slick-carousel dependency is only for css

**Comment by Gervwyk** [comment]
Ok. But that means jQuery ends up in bundle because of slick-carousel, which is only used for css. Can't we only copy the css to this project and remove slick-carousel dependency to get rid of jQuery in the bundle?

**Comment by akiran** [comment]
We use wepack to bundle this library. We never imported jQuery. So it will not be bundled in this library.

**Comment by Gervwyk** [comment]
Ok. Sorry. my bad. I missed the ⚠️ Also install slick-carousel for css and font part - which actually creates the issue. When using ant design and meteor, the import of antd causes it to import slick-carousel which is jquery dependent and causes this issue.
