### ISSUE TITLE
[Solution] for exploding layouts

### ISSUE THREAD

**Issue by MadKillerChicken** [akiran/react-slick#2402]
Not an issue, but hopefully useful for the next poor soul wondering why using this in a grid causes his layout to continuously explode.

I placed several of these sliders inside a responsive layout (material-ui grid) and watched in awe as the page kept re-rendering several times each second, which in of itself was quite a spectacular way to fail, but I digress.

Nothing, aside from wrapping the slider with a static-width div, stopped the sliders from unleashing Armageddon.
Since this kills the responsiveness, which is usually undesired, at least to me, I spent a couple hours respectfully cursing at whoever came up with CSS, and finally found a solution that actually works.

Wrapping the slider with a div, having the following style, will forcefully limit it to the width of the parent element.
```
display: 'grid',
grid-template-columns: 'minmax(0, 1fr)'
```
Note that this only works because of `grid-template-columns: 'minmax(0, 1fr)'`.

**Comment by esetnik** [comment]
I had the same issue using this library and I have no idea why this works but it does. Yay css 🎉

**Comment by MadKillerChicken** [comment]
> I have no idea why this works but it does. Yay css 🎉

Glad to see that my comment helped you.  

The fact that this works while a simple `fr1` does not, is caused by the CSS grid default behavior. Apparently `fr1` is being interpreted as `minmax(auto, 1fr)`, which forces columns to grow with their children. Strange choice as far as default behaviors for layout components are concerted, at least IMO.  

The following answer on Stackoverflow has more insight: https://stackoverflow.com/a/52861514
