### ISSUE TITLE
Initial silde will not be displayed when lazyLoad mode enabled

### ISSUE THREAD

**Issue by chentsulin** [akiran/react-slick#246]
Initial silde will not be displayed when lazyLoad mode enabled, and set `lazyLoad: false` slide will be displayed correctly. It seem some weird behavior in lazyLoad mode. Below is my setting when encountered this issue:

``` js
const settings = {
      className: 'center',
      infinite: false,
      speed: 500,
      lazyLoad: true,
      slidesToShow: 3,
      centerMode: true,
      centerPadding: '60px',
};
```

**Comment by akiran** [comment]
I was able to replicate this issue https://jsfiddle.net/kirana/xq3ph2vx/1/
I will try to fix it soon

**Comment by chentsulin** [comment]
@akiran Any update on this?

**Comment by davincho** [comment]
+1 I have the same problem.
