### ISSUE TITLE
Component .css isn't loading

### ISSUE THREAD

**Issue by Light1c3** [akiran/react-slick#253]
I was trying to get the component working, but this is as far as I am able to go. I installed bower, but even with without css on the jsfiddle your example works so what's the issue here? Is it me (I'm new so very possible), or the code somehow?

This also seems to cause the gallery to not display correctly on mobile, but I can't seem to figure out what's the issue.

Example:
http://s615680131.onlinehome.us/

**Comment by akiran** [comment]
In jsffidle, I added below links as external css files 
https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick.min.css
https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick-theme.css

You can also link to cdn files similarly
