### ISSUE TITLE
Fade and autoplay do not play nicely together

### ISSUE THREAD

**Issue by fender** [akiran/react-slick#255]
Seeing issues when `fade` and `autoplay` are both set to `true`. To see this, go to the JSFiddle below and after hitting next/prev a few times you will see the dots starting to jump around. This is likely because the autoplay timer is not being reset?
https://jsfiddle.net/20bumb4g/21/

Note: Using version 0.11.1.

**Comment by jalyna** [comment]
:+1: facing the same issue.

**Comment by cbhoweth** [comment]
+1

**Comment by andrewdelprete** [comment]
👍

**Comment by mibowser** [comment]
+1

**Comment by mibowser** [comment]
actually.. I think I have a fix, at least.. it works for what I needed it for.. including speed and autoplay speed.. here's my fiddle.

https://jsfiddle.net/micbowser/mL1524cb/

**Comment by alirezavalizade** [comment]
Im have same issue :@

**Comment by MimiLau** [comment]
+1

**Comment by cjtafoya** [comment]
+1

**Comment by proverbface** [comment]
+1

**Comment by laveesingh** [comment]
The issue doesn't exist anymore. It has been fixed in previous releases. Please feel free to request reopen if disagree.
