### ISSUE TITLE
initial silde will not be displayed when use map()

### ISSUE THREAD

**Issue by nic611** [akiran/react-slick#261]
initial silde will not be displayed when use map() to creat activtive pic,but press the dots,the second pic will run...

![ul tv y tf4 ke rk3l7w04](https://cloud.githubusercontent.com/assets/8542939/13770037/43116ee2-eabf-11e5-9f62-b8b53063ecd8.png)

**Comment by GoToBoy** [comment]
i had the same question

**Comment by hitamu** [comment]
Not working when mapping with component
```javascript
    const slides = chars.map( (char) => {
      return <MyComponent char={char}/>
    })
    return (
      <Slider {...settings}>
        {slides}
      </Slider>
    );
```

**Comment by kevinahuber** [comment]
I've got the same issue.. any ideas?

**Comment by xxronis** [comment]
Nice1,  this comment got my slider working...somehow, but whats happening here?

**Comment by laveesingh** [comment]
I'm not sure if that's still the case. The issue could have been fixed in previous releases. Please feel free to request reopen if disagree.
