### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined, trackHelper.js:115

### ISSUE THREAD

**Issue by fyyyyy** [akiran/react-slick#263]
``` js
        let settings = {
            dots: false,
            arrows: true,
            infinite: false,
            afterChange: this.afterChange.bind(this),
            slickGoTo: this.state.slickGoTo,
            variableWidth: true,
            centerMode: true,
            focusOnSelect: true
        };
```

```
"react-slick": "^0.11.1",
"slick-carousel": "^1.5.9"
"react": "^0.14.6",
```

This is the error message, its caused by `centerMode: true`, without it this runs fine.

`trackHelper.js:115 Uncaught (in promise) TypeError: Cannot read property 'offsetWidth' of undefined(…)getTrackLeft @ trackHelper.js:115(anonymous function) @ helpers.js:71assign.notifyAll @ CallbackQueue.js:65UPDATE_QUEUEING.close @ ReactUpdates.js:57Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66NESTED_UPDATES.close @ ReactUpdates.js:45Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:65(anonymous function) @ App.js:273
trackHelper.js:115 Uncaught (in promise) TypeError: Cannot read property 'offsetWidth' of undefined(…)getTrackLeft @ trackHelper.js:115(anonymous function) @ helpers.js:71assign.notifyAll @ CallbackQueue.js:65UPDATE_QUEUEING.close @ ReactUpdates.js:57Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66NESTED_UPDATES.close @ ReactUpdates.js:45Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:65notify @ App.js:361(anonymous function) @ App.js:281`

**Comment by sanchitgangwar** [comment]
Facing the same problem.

**Comment by fyyyyy** [comment]
Wrote my own carousel to fix this. Was much faster than customizing this ;)

**Comment by sanchitgangwar** [comment]
@fyyyyy Is it open-source and free? :)

**Comment by miraage** [comment]
Any progress?

**Comment by fyyyyy** [comment]
Bit offtopic but here you go, this carousel calculates each tasks width by task.duration, so shorter tasks are smaller than longer tasks. You can change this scaling of course but in the end i found this more flexible than a ui plugin. 

https://gist.github.com/fyyyyy/a5013633b927d00adc7cb596ed3296b1

**Comment by AdaltonLeite** [comment]
Any Progress?
