### ISSUE TITLE
Weird rendering when children are react component

### ISSUE THREAD

**Issue by clearmirror** [akiran/react-slick#275]
Notice that when child is react component instead of native html the rendering is not showing expected result. See https://jsfiddle.net/8a9ejzqk/

Any workarounds or do I miss anything?

**Comment by J-F-Liu** [comment]
`https://facebook.github.io/react/js/jsfiddle-integration-babel.js` no longer exists?

**Comment by akiran** [comment]
@clearmirror You have pass {...this.props} to the element inside custom component
https://jsfiddle.net/8a9ejzqk/1/
