### ISSUE TITLE
Custom Next Arrow shown below the slider

### ISSUE THREAD

**Issue by adrianha** [akiran/react-slick#277]
Hi,
I was trying to create custom component for next arrow but it shown below the slider
Heres the fiddle: https://jsfiddle.net/bj0ue9r8/

**Comment by akiran** [comment]
@adrianha You have to style it to make it appear the way you wanted.
You can refer how default arrow elements are styled 
https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.scss#L63
