### ISSUE TITLE
The slider has less slides won't display if switch from a slider has more slides

### ISSUE THREAD

**Issue by wuyiqun0718** [akiran/react-slick#278]
Hi there,

I was trying to use a dropdown menu to change the displaying slides. Option 1 has a few slides, option 2 only has 1 or 2 slides so it can't slide at all.  So when I select the option 1 first, and slide it to the right end. Then switch to option2, then the slides won't displayed at all and the next/prev buttons is disables.

I hope it's described clearly, this is the best I can do. Here's the jsfiddle:

https://jsfiddle.net/20bumb4g/231/

Thanks!

**Comment by akiran** [comment]
Fixed in master. Will make a npm release soon
