### ISSUE TITLE
Responsive initialSlide setting not working

### ISSUE THREAD

**Issue by dougmacklin** [akiran/react-slick#282]
The `initialSlide` setting doesn't seem to have any effect when added to a `responsive` breakpoint: https://jsfiddle.net/20bumb4g/241/

```
responsive: [
  { breakpoint: 768, settings: { slidesToShow: 2, initialSlide: 3 } }
]
```

`slickGoTo`, on the other hand, is working (I'm actually getting a 'Keys Missing' error on jsfiddle that I'm not experiencing locally, however): https://jsfiddle.net/20bumb4g/240/

```
responsive: [
  { breakpoint: 768, settings: { slidesToShow: 2, slickGoTo: 3 } }
]
```

(Note that you may have to adjust the size of the Result tab on jsfiddle to view the issue at the specified breakpoint).

Is this by design for some reason? Thanks in advance!

**Comment by akiran** [comment]
Yes,  initialSlide is only for initial mount and slickGoTo is to change slide after mounting.
This is by design
