### ISSUE TITLE
Settings variation and slickGoTo

### ISSUE THREAD

**Issue by linuxenko** [akiran/react-slick#295]
It seems like after state change when i'm trying open slide with `slickGoTo`, slider does not work anymore (does not handle swipe events and i cannot change slide by dragging/swiping it).

With `dots: true` settings option `slickGoTo` works fine . But it makes DOM for dots, that not so cool.

Thank you

**Comment by dougmacklin** [comment]
+1. I just updated to react@15.0 and react-slick@0.12.0 and slickGoTo is no longer working for me as well, it results in a blank slider.

**Comment by HriBB** [comment]
Try setting `waitForAnimate: false`

**Comment by akiran** [comment]
slickGoTo is now change to method instead of prop.
Check this example https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

open a new issue if you are still facing issues with slickGoTo
