### ISSUE TITLE
react-slick works with React v15.0.0?

### ISSUE THREAD

**Issue by kennetpostigo** [akiran/react-slick#296]
I'm wanting to use react-slick in one of my projects. Just wondering if it works with react 15.0.0

**Comment by kamui** [comment]
https://github.com/akiran/react-slick/blob/master/package.json#L69-L70

Looks like it at least from it's peer dependencies.

**Comment by rafaelteixeira** [comment]
@kennetpostigo is it working in your project? It's not on mine.

I get this error:

> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by rochestb** [comment]
![hd-8h3gUKPZKrvm8](https://media2.giphy.com/media/8h3gUKPZKrvm8/giphy.gif)

**Comment by adamclark64** [comment]
This was not working originally but set up with react 15.0.1 as a peerDependency and using react-slick 0.9.2, I was able to get it running

**Comment by kennetpostigo** [comment]
@rafaelteixeira Yes it seems to be working for me.
