### ISSUE TITLE
Slider can become unusable when altering the number of children

### ISSUE THREAD

**Issue by chrisknepper** [akiran/react-slick#297]
When re-rending the slider due to a change in the number of children (slides), certain situations can cause the slider to incorrectly it position itself far to the right of the window (off-screen).

The most common way I can reproduce this issue is by starting with a large list, with the current slide at least half-way through the list, then re-rendering with fewer children.

I have reproduced this issue in a [jsfiddle](https://jsfiddle.net/chrisknepper/sg9tn203/1/) and I have created a [short video](http://chrisknepper.com/misc/react-slick-index-error.mp4) demonstrating the problem.

This is likely the same problem causing #267, #278, and perhaps #295.

**Comment by chrisknepper** [comment]
I believe I have fixed this problem. When changing the slider children, while keeping `slickGoTo` the same (which happens if your slides change but the number of them do not), the logic in `componentWillReceiveProps` calls `this.update` when it should call `this.changeSlide` instead.

**Comment by akiran** [comment]
Fixed in master. Will make a release soon
