### ISSUE TITLE
Initial slides on top of the real slides 

### ISSUE THREAD

**Issue by drorsun** [akiran/react-slick#300]
Hi,
I am presenting videos with react-slick and auto-play videos when they are in the center. I am showing 3 slides each time (slidesToShow: 3) and I am using beforeChange and afterChange to play/pause.
I am able to play and pause using a ref I added a ref={'preview' + index} for every video so I can play it when it gets into focus and pause it when it goes out of focus. 
So this all works, videos play and pause well.  Except the 3 first slides for which I just hear audio. After investigating it turned out that the Slider holds 3 extra divs, with data-index -1, -2 and -3 for the first 3 slides with exactly the same content of my first three slides. When I play one of the videos on these 3 slides it works, but I can't see the video because there another PreviewPlayer on top of the one that is playing.
I hope I was clear. 
The important bit in my code is this:

```
itemWillMove(index) {
    var playerRef = 'preview' + index; 
    console.log("pausing " + playerRef);
    this.refs[playerRef].pause();
},
itemMoved(index) {
    var playerRef = 'preview' + index;
    console.log("playing " + playerRef);
    this.refs[playerRef].play();
},
render() {
    var previewPlayers = [];
    this.state.videos.forEach(function(video, index) {
        console.log("pushing video index - " + index);
        previewPlayers.push(<div key={'preview' + video.performanceId}><PreviewPlayer video={video} ref={'preview' + index} /></div>);
    }.bind(this));

    var settings = {
        autoplay: false,
        arrows: true,
        dots: true,
        slidesToShow: 3,
        slidesToScroll: 1,
        centerMode: true,
        beforeChange: this.itemWillMove,
        afterChange: this.itemMoved
    };

    return(
            <div className='container'>
                <Slider {...settings} >
                    {previewPlayers}
                </Slider>
            </div>
    );
}   
```

**Comment by surajhell88** [comment]
I have basically the same setup too. But instead of playing video, I have slides that the User can delete, so when the User starts deleting 1 by 1. Until the last 1 remains, there are still 3 slides, 1 original & 2 extra slides(copies of the original 1). Any help ?

**Comment by yathomasi** [comment]
Still facing the issue and I couldn't figure out the issue. @drorsun @surajhell88  do you guys have found any solution?

Here is the sandbox with the issue to play around. Please check and provide the possible solution around
https://codesandbox.io/s/slick-slider-react-slick-bug-with-video-forked-967b5?file=/src/index.js
