### ISSUE TITLE
autoplaySpeed is changed by clicking nextBtn when fade equals true

### ISSUE THREAD

**Issue by penguin3069** [akiran/react-slick#301]
https://jsfiddle.net/penguin3069/L96rm9j6/
set autoplaySpeed, then click `nextBtn` very quickly,and speed will be changed

**Comment by dalpo** [comment]
I encountered the same issue.

@penguin3069 I downgraded to the `v0.10.0` and it seems to work.

**Comment by penguin3069** [comment]
@dalpo Thanks
