### ISSUE TITLE
Autoplay not functioning

### ISSUE THREAD

**Issue by horaceleung** [akiran/react-slick#303]
My code below uses autoplay feature but the slides are not auto-transiting. Any help would be appreciated.

    const sliderSettings = {
      'dots': true,
      'infinite': true,
      'autoplay': true,
      'autoplaySpeed': 5000,
      'speed': 10,
      'slidesToShow': 4,
      'slidesToScroll': 4,
      'swipe': true,
      'draggable': false,
      'arrows': true,
      'responsive': [
        {
          'breakpoint': 970,
          'settings': {
            'slidesToShow': 3,
            'slidesToScroll': 3,
          },
        },
        {
          'breakpoint': 768,
          'settings': {
            'slidesToShow': 2.1,
            'slidesToScroll': 2.1,
            'arrows': false,
          },
        },
        {
          'breakpoint': 540,
          'settings': {
            'slidesToShow': 1.1,
            'slidesToScroll': 1,
            'arrows': false,
          },
        },
      ],
    };

**Comment by jitenderchand1** [comment]
How did fix this problem

**Comment by shineSnow** [comment]
i am waiting
