### ISSUE TITLE
Encountered two children with the same key, when infinite=true

### ISSUE THREAD

**Issue by marcusbrose** [akiran/react-slick#312]
> Warning: flattenChildren(...): Encountered two children with the same key, `firstkey`. Child keys must be unique; when two children share a key, only the first child will be used.

It seems like the 1st and last slide are added rendered twice.

**Comment by Noel-bk** [comment]
Yeah. I have same problem, too.. 😭

**Comment by akiran** [comment]
checkout 0.12.2 version

**Comment by Noel-bk** [comment]
Thank you very much. You're my lifesaver!! 👍

**Comment by marcusbrose** [comment]
thanks!

**Comment by orthes** [comment]
The same problem here even on 0.12.2:

> Warning: flattenChildren(...): Encountered two children with the same key, `.$cloned0`. Child keys must be unique; when two children share a key, only the first child will be used.

**Comment by jamesfzhang** [comment]
@orthes I noticed this error as well. I got rid of it by removing the `key` attributes from the `<Slider>`'s children.

**Comment by petesaia** [comment]
This is still an issue. @jamesfzhang's suggestion works but React throws a warning about not supplying a key which is a little annoying.

> warning.js:44 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Map`. See https://fb.me/react-warning-keys for more information.

**Comment by ruscoder** [comment]
I have the same problem as @dalpo when I use `infinite: true` option and keys for slides.

**Comment by alexanderfrey** [comment]
Same issue here.

**Comment by johuder33** [comment]
I had the same issue, but I started to deep inside the code and I got this function 

```
var getKey = function getKey(child, fallbackKey) {
  // key could be a zero
  return child.key === null || child.key === undefined ? fallbackKey : child.key;
};
```

this function define what key use when key attr is no passed, but it is, so always return child.key, so, what I did to solved the warnings for the slick and react, just add this.

```
var getKey = function getKey(child, fallbackKey) {
  // key could be a zero
  return child.key === null || child.key === undefined ? fallbackKey : child.key + new Date().getTime();
};
```

or this works as well

```
var getKey = function getKey(child, fallbackKey) {
  // key could be a zero
  return child.key === null || child.key === undefined ? fallbackKey : child.key + fallbackKey;
};
```

I hope, it is useful for you.

**Comment by lookapanda** [comment]
Version 0.14.11
I still have this issue.

**Comment by lookapanda** [comment]
Okay, just a heads up: I seem to "fixed" the issue. The issue was, that I used the IDs of the items directly as keys. Those IDs were numerical and whenever an item with the ID `10` appeared, it showed me that error.
![image](https://cloud.githubusercontent.com/assets/770632/26823348/9a915426-4aad-11e7-8448-231a5e4d1d30.png)

Now I just prepended a string like `item_${id}` and it seems to work.

**Comment by Frozenix94** [comment]
Hi,
I use 0.15.4 and i have the same issue :(
I use " key={`int-${slide.title_slide}`} " to create my key and react warning me : 
"
Each child in an array or iterator should have a unique "key" prop.
"

Can you help me ?
Thank a lot :]

**Comment by SamiurRahmanMukul** [comment]
![image](https://user-images.githubusercontent.com/64055126/173553420-350569e9-da5b-4c96-8395-d6fd261d003f.png)
How can i fixed unique key warnings ⚠?. I am already set unique in this sliders. But still this problem 😴
