### ISSUE TITLE
the component in slick do not fill the space

### ISSUE THREAD

**Issue by bethinner** [akiran/react-slick#314]
![image](https://cloud.githubusercontent.com/assets/9563056/15347082/c758ba1c-1cf0-11e6-8e27-8da700567f25.png)
the red space in picture. how to fix it

**Comment by akiran** [comment]
Set width of images as well to make width of all images same

**Comment by bethinner** [comment]
@akiran I had set style={{height:"200",width:"100%"},but still the same

**Comment by 727177817** [comment]
hi ，How do you solve？

**Comment by 727177817** [comment]
@bethinner 你怎么解决的？我也遇到这问题了

**Comment by 727177817** [comment]
@akiran I also encountered this problem，I wrote it according to the example。I think both sides spacing is zero。thanks

**Comment by Ibrasau** [comment]
You need to show us what settings you've provided to slick。Do you have "variableWidth" option enabled?

**Comment by 727177817** [comment]
@Ibrasau  This is my configuration. After variableWidth option is set to true, the vertical display。
![image](https://cloud.githubusercontent.com/assets/12344794/19632275/8aeb1b4c-99d7-11e6-90a3-e3bceffbfb85.png)

**Comment by cjke** [comment]
I had a similar issue, the container element for the slider wasn't itself 100% width, so all the calculations were off. As a test, try removing the slider (temporarily) and check that where the slider would appear is actually the width you expect it to be.

**Comment by 727177817** [comment]
thanks, I have  been solved, body element set margin:0

**Comment by cjke** [comment]
No worries, easy easy
