### ISSUE TITLE
slickGoTo with infinite variableWidth images

### ISSUE THREAD

**Issue by davidwadge** [akiran/react-slick#317]
I would like the slickGoTo image to appear to the left or the centre of the users' screen when multiple images of different widths are displayed. Is this at all possible? My current settings are:

            infinite: true,
            speed: 500,
            arrows: true,
            adaptiveHeight: true,
            draggable: true,
            variableWidth: true,
            slickGoTo: this.props.index
`

**Comment by akiran** [comment]
slickGoTo is now change to method instead of prop.
Check this example https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

open a new issue if you are still facing issues with slickGoTo
