### ISSUE TITLE
Slider stays on same page if slides items are changed

### ISSUE THREAD

**Issue by jabhishek** [akiran/react-slick#319]
The subject line may not make sense, but I will try to explain the scenario in detail. See this example [fiddle](https://jsfiddle.net/jain208/20bumb4g/630/) to see the issue in action.

In this demo, initially the slider shows 20 slides (3 per page). The idea is that if you click the button, it will generate a random number, which would be the new number of slides. The code is fairly simple and self-explanatory.

To reproduce the problem, 
1. keep on clicking Next arrow until you reach the last slide.  
2. click on the button that says 'Click' to generate a new random number of slides.

My expectation was that the slide will go back to the first slide but not to stay on the page where it previously was. Even worse, if the new number of slides is lower than the previous number, the user will see a black page with no slides. On clicking Previous error, he/she can go to the previous slides, and everything works normally but the initial display ruins the user experience.

Is there something I am missing to add in the code, or is this a bug?

Thanks,
Abhi.

**Comment by psimyn** [comment]
you could use the `slickGoTo` prop after changing slides.

I think trying to handle this automatically could get complex (a lot of cases where the currently visible ones don't change but others do)
