### ISSUE TITLE
CommonJS/ES2015 support?

### ISSUE THREAD

**Issue by iamricky** [akiran/react-slick#326]
Does react-slick support ES6 syntax for `import` calls? If not, are there plans to implement proper CommonJS/ES2015 support in the near future?

e.g. `import Slider from 'react-slick'` in lieu of `const Slider = require('react-slick');`

**Comment by alexanderfrey** [comment]
it does

**Comment by iamricky** [comment]
@alexanderfrey Strange it didn't before but now it does. I ended up using another slider but this is good to know for future reference.
