### ISSUE TITLE
server data  coursel not working

### ISSUE THREAD

**Issue by aamirbhat** [akiran/react-slick#330]
react-slick carousel not working with server data

**Comment by alexanderfrey** [comment]
why ? what is the error message ?

**Comment by AlexanderCannonAcn** [comment]
I have noticed a similar issue; when I have a set up loading data asyncronously
loadItemsFromServer() {
return do.some.ajax;
}

itemNodes = loadItemsFromServer.map(function (item) {
  return (
    <div>
   <h3>{item.title}</h3>
   <img src={item.image}>
   </div>
      );
});
With a setup like;
return (
  <Slider {...settings}>
    {itemNodes}
  </Slider>
);
The slider doesn't acknowledge the nodes have been passed to it and it fails silently.

If I do:
  <Slider {...settings}>
    <div><h3>static thing</h3></div>
    {itemNodes}
  </Slider>
);
It renders the items properly with the static div as the first slide.
