### ISSUE TITLE
Button gets disabled too early

### ISSUE THREAD

**Issue by nielsdB97** [akiran/react-slick#331]
https://jsfiddle.net/eeky9n4a/

Press the _next_ button until it stops working.
The next button is being disabled before the last picture reaches the 'slick-center' position.
I looked at the code and it seems like this problem lies in arrows.jsx
```jsx
if (!this.props.infinite) {
    if (this.props.centerMode && this.props.currentSlide >= (this.props.slideCount - 1)) {
      nextClasses['slick-disabled'] = true;
      nextHandler = null;
    } else {
      if (this.props.currentSlide >= (this.props.slideCount - this.props.slidesToShow)) {
        nextClasses['slick-disabled'] = true;
        nextHandler = null;
  }
}
```
When I change it to this
```jsx
if (this.props.currentSlide >= (this.props.slideCount - this.props.slidesToShow))
```
it works, but then it breaks other scenario's, for example when you have less than 6 slides.

It would be great if this can be fixed soon so I can keep using this package in my projects!

**Comment by akiran** [comment]
This issue is fixed in latest release
