### ISSUE TITLE
Consider the non-integral `slidesToShow` case: Should these be merge to master?

### ISSUE THREAD

**Issue by pokka** [akiran/react-slick#340]
Hello:

While the `slidesToShow` is a numerical like:

```
settings = {
   slidesToShow: 1.5,
   ...
}
```

I need to Turn:
![2016-06-24 16 15 25](https://cloud.githubusercontent.com/assets/524319/16332158/16f1e5dc-3a27-11e6-8489-a8a385712227.png)

Into:

![2016-06-24 16 09 41](https://cloud.githubusercontent.com/assets/524319/16332195/513be30a-3a27-11e6-8d67-5fb82986a02d.png)

Maybe it's related to the `rtl`, but I haven't find a way to get that prop in `trackHelper`.

I wrote a commit for this(https://github.com/pokka/react-slick/commit/fe9396c0311d1a581d35783eb8eb4a2a36df2e28) (auto-generated files just for test)
Any help or just left them in my repo?

Thanks.

**Comment by akiran** [comment]
We don't want to support  non-interger slidesToShow. 

You can use centerMode and centerPadding options if you want to show part of other slides

**Comment by sanishkr** [comment]
[CodeSandbox](https://codesandbox.io/s/rough-wave-xyg9m?fontsize=14&hidenavigation=1&theme=dark)
@akiran , centerMode and centerPadding options does solve the issue but not in a responsive way. Any workarounds?
