### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by pixelatorz** [akiran/react-slick#351]
I am creating a slider it does render the component and the styles however I do get a js error:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

the code is:

```
render()
    {
        var settings = {
            dots: true,
            infinite: true,
            speed: 500,
            arrows: false,
            autoplay: true,
            slidesToShow: 3,
            centerMode: true
        };

        return (
            <Slider {...settings}>
            {
                ObjectToArray.toArray(this.props.winners).map(function (raw, i) {
                    let winnerData = raw.value;

                    return (
                        <div>
                            <Winner userName={winnerData.userName}
                                    sex="male"
                                    rank={winnerData.rank}
                                    game={winnerData.game}
                                    date={winnerData.createdOn}
                                    winnings={winnerData.winnings}
                                    userRank={winnerData.userRank}
                            />
                        </div>
                    );
                }.bind(this))

            }
            </Slider>
        );
    }
```

when dragging the items they seem to collapse and the following error occures:

recently-won.react.js:5636 Keys Missing Object {slideIndex: 0, trackRef: undefined, className: "", adaptiveHeight: false, arrows: false…}

any idea?

**Comment by gajmani** [comment]
Do we have the fix / workaround for this ?

**Comment by djbobbydrake** [comment]
Seeing the same issue. Any word?

**Comment by thomasmattheussen** [comment]
Also seeing this issue. I think it only occurs when the slides are dynamically generated.

**Comment by akiran** [comment]
Can everyone try solution provided in #328 fixes your issues as well.

If you still see this issue, can you provide a jsfiddle demo replicating the issue

**Comment by serheyShmyg** [comment]
#328 works https://jsfiddle.net/20bumb4g/1293/
But, you can clone children components and extend their props.
`
return React.Children.map(this.props.children, function(child) {
     return React.cloneElement(child, {key: 'value'
})
`

**Comment by guyalon** [comment]
i managed to sove it like this:
`<Slider ref="simpleSquare" {...settings}>
      {this.state.items || <div></div>}
</Slider>`

**Comment by shasha-signifai** [comment]
So I solved it like this:
<Slider {...settings}>
              <div><TestSlide /></div>
              <div><TestSlide /></div>
</Slider>

Wrap the dynamic slide component with <div></div>, such as <div><TestSlide /></div>

**Comment by RakeshBurde** [comment]
I have degrade the version of react-slick from 0.14.5 to 0.13.6. and it works for me.

**Comment by crw** [comment]
Ran into this issue, #328 "fixed" it for me as well.

**Comment by syakuis** [comment]
error.....  T.T
```
<Slider {...settings}>
  {list}
</Slider>

----- error log
Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null

```

not error!!! O_O
```
<Slider {...settings}>
  {list}
  <div></div> <--- why??? need??
</Slider>
```

**Comment by markmcdermid** [comment]
This was happening for me because I didn't pass anything to the <react-slick> component, so I just created a wrapper to check if no children are passed.

**Comment by markmcdermid** [comment]
On further inspection, it was when passing a react element rather than a DOM element, <CarouselItem> doesn't work but <div ...> does

**Comment by arjunskumar47** [comment]
Even though I have wrapped inner components inside `div`, I'm getting this error. 

The stack trace shows the parent call happened in `this.update()` invoked on `componentWillReceiveProps`.

Anyone facing similar issue? 

I tried to throttle CPU to test if it is related to performance, but no luck in reproducing.
