### ISSUE TITLE
Slick Go To - Not working expected

### ISSUE THREAD

**Issue by manimuthukumar6** [akiran/react-slick#356]
Slick Go To Slider & next arrows syncs not working properly.

Demo URL : 

http://webrafter.com/opensource/react-slick

Example : Slick Go To
Step 1 :

* track the slider -> active element is calculating wrongly.

![image](https://cloud.githubusercontent.com/assets/417217/16688740/137c8080-453d-11e6-8344-0faec9522d8d.png)

Step : 2

* After click the next arrow  translate position calculating wrongly because of last active item while dragging the Go To Slider.

![image](https://cloud.githubusercontent.com/assets/417217/16688923/f745f1f2-453d-11e6-8075-5457f40420f5.png)

**Comment by manimuthukumar6** [comment]
Getting blank space issue between the action of slider track and next for the first time. After that corresponding next click working fine. 

Only the problem is slider track and next button syncs.

**Comment by manimuthukumar6** [comment]
Any fix for this issue ?

**Comment by akiran** [comment]
slickGoTo is now change to method instead of prop.
Check this example https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

open a new issue if you are still facing issues with slickGoTo

**Comment by roopemerikukka** [comment]
The event value in https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js#L11 might be a string so you need to remember to parse the Integer out of it.
