### ISSUE TITLE
Bug with variableWidth and centerMode

### ISSUE THREAD

**Issue by bratva** [akiran/react-slick#357]
Hello!

I have slider with this options

```
var options = {
        infinite: false,
        variableWidth: true,
        centerMode: true
}
```

When i swipe last slide to left or first slide to right, the slider throw error `Cannot read property 'offsetWidth' of undefined`; in `getTrackLeft`

Demo https://jsfiddle.net/t1ovuve8/

**Comment by chrishinrichs** [comment]
+1

**Comment by nluck** [comment]
+1

**Comment by maximusnikulin** [comment]
+1

**Comment by roman-yakobnyuk** [comment]
Same here, it also occurs without infinite mode enabled, with just center mode.

**Comment by chrishinrichs** [comment]
Might want to give https://github.com/godaddy/react-img-carousel a try

**Comment by pjjanak** [comment]
@akiran - Has there been any movement on this? I'm experiencing a similar issue with variableMode = true and setting an intialSlide. Namely, the initial slide isn't brought into frame. Forcing an update after the component mounts makes it a little better, but the initial slide is still a little bit off.

It seems like you closed #325 which describes my issue marking it as a duplicate of this.

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.

**Comment by josephdonnelly** [comment]
Unfortunately this issue still exists:
https://codesandbox.io/s/7m0qow8l9j

**Comment by laveesingh** [comment]
The referenced commit should do it.
