### ISSUE TITLE
afterChange callback returns the previous slide index instead  of current slide index

### ISSUE THREAD

**Issue by jerson419** [akiran/react-slick#358]
afterChange callback returns the previous slide index instead 
of current slide index.

Just noticed that it happens only when fade is true

var settings = {
    	dots: true,
        fade: true,
        infinite: false,
       afterChange: function(currentSlide){
		    	      console.log(currentSlide);
		             }
}

See:
https://jsfiddle.net/20bumb4g/877/

**Comment by blairanderson** [comment]
https://jsfiddle.net/syz9z5wf/

**Comment by soutarm** [comment]
A fix for this was merged yesterday: https://github.com/akiran/react-slick/pull/224

**Comment by akiran** [comment]
Yes, this fixed in master
