### ISSUE TITLE
Is there an easing example?

### ISSUE THREAD

**Issue by forthedamn** [akiran/react-slick#363]
Excuse me, but I didn't find an easing example in docs.

The only message i have got now is that easing need a String param.

**Comment by iblack10** [comment]
I don't think the 'easing' property has been implemented yet. However, you can use CSS easing by using 'cssEase':

cssEase: 'ease'in'

or 

cssEase: 'cubic-bezier(0.165, 0.840, 0.440, 1.000)'

https://developer.mozilla.org/en/docs/Web/CSS/transition-timing-function is a good reference for CSS easing options and also http://easings.net/ has a list of other common easing functions and how to represent them in CSS using cubic-bezier.

**Comment by laveesingh** [comment]
We do have `cssEase` prop. Please feel free to clarify further and request reopen if disagree.

**Comment by processprocess** [comment]
The ease prop is incorrect in the docs.

It's currently listed as 'easing' and needs to be 'cssEase'. 
https://react-slick.neostack.com/docs/api#easing

I'm happy to update that but I don't know how to contribute to that page.
Thanks for your great carousel! I use it daily.

**Comment by tomasdev** [comment]
Why is this even closed? documentation is wrong and the doc link is not in this repo.

**Comment by n0umankhan** [comment]
@laveesingh please reopen this issue as it is not resolved yet. 

> I don't think the 'easing' property has been implemented yet. However, you can use CSS easing by using 'cssEase':
> 
> cssEase: 'ease'in'
> 
> or
> 
> cssEase: 'cubic-bezier(0.165, 0.840, 0.440, 1.000)'
> 
> https://developer.mozilla.org/en/docs/Web/CSS/transition-timing-function is a good reference for CSS easing options and also http://easings.net/ has a list of other common easing functions and how to represent them in CSS using cubic-bezier.

cssEase propety exist this answer is correct
