### ISSUE TITLE
Modals & Router support

### ISSUE THREAD

**Issue by oyeanuj** [akiran/react-slick#369]
Hi @akiran! Thank you for the component. I was planning to use Slick as a slides/lightbox, so this component is perfect. For the v1.0 - I was wondering if there are any plans to support router support, i.e., update url when navigating from left to right? 

Thank you!

**Comment by akiran** [comment]
There beforeChange and afterChange options to implement features like this in your project 
check this example
https://github.com/akiran/react-slick/blob/master/examples/SlideChangeHooks.js
