### ISSUE TITLE
How to override react-slick style in component css file?

### ISSUE THREAD

**Issue by AzrielLiang** [akiran/react-slick#371]
Here are the [specifics](https://github.com/davezuko/react-redux-starter-kit/issues/930).

**Comment by akiran** [comment]
It is better to ask about using css-module in stackoverflow

**Comment by alduro** [comment]
I'm having the same issue. https://github.com/akiran/react-slick/issues/675.

**Comment by akhilalekha** [comment]
Same issue. And it's weird that all the styles are inline in the library. I just can't seem to override the image container width! Please explain how can I override anything if all styles are inline?
