### ISSUE TITLE
support for modular css

### ISSUE THREAD

**Issue by vgrafe** [akiran/react-slick#373]
I've been struggling to add this component to a reactjs project basing styling on modular css, so I started hacking around. This is definitely not PR worthy at this point, so I here is an issue. 
The concept is very simple: get rid of `classnames` and `import` the css instead.

[The branch is here](https://github.com/vgrafe/react-slick/tree/modular_css), feel free to participate/criticize.

Shortcomings:
* I removed all fonts referenced in css
* I merged the theme into the base css file
* the dots won't work

I'd love to provide a decent PR, but won't spend much more time if no one shows interest.

**Comment by akiran** [comment]
We may not support this at the moment.
