### ISSUE TITLE
Slick carousel in two rows left to right

### ISSUE THREAD

**Issue by 2505rathod** [akiran/react-slick#376]
I need to make a two lines carousel with left to right order (also responsive).

![demo](https://cloud.githubusercontent.com/assets/20612450/17077894/202f9726-5100-11e6-8736-6159916a7667.jpg)

I have used below code but it is not working
$('.carousel').slick({
    dots: true,
    **slidesPerRow: 3,
    rows: 2,**
    responsive: [
    {
      breakpoint: 478,
      settings: {
        slidesPerRow: 1,
        rows: 1,
      }
    }
  ]
});

**Comment by blairanderson** [comment]
the jquery library is https://github.com/kenwheeler/slick/

this repo is for react.

**Comment by blairanderson** [comment]
@akiran can probably close this

**Comment by tumblermonkey** [comment]
How can I fill the empty rows with the first images @blairanderson ?

**Comment by blairanderson** [comment]
Use google and stack-overflow
