### ISSUE TITLE
Add dotsActiveClass

### ISSUE THREAD

**Issue by suhaotian** [akiran/react-slick#379]
it's useful in css module

**Comment by akiran** [comment]
slick-active class is already added to active dot.
You can use that for styling

**Comment by mmazzarolo** [comment]
Hi @akiran, I think that what @suhaotian wanted to achieve was adding a a prop `dotActiveClass` to the repo, because currently if you use `css-modules` you can't target the `slick-active` classname easily (with css-modules the classname are hashed and you can't reference them directly).  
Would a PR for this feature be accepted?

**Comment by akiran** [comment]
There are other classes as well which are added by slick. I am not sure if it is a good idea to add a new prop each one of them.

I will think about clean way to support css-modules and get back to you.

**Comment by mmazzarolo** [comment]
That's a good point.  
Thank you for re-opening the issue and for the fast answer.

**Comment by sunnyvempati** [comment]
+1 to this.

**Comment by sunnyvempati** [comment]
@suhaotian did you come up with a solution for this? @mmazzarolo ?

**Comment by amerllica** [comment]
Two years past but and simple prop `activeClassName` not added to project, big shame.

**Comment by flavioribeirojr** [comment]
I've written an workaround for this. If you need to use css modules you can create new React elements based on the dots provided on the `appendDots` callback:

```js
function CustomDots(dots) {
  const customDots = dots
    .map(dot =>
      React
        .createElement(
          dot.type,
          {
             ...dot.props,
             className: dot.props.className === 'slick-active' ? styles.slickActive : ''
          },
          dot.props.children
      ))

      return (
        <ul> { customDots } </ul>
      )
}
```

**Comment by Rutvij07** [comment]
> slick-active class is already added to active dot. You can use that for styling

No that is not
