### ISSUE TITLE
Click Events on Child Items Not Firing - iOS (Desktop Browsers working as intended)

### ISSUE THREAD

**Issue by merlinf14b** [akiran/react-slick#38]
Slider portion works great, but any buttons that are within the panes are having their click events trapped.  I attempted to turn off the swipe detection, but that also didn't allow clicks to go through.  Any thoughts?
```
var Slick = require('react/react-slick');
React.createElement(Slick, {},
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'one'),
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'two'),
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'three'),
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'four'),
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'five'),
     React.DOM.button({onClick: function() {console.log('does this work??');}}, 'six')
)
```

**Comment by haohcraft** [comment]
Ran into the same issue

**Comment by haohcraft** [comment]
Related to https://github.com/kenwheeler/slick/issues/412

if we upgrade the slick version we are using here, it would fix

**Comment by yankrasny** [comment]
I've run into the same issue. On desktop, onClick events work as expected, but on mobile (whether in the chrome simulator or on an actual phone) onClick events don't go through. Thinking that this may have been related to https://github.com/facebook/react/issues/1169, I added cursor: pointer on all clickable elements, but that did not solve the problem.

**Comment by vramana** [comment]
@yankrasny Can you make a gist or jsfiddle? From which I can reporduce this issue? It will help a lot.

**Comment by yankrasny** [comment]
@vramana sure, I'll try to get you an example later today. Thanks for the quick response.

**Comment by yankrasny** [comment]
Hey @vramana, here are the jsfiddles for desktop and mobile.

Desktop: https://jsfiddle.net/yankrasny/hug2f0r1/6/
Mobile (access from a mobile or a simulator, I used chrome): https://jsfiddle.net/m/rvt/ 

The behavior is to display the link that was last clicked as proof that the onClick event went through. It works on desktop but not on mobile. 

You'll also notice that on desktop, clicking any of the slides brings you back to the first one. I believe @haohcraft is right and this may be related to https://github.com/kenwheeler/slick/issues/412.

**Comment by stevemckenzie** [comment]
This is also happening for me.

**Comment by stevemckenzie** [comment]
@akiran any update on this?

**Comment by akiran** [comment]
@stevemckenzie  Can you test the fix in 0.6.1 version

**Comment by yankrasny** [comment]
Just tested version 0.6.1 and the issue appears to be fixed. Thank you!

**Comment by stevemckenzie** [comment]
Thank you @akiran ! This definitely fixes the ability to touch links in slides.

I thought this was going to fix the automatically scrolling back to the first item when you start scrolling the page issue too but it didn't.

**Comment by akiran** [comment]
@stevemckenzie  Can you open a separate issue for the scrolling issue.

**Comment by gus4no** [comment]
how can I get version 0.6.1 with this fix? Available versions using bower are 0.5.0, 0.4.1 and 0.3.1

**Comment by akiran** [comment]
I created a github release with 0.6.4 version.

Now you should be able to get it from bower

**Comment by gus4no** [comment]
Thank you very much! @akiran
