### ISSUE TITLE
React-Slick is not being styled

### ISSUE THREAD

**Issue by teckore** [akiran/react-slick#381]
Hi,
I was just playing around with react-slick and I've  run into an issue whereby there is no styling at all on the carousel. I've also put the CDN link for the CSS in the header of my index.html file. Functionality wise, the dots are clickable and they do change the slides. 

Thank you.

Currently, it looks like the following:
<img width="616" alt="screen shot 2016-07-26 at 12 46 30 pm" src="https://cloud.githubusercontent.com/assets/19312202/17152933/0a3d8e9c-532f-11e6-9781-dd1646102953.png">

**Comment by akiran** [comment]
Can you paste your code snippet here

**Comment by teckore** [comment]
Here is the code for the Carousel itself:



```
import React, { Component } from 'react';
import Slider from 'react-slick';

var SingleItem = React.createClass({
  getInitialState: function () {
    return {count: 6};
  },
  click: function () {
    this.setState({count: this.state.count + 1});
  },
  render: function () {
    var settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1,
      waitForAnimate: false,
      beforeChange: function (currentSlide, nextSlide) {
        console.log('before change', currentSlide, nextSlide);
      },
      afterChange: function (currentSlide) {
        console.log('after change', currentSlide);
      },
    };
    return (
      <div>
        <h2> Single Item</h2>
        <Slider {...settings}>
          <div key={1} onClick={this.click}><h3>{this.state.count}</h3></div>
          <div key={2}><h3>2</h3></div>
          <div key={3}><h3>3</h3></div>
          <div key={4}><h3>4</h3></div>
          <div key={5}><h3>5</h3></div>
          <div key={6}><h3>6</h3></div>
        </Slider>
      </div>
    );
  }
});

module.exports = SingleItem
```

In another file where I am calling the carousel is as follows:


```
import React, {Component} from 'react';
import SingleItem from '../CarouselTest/CarouselTest'

export default class Carousel extends Component {
	render(){
		return(
			<div>
				<SingleItem />
			</div>
		)
	}
}
```

I also have these two CDN's in my index.html as well:
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Kit</title>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css" />
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick-theme.css" />
		
	</head>
	<body>
		<div id="app"></div>
	</body>
</html>

```
I am also using Material-UI with my project, I am not sure if that affects the carousel in any way. 
Thanks!

**Comment by kellyrmilligan** [comment]
same issue here, must be missing something in the setup.

**Comment by teckore** [comment]
Could it be something to do with the webpack configuration?

**Comment by kellyrmilligan** [comment]
I partially solved my issue. I had a map that was returning a component with a classname. I wrapped it in a plain old div, and this allowed the containers to have the slick-slide class.  the adaptive height I am going to try next. I think that's a setting. 

code: 

```
<Carousel {...settings}>
              {stuffs.map((stuff, i) => {
                return (
                  <div key={i}>
                    <Component
                      className="stuff class"
                      {...props}
                      />
                  </div>
                )
              })}
            </Carousel>
```

I used to just have the Component className="stuff class" as the return.

**Comment by akiran** [comment]
You check how demos in this repo are working

you clone this repo,
npm install 
npm start
open http://localhost:8080 to see the demos
