### ISSUE TITLE
centerMode does not show parts of next and previous slides

### ISSUE THREAD

**Issue by dariobanfi** [akiran/react-slick#382]
Hi,

Slick carousel center mode shows part of next slides in the following examples: http://kenwheeler.github.io/slick/ (See center mode example). However I cannot manage to replicate this behavior with react-slick, using the same settings of the example.

Is this behavior being modified on purpose, or a pull request is welcome?

**Comment by akiran** [comment]
yes, need to implement centerPadding option.
PR is welcome

**Comment by grossmail1** [comment]
I was just able to implement this recently.  Here are the settings I used.

```	var settings = {
		adaptiveHeight: true,
		arrows: true,
		autoplay: true,
		centerMode: true,
		dots: false,
		infinite: true,
		initialSlide: 1,
		nextArrow: <RightNavButton/>,
		prevArrow: <LeftNavButton/>,
		responsive: [
			{
				breakpoint: 550,
				settings: {
					slidesToShow: 1,
					variableWidth: false
				}
			}
		],
		slidesToShow: 3,
		speed: 1000,
		variableWidth: true
	}
```
I think the trick is centering with variable width.  It does mean that you have to set a size for the slides though.
![fullscreen_7_27_16__8_52_am](https://cloud.githubusercontent.com/assets/7915574/17179757/8a8de1a2-53d7-11e6-8020-41feb7542342.jpg)

**Comment by dariobanfi** [comment]
Hey @grossmail1 , I tried your method and it's quite clever. However don't you have a bug with the first time you slide, where the first one is empty (regardless of initialSlide) and when going to next multiple are skipped at the same time?

**Comment by dariobanfi** [comment]
For example here: https://jsfiddle.net/ambigioz/1fmxsohh/

**Comment by grossmail1** [comment]
I may. I just don't think I noticed it with autoplay: true

**Comment by sauravskumar** [comment]
@grossmail1 @dariobanfi @akiran  were you able to come up with a solution with no bugs? I am facing the same issue and need help.

**Comment by dariobanfi** [comment]
I didn't find a solution yet..

**Comment by renddiyeh** [comment]
my [PR](https://github.com/akiran/react-slick/pull/396) is just been merged.
now centerMode with centerPadding should be worked with the latest version `v0.12.3`

**Comment by sauravskumar** [comment]
@renddiyeh any examples?

**Comment by renddiyeh** [comment]
@sauravskumar here it is https://renddiyeh.github.io/react-slick/ , you can check the centerMode section.

slisk has a default `centerPadding = 50px` setting, so we just need add `centerMode: ture` setting to make it work.
