### ISSUE TITLE
How to use React-Slick!

### ISSUE THREAD

**Issue by leekang** [akiran/react-slick#387]
Today,I want to do a HTML5 application.And i write my program according to the example of the README.md However it does't work.There is my code:
`import React, { Component } from 'react'
import Slider from 'react-slick'
export default class Banners extends Component {
	render() {
		let	settings = {
	      dots: true,
	      infinite: true,
	      speed: 500,
	      slidesToShow: 1,
	      slidesToScroll: 1,
	      vertical:false
	    };
		return (
			<div style={{width:screen.width,height:screen.height*0.2}}>
				<Slider {...settings}>
		                <div><h3>1</h3></div>
		                <div><h3>2</h3></div>
		                <div><h3>3</h3></div>
		                </Slider>
			</div>
		)
	}
}
`
And import it in another code:
`import React, { Component } from 'react'
import Banners from './components/banners'
import Apps from './components/apps'
export default class Home extends Component {
	render() {
		return (
			<div>
				<Banners />
				<Apps />
			</div>
		)
	}
}
`

**Comment by akiran** [comment]
Check out readme and demos.jsx in docs folder
