### ISSUE TITLE
Custom next/next arrows disabled

### ISSUE THREAD

**Issue by will88** [akiran/react-slick#388]
Hi, Do you know if there is a way to add the "slick-disabled" class in order to hide the Custom next/prev arrows? I need it for a responsive carousel.

Thanks

**Comment by blairanderson** [comment]
the next/prev arrows are provided `className` props which include `slick-disabled` if it is disabled.

**Comment by will88** [comment]
@blairanderson Ok but how can I access to this `slick-disabled`, I mean how can I edit this for my custom next/prev arrows? Is it just css/sass?

**Comment by giladbr** [comment]
Worked like a charm, though I didn't see any other documentation about it. Also, I found that once I did:

```
let NextArrow = ({ onClick, **className**}) => (
    <div **className={className}**>
```

I had to add the following CSS:
```
.slick-arrow {
    position: absolute;
    color: $colorBlue;
    cursor: pointer;
    @include calc(top, "((100% - 1em)/2)");
    **&:hover i:before {
        color: $colorBlue!important; //otherwise it becomes white on hover...
    }**
}
```
I guess it's just the default styling which I don't know another way to override.



 need to do something like:
