### ISSUE TITLE
SlickGoTo Explanation

### ISSUE THREAD

**Issue by mxmtsk** [akiran/react-slick#389]
Hi,

how would I access the Slider to call slickGoTo from outside? I wanna slide to a certain slide on a Button Click?

Thanks!

**Comment by saharhashai** [comment]
Just set slickGoTo variable in your onClick() handler
this.setState({slickGoTo: slideIndex})

of course, don't forget to initialize slickGoTo to 0 on ctor -
this.state = {
      slickGoTo: 0    
}

and in settings - 
var settings = {
     ...
      slickGoTo: this.state.slickGoTo
}

**Comment by akiran** [comment]
You can check this example
https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js
