### ISSUE TITLE
have an issue using react-slick with Gulp TypeError: Object reactify,[object Object] has no method 'match'

### ISSUE THREAD

**Issue by StevenIseki** [akiran/react-slick#39]
I was trying to use react-slick and ran into the following issue trying to use it with the reactify transform using browserify.

TypeError: Object reactify,[object Object] has no method 'match'

Here is my gulpfile: I was using gulp-browserify which could be the issue. I am going to try using it with vinyl-source-stream as I know this is the correct way to use browserify with gulp, and will report back if it fixes the issue.

    var gulp = require('gulp'),
          browserify = require('gulp-browserify'),
          reactify = require ('reactify');

    gulp.task('scripts', function () {
      var bundles = ['app/client/slider.js' ];
      return gulp.src(bundles)
        .pipe(browserify({
            debug: true,
            transform: [reactify]
        }))
        .pipe(gulp.dest('./public/scripts/'));
    });

I was just using the demo Slider example from the [react-slick github readme](https://github.com/akiran/react-slick)

**Comment by akiran** [comment]
This issue is fixed in react-slick 0.5 by providing transformed js files
