### ISSUE TITLE
Weird behavior of slick-slide width

### ISSUE THREAD

**Issue by Anshul-HL** [akiran/react-slick#391]
The width of the slides inside the carousel is large ie doesn't display according to the specified 'slidesToShow' on initial load but when I resize the window the slides' width is adjusted properly.
Attached are the images for reference.
1)On first load(Incorrect)
![1](https://cloud.githubusercontent.com/assets/12951443/17384754/cd0e2e72-59fb-11e6-9450-1799d1220878.png)
2)After I resize the window(correct)
![2](https://cloud.githubusercontent.com/assets/12951443/17384763/d88b92f8-59fb-11e6-8f29-321b6b87888a.png)

**Comment by akiran** [comment]
Can you reproduce this issue with this https://jsfiddle.net/kirana/20bumb4g/  jsfiddle and reopen the issue

**Comment by form3** [comment]
I have the same issue 
https://jsfiddle.net/20bumb4g/1429/

**Comment by hackhat** [comment]
+1 same issue here. I have it in 2 places and I don't know why in one place works fine and in another only works fine after the window is resized.

**Comment by hackhat** [comment]
Ok, so this only happens when the container of the slick-react has a margin.

**Comment by JetFault** [comment]
This issue should be re-opened. And yeah when I remove the margin of the container of the slick element, it fixes itself.

**Comment by hayyaun** [comment]
> +1 same issue here. I have it in 2 places and I don't know why in one place works fine and in another only works fine after the window is resized.

me too
