### ISSUE TITLE
Inline Navigator

### ISSUE THREAD

**Issue by dhruvdutt** [akiran/react-slick#395]
Please consider adding an option for inline navigation inside image similar to this:
`https://github.com/xiaolin/react-image-gallery/raw/master/example/image_gallery.gif`

**Comment by akiran** [comment]
I am getting 404 for the link you provided

**Comment by dhruvdutt** [comment]
@akiran 
Please refer here:
[https://github.com/xiaolin/react-image-gallery/raw/master/static/image_gallery.gif](url)
