### ISSUE TITLE
How could I put links on different slides?

### ISSUE THREAD

**Issue by poc7667** [akiran/react-slick#403]
I want to make each slide can have different hyper link, but it didn't work.
Sometimes the order is in correct.
the first slide should trigger this.yoyo but sometimes it will trigger this.yoyo2

            <div>
              <Slider {...settings} className="slider-portal-container">
                <div key={1}  onClick={this.yoyo}> <img className="slider-portal-img"
                src="img/slides/slide_1.jpg"  />
                  <h3　className="slider-portal-text" onClick={this.yoyo}>一起買更便宜</h3>
                </div>

                <div key={2}> <img className="slider-portal-img" src="img/slides/slide_2.jpg"  onClick={this.yoyo2}  />
                    <h3　className="slider-portal-text"  onClick={this.yoyo2}>說走就走</h3>
                </div>
              </Slider>
            </div>

**Comment by akiran** [comment]
It is working.
Check this demo 
https://jsfiddle.net/20bumb4g/1126/
