### ISSUE TITLE
Bug: the text on image  sliders are synchronized

### ISSUE THREAD

**Issue by poc7667** [akiran/react-slick#404]
When you click  text `111` it should trigger `this.yoyo` but it triggers `this.yoyo2`.

When you click  text `222` it should trigger `this.yoyo2` but it triggers `this.yoyo`.

Strange bug~~ please fix it thank you.

    class App extends React.Component {

        yoyo() {
          console.log("111")
        }
        yoyo2() {
          console.log("222")
        }
        render() {

            var settings = {

            }

            return (
                  <Slider {...settings} className="slider-portal-container">
                    <div>
                      <h3　className="slider-portal-text" onClick={this.yoyo}>111</h3>
                      <img className="slider-portal-img" src="img/slides/slide_1.jpg" />
                    </div>

                    <div>
                      <h3　className="slider-portal-text" onClick={this.yoyo2}>222</h3>

                      <img className="slider-portal-img" src="img/slides/slide_2.jpg" />
                    </div>
                  </Slider>
            )
        }
    }

**Comment by akiran** [comment]
It could be problem with your css
