### ISSUE TITLE
the way of beforeChange being called

### ISSUE THREAD

**Issue by silentcloud** [akiran/react-slick#415]
How can I known which is the way (swipe or click dots) of `beforeChange` or  `afterchange`  being called?

Can you add an argument for `beforeChange` & `afterchange` func? like:

``` javascript
beforeChange(current, next, swiper: boolean) {
   // some code with `swiper` argument
}
```

**Comment by akiran** [comment]
What is you usecase for this feature ?

We are closely following the original slick api
http://kenwheeler.github.io/slick/

We want to keep the API simple and don't want to expand API unless we have strong reason to do so

**Comment by akiran** [comment]
@silentcloud  I think it will be better if we leave the beforeChange as it is and implement new callback method called onSwipe which is called after swipe

**Comment by HTaiNguyen** [comment]
Did you implement onSwipe yet ?

**Comment by laveesingh** [comment]
The `onSwipe` event has been implemented.

**Comment by laveesingh** [comment]
Not sure what you're complaining about. onSwipe works fine for me. Make sure you're using the latest version. And if you still have it, try replicating the issue with codesandbox demo.

**Comment by vieckys** [comment]
Ok so now i have got the way around this. Can you tell me how to get swipe direction on afterChange event ?

**Comment by laveesingh** [comment]
First of all, onSwipe gets a direction parameter, it's called like: onSwipe = direction => {....}.
Second, afterChange gets an index parameter, it's called like: afterChange = slideIndex => {...}.
So you can check with previous index and current index to know the direction.
