### ISSUE TITLE
Make slickGoTo not state based

### ISSUE THREAD

**Issue by JeSuis** [akiran/react-slick#421]
Doing this would open up the door to more implementations.

Since this is currently state based, you must always go to a different slide number.

Here's a scenario.
You have a restart gallery button, that button would only work once because, if the user used the arrows to navigate away, slickGoTo state is already at 1 if they try to trigger it again.

If this would be considered I can look into possibilities.

**Comment by akiran** [comment]
slickGoTo is now change to method instead of prop.
Check this example https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

Invoking slickGoTo method will have no effect if the user is already in the slide that is passed to slickGoTo method
