### ISSUE TITLE
Slider single slide onClick event ES6

### ISSUE THREAD

**Issue by Riccardo-Zanutta** [akiran/react-slick#424]
Hello, I've some troubles attaching a `onClick` event to the slides.
I didn't notice any advise in the console.
I tried to make also: `{() => console.log('ehi')}` inside the onClick handler but didn't work.
Any clue about how to resolve?
Thanks

![schermata 2016-08-19 alle 13 42 50](https://cloud.githubusercontent.com/assets/8215555/17808873/eec6948c-6612-11e6-94f9-766f0b81e6e6.png)

**Comment by xuchaobei** [comment]
I also meet this issue. Really a confusing thing while v0.12 works fine.

**Comment by trailingend1992** [comment]
@Riccardo-Zanutta I am experiencing the same issue. However for now it works for me to add event listener to any element inside the wrapper div. E.g. if you write, the event listener will run 
```
<div className="single-artwork-slide">
  <div data-image={"http://unsplash.it/650/400"} onClick={this.changeMainImage} style={{backgroundImage: url(${urlYouDontCare})}}></div>
</div>
```

**Comment by akiran** [comment]
Are you facing this issue on mobile or desktop browser ?

**Comment by trailingend1992** [comment]
desktop, hav'nt test on mobile yet

**Comment by Riccardo-Zanutta** [comment]
@trailingend1992 thanks! Moving the event listener to any element inside the div works. Facing the issue on desktop browser (chrome last versione for mac) , haven't tested on mobile yet.

**Comment by Riccardo-Zanutta** [comment]
@trailingend1992 thanks! Moving the event listener to any element inside the div works. Facing the issue on desktop browser (chrome last versione for mac) , haven't tested on mobile yet.

**Comment by xuchaobei** [comment]
@akiran both on mobile and desktop.

**Comment by Eschon** [comment]
I'm having the same problem

Here's a fiddle with react-slick 0.12.1 that works:
https://jsfiddle.net/Eschon/322u60ae/1/

And here's another one with 0.13.1 that doesn't:
https://jsfiddle.net/Eschon/322u60ae/2/

**Comment by akiran** [comment]
Recent addition focusOnSelect is overriding the click handler.
I will fix this soon

**Comment by HunterManhart** [comment]
I am also having trouble with the onClick event.  My handler function calls with onMouseOver, but not with onMouseDown and onClick. I tried making focusOnSelect: false, but that didn't change anything.

I have only tested this on desktop in Chrome.

**Comment by carlosloaiza21** [comment]
i had the same problem but i resolved whit this way:
the wrapper has the onclick and i generate a reference:
<img width="420" alt="captura de pantalla 2017-11-14 a la s 09 47 21" src="https://user-images.githubusercontent.com/2198709/32789301-19f4e4c0-c921-11e7-8099-2e471555b1b4.png">

then: i get the index in seleccion metod: 
<img width="455" alt="captura de pantalla 2017-11-14 a la s 09 51 45" src="https://user-images.githubusercontent.com/2198709/32789444-7a06795a-c921-11e7-9734-2837f8f9486e.png">
because i have the reference i can have access to all the slick context

**Comment by renerubio** [comment]
I have a solution with the Lifecycle "componentDidMount" i know is not the ideal but works!
1. the item slide : `<img className="class-img" src={myUrl} data-id={dataId} />);`
2. in componentDidMount : `this.handlerBindClickImage();`
3. in handlerBindClickImage : ```
$(".class-img").on("click",(e)=>{           
     this.myHandler(e.target.dataset.id) 
});
```

**Comment by vaibhavi3t** [comment]
I have the same issue with the latest version 0.23.2 . but working fine with 0.14.11 for me.

**Comment by TinyChou** [comment]
I just bind an onClick listener to every item dom element.But when `beforeChange` event fired, we should disable the item onClick and then `afterChange` recover the listener.

```js
const SimpleSlider = (props) => {
  const { onChange, imageUrlsList, onItemClick } = props;
  const [index, setIndex] = useState(0);
  const [clickable, setClickable] = useState(true);
  const onSliderChange = (newIndex) => {
    setClickable(true);
    setIndex(newIndex);
    onChange(newIndex);
  };
  const options = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,

    centerPadding: 0,
    centerMode: false,
    afterChange: onSliderChange,
    beforeChange: () => setClickable(false),
  };

  return (
    <Slider {...options}>
      {
        imageUrlsList.map((image, idx) => (
          <div className='slider-container'>
            <img onClick={() => clickable && onItemClick(idx) } className='slider-img' width='100%' height='500px' src={image} alt='' />
          </div>
        ))
      }
    </Slider>
  );
};
```
