### ISSUE TITLE
@initialSlide not working

### ISSUE THREAD

**Issue by yiooxir** [akiran/react-slick#427]
When I try to change @initialSlide property dynamically, nothing happens. I expect that specified slide should be the first one in a visible section. Or am I wrong ?

Here is [jsFiddle example](https://jsfiddle.net/yiooxir/L4entnr9/1/)

**Comment by akiran** [comment]
InitialSlide works on initial mount and cannot be changed latter.

I am implementing a method called slickGoTo to dynamically change slides.
It will be ready in 1 or 2 days

**Comment by yiooxir** [comment]
Ohh, that is awesome !!! It is a critical point in my project now. Looking forward to it.
