### ISSUE TITLE
Missing some styles when install slick-carousel as bower component

### ISSUE THREAD

**Issue by catcheshirecat** [akiran/react-slick#428]
Hi! I've noticed that slick.css is missing styles for arrows and dots (and doesn't matches the file from cdn - https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css

**Comment by akiran** [comment]
You have to add slick-theme.css as well

```<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />```
