### ISSUE TITLE
Adding a post init callback inside inner-slide

### ISSUE THREAD

**Issue by gkilian** [akiran/react-slick#429]
Currently we're running  `initialize()` and then `adaptHeight()` in the `componentDidMount` of `inner-slide.jsx`. 

**Issue:**  For a second or two, while we are adapting the height of the `inner-slide`, the component's height is 100% the height of the stack of slides and then they snap into place.

![images-stacked](https://cloud.githubusercontent.com/assets/801136/17866089/38cf139e-6873-11e6-80dd-83b0e3e40d3c.png)

**Proposed solutions**
1. Add a `postInit` callback after `adaptHeight`, so the user can do what they need after (_eg. show the slider_)
2. Or add an initialized class to the component after we adapt the height, similar to what we do with `slick-slider`.

**Comment by nmynarcik** [comment]
Can the CN fix referenced above be applied to this project?

**Comment by gkilian** [comment]
@nmynarcik - It can! It's the first proposed solution above.

**Comment by nmynarcik** [comment]
this has been a hurdle for me, since I have this lib inside of a ReactTransitionGroup and it prevents proper animation since the DOM is being adjusted during the parent transition. So I need a way to tap into after its been initiated so I can fade it in.

**Comment by gkilian** [comment]
@nmynarcik - Sorry for the long wait. I have some time to add PRs to this repo, so hopefully this works and is accepted. 

https://github.com/akiran/react-slick/pull/1013

**Comment by laveesingh** [comment]
Can't support props that deviate from slick.
If you want this issue open please regenerate the problem on codesandbox.

**Comment by gkilian** [comment]
@laveesingh - The only other approach that doesn't require an additional prop would be to add a classname, similar to what `initialize()` does to `adaptHeight()`.
