### ISSUE TITLE
Support for lazyLoad?

### ISSUE THREAD

**Issue by mattjstar** [akiran/react-slick#43]
I noticed you commented out lazyLoad in default-props.js. Will there be support for this in the future?

Thanks!

**Comment by akiran** [comment]
yes

**Comment by mattjstar** [comment]
I want to start looking into this to use it and potentially fix it myself. Do you have any context as to why this feature was disabled?

thanks!

**Comment by akiran** [comment]
This feature is not yet implemented.
We are thinking about implementing it.

We will be happy if you can submit a pull request with fix

**Comment by vramana** [comment]
@mattjstar I am working this feature will land in a day or two.

**Comment by mattjstar** [comment]
Thanks Vramana

**Comment by mattjstar** [comment]
@akiran Do you have any sense when you might publish the lazyload code in as a new version? Thanks!

**Comment by akiran** [comment]
It might take a week.  We are adding lot of other features as well. 
We will test it thoroughly and then publish

**Comment by mattjstar** [comment]
great thanks!
