### ISSUE TITLE
prevArrow render order

### ISSUE THREAD

**Issue by Eschon** [akiran/react-slick#436]
Since I updated react-slick the order of elements in the DOM changed. Before the update (v 0.12.2) I got 
```
<div class="slick-list">...</div>
<span class="left-button">...</span>
<span class="right-button">...</span>
```

Now after the Update I get
```
<span class="left-button">...</span>
<div class="slick-list">...</div>
<span class="right-button">...</span>
```
Usually this wouldn't be a problem but I have the buttons inside the slider over the image and the change causes the left button to be behind the images.

I know that this can be easily fixed with `z-index` but it still is mildly inconvenient.

**Comment by akiran** [comment]
This might have happened during a refactor.

Current ordering is more semantic. 
I think, it is better to fix the issue you have with css
