### ISSUE TITLE
children onClick no longer works

### ISSUE THREAD

**Issue by Eschon** [akiran/react-slick#437]
I have a click handler on the children of my slider. Up until recently this worked fine but after I last updated react-slick it stopped working.

Here's a fiddle with react-slick 0.12.1 that works:
https://jsfiddle.net/Eschon/322u60ae/1/

And here's another one with 0.13.1 that doesn't:
https://jsfiddle.net/Eschon/322u60ae/2/

**Comment by akiran** [comment]
Duplicate of #424

**Comment by Eschon** [comment]
Oh sorry I've overlooked that. 
I posted my fiddles there
