### ISSUE TITLE
No way to set initialSlide or slickGoTo Responsively

### ISSUE THREAD

**Issue by dougmacklin** [akiran/react-slick#438]
Now that `slickGoTo` is now a [method instead of a prop](https://github.com/akiran/react-slick/issues/295#issuecomment-241773206), and since [initialSlide does not work as a responsive attribute](https://github.com/akiran/react-slick/issues/282#issuecomment-207693418), there is no longer a way to set the first slide shown to different values responsively.

For example, say I have a carousel with 3 visible slides where the middle (index 1) is the main focal point: `slidesToShow: 3, initialSlide: 0`. On mobile there is only space for one slide, however, so I would like to have `slideToShow: 1, initialSlide: 1`.

This works fine with the original slick.js (refresh after adjusting your screen width): http://codepen.io/anon/pen/pbXOLB

However it does not work with react-slick. Let me know if there's a workaround for this, as previously I would use `slickGoTo` when it was a prop. I think it would make sense to set `initialSlide` at the initial mount based on whatever the current responsive breakpoint is.

**Comment by kevindavis** [comment]
+1

I'm pretty new to React so wasn't sure if I wasn't understanding something. I still might be able to accomplish this another way :)

My scenario is a bit different than the responsive case - I'm using the carousel to have folks select a few different things. When they're ready to move onto selecting the next thing I send different properties to the carousel. Rather than start at the first slide, it starts at the index the user had scrolled to in the previous step. Is there another way I could be doing this?

**Comment by dougmacklin** [comment]
Hey @kevindavis, are you saying you'd like to switch the index back to the first slide after something else in your script? If so, then that is separate from this issue and should be fairly easy to accomplish using `slickGoTo`. Make sure you are updated to the latest version of react-slick and then give your Slider a [ref attribute](https://facebook.github.io/react/docs/more-about-refs.html), for example 'slider', and call `this.refs.slider.slickGoTo(0);`. This will take your slider back to the first slide (index 0).

Here is an example of this in action, in this case using an input slider to trigger the slickGoTo: https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

**Comment by kevindavis** [comment]
I saw that example and tried to do something similar using the componentDidUpdate callback, but it didn't seem to have any impact. Curious what I'm missing here?

**Comment by akiran** [comment]
@kevindavis,  In the codepen you provided,  initialSlide is not changing when I resize browser

**Comment by dougmacklin** [comment]
Hey @akiran, in the codepen I provided, try resizing the browser and then refreshing. `initialSlide` is set once when the slider is initialized, based on whatever the current breakpoint is at that time. This behavior is not present with react-slick, as `initialSlide`'s within `responsive` are ignored.

@kevindavis is describing a separate issue he's running into, which should probably be moved to it's own thread.

**Comment by akiran** [comment]
@dougmacklin  Got it.

For the issue @kevindavis  is mentioning, there is a breakpoint event in original slick, which fires when an breakpoint is hit.  But breakpoint event is not yet implemented in  react-slick

**Comment by dougmacklin** [comment]
If we have:

```js
var settings = {
  initialSlide: 0,
  slidesToShow: 3,
  responsive: [
    {
      breakpoint: 600,
      settings: {
        initialSlide: 1,
        slidesToShow: 1
      }
    }
  ]
};
```

Would it be possible to have `initialSlide` be 1 if the screen is less than 600px wide when the Slider first mounts? `slidesToShow` will correctly be 1 instead of 3, can initialSlide be set in the same way? I don't think it needs to update if the window is resized like `slidesToShow` does, it just needs to be set to the appropriate value the first time.

**Comment by akiran** [comment]
@dougmacklin Yes, Fixed it. Will make a release soon

**Comment by kevindavis** [comment]
I was mistaken thinking these issues were related. I opened https://github.com/akiran/react-slick/issues/440 which might well be a misunderstanding of how to use this stuff

**Comment by gowthambalashanmugam** [comment]
Is anyone faced this issue ? After done slickGoTo, the upcoming sliders lost his control of sliding property. 
http://jsfiddle.net/svx2dzwL/. After i applied slickGoTo, last item is not visible.
