### ISSUE TITLE
how can i set slide item margin ?

### ISSUE THREAD

**Issue by V-Tom** [akiran/react-slick#443]
I saw the code write this in `mixins.helpers.initialize` and line 30
` var slideWidth = trackWidth / props.slidesToShow;`

But i want add margin or padding on slidesItem rather than each mixed together
like this:
`var slideWidth = (trackWidth+padding*2) / props.slidesToShow;`

I saw the examples,every slides item not mixed together.

and however i can use css like `padding:0 10px;` to resolve it

Is there any options to set it?

**Comment by akiran** [comment]
Using css is the best way to control margin/padding on slides

**Comment by mcmillhj-wta** [comment]
@V-Tom Did you ever happen to find a good solution to this? Like @akiran says you can set margin or padding on the slides, but the next slide and previous slide button don't respect that and end up not left-aligning the slides with the start of the carousel.

**Comment by silicakes** [comment]
I'd love a better solution too

**Comment by mcmillhj-wta** [comment]
A solution that worked well for our team was to add a border to each item that is the same color as the background. This way the padding doesn't affect the carousel in any way.

**Comment by azjgard** [comment]
@mcmillhj-wta That worked really well for me as well, in combination with setting the box-sizing property to "border-box".

**Comment by lamari** [comment]
What did work for me, is this:
I wrapped my item with a container that have height bigger than the item itself, and then I deleted the margin from my item ;)

**Comment by srikanthbandaru** [comment]
I fixed it using 

```
.slick-slide {
  padding: 0 15px;
}

.slick-list {
  margin: 0 2em;
}
```

**Comment by tylik1** [comment]
I ended up adding margin to the element inside .`.slick-slide` and then add negative margin on `.slick-list`

e.g.

`.slick-slide img {margin-left:10px;}`
`.slick-list {margin-left:-10px;}`

**Comment by ZeroCool-85** [comment]
You dont need to set margins just set:

     .slick-slide {
	     padding: 0 8px;
     	     box-sizing: border-box;
      }
padding-left/right depends on your centerPadding.

**Comment by nhd2106** [comment]
> I fixed it using
> 
> ```
> .slick-slide {
>   padding: 0 15px;
> }
> 
> .slick-list {
>   margin: 0 2em;
> }
> ```

many thanks, it worked in my case!

**Comment by shaktish** [comment]
```
 // short
 .slick-slider {
    overflow: hidden;

    .slick-track {
      margin: inherit;
    }

    /* the parent */
    .slick-list {
      width: calc(100% + 20px);
    }
}
 
 .item {
  margin-right: 20px;
  }
 
// complete-code
.slick-slider {
    overflow: hidden;

    .slick-track {
      margin: inherit;
    }

    /* the parent */
    .slick-list {
      width: calc(100% + 20px);
    }

    .slick-prev {
      left: 2px;
    }

    .slick-next {
      right: 2px;
    }

    .slick-prev,
    .slick-next {
      z-index: 2;

      @media (min-width: 769px) {
        opacity: 0;

        transition: all 0.2s;
      }
    }

    .slick-prev:before,
    .slick-next:before {
      color: #fff;
    }

    @media (min-width: 769px) {
      &:hover {
        .slick-prev,
        .slick-next {
          opacity: 1;
        }
      }
    }
  }
  
  .item {
  margin-right: 20px;
  }
```


![image](https://user-images.githubusercontent.com/7484016/148761078-152ec7e0-c7f1-4677-9104-94d250117dda.png)

**Comment by shaktish** [comment]
```
// scss
 .slick-slider {
    overflow: hidden;

    .slick-track {
      margin: inherit;
    }

    .slick-list {
      width: calc(100% + 20px);
    }
}
 
 .item {
  margin-right: 20px;
}
```


![image](https://user-images.githubusercontent.com/7484016/148761616-e26a636b-841b-48a4-804d-6913c83e3822.png)

**Comment by shaktish** [comment]
```
// scss
 .slick-slider {
    // when you set this, the arrows and dots will be hidden, so you have to handle it via css
    overflow: hidden;

    .slick-track {
    // removes default auto margin
      margin: inherit;
    }

    .slick-list {
     // adjust the card-margin 
      width: calc(100% + 20px);
    }
}
 
 .item {
  margin-right: 20px;
}
```
![image](https://user-images.githubusercontent.com/7484016/148761962-3d033e3a-e7a4-46c9-a591-ac82e8de178a.png)
