### ISSUE TITLE
Serverside rendering broke with version 0.13.3

### ISSUE THREAD

**Issue by thebuilder** [akiran/react-slick#444]
I upgraded from version 0.13.2 to 0.13.3 today, and this caused my serveside rendering test to fail:

```
  1) SlideshowRibbon should render serverside:
     TypeError: enquire.register is not a function
      at ResponsiveMixin.media (dist/scripts/webpack:/~/react-responsive-mixin/index.js:13:1)
      at dist/scripts/webpack:/~/react-slick/lib/slider.js:56:1
      at Array.forEach (native)
      at componentWillMount (dist/scripts/webpack:/~/react-slick/lib/slider.js:49:1)
```

Looking at `react-responsive-mixin`, the error is caused because `media` is called, but enquirer.js is only loaded in the dom can be used. Unfortunately it doesn't check if enquirer actually exists before calling it.

```
media: function (query, handler) {
    query = json2mq(query);
    if (typeof handler === 'function') {
      handler = {
        match: handler
      };
    }
    enquire.register(query, handler);
   ...
```

I'm guessing something changed, that causes media to be called early with the last update.

**Comment by renatorib** [comment]
I have the same problem...
Opened this PR. 
https://github.com/akiran/react-responsive-mixin/pull/4

Should fix this

@akiran

**Comment by akiran** [comment]
@renatorib  Thanks.  I will review it today

**Comment by akiran** [comment]
@renatorib I merged your PR and released 0.13.6
Can you test if this issue is fixed.

**Comment by renatorib** [comment]
Testing right now, wait a moment

**Comment by nelsieborja** [comment]
Getting same issue. Working fine now after pulling your latest code. Thanks!
