### ISSUE TITLE
Use camel case styles

### ISSUE THREAD

**Issue by mauricioklein** [akiran/react-slick#448]
Hello!

First of all, great work providing this library :+1: 

I'm using SCSS files in my React and, in order to load them, I'm just requiring the file, like:
```js
const Styles = require('app.scss');
```

I've imported *slick-carousel* styles on my *app.scss* as well and it's loading without any problem.
The problem is that I use a webpack module to convert CSS classes to camelcase. So, classes like *.my-class* will become *.myClass*.

And, since the classes are camelized, the proper styles are not being applied to Slider structure.

My question is: 
**How to make Slider use the camel case class format?**

Thanks in advance for any support!

**Comment by akiran** [comment]
exclude the slick-carousel scss files in config of loader that convert CSS classes to camelcase

You can check this for exclude usage
https://webpack.github.io/docs/configuration.html#module-loaders
