### ISSUE TITLE
running "npm install" in home directory produces error

### ISSUE THREAD

**Issue by paulwehner** [akiran/react-slick#45]
I get the following output when trying to run "npm install" in the react-slick directory:

    > node-sass@1.2.3 install /Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/mvm-react-radium/node_modules/react-slick/node_modules/sass-loader/node_modules/node-sass
    > node scripts/install.js

    Binary downloaded and installed at /Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/mvm-react-radium/node_modules/react-slick/node_modules/sass-loader/node_modules/node-sass/vendor/darwin-x64/binding.node

    > node-sass@1.2.3 postinstall /Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/mvm-react-radium/node_modules/react-slick/node_modules/sass-loader/node_modules/node-sass
    > node scripts/build.js

    `darwin-x64` exists; testing
    module.js:355
      Module._extensions[extension](this, filename);
                                   ^
    Error: Module did not self-register.
        at Error (native)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/mvm-react-radium/node_modules/react-slick/node_modules/sass-loader/node_modules/node-sass/lib/index.js:181:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.1
    npm ERR! npm  v2.7.5
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
    npm ERR! This is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

**Comment by akiran** [comment]
I clonned this repo freshly, and ran `npm install`
It worked fine for me.  Can you check if there is anything wrong with your setup

**Comment by paulwehner** [comment]
I tried it again. I directly cloned the project as well as downloaded the zip. Both times when I run "npm install" from the root folder I get the following output:

    Pauls-MacBook-Pro:react-slick paulme$ npm install
    npm WARN package.json Dependency 'object-assign' exists in both dependencies and devDependencies, using 'object-assign@^2.0.0' from dependencies
    npm WARN peerDependencies The peer dependency react included from react-slick will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
    npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
    npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.1","npm":"2.7.5"})
    npm WARN peerDependencies The peer dependency babel-core@* included from babel-loader will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
    npm WARN peerDependencies The peer dependency react@0.12.x included from react-router will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
    /
    > fsevents@0.3.6 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/karma/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

      SOLINK_MODULE(target) Release/.node
      SOLINK_MODULE(target) Release/.node: Finished
      CXX(target) Release/obj.target/fse/fsevents.o
      SOLINK_MODULE(target) Release/fse.node
      SOLINK_MODULE(target) Release/fse.node: Finished
     
    > ws@0.5.0 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
      SOLINK_MODULE(target) Release/bufferutil.node: Finished
      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node
      SOLINK_MODULE(target) Release/validation.node: Finished
     
    > fsevents@0.3.6 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

      SOLINK_MODULE(target) Release/.node
      SOLINK_MODULE(target) Release/.node: Finished
      CXX(target) Release/obj.target/fse/fsevents.o
      SOLINK_MODULE(target) Release/fse.node
      SOLINK_MODULE(target) Release/fse.node: Finished
     
    > ws@0.4.31 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
     
    > ws@0.4.32 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
      SOLINK_MODULE(target) Release/bufferutil.node: Finished
      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node
      SOLINK_MODULE(target) Release/validation.node: Finished
    -
    > node-sass@1.2.3 install /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/sass-loader/node_modules/node-sass
    > node scripts/install.js

    Binary downloaded and installed at /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/sass-loader/node_modules/node-sass/vendor/darwin-x64/binding.node

    > node-sass@1.2.3 postinstall /Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/sass-loader/node_modules/node-sass
    > node scripts/build.js

    `darwin-x64` exists; testing
    module.js:355
      Module._extensions[extension](this, filename);
                                   ^
    Error: Module did not self-register.
        at Error (native)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/paulme/Google Drive/Development/Awfbeat/react-slick/node_modules/sass-loader/node_modules/node-sass/lib/index.js:181:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.1
    npm ERR! npm  v2.7.5
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
    npm ERR! This is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/paulme/Google Drive/Development/Awfbeat/react-slick/npm-debug.log

**Comment by akiran** [comment]
@paulwehner This is the problem with node-sass
Updating its version fixed the problem
