### ISSUE TITLE
How to listen to Track component style

### ISSUE THREAD

**Issue by manodupont** [akiran/react-slick#454]
Is there any way I could listen to the track style changed. ?

What I am trying to achieve is to translate some overlayed objects according to the transition of the track.

So in the DOM, when a slider is animated on and moving from left to right for example, this component change the style.

So i would like to get those information and apply that style to some other objects overlayed on top of the slide.

**Comment by akiran** [comment]
You can use beforeChange and afterChange props.
https://github.com/akiran/react-slick/blob/master/examples/SlideChangeHooks.js

**Comment by manodupont** [comment]
No its not what I meant. The slide-track, its style ... contains a transform: translate3d ....

When the transition animation are on, that value changes along the transition. 

So lets say you put a text on the slide, and you want it to always follow (x,y) position of the slide behind ..... i can't jsut use before and afterChange event, i need to follow the element itself as it translate, and the only information i got from the DOM, is the slide-track, transform: translate3d(....) values. 

This or any other suggestion would be appreciate. Thanks.

**Comment by manodupont** [comment]
That div. 

```html
<div class="slick-track" style="opacity: 1; width: 10000px; transform: translate3d(0px, 0px, 0px);">
```

**Comment by enxajt** [comment]
I'm in the same situation with @manodupont.
