### ISSUE TITLE
Start using semver

### ISSUE THREAD

**Issue by thecaddy** [akiran/react-slick#456]
Every patch update of this package has breaking changes making it difficult to use.

Major - breaking changes
Minor - new feature
Patch - bug fix

**Comment by akiran** [comment]
Which breaking change are you mentioning  ?

**Comment by akiran** [comment]
I am reviewing lot of PR's and merge them and also adding missing features of slick
In couple of weeks this package will be more stable

**Comment by thecaddy** [comment]
CSS, prop changes, and breaking of server side rendering.  Much of the package works great as I still run 0.12 but as new features are being added they are being added in a patch version and breaking existing features.

**Comment by akiran** [comment]
I just added a depreciation warning to props. props still works and it will be removed in next major release.

server side issue is unexpected.  I still doesn't understand why it happened. 
Server side issue is coming from react-responsive-mixin and it is same in both the versions.

Anyway, I merged a PR that fixes the issue with  react-responsive-mixin. 
I will make a release soon
