### ISSUE TITLE
How to add space between slides?

### ISSUE THREAD

**Issue by srinivaasang1** [akiran/react-slick#459]

**Comment by lcoder** [comment]
How to add space between slides?  is any one resolve?

**Comment by nbkhope** [comment]
I'm trying to add space between slides in centerMode. If I try to style the slick-slide with side margins, it no longer aligns center. Any ideas?

**Comment by cassianomon** [comment]
I could accomplish it with Styled Components, but I think regular SCSS will do the job too:

```
export const SliderStyles = styled(Slider)`
    .slick-list {
        margin: 0 -4px;
    }
    .slick-slide > div {
        margin: 0 4px;
    }
`;
```
