### ISSUE TITLE
Rendering the component provided in the directions doesn't result in a slider. 

### ISSUE THREAD

**Issue by paulwehner** [akiran/react-slick#46]
Following the directions and running the following commands:

    npm install react-slick

    bower install slick-carousel

I then drop in the example component into my project:

    var React = require('react');
    var Slider = require('react-slick');

    var SimpleSlider = React.createClass({
      render: function () {
        var settings = {
          dots: true,
          infinite: true,
          speed: 500,
          slidesToShow: 1,
          slidesToScroll: 1
        };
        return (
          <Slider {...settings}>
            <div><h3>1</h3></div>
            <div><h3>2</h3></div>
            <div><h3>3</h3></div>
            <div><h3>4</h3></div>
            <div><h3>5</h3></div>
            <div><h3>6</h3></div>
          </Slider>
        );
      }
    });

And when I render it it looks like this:

![screen shot 2015-05-05 at 12 23 36 pm](https://cloud.githubusercontent.com/assets/905420/7481106/76f0c7de-f322-11e4-99a2-b7bc35f67252.png)

**Comment by akiran** [comment]
Have you added the css link in your html ?

**Comment by paulwehner** [comment]
No, adding the CSS links provided here: http://kenwheeler.github.io/slick/ it looks correct. I think it would make sense to add this as a step to the directions you provide... or better yet, as a "require()" within the project, so webpack will automatically bundle and inject it into the site wherever the slider is used.
