### ISSUE TITLE
focusOnSelect no-op implementation requires unsafe-eval CSP content source

### ISSUE THREAD

**Issue by suniala** [akiran/react-slick#461]
If `!focusOnSelect` then `new Function` is executed. This is actually code evaluation and requires the `unsafe-eval` Content Security Policy content source for `script-src` directive in order to work. We should allow clients to use strict CSP rules and deny `unsafe-eval` and replace `new Function` with something that does not require this content source.

I will create a PR for this.

https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Keywords

**Comment by akiran** [comment]
@suniala, I think we should replace new Function with null and execute function only if it exits

**Comment by suniala** [comment]
@akiran, sure why not. I already created a pull request with another kind of solution but I can do a new one, if you prefer.

**Comment by akiran** [comment]
@suniala Thanks. That would be great

**Comment by suniala** [comment]
Done. Please see the updated pull request.

**Comment by akiran** [comment]
Fixed in release 0.14
