### ISSUE TITLE
NPM installs 0.13.6 and not 0.14.0

### ISSUE THREAD

**Issue by creatifyme** [akiran/react-slick#464]
When installing `react-slick`, npm is still pointing to 0.13.6 and not 0.14.0

I've deleted my `node_modules` folder, removed `react-slick` from my package.json. Clean installed my modules and then re-installed react slick and still getting the old version. But when I run `npm outdated` it tells me there is a new version. Issue with npm cached?
```
Package                            Current      Wanted     Latest 
react-slick                         0.13.6         0.13.6        0.14.0
```

**Comment by akiran** [comment]
Are you using any npm caching mechanisms like local-npm ?

**Comment by creatifyme** [comment]
@akiran nope, looks like it was just something weird going on with NPM yesterday. All good now. THank you!
