### ISSUE TITLE
Bower file out of date

### ISSUE THREAD

**Issue by jswelker** [akiran/react-slick#466]
The bower file lists click as a dependency slick-carousel ~1.3.15. Can this be updated to the new 1.6 as it is in the package.json? I am using rails-assets.org and stuck with Bower...

**Comment by akiran** [comment]
We might stop support for bower soon.

Can you add slick-carousel to your dependency list and install react-slick from unpkg.com
```
bower install https://unpkg.com/react-slick@0.14.1/dist/react-slick.js
```

**Comment by jswelker** [comment]
My app uses rails-assets.org to manage bower packages as gem, so there is no bower file for my app. Since react-slick requires slick-carousel 1.3.15, requiring 1.6.0 causes a dependency conflict. My workaround for now is just to include the up-to-date slick-carousel css in my vendor directory in Rails. Not a big deal but a little sloppier than I'd like.

**Comment by akiran** [comment]
I will update bower file in my next release today.

**Comment by akiran** [comment]
Fixed it
