### ISSUE TITLE
How to replace the default Arrow with my custom arrow ?

### ISSUE THREAD

**Issue by aziz-boudi4** [akiran/react-slick#478]
I'm trying to replace the default next/previous arrow with a custom arrow.
I was able to add my custom arrow but the default one is still showing on the screen.

How can I get rid of the custom arrow ?

I initially tried to increase the size of the custom but I couldn't that is why I opted to add my custom arrow instead .

So basically either solutions would work for me,
1- How can I increase the size of the default arrow ?
Or
2- How can I use my custom arrow instead of the default arrow ? How to remove the default arrow and use my icon instead ?

![screen shot 2016-09-14 at 9 09 12 pm](https://cloud.githubusercontent.com/assets/7435015/18538139/96c1aeea-7abf-11e6-8137-7e90c369b144.png)

Here is how I'm adding my custom icon:

        var NextArrow = React.createClass({
             render: function() {
               return <button {...this.props}   style={{fontSize: "40px", display: 'block', right:"100px", zIndex:"15", height:"40px", width:"40px", opacity:"1", color:"White"}} >
                <span className="icon icon-chevron-with-circle-right"></span>
             </button> ;
   	
    }
  });

**Comment by akiran** [comment]
Check this example 
https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js

**Comment by aziz-boudi4** [comment]
@akiran Thanks for your answer, but I already checked this example.
This is the example that I followed and the code in the example creates my problem.
If I follow the example you have sent me, I'll end up with the small default arrow, and I want to get rid of it and replace it with my custom arrow.

Or let me know how I can increase its size, I was able to change many of it's css property but I cannot change it's size.

Thank you

**Comment by angieyu** [comment]
this works for me, i replaced the className with "slick-arrow"

```
function LeftNavButton(props) {
    const {className, style, onClick} = props
    return (
        <div
            className="slick-arrow"
            style={{...style, display: 'block'}}
            onClick={onClick}
        >
            <img src={ARROW_left} alt="arrow_left"/>
        </div>
    );
}
```

**Comment by MasterChenGitHub** [comment]
:global {
    .slick-prev:before, .slick-next:before {
        display: none;
    }
  
}

**Comment by matheus-lima** [comment]
`
.slick-prev, .slick-next {
  font-size: 15px !important;
}

 .slick-prev:before {
  content: '' !important;
}
`

**Comment by matheus-lima** [comment]
`.slick-prev, .slick-next {
  font-size: 15px !important;
}

 .slick-prev:before {
  content: '' !important;
}`

**Comment by matheus-lima** [comment]
.slick-prev, .slick-next {
  font-size: 15px !important;
}

 .slick-prev:before {
  content: '' !important;
}

**Comment by matheus-lima** [comment]
```javascript
const SamplePrevArrow = (props) => {
    const { className, onClick } = props
    return (
        <div 
            className={className}
            onClick={onClick}
        >
            <FontAwesomeIcon
                icon={Icons.faAngleLeft}
                color="#000"
                size="2x"
            />
        </div>
    );
}
```

```css
.slick-prev, .slick-next {
  font-size: 15px !important;
}

 .slick-prev:before {
  content: '' !important;
}

.slick-next:before {
  content: '' !important;
}
```

**Comment by hypeofpipe** [comment]
Is there a better solution? Looks terrible :/

**Comment by hypeofpipe** [comment]
This helped me:

`import React from 'react';
import styled from 'styled-components';
import Slider, { Settings } from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const settings: Settings = {
  dots: false,
  infinite: true,
  speed: 500,
  slidesToShow: 4,
  slidesToScroll: 4,
  prevArrow: <EmptyButton />,
  nextArrow: <NavButton />,
};

const StyledSlider = styled(Slider)`
  .slick-next {
    width: 4rem;
    height: 4rem;
    right: -5.4rem;
    top: 40%;
  }
`

<StyledSlider  {...settings}>...;
`

**Comment by toilahungvn98** [comment]
I'm using styled-components :


import styled from 'styled-components';

const Dots = styled.div`
  /* background-color: red; */
  &.slick-dots li button::before {
   font-size: 12px;
  
 }

`;

const NextArrow = styled.div`
 
    display: block;
    position: relative;
  

    &.slick-next::before {
      content: '';
      position : absolute;
      top: -50%;
      width: 3rem;
      height: 3px;
      transform: rotate(45deg);
      background-color: rgba(0,0,0,0.8);
      transition: all 0.2s;
    }
    &.slick-next::after {
      content: '';
      top: 50%;
      position : absolute;
      width: 3rem;
      height: 3px;
      transform: rotate(-45deg);
      background-color: rgba(0,0,0,0.8);
      transition: all 0.2s;
    }
    &.slick-next:hover::before {
      top: -40%;
      transform: rotate(35deg);
    }
    &.slick-next:hover::after {
      top: 40%;
      transform: rotate(-35deg);
    }

`;


const PrevArrow = styled.div`
   
    display: block;
    position: relative;
    transform: rotate(360deg);

    &.slick-prev::before {
      content: '';
      position : absolute;
      top: -50%;
      width: 3rem;
      height: 3px;
      transform: rotate(-45deg);
      background-color: rgba(0,0,0,0.8);
      transition: all 0.2s;
    }
    &.slick-prev::after {
      content: '';
      top: 50%;
      position : absolute;
      width: 3rem;
      height: 3px;
      transform: rotate(45deg);
      background-color: rgba(0,0,0,0.8);
      transition: all 0.2s;
    }
    &.slick-prev:hover::before {
      top: -40%;
      transform: rotate(-35deg);
    }
    &.slick-prev:hover::after {
      top: 40%;
      transform: rotate(35deg);
    }

`;

function SampleNextArrow(props) {
  const { className, onClick } = props;
  
  return (
    <NextArrow
      className={className}  
      onClick={onClick}
    > </NextArrow>
  );
}

function SamplePrevArrow(props) {
  const { className, onClick } = props;
  return (
    <PrevArrow
      className={className}
      onClick={onClick}
    ></PrevArrow>
  );
}

**Comment by hieunguyendut** [comment]
> I'm using styled-components :
> 
> import styled from 'styled-components';
> 
> const Dots = styled.div`
> /* background-color: red; */
> &.slick-dots li button::before {
> font-size: 12px;
> 
> }
> 
> `;
> 
> const NextArrow = styled.div`
> 
> ```
> display: block;
> position: relative;
> 
> 
> &.slick-next::before {
>   content: '';
>   position : absolute;
>   top: -50%;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-next::after {
>   content: '';
>   top: 50%;
>   position : absolute;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(-45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-next:hover::before {
>   top: -40%;
>   transform: rotate(35deg);
> }
> &.slick-next:hover::after {
>   top: 40%;
>   transform: rotate(-35deg);
> }
> ```
> 
> `;
> 
> const PrevArrow = styled.div`
> 
> ```
> display: block;
> position: relative;
> transform: rotate(360deg);
> 
> &.slick-prev::before {
>   content: '';
>   position : absolute;
>   top: -50%;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(-45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-prev::after {
>   content: '';
>   top: 50%;
>   position : absolute;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-prev:hover::before {
>   top: -40%;
>   transform: rotate(-35deg);
> }
> &.slick-prev:hover::after {
>   top: 40%;
>   transform: rotate(35deg);
> }
> ```
> 
> `;
> 
> function SampleNextArrow(props) {
> const { className, onClick } = props;
> 
> return (
> 
> );
> }
> 
> function SamplePrevArrow(props) {
> const { className, onClick } = props;
> return (
> 
> );
> }

This worked for me. thanks a lot

**Comment by hieunguyendut** [comment]
@toilahungvn98 thanks a lot. That worked for me.

**Comment by akifarhan** [comment]
> I'm using styled-components :
> 
> import styled from 'styled-components';
> 
> const Dots = styled.div`
> /* background-color: red; */
> &.slick-dots li button::before {
> font-size: 12px;
> 
> }
> 
> `;
> 
> const NextArrow = styled.div`
> 
> ```
> display: block;
> position: relative;
> 
> 
> &.slick-next::before {
>   content: '';
>   position : absolute;
>   top: -50%;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-next::after {
>   content: '';
>   top: 50%;
>   position : absolute;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(-45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-next:hover::before {
>   top: -40%;
>   transform: rotate(35deg);
> }
> &.slick-next:hover::after {
>   top: 40%;
>   transform: rotate(-35deg);
> }
> ```
> 
> `;
> 
> const PrevArrow = styled.div`
> 
> ```
> display: block;
> position: relative;
> transform: rotate(360deg);
> 
> &.slick-prev::before {
>   content: '';
>   position : absolute;
>   top: -50%;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(-45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-prev::after {
>   content: '';
>   top: 50%;
>   position : absolute;
>   width: 3rem;
>   height: 3px;
>   transform: rotate(45deg);
>   background-color: rgba(0,0,0,0.8);
>   transition: all 0.2s;
> }
> &.slick-prev:hover::before {
>   top: -40%;
>   transform: rotate(-35deg);
> }
> &.slick-prev:hover::after {
>   top: 40%;
>   transform: rotate(35deg);
> }
> ```
> 
> `;
> 
> function SampleNextArrow(props) {
> const { className, onClick } = props;
> 
> return (
> 
> );
> }
> 
> function SamplePrevArrow(props) {
> const { className, onClick } = props;
> return (
> 
> );
> }

Hi @toilahungvn98, do you have any example of the full code? Im kinda lost on how you use the NextArrow, PrevArrow and Dots. Thank you in advance.

**Comment by ariq2901** [comment]
> this works for me
> 
> ```js
> const SamplePrevArrow = (props) => {
>     const { className, onClick } = props
>     return (
>         <div 
>             className={className}
>             onClick={onClick}
>         >
>             <FontAwesomeIcon
>                 icon={Icons.faAngleLeft}
>                 color="#000"
>                 size="2x"
>             />
>         </div>
>     );
> }
> ```
> 
> ```css
> .slick-prev, .slick-next {
>   font-size: 15px !important;
> }
> 
>  .slick-prev:before, .slick-next:before  {
>   content: '' !important;
> }
> ```

Thank you for the reference. Its work Perfectly!

**Comment by ayushjii** [comment]
No-one is working

**Comment by akifarhan** [comment]
@ayushjii  https://stackoverflow.com/questions/49018820/custom-arrows-react-slick/59232727#59232727

**Comment by mvandergrift** [comment]
There are some excellent solutions here. I needed something straightforward for a one-off use and ended up using the CSS scale transform within a custom arrow component.

```js
function SampleNextArrow(props) {
        const { className, style, onClick } = props
        return (
          <div
            className={className}
            style={{ ...style, display: "block", transform: "scale(1.5)" }}
            onClick={onClick}
          />
        );
      }
```

**Comment by nurhamsah1998** [comment]
maybe like this :

`function SamplePrevArrow(props: any) {
  const { className, style, onClick } = props;
  return (
    <div
      className={className}
      style={{
        ...style,
        display: "block",
        background: "#fff",
        marginLeft: "20px",
        padding: "20px",
        zIndex: 99,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "100%",
        boxShadow: "0px 8px 22px 0px rgba(179, 179, 208, 0.30)",
      }}
      onClick={onClick}
    >
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
        }}
      >
        <ICON />
      </div>
    </div>
  );
}`

**Comment by nurhamsah1998** [comment]
hope this can help yu

![111111](https://github.com/akiran/react-slick/assets/95860539/06211874-baf0-4456-81ab-ae16295c8eeb)

**Comment by sm791600** [comment]
This is what worked for me using local svg files, use similar code for the left arrow:
```javascript
const CustomNextArrow = ({ className, onClick }) => (
  <div
    className={`${className} custom-next-arrow`}
    onClick={onClick}
    role="button"
    tabIndex={0}
    onKeyDown={(e) => {
      if (e.key === 'Enter' || e.key === ' ') onClick();
    }}
  >
    <img
      src="/images/chevron-right.svg"
      alt="Next"
    />
  </div>
);

CustomNextArrow.propTypes = {
  className: PropTypes.string,
  onClick: PropTypes.func.isRequired,
};

CustomNextArrow.defaultProps = {
  className: '',
};
``` 
hide the default Slick buttons with:
```css
.slick-prev::before,
.slick-next::before {
  display: none;
}
```
