### ISSUE TITLE
Make use of Slick methods

### ISSUE THREAD

**Issue by mdaverde** [akiran/react-slick#48]
[Slick](http://kenwheeler.github.io/slick/) has a list of several methods we can use to programmatically control the carousel. How do we access them through this component?

**Comment by akiran** [comment]
Those methods are not yet implemented in this module.
Need to do it.

**Comment by alkali47** [comment]
How far with these please?

**Comment by milanlandaverde** [comment]
I just ended up implementing my own react-slick component. Not that much
more difficult and more flexibility.

**Comment by vramana** [comment]
@alkali47 What methods do you need support of ?

**Comment by akiran** [comment]
@alkali47  Many slick methods can be implemented by programmatically changing the children of Slider in your react components
Calling slick method similar to jQuery $('.slick').method() is not a got pattern in react.
Instead you can render slides inside Slider according to your requirement

**Comment by alkali47** [comment]
That's helpful, thanks

**Comment by jasontighe** [comment]
Just wanted to check in if these have been implemented. Thanks alkali47!

**Comment by jon-bloomerang** [comment]
Any update on when this will be added?

Changing the slickGoTo prop does change the slide, but there's no transition between slides like you get with the dots or the prev/next buttons. Or is there another way to programmatically change the slide with a transition between? Thanks!
