### ISSUE TITLE
initialSlide being ignored on rerender.

### ISSUE THREAD

**Issue by shendrick** [akiran/react-slick#484]
I have a use where there are buttons in the slides that effect the state and triggers a rerender. I'm keeping track of the current slide and adding this to to the state and then using it for the initialSlide property, but it seems it always goes to the second slide every time. In the react debugger in chrome I can see the prop updates as it should, but it's not affecting the carousel. Any help would be appreciated!

**Comment by dannybloe** [comment]
Yes, I was just trying to figure out why my slide position didn't update. Exactly this case. It seems to be completely ignored.

**Comment by akiran** [comment]
InitialSlide is meant only for initial render. To change slide after 1st render, you have to use slickGoTo method 

Check this example
https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

**Comment by dannybloe** [comment]
This doesn't make any sense in a redux context. Please don't close before the discussion is over. Feels kinda rude.

**Comment by akiran** [comment]
We are following the API of original slick 
http://kenwheeler.github.io/slick/

Currently we have slickGoTo prop which can be used to change slide.
But because of some issue we had to deprecate it in favor of slickGoTo method.

**Comment by dannybloe** [comment]
Ok, so what you have to do is something like this:

```
componentDidUpdate (prevProps) {
	if (this.refs.slider) {
		this.refs.slider.slickGoTo(this.props.someIndex);
	}
}
```

**Comment by akiran** [comment]
Yes, you can do that if you are getting someIndex from redux store.

You also have to prevent re-render of Slider when someIndex change by implementing shouldComponentUpdate.  Otherwise you will lose animation effect during slide change

**Comment by shendrick** [comment]
The thing is, I have a carousel where there are a set of options a user goes through. I start with slide one select something, then swipe to slide 2. When I click in slide two, it will render as slide 1, since my props have changed. Then if I use slickGoTo, it will animate from slide 1 to slide 2. The user will be confused as it switches from slide 2 to slide 1 without animation, then slides to slide 2 in an animated way? That would be very odd behavior. Is there some way to do slickGoTo without the animation?

**Comment by shendrick** [comment]
So it looks like the slick library accepts a second argument of a boolean to animate or not..
```javascript
    Slick.prototype.goTo = Slick.prototype.slickGoTo = function(slide, dontAnimate) {

        var _ = this;

        _.changeSlide({
            data: {
                message: 'index',
                index: parseInt(slide)
            }
        }, dontAnimate);

    };
```
But it doesn't seem to be accepted in react-slick...
```javascript
slickGoTo: function slickGoTo(slide) {
    this.innerSlider.slickGoTo(slide);
},
```

**Comment by akiran** [comment]
@shendrick Nice catch.

Can you open a new issue with that feature request

**Comment by Sofia-H** [comment]
set variableWidth=false, the state may be work. if you set variableWidth=true & initialSlide=someIndex, the slider don't know the width, so do not work. hope to help.
