### ISSUE TITLE
Warning: Component's children should not be mutated.

### ISSUE THREAD

**Issue by kencckw** [akiran/react-slick#487]
Warning: Component's children should not be mutated.
    in button (created by Dots)
    in li (created by Dots)
    in ul (created by Dots)
    in Dots (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
....

  const sliderSettings = {
    dots: true
  }

env:
react@15.3.0
react-slick@0.14.3 

How can I fix this warning?

**Comment by AnnaKosolapova** [comment]
@kencckw, had the same issue, It's disappearing in react-slick@0.14.4

**Comment by kencckw** [comment]
disappearing in react-slick@0.14.4
