### ISSUE TITLE
Add animate argument to slickGoTo method

### ISSUE THREAD

**Issue by shendrick** [akiran/react-slick#488]
So it looks like the slick library accepts a second argument of a boolean to animate or not..

``` javascript
    Slick.prototype.goTo = Slick.prototype.slickGoTo = function(slide, dontAnimate) {

        var _ = this;

        _.changeSlide({
            data: {
                message: 'index',
                index: parseInt(slide)
            }
        }, dontAnimate);

    };
```

But it doesn't seem to be accepted in react-slick...

``` javascript
slickGoTo: function slickGoTo(slide) {
    this.innerSlider.slickGoTo(slide);
},
```

**Comment by PsiXdev** [comment]
Hello. How are things going with this issue? I also need to use this functionality.

**Comment by edencorbin** [comment]
This would also be huge for me, any progress?

**Comment by goncalomarques** [comment]
Any updates on this?

**Comment by mricketts** [comment]
Checking in here, is there no current way to have the slickGoTo method animate?

**Comment by peterph-am** [comment]
Any updates on this issue? I would like to animate the slickGoTo method too.

**Comment by laveesingh** [comment]
The referenced commit should take care of it.

**Comment by leomyth330** [comment]
Could you release new version with this update?
