### ISSUE TITLE
Center mode for 3 slides isn't centered

### ISSUE THREAD

**Issue by teckore** [akiran/react-slick#489]
Hi, 
Anyone having an issue where loading 3 slides and using the center property doesn't make it centered between the left and right arrows?

Any help is appreciated, thanks!

**Comment by matthewbschneider** [comment]
The 50px left/right inline padding on the DIV with the slick-list class is causing this issue.  

![screen shot 2016-09-29 at 7 50 51 pm](https://cloud.githubusercontent.com/assets/1120582/18979278/47acda76-867e-11e6-8ab0-2e96dde9d265.png)

**Comment by szimek** [comment]
I found how to fix it and described it in https://github.com/akiran/react-slick/issues/566, but it does require some changes to the library itself. I'll try to come up with a PR once I'm sure it doesn't break anything else.

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases, please try the latest version.
If it still persists, please create a codesandbox demo for the same and reopen it.
