### ISSUE TITLE
rows setting

### ISSUE THREAD

**Issue by paulwehner** [akiran/react-slick#49]
Do you have plans to add this feature from Slick Carousel?

rows
int
1
Setting this to more than 1 initializes grid mode. Use slidesPerRow to set how many slides should be in each row.

**Comment by joewestcott** [comment]
Is this able to be implemented any time soon? It also should be mentioned on the readme as not working (unless it is and I'm doing something wrong)

**Comment by diessica** [comment]
Is it on the roadmap?

**Comment by FanAs** [comment]
Bump

**Comment by mr-madamin** [comment]
Rows setting is very needed

**Comment by j-baconator** [comment]
Any plans to implement rows?

**Comment by laveesingh** [comment]
refer to #502 for updates
