### ISSUE TITLE
unable to install react-slick

### ISSUE THREAD

**Issue by NambiRamanujam** [akiran/react-slick#490]
Hey, could use some help.
I want to avoid using Jquery with reactjs as it is not recommended widely among developer's community. So I tried to install this react package which is throwing an error. What might be the issue?

**Comment by akiran** [comment]
Which npm version are you using ?

You need to install slick-carousel for css

**Comment by NambiRamanujam** [comment]
npm: 3.10.5 & react: 15.2.0

**Comment by NambiRamanujam** [comment]
hey could use some help,
I mean package itself is not getting installed.

**Comment by akiran** [comment]
Can you paster error message

**Comment by NambiRamanujam** [comment]
![image](https://cloud.githubusercontent.com/assets/20304446/18815736/a0129cbc-8356-11e6-8eb9-906a7f296db4.png)
PFA of the screenshot of cmd

**Comment by NambiRamanujam** [comment]
Hi,  thank you for your response. It was my mistake. got it solved
