### ISSUE TITLE
I am unable to get rid of the default arrow and only display my custom arrow ?

### ISSUE THREAD

**Issue by aziz-boudi4** [akiran/react-slick#491]
I was able to add my custom Arrow using Bootstrap but the default arrow is still visible and I cannot find a solution to get rid of that default arrow.

My goal is to only display my custom Arrow.

Here is a jsfiddle that reproduce the issue: 
https://jsfiddle.net/20bumb4g/1344/

**Comment by blairanderson** [comment]
This is a CSS problem, not a React problem. 

If you inspect the HTML you can see there are properly only 2 buttons but you have appended a glyph icon AND retained the **old** button styles(which add an icon). 

Remove the styles which add the old icon.

**Comment by blairanderson** [comment]
@akiran this is good to close

**Comment by akiran** [comment]
Thanks @blairanderson 

@aziz-boudi4 props that are passed to custom arrow still have className with css classes for default arrow. You have to override it according to your requirement

**Comment by phoenixbox** [comment]
@aziz-boudi4 came across this myself just now. Specifically, you can the arrow styles using this.

```
.slick-next::before, .slick-prev::before {
  content: none;
}
```

**Comment by decoderstreak** [comment]
That's working finally! Thanks for sharing

**Comment by Mental-Parkour** [comment]
How would you recomend to do this with tailwind?

**Comment by Ignacio1996** [comment]
If you're on next.js, put it on the globals.css file
