### ISSUE TITLE
can we include package version into the build?

### ISSUE THREAD

**Issue by blairanderson** [akiran/react-slick#492]
It would be cool for people actively following this project to have `Slider.VERSION` output the current build version. 

I have some projects write it into a `statics:{}` object on the top level. 

Something like 

``` jsx
const Slider = React.createClass({
  statics: {
    VERSION: package.version
  }
  ... 
})
```

would you accept a pull request for this?

**Comment by akiran** [comment]
Yes,  Please send a PR
