### ISSUE TITLE
Dragging can break the carousel.

### ISSUE THREAD

**Issue by stevemckenzie** [akiran/react-slick#5]
I'm using the latest version of Chrome and can reproduce this in the example.

Slide or drag forward a few items, then drag back. If you attempt to drag when its already easing back into place after a previous drag, you can cause the items to get stuck and dragging no longer has easing. If you attempt to use the buttons at this point they will not work. Refreshing the page seems to be the only way to resolve this.

**Comment by stevemckenzie** [comment]
Actually you can reproduce this by just being a bit aggressive with your dragging. Doesn't matter which way you go.

**Comment by akiran** [comment]
@stevemckenzie ,  I was able to replicate this bug. 
I will fix it soon.

**Comment by akiran** [comment]
@stevemckenzie  Thanks for reporting bugs.

Fixed #5 and #6 issues and made a npm release 0.3.1.

**Comment by stevemckenzie** [comment]
Thanks @akiran !

**Comment by abellee** [comment]
it seems still happend to me.
