### ISSUE TITLE
Vertical scrolling

### ISSUE THREAD

**Issue by milanlandaverde** [akiran/react-slick#50]
Currently testing on Android Nexus 5. 

When I load the [slick](http://kenwheeler.github.io/slick/) demos on the device, scrolling vertically does not break. When I try to scroll from an area where the slider is, it lets me just fine.

When I load the demos for [react-slick](http://webrafter.com/opensource/react-slick) on the device, vertical scrolling is broken. When I try to scroll from an area where the slider is, it doesn't let me. 

The way I encountered this issue was trying to create a greater than full height of the page slider doesn't allow me to scroll on the device to the bottom of the page.

**Comment by akiran** [comment]
Vertical scrolling is no yet implemented in react-slick.
Need to implement it

**Comment by sorrycc** [comment]
:+1: , any progress ?

**Comment by vramana** [comment]
Nope.

**Comment by charlesbodman** [comment]
Much needed

**Comment by dbuarque** [comment]
+1

**Comment by MrChe** [comment]
+1 pls add vetical

**Comment by akiran** [comment]
This feature is added in 0.14 version
Please check and give us feedback

**Comment by tejaswibharadwajp** [comment]
Hi,  I have tried react-slick to render products in my website but It is not allowing me to scroll till the end of product list it automatically pushing me back when I try to see the last product,

Scenario: I have 10 products that I have rendered using React Slick.

Can anyone help me on this issue?

**Comment by pimkle** [comment]
react-slick is now supporting vertical scrolling, the prop is not written in README, but code is as follows:

<Carousel afterChange={pageChange} vertical={true} dotsClass={styles.dotCls} verticalSwiping={true} draggable={true} slidesToScroll={1}
