### ISSUE TITLE
Can we have Two rows of slides when the screen is small ?

### ISSUE THREAD

**Issue by aziz-boudi4** [akiran/react-slick#502]
I am using the responsive option, it's working fine on large device but and I was wondering If I could have two rows of slides when displaying the carousel in mobile/small screens as shown in the below screenshot

Example:

![screen shot 2016-09-30 at 5 45 05 pm](https://cloud.githubusercontent.com/assets/7435015/19010576/3f7670ce-8737-11e6-95d0-18eda0d73f39.png)

**Comment by akiran** [comment]
There is a rows options in slick library which is not yet implements in react-slick.
rows feature will meet yours requirements

**Comment by aziz-boudi4** [comment]
Are you planning to implement rows feature in react-slick ?
If yes when are planning to do that ?
Thanks for your answers

**Comment by amcode** [comment]
👍

**Comment by NoobSkie** [comment]
Has there been any update to this?

**Comment by binarymee** [comment]
I am also in need of this feature.

**Comment by j-baconator** [comment]
Has there been any progress on adding the rows functionality? Also looking to use in the plugin.

**Comment by laveesingh** [comment]
@j-baconator this has been taken into account, this should be in place very soon.

**Comment by sveta4acova** [comment]
What status?

**Comment by laveesingh** [comment]
This feature will be implemented very soon.

**Comment by laveesingh** [comment]
The `rows` and `slidesPerRow` has been implemented and the changes will be released soon enough. You can check if on dev branch.

**Comment by flmuel** [comment]
Will this be merged in master "soon"?

**Comment by Rakeshchaganti** [comment]
@akiran @laveesingh Multiple rows are not working.can you please help me.
Here is my code:
import Slider from "react-slick";
        const settings = {
            className: "center",
           // centerMode: true,
            infinite: true,
            centerPadding: "60px",
            slidesToShow: 3,
            speed: 500,
            rows: 2,
            slidesPerRow: 2
          };
![image](https://user-images.githubusercontent.com/19787823/50923453-0316a900-141b-11e9-94e1-3d9d52706a91.png)

**Comment by maddy2get** [comment]
@akiran @laveesingh, I also encounter an with rows setting. When I set the rows to 0, it crashes. I am using nextjs and when using rows: 0, it runs out of memory.

**Comment by GaneshP25** [comment]
having issue when rows 2 and slides to show  to 2 and try to click next button den also it is repeating the same item in it
