### ISSUE TITLE
Slider container should not have `slick-initialized` class when rendered on server

### ISSUE THREAD

**Issue by jonjaques** [akiran/react-slick#508]
AFAIK, the normal slick implementation does not add `slick-initialized` until the JS has run; I believe this class should be applied via `componentDidMount` to avoid FOUC.

**Comment by gkilian** [comment]
Similar to this issue https://github.com/akiran/react-slick/issues/429

**Comment by laveesingh** [comment]
Referenced commit should take care of it.
