### ISSUE TITLE
Vertical slide for carousel not working

### ISSUE THREAD

**Issue by sudarshanb1988** [akiran/react-slick#510]
We have a react slick carousel with the following settings for the vertical carousel, However it doesn't seem to work . Please help with this

var settings = {
      dots: true,
      infinite: true,
      speed: 500,
      vertical: true,
      arrows: false
    };

**Comment by akiran** [comment]
Which version of slick are you using ?

**Comment by sudarshanb1988** [comment]
Version used is 0.13.6

**Comment by akiran** [comment]
Can you use latest version. it is added 0.14.x

**Comment by ddruker** [comment]
@akiran I am encountering an issue where the vertical slider is only sliding on hover.  Do you know why this could be happening?  I'm using version ^0.14.11.
