### ISSUE TITLE
Attach scroll event to Slider component

### ISSUE THREAD

**Issue by arjunskumar47** [akiran/react-slick#514]
Is there any way in which I can enable the user to scroll horizontally or attach an event for onScroll and modify the slide index ?

I was trying to attach onScroll like this.

```
<Slider {...settings} onScroll={this.handleSliderScroll} >
    <Child />
</Slider>
```

and handleSliderScroll will handle changing the index using `slickGoTo`.

Any leads on how to go on implementing this for my use case or as a feature?

**Comment by akiran** [comment]
You can attach scroll handler on div that wraps slider
```
<div  onScroll={this.handleSliderScroll}>
  <Slider {...settings}>
    <Child />
  </Slider>
</div>
```

**Comment by umerjaved178** [comment]
I want to add extra functionality that swiping across the laptop mouse pad will cause Slider Items to move/slide.
You can see the desired functionality at https://www.apple.com/store

I am not able to find this option in documentation, not even on Github, can anyone help me with that?
