### ISSUE TITLE
Bug with responsive slider; need to support resize from small to large.

### ISSUE THREAD

**Issue by RachelTakeuchi-minted** [akiran/react-slick#522]
I noticed that there is an issue with the responsive slider when the window is small, and then resized to a large window. Ideally, if I am on the last slide in a small window, and then resize the window to be large, the slides should fill up the carousel. See attached gifs. 

**Desired**

![properresponsive](https://cloud.githubusercontent.com/assets/8549034/19662251/93faa9d2-99eb-11e6-9375-0a5120f1b812.gif)

**Actual**

![responsivebug](https://cloud.githubusercontent.com/assets/8549034/19662258/97a0125c-99eb-11e6-95b6-29e90c1c1e82.gif)

**Comment by jeannei** [comment]
To add to this bug, when enlarging the screen and using responsive breakpoints, I'm unable to scroll to the previous elements, resulting in the other elements being unreachable. Using version 0.14.5.

![sliderbug](https://cloud.githubusercontent.com/assets/15200569/19818959/455796e0-9d20-11e6-9d89-71051193af80.gif)

Here are my slider settings : 
``` javascript
const settings = {
 dots: false,
 speed: 500,
 centerMode: false,
  responsive : [{
   breakpoint: 700,
    settings: {
     slidesToShow: 2,
     slidesToScroll: 2,
     }
   }],
   slidesToShow: 3,
   slidesToScroll: 3,
   arrows: true,
   infinite: false
 };

**Comment by tazcarper** [comment]
+1 to this issue. Really would like this fixed.

**Comment by edgarmartinez922** [comment]
Hi,

Solved editting the following file lib/inner-slider.js.

You need to edit the next function onWindowResized,
`  onWindowResized: function onWindowResized() {
    
    this.update(this.props);
    // animating state should be cleared while resizing, otherwise autoplay stops working
    this.setState({
      animating: false
    });
    clearTimeout(this.animationEndCallback);
    delete this.animationEndCallback;
    **if(this.props.slidesToShow > this.props.NumberOfSlides ){
      this.slickGoTo(0);
    }**
  },`

After you need to edit the settings props in your component adding the parameter NumberOfSlides for example:

`        const settings = {
            dots: false,
            infinite: false,
            speed: 500,
            slidesToShow: 5,
            NumberOfSlides: this.props.events.length,
            slidesToScroll: 1,
            initialSlide: 0,
            responsive: [{
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    infinite: false,
                    dots: false
                }
            }, {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    initialSlide: 2
                }
            }, {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                }
            }]
        };`

When window is resized and the SlidesToShow is bigger than your items length Slider goes to position 0

**Comment by rappad** [comment]
any updates on this ?

**Comment by faisalcorra** [comment]
Does anyone resolved this issue?

**Comment by ChCosmin** [comment]
+1 issues still needs solving

**Comment by essaji** [comment]
this is 2021 its still not resolved
