### ISSUE TITLE
jsdom | matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by mbhar6** [akiran/react-slick#523]
Hi 

I am using jsdom with karma for react testing and following is my test file.
The module PDP gallery is importing react-slick.

import React from 'react';
import ReactDOM from 'react-dom';
import ReactTestUtils from 'react-addons-test-utils';
import expect from 'expect';
**import PDPGallery from 'pages/pdp/components/pdp-gallery';**
import configureStore from 'redux-mock-store';
import { Provider } from 'react-redux';
import thunk from 'redux-thunk';

describe('Image Gallery Test', () => {
  
  const store = mockStore(initialState);
  const navThumbnailClick = (abc) => {
    console.log('quick View Handler');
  };
  before(()=>{
  });

    it('Test if pdp gallery gets displayed',() => {
      expect(gallery_list).toExist();
    });    
});

As soon as my react component is loaded the following error comes 

**matchMedia not present, legacy browsers require a polyfill**

Found this solution :
https://github.com/WickyNilliams/enquire.js/issues/82

but not sure where to put this stub - 

window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};

Please help

**Comment by akiran** [comment]
Check solution provided in this issue
https://github.com/akiran/react-slick/issues/472
