### ISSUE TITLE
How to show the images name at the bottom?

### ISSUE THREAD

**Issue by codepandy** [akiran/react-slick#524]
I want to replace the dots with the images's name.

**Comment by akiran** [comment]
You can use customPaging feature
Check this example
https://github.com/akiran/react-slick/blob/master/examples/CustomPaging.js

**Comment by codepandy** [comment]
thank you very much!
var settings = {
            customPaging: function (i) {
                return <span>{['abc','123','hello','nihao'][i]}</span>
            },
            dotsClass: 'slick-dots slick-thumb',
            dots: true,
            infinite: true,
            speed: 500,
            slidesToShow: 1,
            slidesToScroll: 1
        };
