### ISSUE TITLE
Support for Free Scrolling Mode

### ISSUE THREAD

**Issue by adamwan92** [akiran/react-slick#532]
Would like to have support for a "Free Mode" (meaning it doesn't scroll per item), other Slider components have this but React-Slick works for my project.

**Comment by akiran** [comment]
We already have swipe feature . You can drag slides as much as you want and then leave

Check if that works for you

**Comment by adamwan92** [comment]
Hey thanks for the quick reply! Yea, I just found out about the Swipe mode, it works similarly to Free Mode for my use.

Thanks!

**Comment by msurabhi2** [comment]
how to use freescrolling with react-slick?

**Comment by hrkazemi** [comment]
"Swipe" is not the same as "Free Scrolling".
we want slide item stay at wherever position it leaved.

**Comment by alamin00006** [comment]
I am using React Slick but not working free dragging, how to solve this problem

**Comment by anshMouryaa** [comment]
the issue is open since 2023. still haven't get this feature
