### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'targetSlide.offsetWidth')

### ISSUE THREAD

**Issue by jcady** [akiran/react-slick#534]
https://jsfiddle.net/20bumb4g/1542/

Drag slider to the right past bounds to see JS error.

**Comment by akiran** [comment]
@jcady  You are seeing this issue only with centerMode = true and infinite = false right ?

**Comment by jcady** [comment]
@akiran Correct. Also seems to disappear if I set variableWidth = false.

**Comment by roman-yakobnyuk** [comment]
This happens for me too. Is there a fix for it yet?

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.
