### ISSUE TITLE
why somepalce still use `Object.assign`, it cause an error in some browser

### ISSUE THREAD

**Issue by alankell** [akiran/react-slick#535]
https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L26

https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js#L326

**Comment by akiran** [comment]
In which browser you are seeing issue ?
which version of slick are you using ?

**Comment by alankell** [comment]
latest version; IE9 and some android devices

**Comment by chochihim** [comment]
You can add this [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) to solve the problem.

**Comment by akiran** [comment]
We are already using transform-object-assign babel plugin to fix this
https://github.com/akiran/react-slick/blob/master/.babelrc#L6
