### ISSUE TITLE
Ability to stop autoplay after a swipe

### ISSUE THREAD

**Issue by hackhat** [akiran/react-slick#536]
I was wondering if is possible to add the feature to stop autoplay after the carousel has received one swipe.

From: http://baymard.com/blog/homepage-carousel

>3) Auto-rotation should permanently stop after any active user interaction
If the user has interacted with the carousel beyond hover (e.g. actively changed a slide using the carousel controls), the auto-rotation should permanently stop – even when the user isn’t hovering the carousel.

>When the user has actively changed slide by clicking the carousel’s next / previous buttons or slide indicators, the selection is likely to be intentional and should not be changed just because the user decides to check out other parts of the homepage before (potentially) returning to their selected slide.

>A click is fundamentally different from hover, which at best can be used to gauge user focus. A click is an active user request and is a strong indicator of the user’s interests and intent. Therefore, permanently stop auto-rotation once the user begins actively interacting with the carousel, because they might have intentionally left the carousel at that particular slide.

**Comment by jeffreznik** [comment]
Hi, I needed this functionality too so I have submitted #593 

If you use it, just set props pauseOnSwipe and/or pauseOnChange to true

**Comment by afc163** [comment]
I propose a PR might related with this issue: https://github.com/akiran/react-slick/pull/589

**Comment by mpollardFL** [comment]
I'm also interested in this functionality. It may be possible to do using events or methods, but to have it as an option out of the box would be incredibly useful.

**Comment by junaid10521** [comment]
yes, I also need this same functionality
