### ISSUE TITLE
Swipe multiple slides in one motion & triggered animations?

### ISSUE THREAD

**Issue by Ganasist** [akiran/react-slick#538]
1) Is it possible to swipe continuously with some kind of inertia effect like Coverflow? Right now I get smooth swiping, but only one slide at a time. There is no inertial effect or ability to swipe quickly across multiple slides. Is there a setting I can adjust for this?

2) Also, is there a way to trigger animation when clickToScroll is used? Currently I am just jumping directly to the target slide.

**Comment by akiran** [comment]
clickToScroll or slickGoTo ?

**Comment by Ganasist** [comment]
Sorry I'm getting the terms mixed up...

It might be focusOnSelect? It for sure is not slickGoTo since I'm not using that currently to programmatically switch slides. 

What does touchMove enable that's different from focusOnSelect?

swipeToSlide might be what I'm looking for since the definition seems close to a 'coverflow effect', I will try this out more carefully today and see.

**Comment by andrew-whil** [comment]
Hey @Ganasist, were you able to find a solution to your first question? Any direction would be greatly appreciated!

**Comment by jasan-s** [comment]
ANy update guys?

**Comment by Ganasist** [comment]
Hi @andrew-whil I ended up rolling something by hand and not using React Slick. We had very specific requirements for our project and unfortunately could not modify RS enough to meet our needs.

**Comment by vaikutin** [comment]
I am seeking a solution to this issue. It would be great starting auto play mode by fast and hard swiping.
