### ISSUE TITLE
Demo breaks on resize

### ISSUE THREAD

**Issue by RoarkeRandall** [akiran/react-slick#543]
Resize the output window horizontally and it breaks. 

https://jsfiddle.net/kirana/20bumb4g/

**Comment by allantl** [comment]
This seems to be fixed using the latest release (0.14.2).

**Comment by giladbr** [comment]
It seems it's a bug they didn't finish fixing. Here's a workaround that works for me - add the following to React's component that contains the react-slick:

  ```
  constructor() {
        [...]
        this.onWindowResized = this.onWindowResized.bind(this);
    }

    componentDidMount() {
        window.addEventListener('resize', this.onWindowResized);
    }


    componentWillUnmount () {
        window.removeEventListener('resize', this.onWindowResized);
    }

    onWindowResized() { //add debounce for performance?
        this.forceUpdate(); //react's default forceUpdate
    }
```

This will effectively force React to re-render the entire component on window resize, fixing the problem.
* The credit goes to the user [@iandoe](https://github.com/iandoe ) that [wrote about it](https://github.com/akiran/react-slick/issues/67) a year and a half ago...

**Comment by Tonyhark** [comment]
cause this issue appear by ver 0.14.6, so  use version 0.14.5 to avoid this bug

**Comment by kaqiinono** [comment]
将走马灯组件用方法进行定义即可

**Comment by Karl-EdwardFPJeanMehu** [comment]
This is still an unresolved an issue. I'm running v 0.23.1

**Comment by laveesingh** [comment]
@Karl-EdwardFPJeanMehu could you create a codesandbox demo for the same?
