### ISSUE TITLE
Can not click(onClick) button in child component when swipe props is false on mobile.

### ISSUE THREAD

**Issue by leekyuchang** [akiran/react-slick#547]
I'm using react-slick 0.14.5 version.
I can't click button in child component when swipe props is false on mobile.
And also, swipeToSlide is not working on mobile.

```javascript
const settings = {
      dots: false,
      arrows: false,
      draggable: false,
      // swipeToSlide: false,
      swipe: false
};

<Slider {...settings}>
  <div>
    <Main />
  </div>
</Slider>
```

**Comment by mnt** [comment]
I'm also experiencing the same issues. Example of the issue illustrated here:
https://jsfiddle.net/20bumb4g/1627/

**Comment by leekyuchang** [comment]
I modify swipeEnd code(delete e.preventDefault();). So I can click button in child component.
```javascript
swipeEnd: function swipeEnd(e) {
    if (!this.state.dragging) {
      // e.preventDefault();
      return;
    }
    ...
```

**Comment by RyoIkarashi** [comment]
Does the modified code @leekyuchang mentioned above have any side effects?
If no, then I'm gonna create a PR for it. So can you, @akiran just merge the PR?

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases, please try the latest version.
If it still persists, please create a codesandbox demo for the same and reopen it.
