### ISSUE TITLE
SCSS customization only working locally

### ISSUE THREAD

**Issue by skizzo** [akiran/react-slick#548]
This is an issue that can't be reproduced with jsfiddle.

So the thing is, I created 2 .scss files based on [slick.css](https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.css) and [slick-theme.css](https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.css) (note: I removed the references to ajax-loader.gif and the icon font since I don't need it and I can't webpack it otherwise since it throws an error) and include these in my main .scss file. I need to do this in order to customizing the appearance of the dots.

**Locally, everything works as expected, but as soon as I put my project on a web server, the whole slider breaks**, meaning no element of the slick slider comes with the right (or any) styling.

Thanks for any hints.

**Comment by akiran** [comment]
This specific to your project.  
Please post this issue in stackoverflow.com with more details
