### ISSUE TITLE
Dynamic count - not fully rendered

### ISSUE THREAD

**Issue by pionl** [akiran/react-slick#549]
Hi, great package, thank you!
Found a bug: When Slider is initialised with a single item (as a loading placeholder) and updated after fetching the full data the slides are not rendered with new children's (only empty divs). Happens only if `lazyLoad` is `true`. 

Demo: https://jsfiddle.net/5kw0a79n/

Thank you

**Comment by petrgazarov** [comment]
Can confirm - same bug on latest `14.11` version.
Here is the example: https://jsbin.com/cevuvelevi/1/edit?html,css,js,output
