### ISSUE TITLE
Responsive / slideshow width update

### ISSUE THREAD

**Issue by jbracoupeau** [akiran/react-slick#556]
Hi guys, I'm using this awesome slideshow on one of the websites I'm working on.

The only problem I have is that when I resize the window, the slideshow also resizes (as the .slideshow div has width:100%), but the .slick-slide .item dev gets for example width:500.5px (which is the .slick-track width/4)... 
Everytime the .slick-slide .item's width is not a round number, we can see 2 pixels of the next pic on the right side, any parameter to change this behaviour ? I would like to Maths.ceil() it + 1px ;)

Cheers guys.

**Comment by dijonkitchen** [comment]
Related to #221?

**Comment by jbracoupeau** [comment]
yes, I tried to update to 0.14.5 this morning, but it's still there right ?
