### ISSUE TITLE
Fade animation support on mobile?

### ISSUE THREAD

**Issue by kimown** [akiran/react-slick#562]
http://neostack.com/opensource/react-slick

![image](https://cloud.githubusercontent.com/assets/7932380/20711392/63fcf37e-b67a-11e6-9a81-77fe59be31d7.png)

The fade transition don't work properly, does fade animation not support mobile?

**Comment by MimiLau** [comment]
+1

**Comment by codinronan** [comment]
Fade is usually a bad idea on mobile, even our new Galaxy S7 test device chokes on some fade animations, depending on the complexity of the underlying content. 

Saying that, being able to enable/disable it by the developer would be useful.

**Comment by wwsun** [comment]
Any solutions?

**Comment by wwsun** [comment]
Solution: https://github.com/akiran/react-slick/pull/686

**Comment by laveesingh** [comment]
Problems related to fade+swipe were solved in the previous release. I'm closing this for now. If someone still faces any issue similar to this, please feel free to open another one.
