### ISSUE TITLE
Center padding is broken when using non pixel value (e.g. %)

### ISSUE THREAD

**Issue by szimek** [akiran/react-slick#566]
The way slide width is currently calculated is that it parses `centerPadding` value using `parseInt`, which returns an invalid value e.g. when using value like `'30%'`. Here's a demo: https://jsfiddle.net/3at5L45b/.

The way the original slick carousel does it, is that after the padding is applied to the list element, it calculates its width using jQuery `width()` method that returns content width only, i.e. no margin, border or padding (this element uses `box-sizing: border-box;`, so it's a bit tricky to calculate it correctly without jQuery).

UPDATE:
If I change `getWidth` and `getHeight` methods in `mixins/helpers.js` to return content width/height only, like this:
```js
getWidth: function getWidth(elem) {
  var styles = window.getComputedStyle(elem);
  var padding = parseFloat(styles.paddingLeft) + parseFloat(styles.paddingRight);
  return elem.clientWidth - padding;
},
```
and change how `slideWidth` is calculated in `initialize` and `update` methods to this (`listWidth` is a width of list element with applied padding calculated using updated `getWidth` method):
```js
if (!props.vertical) {
  slideWidth = Math.ceil(listWidth / props.slidesToShow);
  } else {
slideWidth = this.getWidth(_reactDom2.default.findDOMNode(this));
}
```
it seems to work better and slide and track widths match those from the original slick carousel 🎉

**Comment by maximusnikulin** [comment]
@szimek Thanks man. It works.

**Comment by szimek** [comment]
@maximusnikulin I released my own version of this package with this fix as `@freeletics/react-slick`. It includes https://github.com/akiran/react-slick/pull/567 and https://github.com/akiran/react-slick/pull/568, but doesn't include changes that were merged to react-slick after I released this custom version.

**Comment by laveesingh** [comment]
Similar issues have already been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.
