### ISSUE TITLE
[Feature Request] - dotsStyle prop

### ISSUE THREAD

**Issue by PolGuixe** [akiran/react-slick#574]
Could we also add a `dotsStyle` to overwrite the default dots style?

**Comment by bassarisse** [comment]
The ability to pass a component to be used for the dots, receiving indexes and other suitable data as props (like it's possible with the arrows), would also be great.

**Comment by akiran** [comment]
You can use customPaging  option to style the dots according to your requirement.
Check this example 
https://github.com/akiran/react-slick/blob/master/examples/CustomPaging.js

**Comment by bassarisse** [comment]
Wow, I overlooked that! Thanks!
