### ISSUE TITLE
Slides not correctly positioned if lazyLoad: true

### ISSUE THREAD

**Issue by urosursej** [akiran/react-slick#575]
I think there is an issue with lazyLoad. If you check jsfiddle example, you'll see that slide items are positioned on the right side.

https://jsfiddle.net/52dL8y6j/3/

But if I set prop slidesToShow on 6, everything is okey:
https://jsfiddle.net/52dL8y6j/

**Comment by laveesingh** [comment]
Similar issues have been fixed previous releases. Such issues don't exist anymore.
If anyone still faces a similar problem, please feel free to reopen the issue.
