### ISSUE TITLE
Swipe option to falsedisables all clicks within contained elements

### ISSUE THREAD

**Issue by malliapi** [akiran/react-slick#577]
Passing the swipe option as false disables all click events in the containing elements! For example, stopping the carousel and having an element with clickable buttons inside no longer works! How can i fix this?

**Comment by malliapi** [comment]
This is very urgent as our project is due to go live soon and this is a show blocker!

**Comment by malliapi** [comment]
#571

**Comment by jeffwilliamsdev** [comment]
We are having the same issue.  Does anyone have the solve?

**Comment by malliapi** [comment]
@jeffwilliamsdev There is a PR #571 fixing this but i haven't looked at the solution. We need the guys to merge if they agree with it.
