### ISSUE TITLE
Missing features from jQuery Slick Plugin

### ISSUE THREAD

**Issue by vramana** [akiran/react-slick#58]
Slick Settings
- [ ] accessibility
- [x] adaptiveHeight
- [x] autoplay
- [x] autoplaySpeed
- [x] centerMode
- [x] centerPadding
- [x] cssEase
- [ ] customPaging
- [x] dots
- [x] dotsClass
- [x] draggable
- [x] easing
- [x] edgeFriction
- [x] fade
- [x] arrows
- [ ] appendArrows
- [ ] appendDots
- [ ] mobileFirst
- [x] prevArrow
- [x] nextArrow
- [x] infinite
- [x] initialSlide
- [x] lazyLoad
- [ ] pauseOnHover
- [ ] pauseOnDotsHover
- [ ] respondTo
- [x] responsive
- [ ] rows
- [ ] slide
- [ ] slidesPerRow
- [x] slidesToShow
- [x] slidesToScroll
- [x] speed
- [x] swipe
- [ ] swipeToSlide
- [x] touchMove
- [x] touchThreshold
- [x] useCSS
- [x] variableWidth
- [ ] vertical
- [ ] verticalSwiping
- [x] rtl
- [x] waitForAnimate
- [ ] zIndex

Slick Events
 - [x] afterChange
 - [x] beforeChange
 - [x] breakpoint
 - [ ] destroy
 - [x] edge
 - [x] init
 - [ ] reInit
 - [ ] setPosition
 - [x] swipe
 
Slick Methods
- [ ] unslick
- [ ] slickAdd and slickRemove
- [ ] slickFilter and slickUnfilter
- [ ] slickPlay and slickPause
- [ ] slickNext and slickPrev
- [x] slickGoTo
- [ ] slickCurrentSlide
- [ ] slickGetOption and slickSetOption

**Comment by vramana** [comment]
@akiran When you have time, check if I have missed mentioning or marked as done.

**Comment by josephMG** [comment]
Hi, is there missing useTransform?

**Comment by jezmck** [comment]
This isn't completed 😕.
