### ISSUE TITLE
Testing react-slick with mocha produces NaN width.

### ISSUE THREAD

**Issue by coreyleelarson** [akiran/react-slick#580]
When testing a component which uses react-slick with Mocha, we get the following log in our output:
```
Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `ProductDetailImage`.
```

The culprit appears to be _mixins/trackHelper.js_ where **spec.slideCount**, **spec.slidesToShow**, and **spec.slideWidth** are all undefined when calculating **trackWidth**.

My specific tests don't fail, and this doesn't appear to be a problem when viewing the slider in a browser. Is there something I'm missing?

**Comment by coreyleelarson** [comment]
UPDATE:

After further investigation, it appears _src/mixins/helpers.js_ **helpers.getWidth** is returning undefined.
**elem.getBoundingClientRect().width** is 0 so it's attempting to fallback to **elem.offsetWidth** which is undefined.

**Comment by saysmaster** [comment]
Any progress on this? I get this error and I see no slider on my screen.

**Comment by coreyleelarson** [comment]
@saysmaster - We were getting this error specifically in tests, but didn't have a problem in the browser. I had merged a minor fix for it with PR https://github.com/akiran/react-slick/pull/581
