### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by VeeteshJain** [akiran/react-slick#583]
we are getting this error on Chrome Mobile 54.0.2840 Android and on page transitions (I have ```react-slick``` only on my landing page).

```
TypeError: Cannot read property 'getBoundingClientRect' of null
  at getWidth(~/react-slick/lib/mixins/helpers.js:108:0)
  at update(~/react-slick/lib/mixins/helpers.js:71:0)
  at apply(~/react-slick/lib/inner-slider.js:137:0)
  at apply(raven.js:379:28)
  at nrWrapper(/:13:14888)
```

<img width="980" alt="screen shot 2016-12-19 at 10 29 18 am" src="https://cloud.githubusercontent.com/assets/6864682/21301715/09ced6ea-c5d6-11e6-87b9-11d8246f226a.png">

**Comment by AlmogRnD** [comment]
I'm getting the same error in the browser

**Comment by EvgeniyLyakhov** [comment]
+1

**Comment by akiran** [comment]
Same as #555
