### ISSUE TITLE
[request] Setting for scroll direction

### ISSUE THREAD

**Issue by jlem** [akiran/react-slick#59]
It would be great if you could define up,down,left,right,random as scroll directions.

**Comment by vramana** [comment]
@jlem What do you mean by random? A transition that happens in random direction??

**Comment by jlem** [comment]
Yes. One application I'm using this for is to display a carousel of misc image and marketing slides, and there are three of these carousels on the page as "tiles". Right now the only way I can differentiate their movement is to use different transition times between slides so they don't look like they're all moving in sync and in the same direction.

It would be nice if I could just let them transition in any direction they choose so that all the transitions feel more "organic"

**Comment by dashed** [comment]
I was hoping to be able to change direction :(  Swiping right like in tinder.
