### ISSUE TITLE
Carousel sliding while drag-scrolling vertically on a touch device

### ISSUE THREAD

**Issue by semenets** [akiran/react-slick#598]
Link to original issue: https://github.com/kenwheeler/slick/pull/2521

In the link above you can see description of the bug. I think it's very important to fix that in react-slick too. So can we merge that changes in react-slick? I am ready to do that, if @akiran or somebody else accept this idea.

**Comment by vitalim** [comment]
I agree with semenets - I think it's important - struggling with it as well on my app

**Comment by vbarnwal** [comment]
Any update on this issue? I am worried about this issue. Please give a solution for this.

**Comment by vbarnwal** [comment]
Anybody have solution for this issue on react-slick node_modules?

**Comment by vijaybarnwal** [comment]
Any update on this?????

**Comment by vitalim** [comment]
Try this for now:
https://www.npmjs.com/package/react-slick-with-mobile-in-mind
Thanks to semenets

**Comment by vijaybarnwal** [comment]
Vitalim, What is the changes you have made in given package? Any changes required for settings in slider tag?

**Comment by vijaybarnwal** [comment]
Hi semenets,

Can you please guide me is any change required for settings in slider tag?

Thanks,
Vijay

**Comment by vijaybarnwal** [comment]
Vitalim, Is it working for you?

**Comment by vitalim** [comment]
Yes, I'm using it just like the regular react-slick

**Comment by vijaybarnwal** [comment]
Have you pass any parameter to slider settings for this issue?

**Comment by vitalim** [comment]
This is the settings i'm using:
  const settings = {
    arrows: false,
    infinite: false,
  }

**Comment by vijaybarnwal** [comment]
I am getting same issue when scrolling vertically carousal moves/slides horizontally.

Is any fix have you done in https://www.npmjs.com/package/react-slick-with-mobile-in-mind?

Thanks,
Vijay

**Comment by naltatis** [comment]
The [pull request](https://github.com/kenwheeler/slick/pull/2521) has just been merged in original slick. Can someone port it?

**Comment by hustlerism** [comment]
Having the same issue as well in my Mobile App.

**Comment by ryota-murakami** [comment]
I pushed the changes I made to solve this problem in my application to PR.
Please review if it is possible. Thanks!

**Comment by emphaticsunshine** [comment]
I see the issue is closed but was it resolved?

**Comment by ryota-murakami** [comment]
@emphaticsunshine I've submitted PR about 2 and half years ago.
According to the [comment](https://github.com/akiran/react-slick/pull/758#issuecomment-376048150), this is fixed version 0.22.2 later.

**Comment by fonkgoku** [comment]
Possible duplicate: https://github.com/akiran/react-slick/issues/1240
