### ISSUE TITLE
Failed to compile - module not found `react`

### ISSUE THREAD

**Issue by heaversm** [akiran/react-slick#599]
Hi - I'm using react-create-app successfully to render react code, but when I attempt to import react-slick, I get the following error:

```
Failed to compile.

Error in /Users/mikeheavers/~/react-slick/lib/slider.js
Module not found: 'react' in /Users/mikeheavers/node_modules/react-slick/lib

 @ /Users/mikeheavers/~/react-slick/lib/slider.js 5:13-29
```

I installed react-slick with `npm install react-slick`, and it appears in my node_modules directory along with `react` folder.

Line 5 of slider.js in react-slic/lib is:

`var _react = require('react');` 

I'm not sure how that require works, but it seems like it is searching for react in the /lib folder?

Let me know what I can do to sort it out.

Here's how I'm attempting to call everything:

```
import React, { Component } from 'react';
import './App.css';
import Slider from 'react-slick';


class SimpleSlider extends Component{
  render() {
    const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1
    };

    return (
      <Slider {...settings}>
        <div><h3>1</h3></div>
        <div><h3>2</h3></div>
        <div><h3>3</h3></div>
        <div><h3>4</h3></div>
        <div><h3>5</h3></div>
        <div><h3>6</h3></div>
      </Slider>
    );
  }
}
```

[JSFiddle](https://jsfiddle.net/8852onbw/)

**Comment by akiran** [comment]
This could be a problem with your build step.
It is not an issue with react-slick
