### ISSUE TITLE
Dragging can't actually be disabled.

### ISSUE THREAD

**Issue by stevemckenzie** [akiran/react-slick#6]
You have a props.draggable but it's never actually used anywhere.

**Comment by akiran** [comment]
Fixed this in commit 837466b02a744ae4b9e723f440379b861c379c1f

swipe = false, will disable swipe or dragging feature on both mobile and desktop.
swipe = true & draggable = false will disable dragging on desktop devices and swipe works on mobile.

**Comment by benkauffman** [comment]
what if I wanted to disable dragging on mobile but enable it for desktop?

**Comment by antkiewiczk** [comment]
@benkauffman you can still use responsive settings, same as with e.g slidesToShow
