### ISSUE TITLE
Size does not get calcutated in some cases

### ISSUE THREAD

**Issue by optiguy** [akiran/react-slick#600]
On IE11, when i maximize the window, the content of the slider should get calculated, so after the resize of the window, I can see two slides, which are too small for the slider.

Please see : http://oi64.tinypic.com/15gxshl.jpg

Version: 0.14.5
OS : Win7 + Win10
Browser :  IE11
Result : Sometime, the width doesn't get calculated when i maximize the window
Expected:  The width of the slider and all slides, should be updated when i maximize the window.

This is the elements which doesn't get calulated with a new width : 
```
<div class="slick-track" data-reactid=".0.0.1.0" style="opacity: 1; transform: translate3d(-1024px, 0px, 0px); width: 1024;">
```
And the slides : 
```
<div data-index="1" class="slick-slide" tabindex="-1" style="outline: medium none; width: 512px;" data-reactid=".0.0.1.0.$original1">
```

Also i couldn't reproduce the error with 0.15.0, but since a new bug with the width is present in https://jsfiddle.net/kirana/20bumb4g/ 

Try to maxmimize the window and see what happening with the width. It get's added everytime, instead of changed. So suddenly we're ending up with a width of a million pixels.
Version: 0.15.0
OS : Win10
Browser :  IE11, FF
Result : The width get's added eveytime i maximize or minimize the window.
Expected:  The width of the slider and all slides, should be updated when I resize the window.

**Comment by giladbr** [comment]
Happens to me too on FF, Chrome (didn't check IE).
