### ISSUE TITLE
Unable to edit form content inside slide when "swipe": false (in touch devices)

### ISSUE THREAD

**Issue by venky1090** [akiran/react-slick#610]
Hi,

When Swipe: false settings is enabled carousel slide is freezes as expected but the content inside is becoming non editable in touch devices. We have form elements inside slide.

Replicated the issue here. https://jsfiddle.net/7074a4qo/2/
Note: Enable mobile debugging in dev tools
1. Try to enter text in input, its not accepting.
2. Even swipe is false dot and next/prev buttons working.
(ideally its seems correct but in generally one would like to stop sliding in all scenarios when swipe is false)

Actually exiting template is not working old react reference. Please update.

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.
