### ISSUE TITLE
Input radio element inside child component of slider cannot be selected

### ISSUE THREAD

**Issue by amithgeorge** [akiran/react-slick#612]
https://jsfiddle.net/amithgeorge/v7vuma3n/2/

The children of the slider are instances of the `Hello` component wrapped in individual divs. The `Hello` component renders a couple of input radio elements. Selecting them doesn't update the checked state of the DOM. The state is getting updated, the react component is getting right prop, the react toolbar shows the input element getting the correct prop, but the dom element's checked property is false.

**Comment by mikkelwf** [comment]
Any update on this..?

**Comment by victsant** [comment]
Did anyone find a solution for this yet ?

**Comment by trueter** [comment]
Very annoying thing to deal with until you figure out where to look for help..

**Comment by laveesingh** [comment]
I think that radio/checkbox are being selected as expected. Please feel free to regenerate and reopen the issue if you disagree.
