### ISSUE TITLE
If slides' amount is less than slidesToShow, when drag the position is not good

### ISSUE THREAD

**Issue by dingcaiying** [akiran/react-slick#615]
Here is an example: https://jsfiddle.net/cyiiin/arcrcxck/1/

When you drag, the image will move to right or left (from opposite position), is there any way to prevent this behavior?

**Comment by apitzele** [comment]
@dingcaiying - without forking the repo, the only way I was able to get around this was to restrict swipe events (via the swipe prop) to only occur when the number of items on the carousel exceeds slidesToShow.

the downside of this appoach is that you lose the animations that occur on swipe events when the total items don't exceed slidesToShow

**Comment by dingcaiying** [comment]
@apitzele The solution works for me, losing the animation is acceptable. Anyway it's better than having the strange behavior  ¯\_(ツ)_/¯. Thanks !
