### ISSUE TITLE
slickGoTo method

### ISSUE THREAD

**Issue by eduAbreu** [akiran/react-slick#618]
Will this method be updated?

**Comment by akiran** [comment]
Check this example for latest implementation of slickGoTo
https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

**Comment by yantakus** [comment]
@akiran this example doesn't work, just checked here: http://neostack.com/opensource/react-slick

**Comment by palamago** [comment]
Hi @akiran 
The @yantakus'  comment is accurate. The slickGoTo api method is not working on the examples (also in my code). Any ideas why?

**Comment by aperkaz** [comment]
Hi, any updates on this? I really need this functionality for a project...

**Comment by richardweb23** [comment]
Hi @akiran!
The method is not working because the check is incorrect.
You are checking as isNa**n**(slide) and not as isNa**N**(slide).
Will this method be updated?

Thank you!

**Comment by laveesingh** [comment]
It's been fixed with a version update.

**Comment by andy14312** [comment]
Hi, 
Say, i have ten slidesToShow and i'm say slickGoTo(4). the fourth slide is still in view, but still after i call the function, it becomes the first slide in the slider. is there any way that i restrict it? And make it the first slide only when it is not in the view?
