### ISSUE TITLE
Dots show up in IE as weird symbols

### ISSUE THREAD

**Issue by brandon-arnold** [akiran/react-slick#620]
For some reason, only in IE11, the dots at the bottom of carousels on [my website](http://brandonarnold.com) are showing up as weird characters, as below. Any idea what would cause this? It is **not** the behavior in the [standard JS Fiddle](https://jsfiddle.net/kirana/20bumb4g/). 

![2017-02-01](https://cloud.githubusercontent.com/assets/7827691/22536904/6f089a56-e8cb-11e6-95a4-0cac882acf78.png)

**Comment by brandon-arnold** [comment]
Apparently my fonts do not have the appropriate dots character. Unfortunately I haven't found out how to select the ```slick-dots``` class and override the font inherit correctly yet.

**Comment by dben89x** [comment]
Happening here too, on Chrome...

**Comment by oyeanuj** [comment]
I'm still seeing this even after adding the font-family. Any ideas @akiran @laveesingh ?

@dben89x Did you ever find a solution for this?
