### ISSUE TITLE
Questions regarding changelog and versioning

### ISSUE THREAD

**Issue by saviomuc** [akiran/react-slick#627]
Hello,

thank you for this great port. 
I have two questions:

**Versioning**
Which versioning scheme does this project follow? Semantic Versioning? (http://semver.org/). 
I am asking because it's not quite clear to me if a version update from i.e. 0.14.5 to 0.14.6 is a big change or not. If I check the commit history I can't see a clear pattern which defines when a version is bumped. Can you maybe clarify that? 

**Changelog**
Also where can I find the changelog? Unfortunately I cannot finde a CHANGELOG.md or anything similar. 

Thanks so much.

**Comment by bostrom** [comment]
I'd also like to see a changelog, please!

**Comment by laveesingh** [comment]
Changelog has been added to dev branch, it should soon be merged to master.
