### ISSUE TITLE
getting current slide index

### ISSUE THREAD

**Issue by csmichaelellis** [akiran/react-slick#629]
i was wondering if there is any way to get the current slide index?

**Comment by flyupstudio** [comment]
Try this solutions:
on component create method for example

nextClick: function(e){
        //alert('next');
        console.log(e);
}

on render function I added like this
render: function() {
.....

var settings = {
                dots: false,
                infinite: true,
                speed: 500,
                swipeToSlide: false,
                arrows: true,
                slidesToShow: 2,
                afterChange: this.nextClick,
                slidesToScroll: 2
            };

return (<Slider {...settings}/>)
}

And I got on console 2 4 6 8 10 (Because I show 2 slider Item in one time
And you can keep from "e" variable current Slider Item

I hope it's help you

**Comment by LiHwsqh** [comment]
I set the `autoplay ` with `true`, and try to use `React.setState` in `afterChange`.
But the strange thing is the Slick just 'autoplay' **once** and the browser console shows nothing. When i remove `setState`, everything will goes rightly.
So, what happened?

**Comment by VladPoe** [comment]
use afterChange method, it allows to get currentSlide index as callback function's parameter

```
afterChangeHandler(currentSlide) {
        this.props.updateInitialSlide(currentSlide);
}

<Slider {...settings} afterChange={this.afterChangeHandler}>
```

**Comment by ravinder-aika** [comment]
In react slick afterChange method returns the current index
 afterChange: index => {
    console.log(index);
  },

**Comment by Anna-kozianowska** [comment]
Example saving the current index into currentIndex state:
 
```
 const [currentIndex, setCurrentIndex] = useState(0);
 
  <SlickSlider
        beforeChange={(currentSlide, nextSlide) => {
              setCurrentIndex(nextSlide);
          }}
    >
```
