### ISSUE TITLE
Jumping behavior when waitForAnimate is set to false

### ISSUE THREAD

**Issue by rlayeh** [akiran/react-slick#632]
I encountered a strange "jumping" behavior, when waitForAnimate is set to false and there are more than 1 element visible at the same time.

Link to fiddle: https://jsfiddle.net/xx3mc124/1/

Please click on the 3rd dot and very quickly (while animation is still ongoing) click on the 1st dot.

**Comment by GuyPaddock** [comment]
@rlayeh May also be related to https://github.com/akiran/react-slick/issues/1415.
