### ISSUE TITLE
Working fine but getting one warning in console

### ISSUE THREAD

**Issue by jpjitendrapal** [akiran/react-slick#636]
Warning: Unknown props `currentSlide`, `slideCount` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by PrevArrow)
    in PrevArrow (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
![slickerror](https://cloud.githubusercontent.com/assets/6689741/22881145/30e02cd2-f20b-11e6-9d90-2a06a5edd872.PNG)

Please let me know what I am missing?

**Comment by luandro** [comment]
Same as #623. Current solution is to downgrade to `0.14.2 `. Being fixed with pull #624

**Comment by krismeister** [comment]
I only needed to rollback to `0.14.5` to not receive this warning.

**Comment by NullDivision** [comment]
The issue has been fixed in v0.14.7. Can you confirm please?
