### ISSUE TITLE
Cant get react-slick to work

### ISSUE THREAD

**Issue by Montoo** [akiran/react-slick#637]
I installed react-slick using _npm install --save react-slick_ and _npm install slick carousel_ for the styling. However, I cant get react-slick to work. I implemented the same code used in jfiddle like this:
![untitled](https://cloud.githubusercontent.com/assets/7222476/22931903/b6e62b7c-f2c6-11e6-8480-1f0f08082f2d.png)

But when I run my program I get the following result:
![untitled2](https://cloud.githubusercontent.com/assets/7222476/22932803/84cbadb2-f2c9-11e6-825d-4bd0f62f9c84.png)

**Comment by kimiyang** [comment]
I also encountered similar issue, I just copy the example code in GitHub example
```
var React = require('react');
var Slider = require('react-slick');
var SimpleSlider = React.createClass({
  render: function () {
    var settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1
    };
    return (
      <Slider {...settings}>
        <div><h3>1</h3></div>
        <div><h3>2</h3></div>
        <div><h3>3</h3></div>
        <div><h3>4</h3></div>
        <div><h3>5</h3></div>
        <div><h3>6</h3></div>
      </Slider>
    );
  }
});
```
<img width="387" alt="slick" src="https://cloud.githubusercontent.com/assets/5389141/23006986/2fc10dda-f440-11e6-8f21-d01367be839c.png">

anyone encountered before?

**Comment by pmdownie** [comment]
Have you included the slick.css file in the head of the public index.html file?

**Comment by kimiyang** [comment]
@pmdownie yes i added still not working, anyway I switched to use nuka-carousel which also satisfies my need.

**Comment by FoxWhite** [comment]
you should include styles from slick-carousel.
I've got it like this (using webpack): 
```
import Slider      from 'react-slick';
import 'slick-carousel/slick/slick-theme.css';
import 'slick-carousel/slick/slick.css';
```

or, you can add these styles in html if you don't use any bundlers

**Comment by kimiyang** [comment]
@FoxWhite I tried, still doesn't work, but thanks

**Comment by krstffr** [comment]
I get this error when adding the code example from the readme file (and also I seem to get the same error as the people above):

```
Warning: Unknown props `currentSlide`, `slideCount` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by PrevArrow)
    in PrevArrow (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
    in Slider (at carousel-flickety.jsx.js:5)
    in Unknown (at vote-on-submissions-template-container.jsx.js:99)
    in div (at vote-on-submissions-template-container.jsx.js:92)
    in div (at row.jsx.js:6)
    in ChildWrapper (at row.jsx.js:30)
    in div (at row.jsx.js:23)
    in Row (at vote-on-submissions-template-container.jsx.js:91)
    in div (at page-part.jsx.js:10)
    in PagePart (at vote-on-submissions-template-container.jsx.js:83)
    in div (at vote-on-submissions-template-container.jsx.js:50)
    in SubmissionPageTemplateContainer (created by Connect(SubmissionPageTemplateContainer))
    in Connect(SubmissionPageTemplateContainer) (at page-container.jsx.js:32)
    in div (at page-container.jsx.js:52)
    in PageContainer (created by Connect(PageContainer))
    in Connect(PageContainer) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (at index.js:23)
    in Provider (at index.js:22)
    in RouterContainer (at index.js:33)
```

**Comment by suheltanveer** [comment]
@FoxWhite , can you share your webpack config please. Thanks

**Comment by gautammadaan** [comment]
@kimiyang After importing the CSS correctly, make sure that each of the inner slides that you want to display are wrapped inside another `<div>` apart from it's own div.

**Comment by matherton** [comment]
I am unable to get this working as a component in react - is this even supported in the latest version of React?

**Comment by akiran** [comment]
@matherton  Check this codesandbox https://codesandbox.io/s/ppwkk5l6xx

It is working fine with react 16.5.2

**Comment by matherton** [comment]
It's ok - I end up writing my own component using blog.alexdevro.com/create-simple-carousel-react-js. I think it was due to the way I was exporting my es6 classes which is why I could not get the example code to work. Thanks for your response.

**Comment by zeel97** [comment]
I had the same issue. I imported the following to the index.css file in my project:
@import "~slick-carousel/slick/slick.css";
@import "~slick-carousel/slick/slick-theme.css";

**Comment by rahuls360** [comment]
npm install slick-carousel --save

import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";

Apparently we need to install slick-carousel manually

**Comment by guilhermedeoliveira** [comment]
I had the same problem, @rahuls360 solution worked.

**Comment by lahiruz** [comment]
Hi, I'm new to this react. When we do like the way mentioned  @rahuls360 , is react only imports the css files?. Because I am wondering when we install slick carousel, will it also ships the slick carousel codebase with my application code?

Please help me to understand this?

**Comment by DanielAdek** [comment]
Hi guys, I'm having this same issue, and have not figured out on how to get it working. I'm using react version 16.8. Does anyone have an idea on how to get it work on this new version of react?
Thanks in advance!

**Comment by voigtd** [comment]
> npm install slick-carousel --save
> 
> import "slick-carousel/slick/slick.css";
> import "slick-carousel/slick/slick-theme.css";
> 
> Apparently we need to install slick-carousel manually

This should be in the react-slick docs.

**Comment by Ashpar2001** [comment]
> I am unable to get this working as a component in react - is this even supported in the latest version of React? I have included the CSS in the component so there are no errors and it just stretches any page I include the component in to be massive with both X and Y scroll bars that go on forever. My advice to anyone looking for a quick carousel implementation in your react project is not to waste time using slick-carousel.

I am still getting this kind of output. Yes I did npm install react-slick and slick-carousel, yet this is happening ... any help would be really appreciated

**Comment by findnizam** [comment]
Any one found the solution for this?

**Comment by adriandifelice** [comment]
Installing slick-carousel and importing it on the component did it for me.

<img width="871" alt="Captura de pantalla 2021-04-14 a las 17 36 21" src="https://user-images.githubusercontent.com/53629060/114783661-573b3100-9d7a-11eb-9930-f12c345dca84.png">

**Comment by kevohm** [comment]
The reason for this behavior is using display flex on the parent of the Slider component.
