### ISSUE TITLE
[Request] Add function who recalculate position on browser resize.

### ISSUE THREAD

**Issue by spartDev** [akiran/react-slick#64]
It would be great to implement like current **jQuery-Slick** a resize function who recalculate position of each item on browser resize.
Have you planned to implement this ?

**Comment by akiran** [comment]
We are trying to add all the features of jquery slick to this project, hopefully by the end of the month

**Comment by spartDev** [comment]
Awesome ! thx

**Comment by akiran** [comment]
Fixed this in 0.6.3 release
