### ISSUE TITLE
Using components as children

### ISSUE THREAD

**Issue by alaingoga** [akiran/react-slick#640]
I'm trying to use array of components as children inside slider but the the slider is not been bound.
[Here is the issue replicated](https://jsfiddle.net/alaingoga/20bumb4g/2168/)
Can you please advice what is the best way of doing this, if everything is ok with the code.
Thanks.

**Comment by alaingoga** [comment]
I found a work around using a wrapper div for each component slide:
```const Cpns = [
  <div><Cpn letter="A" /></div>, 
  <div><Cpn letter="B" /><div>,  
  <div><Cpn letter="C" /><div>
];```

**Comment by jarzuaga** [comment]
@akiran Is there a fix for this that doesn't require that workaround above? Having to wrap everything on a div is a bit arduous.

**Comment by andrefox333** [comment]
Yeah adding a <div></div> around my sub component seems a bit weird...

**Comment by akiran** [comment]
If you pass props to the root element in the custom slide, you don't need to warp with extra div
https://github.com/akiran/react-slick/blob/master/examples/CustomSlides.js#L8
