### ISSUE TITLE
With Chai Test: Adding react-slick throws error - matchMedia not present

### ISSUE THREAD

**Issue by steelow** [akiran/react-slick#645]
After adding the react-slick slider to my webpack project, my chai test began to fail with
C:\project\proj\js\node_modules\enquire.js\dist\enquire.js:226
            throw new Error('matchMedia not present, legacy browsers require a polyfill');
            ^
Error: matchMedia not present, legacy browsers require a polyfill
    at Object.MediaQueryDispatch (C:\project\proj\js\node_modules\enquire.js\dist\enquire.js:226:19)
    at C:\project\proj\js\node_modules\enquire.js\dist\enquire.js:291:9
    at i (C:\project\proj\js\node_modules\enquire.js\dist\enquire.js:11:20)
    at Object.<anonymous> (C:\project\proj\js\node_modules\enquire.js\dist\enquire.js:21:2)

The only fix for this problem that the author of the slider component recommended here is for jest. I have tried that in my environment but it did not work. 

[http://stackoverflow.com/questions/42346998/with-chai-test-adding-react-slick-throws-error-matchmedia-not-present](url)

**Comment by steelow** [comment]
I ended up throwing this react-slick slider into the garbage and creating my own slider instead. The react-slick slider is useless if only because unlike most npm packages out there, it managed to entangled itself with some arcane dependency. Perhaps platform specific requirement which the creator failed to communicate to prospective users. Completely useless unless you intend to test with jest.

**Comment by matheusrocha89** [comment]
@steelow I fixed for me just adding on my mocha setup:
```javascript
global.window.matchMedia = window.matchMedia || (() => ({}));
global.matchMedia = global.window.matchMedia;
```

**Comment by dschinkel** [comment]
nobody using react-slick should have to care anything about Jest tests in here. This is not something any consumer of react-slick should have to be dependent on. This is still a major issue which I've posted here: WickyNilliams/enquire.js#169. In our tests, I don't use Jest, I hate Jest. I use Mocha. But regardless our projects shouldn't even be aware of Jest Tests or dependencies related to react-slick testing.

@matheusrocha89 nobody should have to do anything to their _own_ test setup just to test react-slick with an error related to _their_ testing.
