### ISSUE TITLE
Cannot disable swipe when reach last slide

### ISSUE THREAD

**Issue by Eliceeeeeee** [akiran/react-slick#647]
When slidesToShow set more than 1, the infinite set to false.
But when I swipe it, it will continue swipe until last slide with some gap.
How can stop it continue swipe to next when already at last slide.

![issue](https://cloud.githubusercontent.com/assets/11729283/23152930/7560377c-f840-11e6-8f8d-b0ac6d62ff3e.PNG)

https://jsfiddle.net/ELICE1226/ynLayzqd/#&togetherjs=sSalNtksIO

**Comment by ayal** [comment]
There is an undocumented "edgeFriction" option in settings, set it to 0:
 <Slider dots infinite={false} edgeFriction={0} ... />

**Comment by edencorbin** [comment]
This fixed this issue, I have a strange possibly related issue on the last slide (only on right), if I drag to the right, with or without this setting it jumps back a few slides, I might open a separate ticket on that.

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases. This issue doesn't exist anymore. Other similar issues have been fixed by commit: 38d16a9f567d37ee6c6a6cfdba6c3db76bfaed9d this change will be released soon.

**Comment by Zmiterr** [comment]
> Это устранило эту проблему, у меня есть странная, возможно, связанная проблема на последнем слайде (только справа), если я перетаскиваю вправо, с этим параметром или без него он перескакивает на несколько слайдов назад, я мог бы открыть отдельный тикет по этому поводу.



> This fixed this issue, I have a strange possibly related issue on the last slide (only on right), if I drag to the right, with or without this setting it jumps back a few slides, I might open a separate ticket on that.

do you fix it?
