### ISSUE TITLE
Netflix style animation on hover(question)

### ISSUE THREAD

**Issue by jasan-s** [akiran/react-slick#649]
Hey guys just started playing around with this lib. Is there any options for adding hover animations similar to netflix?

**Comment by harklee** [comment]
I was wondering the same. 

A crude, hacky way is just to apply CSS scale animation to the "slick-slide" class to enlarge and z-index to lift it up over neighboring slides, but the container does not allow overflowing, so the edges will be cropped. If you set the overflow to visible for the container than you will end up with the previous and next pages rendered (when infinite:true). 

Obviously the best way is to override the onMouseEnter handler to change size and push away the rest of the slides by the increased width / 2. Hopefully this option becomes available.

**Comment by treyhoover** [comment]
I used this hack to fix the overflow issue.

```
.slick-list {
  padding: 100px 0;
  margin: -100px 0;
}
```

It's not great, but it seemed to be the best option I could find.
