### ISSUE TITLE
ResponsiveMixin throws an exception if no breakpoints are set on componentWillUnmount

### ISSUE THREAD

**Issue by hannesj** [akiran/react-slick#65]
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at ResponsiveMixin.componentWillUnmount (webpack:///./~/react-slick/~/react-responsive-mixin/index.js?:22:34)

**Comment by vramana** [comment]
@hannesj Can you give little more details of your problem?? How can we reproduce this??

**Comment by hannesj** [comment]
Hi @vramana,

Currently the [slider.jsx](https://github.com/akiran/react-slick/blob/master/src/slider.jsx#L10) uses [react-responsive-mixin](https://github.com/akiran/react-responsive-mixin). If you create a react-slick component without any breakpoints and later on try to unmount it, it tries to [remove all media handlers](https://github.com/akiran/react-responsive-mixin/blob/master/index.js#L22), but as none have been created, the array it tries to loop though doesn't exits, thus throws the error.
