### ISSUE TITLE
react-slick and ES6

### ISSUE THREAD

**Issue by cairnsjoe** [akiran/react-slick#652]
Does this component work with ES6 is the first question I have? I am getting some strange behavior like some of the properties are stating that they are functions and not what they are defined in you documentation, for example speed when I define it as React.PropTypes.int as per your documentation I get the following error 

csfWidgets-external.js:33520Warning: Failed prop type: Carousel: prop type `speed` is invalid; it must be a function, usually from React.PropTypes.
    in Carousel

Also I can never get the carousel to only show one slide:

    render() {
        return(
            <div>
                <Slider {...this.props}>
                    <div><img src="http://placekitten.com/g/300/300" /></div>
                    <div><img src="http://placekitten.com/g/300/200" /></div>
                    <div><img src="http://placekitten.com/g/400/400" /></div>
                    <div><img src="http://placekitten.com/g/400/300" /></div>
                    <div><img src="http://placekitten.com/g/400/200" /></div>
                    <div><img src="http://placekitten.com/g/200/200" /></div>
                </Slider>
            </div>
         );
    }

Carousel.defaultProps = {
    id: 'carouselContainer',
    content: '',
    dots: true,
    infinite: true,
    adaptiveHeight: false,
    arrows: true,
    slidesToShow: 1
};

I believe that I have defined things correctly and I have also included both of the CSS files that I need.

Please let me know what I might be missing here or if there is a issue with this component and ES6.

Thank you in advance for looking into this matter.

**Comment by cairnsjoe** [comment]
If I remove all the property definitions from my class it seems to fix the issue

**Comment by cairnsjoe** [comment]
The error messages go away but the system still does not show only 1 image and the arrows do not show either

**Comment by ongmin** [comment]
I have the same problem.
