### ISSUE TITLE
Each picture inside the carousel overflows into the next picture

### ISSUE THREAD

**Issue by patrickhuang94** [akiran/react-slick#655]
I'm using the default example code to put in my images: simply wrapping it inside the Slider component. In the right ~10px margin of the current picture, you can see the next picture - it's sort of leaking into the current picture. However, upon downsizing the browser window and resizing it back to the original full screen, the second picture in the carousel no longer overflows.

**Comment by joinjoohny** [comment]
Same issue

**Comment by fafafariba** [comment]
Same

**Comment by adeelibr** [comment]
Same

**Comment by msiadak** [comment]
I'm seeing similar behavior.  It seems like it fixes itself after a browser resize event, but I can't even figure out a hacky way to do this consistently in React.

**Comment by adeelibr** [comment]
I have found a solution simply in your CSS in your body tag do `something` like this

```
body {
    overflow-x: hidden;
}
```

I hope it helps anyone having this trouble.

**Comment by marhalpert** [comment]
It happens to me when it is server side rendered.

**Comment by adeelibr** [comment]
@marhalpert Have you tried the CSS trick I used at my end to resolve this bug. 
```
body {
    overflow-x: hidden
}
```

**Comment by marhalpert** [comment]
Mate that worked for when it is not server-side rendered.

**Comment by adeelibr** [comment]
Well I hope someone comes up with a solution for this. :)

**Comment by brownsmith** [comment]
It's not ideal, but I found forcing the component to update after mounting essentially mimics what happens when the browser window is resized, and leaves it looking as it should.

`componentDidMount() {
    setTimeout(() => {
      this.forceUpdate();
    }, 0);
  }`

**Comment by KevinTaron** [comment]
@brownsmith thx 4 this solution. Not perfect but still works.

**Comment by kagadek** [comment]
Still having the bug - after some digging I think it calculates the carousel element width and transform wrong - when page with carousel has a scrollbar everything looks fine. 

With and without scrollbar the slick-track  and carousel elements have the same widths, so without scrollbar image of the next element overlaps with offset equal to scrollbar width. Screens below based on jsfiddle demo of react-slick.

![with-scrollbar](https://user-images.githubusercontent.com/31310248/29663644-6676ff6c-88cc-11e7-857c-4f232fdef598.png)
![without-scrollbar](https://user-images.githubusercontent.com/31310248/29663645-667a572a-88cc-11e7-97d6-2bb6187141fe.png)

**Comment by epenabella** [comment]
create an overlay div to block the 1px strip of the next pic

technically speaking:
set parent div position relative, create child div width 1px position aboslute top 0, right 0 background color same as background behind carousel

:)

**Comment by alfredrafael** [comment]
epenabella, can you provide a demo? Thanks :)

**Comment by epenabella** [comment]
parent is the div that you put the carousel in, child is another div as sibling to carousel

CSS:
.parent { position: relative; }
.child {width: 1px; height: 100%, position: absolute; top: 0px, right: 0px; background-color: #<color behind carousel>}

**Comment by sbaqthiar209** [comment]
I am using single image and I am targeting active slide. This will scale the active slide and hide extra space.

`:global(.slick-active){
          scale: 1.1 1;
  }`
