### ISSUE TITLE
Responsive settings not working?

### ISSUE THREAD

**Issue by thomasbritton** [akiran/react-slick#656]
I'm not sure responsive setting is working properly.

Here is my code: 

```
var carouselSettings = {
    arrows: false,
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    swipeToSlide: true,
    centerMode: true,
    centerPadding: "15px",
    autoPlay: false,
    adaptiveHeight: true,
    responsive: [
      {
        breakpoint: 768, settings: "unslick",
      },
    ],
  };

  return (
    <div className="us-container home-page-promo-slot-wrapper">
      {title()}

      <div className="us-clearfix">
        <Slider {...carouselSettings}>
          {comparisonSummaries}
        </Slider>
      </div>
    </div>
  );
```

What I'm expecting to happen is when the browser window gets to 768 or above the layout will fallback to default styles from the CSS and have elements such as the `dots` etc to disappear.

Can't see that I'm doing anything wrong according to the documentation.

Anyone have any ideas?

Thanks

**Comment by lizlove** [comment]
I'm having the same issue... any luck finding a solution? 

tnx

**Comment by PachiSystems** [comment]
Same here. Any solution found for this?

**Comment by thomasbritton** [comment]
Ok, so after finding some time to re-visit this I  have kind of got it where I needed it to be.

So in your breakpoint objects the integer you set is effectivley a `max-width` media query, so anything you specify will be applied until you reach that value, so only set what you want to happen everywhere in the default settings and set everything else in each breakpoint object.

Hope this helps @lizlove @PachiSystems 

Here is my code as it stands at the moment and it roughly there:

```
var carouselSettings = {
  speed: 500,
  centerMode: true,
  centerPadding: "15px",
  autoPlay: false,
  responsive: [
    {
      breakpoint: 768,
      settings: {
        dots: true,
        arrows: true,
        infinite: true,
        slidesToScroll: 1,
        swipeToSlide: true,
      }
    },
    {
      breakpoint: 992,
      settings: 'unslick',
    }
  ]
};
```

**Comment by Rterrell25** [comment]
This doesn't work if you are trying to update slides to show etc.... needs to be reopened

**Comment by shantanuSakpal** [comment]
i also had the same issue, turns out  i just had to restart the dev server (npm run dev) . sometimes all you have to do is restart, lol.

**Comment by Nivu789** [comment]
> i also had the same issue, turns out i just had to restart the dev server (npm run dev) . sometimes all you have to do is restart, lol.

lol, this worked
