### ISSUE TITLE
prevArrow onClick does not work as expected

### ISSUE THREAD

**Issue by jmacioszek** [akiran/react-slick#658]
https://jsfiddle.net/20bumb4g/2278/

Go to last slide then try to slide back with previous arrow. In beforeChange callback, current slide index is 12 and next slide index is also 12 instead of 4, hence I can't go back to previous slide.

**Comment by janelle-boyd** [comment]
I think something is blocking it from being clicked on. I would try maybe setting the z-index to something like 1000. This would move that element to the top. I know I'm a year late, but I hope this helps someone :)

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases. If someone disagrees, please feel free to reopen the issue.
