### ISSUE TITLE
variableWidth: wrong first slide and problem with height

### ISSUE THREAD

**Issue by damien916** [akiran/react-slick#664]
Hello,

There is the jsfiddle with the problems: https://jsfiddle.net/cw4qdevL/

The first slide is index -1, and slick-track width is too small

There is no problem when infinite is set to false

**Comment by lionel95200x** [comment]
Have you found a solution ?

**Comment by damien916** [comment]
Hello,
I have wrapped my slides into containers with a width of 100% (no more variableWidth, slidesToShow:1, slidesToScroll:1)

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases. Please feel free to request reopen if disagree.
