### ISSUE TITLE
[Bug] Slides not showing unless includes an empty div

### ISSUE THREAD

**Issue by xc4330** [akiran/react-slick#666]
Hi,

I have the following slider which is showing a list of vehicles.

```javascript    
<Slider {...settings}>
    {this.props.vehicles.map(vehicle =>
      <div className="vehicle-card-container">
        <VehicleCard vehicle={vehicle} />
      </div>
     )
   }
</Slider>
```
However the slides will not appear unless I add an empty div before the list like this:

```javascript    
<Slider {...settings}>
    {this.props.vehicles.map(vehicle =>
      <div className="vehicle-card-container">
        <VehicleCard vehicle={vehicle} />
      </div>
     )
   }
   <div />
</Slider>
```
Anyone has faced the same issue? Thank you so much!

**Comment by NullDivision** [comment]
Could you also give the props you're passing to `Slider` and the number of elements you're trying to render please?

**Comment by xc4330** [comment]
Found the solution in https://github.com/akiran/react-slick/issues/504.
