### ISSUE TITLE
Responsive not on the window but on the component container

### ISSUE THREAD

**Issue by cmalonzo** [akiran/react-slick#672]
The responsive breakpoints for the carousel listen to resizes of the window. Is it possible to implement an interface or a change so that I can either:
- listen to resizes of the container div of the carousel
- allow the consumer of the carousel to define for themselves the responsive breakpoints, the listeners upon which to listen on resizes or changes to the width of the components

For extensibility, I'd prefer the second solution as it allows for more freedom for consumers to solve for their various scenarios.

**Comment by WilliamHolmes** [comment]
Had a similar issue recently.
Ended up using [eq.js](https://www.npmjs.com/package/eq.js) then creating the new settings object to be passed on render.
