### ISSUE TITLE
Show a small portion of the next slide (like Airbnb)

### ISSUE THREAD

**Issue by andrefox333** [akiran/react-slick#674]
Hi, anyone found a way to show a small section of the next hidden slide, like how the Airbnb guys do it on smaller resolution?

<img width="1072" alt="screen shot 2017-03-18 at 8 30 38 am" src="https://cloud.githubusercontent.com/assets/5422172/24073472/3bbeb51a-0bb5-11e7-97fc-7c2bad3d1e06.png">

**Comment by andrefox333** [comment]
Easy enough :) 
```css
.slick-list {
 margin-left: -20px;
}
```

**Comment by jpabbuehl** [comment]
Hi

same question, but when vertical is true?
margin-top and margin-bottom just shift up and down and overlay arrows

**Comment by yoopoong96** [comment]
The answer you provided is not good. You can set slideToShow: 4.1

**Comment by maddhruv** [comment]
>The answer you provided is not good. You can set slideToShow: 4.1

you can set `slidesToShow` setting to a decimal value as well

**Comment by sehrun** [comment]
you need to add `infinite:false` to `slidesToShow` otherwise part of previous slide also will be shown
