### ISSUE TITLE
How to override the main className of Slider ?

### ISSUE THREAD

**Issue by alduro** [akiran/react-slick#675]
I'm using less ( webpack loader )  and overriding Slider styles in our own bootstrap theme based on Less. But it does not work. I guess there are some issues with less webpack loader order and styleName slider.

```
import React from 'react';
import Slider from 'react-slick';
import cssModules from 'react-css-modules';
import 'slick-carousel';
import PrevArrow from './PrevArrow';
import NextArrow from './NextArrow';
import '../../styles/slick.less';
import styles from '../../styles/index.less';

const HomeSlider = () => (
  <div styleName="slider-holder">
    <div styleName="slider">   // <----- Main Style that I'm overriding but it does not work
      <Slider {...settings}>
        <div>
          <a href="#">
```

in particular `styles/slick.less` has: ( in fact this doesn't work except when adding stylesheets in index.html ).
```
@import '~slick-carousel/slick/slick.less';
@import '~slick-carousel/slick/slick-theme.less';
```

and `styles/index.less` our theme:
```
@import '~bootstrap-less/bootstrap/bootstrap.less';
@import './newstyle.less';
```

Thanks in advance. Any help would be great.

**Comment by alduro** [comment]
The problem is here I guess in class inner-slider.js:
Classes 'slick-initialized', 'slick-slider' are fixed so there is no way to be overrides using react-ccs-modules. This is really hard to be extended in React.

```
    var className = classnames('slick-initialized', 'slick-slider', this.props.className, {
      'slick-vertical': this.props.vertical,
    });
```
Is the solution using fixed CSS in index.html  ?

**Comment by alduro** [comment]
Did work using create-react-app and importing CSS styles in index.js.

**Comment by havantuan** [comment]
<div class="slick-track" style="opacity: 1;transform: translate3d(0px, 0px, 0px);height: 22931.7px;">
how to override css? I want to disable height 22931.7

**Comment by pabloluz** [comment]
I was running into a similar issue, where styles weren't being applied, once I'm using CSS modules. Just imported styles via JS and it worked!

`import 'slick-carousel/slick/slick.scss'`
`import 'slick-carousel/slick/slick-theme.scss`

**Comment by St3f4NS** [comment]
I didnt had this problem before, since updating to latest version it showed up. Couldn't override with custom css.

Fixed it by using styled components and wrapping slider in it.

Here is the example.
```import React, { Component } from 'react'
import Slider from 'react-slick-slider'
import styled from 'styled-components'

const SliderWrap = styled.div`
    .slick-slider {
        height: 100vh;
        background-color: var(--brand-black);
        .slick-list {
            .slick-track {
                .slick-slider.slide_item {
                    height: 100vh;
                    width: 100vw;
                    background-size: cover;
                    background-repeat: no-repeat;
                }
            }
        }
    }
`

const settings = {
    arrows: false,
    slidesToShow: 1,
    focusOnSelect: true,
    verticalSwiping: false,
    swipe: false,
    swipeToSlide: false,
    dragable: true,
    autoplay: true,
    autoplaySpeed: 2000,
    fade: true,
}

class HeroSlider extends Component {
    render() {
        return (
            <SliderWrap>
                <Slider {...settings}>
                    {this.props.slides.map(slide => (
                        <div
                            className="slide_item"
                            key={slide.id}
                            style={{
                                backgroundImage: `url(${slide.imageUrl})`,
                            }}
                        />
                    ))}
                </Slider>
            </SliderWrap>
        )
    }
}```

**Comment by send2abhishek** [comment]
> I didnt have this problem before, since updating to latest version it showed up. Couldn't override with custom css.
> 
> Fixed it by using styled components and wrapping slider in it.
> 
> Here is the example.
> 
> ```
> import Slider from 'react-slick-slider'
> import styled from 'styled-components'
> 
> const SliderWrap = styled.div`
>     .slick-slider {
>         height: 100vh;
>         background-color: var(--brand-black);
>         .slick-list {
>             .slick-track {
>                 .slick-slider.slide_item {
>                     height: 100vh;
>                     width: 100vw;
>                     background-size: cover;
>                     background-repeat: no-repeat;
>                 }
>             }
>         }
>     }
> `
> 
> const settings = {
>     arrows: false,
>     slidesToShow: 1,
>     focusOnSelect: true,
>     verticalSwiping: false,
>     swipe: false,
>     swipeToSlide: false,
>     dragable: true,
>     autoplay: true,
>     autoplaySpeed: 2000,
>     fade: true,
> }
> 
> class HeroSlider extends Component {
>     render() {
>         return (
>             <SliderWrap>
>                 <Slider {...settings}>
>                     {this.props.slides.map(slide => (
>                         <div
>                             className="slide_item"
>                             key={slide.id}
>                             style={{
>                                 backgroundImage: `url(${slide.imageUrl})`,
>                             }}
>                         />
>                     ))}
>                 </Slider>
>             </SliderWrap>
>         )
>     }
> }```
> ```

many many thanks it helped

**Comment by LiterallyCollective** [comment]
> I didnt have this problem before, since updating to latest version it showed up. Couldn't override with custom css.
> 
> Fixed it by using styled components and wrapping slider in it.
> 
> Here is the example.
> 
> ```
> import Slider from 'react-slick-slider'
> import styled from 'styled-components'
> 
> const SliderWrap = styled.div`
>     .slick-slider {
>         height: 100vh;
>         background-color: var(--brand-black);
>         .slick-list {
>             .slick-track {
>                 .slick-slider.slide_item {
>                     height: 100vh;
>                     width: 100vw;
>                     background-size: cover;
>                     background-repeat: no-repeat;
>                 }
>             }
>         }
>     }
> `
> 
> const settings = {
>     arrows: false,
>     slidesToShow: 1,
>     focusOnSelect: true,
>     verticalSwiping: false,
>     swipe: false,
>     swipeToSlide: false,
>     dragable: true,
>     autoplay: true,
>     autoplaySpeed: 2000,
>     fade: true,
> }
> 
> class HeroSlider extends Component {
>     render() {
>         return (
>             <SliderWrap>
>                 <Slider {...settings}>
>                     {this.props.slides.map(slide => (
>                         <div
>                             className="slide_item"
>                             key={slide.id}
>                             style={{
>                                 backgroundImage: `url(${slide.imageUrl})`,
>                             }}
>                         />
>                     ))}
>                 </Slider>
>             </SliderWrap>
>         )
>     }
> }```
> ```

It's a really nice solution.

**Comment by pedrokuper** [comment]
> I didnt have this problem before, since updating to latest version it showed up. Couldn't override with custom css.
> 
> Fixed it by using styled components and wrapping slider in it.
> 
> Here is the example.
> 
> ```
> import Slider from 'react-slick-slider'
> import styled from 'styled-components'
> 
> const SliderWrap = styled.div`
>     .slick-slider {
>         height: 100vh;
>         background-color: var(--brand-black);
>         .slick-list {
>             .slick-track {
>                 .slick-slider.slide_item {
>                     height: 100vh;
>                     width: 100vw;
>                     background-size: cover;
>                     background-repeat: no-repeat;
>                 }
>             }
>         }
>     }
> `
> 
> const settings = {
>     arrows: false,
>     slidesToShow: 1,
>     focusOnSelect: true,
>     verticalSwiping: false,
>     swipe: false,
>     swipeToSlide: false,
>     dragable: true,
>     autoplay: true,
>     autoplaySpeed: 2000,
>     fade: true,
> }
> 
> class HeroSlider extends Component {
>     render() {
>         return (
>             <SliderWrap>
>                 <Slider {...settings}>
>                     {this.props.slides.map(slide => (
>                         <div
>                             className="slide_item"
>                             key={slide.id}
>                             style={{
>                                 backgroundImage: `url(${slide.imageUrl})`,
>                             }}
>                         />
>                     ))}
>                 </Slider>
>             </SliderWrap>
>         )
>     }
> }```
> ```

I've tried this and it worked partially.  I added the style i wanted but i broke how the arrows works. When u click, u need to double click to function and infinite stop working. 

Did you have this issue? 
This was working on  Nextjs/react with functional components

**Comment by St3f4NS** [comment]
> > I didnt have this problem before, since updating to latest version it showed up. Couldn't override with custom css.
> > Fixed it by using styled components and wrapping slider in it.
> > Here is the example.
> > ```
> > import Slider from 'react-slick-slider'
> > import styled from 'styled-components'
> > 
> > const SliderWrap = styled.div`
> >     .slick-slider {
> >         height: 100vh;
> >         background-color: var(--brand-black);
> >         .slick-list {
> >             .slick-track {
> >                 .slick-slider.slide_item {
> >                     height: 100vh;
> >                     width: 100vw;
> >                     background-size: cover;
> >                     background-repeat: no-repeat;
> >                 }
> >             }
> >         }
> >     }
> > `
> > 
> > const settings = {
> >     arrows: false,
> >     slidesToShow: 1,
> >     focusOnSelect: true,
> >     verticalSwiping: false,
> >     swipe: false,
> >     swipeToSlide: false,
> >     dragable: true,
> >     autoplay: true,
> >     autoplaySpeed: 2000,
> >     fade: true,
> > }
> > 
> > class HeroSlider extends Component {
> >     render() {
> >         return (
> >             <SliderWrap>
> >                 <Slider {...settings}>
> >                     {this.props.slides.map(slide => (
> >                         <div
> >                             className="slide_item"
> >                             key={slide.id}
> >                             style={{
> >                                 backgroundImage: `url(${slide.imageUrl})`,
> >                             }}
> >                         />
> >                     ))}
> >                 </Slider>
> >             </SliderWrap>
> >         )
> >     }
> > }```
> > ```
> 
> I've tried this and it worked partially. I added the style i wanted but i broke how the arrows works. When u click, u need to double click to function and infinite stoped working.
> 
> Did you have this issue?
> This was working on Nextjs/react with functional components

I think the issue is functional components.

**Comment by Cranberryair-conditionin** [comment]
> > I didnt have this problem before, since updating to latest version it showed up. Couldn't override with custom css.
> > Fixed it by using styled components and wrapping slider in it.
> > Here is the example.
> > ```
> > import Slider from 'react-slick-slider'
> > import styled from 'styled-components'
> > 
> > const SliderWrap = styled.div`
> >     .slick-slider {
> >         height: 100vh;
> >         background-color: var(--brand-black);
> >         .slick-list {
> >             .slick-track {
> >                 .slick-slider.slide_item {
> >                     height: 100vh;
> >                     width: 100vw;
> >                     background-size: cover;
> >                     background-repeat: no-repeat;
> >                 }
> >             }
> >         }
> >     }
> > `
> > 
> > const settings = {
> >     arrows: false,
> >     slidesToShow: 1,
> >     focusOnSelect: true,
> >     verticalSwiping: false,
> >     swipe: false,
> >     swipeToSlide: false,
> >     dragable: true,
> >     autoplay: true,
> >     autoplaySpeed: 2000,
> >     fade: true,
> > }
> > 
> > class HeroSlider extends Component {
> >     render() {
> >         return (
> >             <SliderWrap>
> >                 <Slider {...settings}>
> >                     {this.props.slides.map(slide => (
> >                         <div
> >                             className="slide_item"
> >                             key={slide.id}
> >                             style={{
> >                                 backgroundImage: `url(${slide.imageUrl})`,
> >                             }}
> >                         />
> >                     ))}
> >                 </Slider>
> >             </SliderWrap>
> >         )
> >     }
> > }```
> > ```
> 
> It's a really nice solution.





https://snorkel39.github.io/3oYcZtKQmhmKpc5040vHptty1_Rqh6MG--UdDPcKMR5QSapHPv8PZQqPAv0VRx5kNfnbLmwdMK05o2h6n98/
