### ISSUE TITLE
slickGoTo as prop for PureComponent 

### ISSUE THREAD

**Issue by briziel** [akiran/react-slick#676]
Hi,

It would help a lot to keep the ability to pass slider position as int in the props. I use the slider in a pure component and it would be a mess to care about the livecylce hooks. Any chances to prevent deprecation?

best regards :)

**Comment by akiran** [comment]
If you want to set slider position only once, you can use initialSlide option.

**Comment by barnc** [comment]
@akiran  is there no way to manage manage the slider state in a pure component after mounting?
