### ISSUE TITLE
Swiping past last slide jumps back a few slides

### ISSUE THREAD

**Issue by edencorbin** [akiran/react-slick#678]
Only on the right (last) slide (or bottom if vertical mode) swiping jumps back a few slides. Is this a bug or is there a workaround?

**Comment by edencorbin** [comment]
I think this was my bad found some ways around it, closing.

**Comment by DennnyGreb** [comment]
@edencorbin can you explain how did you solve that issue?

**Comment by edencorbin** [comment]
I can't remember exactly what it was, are you experiencing the same issue? If you wanted to paste some code where your having the issue I could compare.

**Comment by DennnyGreb** [comment]
@edencorbin const settings = {
            centerMode: true,
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: false,
            infinite: false,
            className: "letter-slider"
} - my settings variable, slider is in center mode and 3 items are displayed at once(center item has other styles). When I try to slide right last slide it jumps back on count of slides in addition to slidesToShow value.

**Comment by edencorbin** [comment]
Our issue is the same, thus I'm reopening the ticket. I'm a bit fuzzy still on what I did, reviewing the code it looks like I enabled infinite, and also have slidesToScroll and slidesToShow consistently the same. This is a workaround though, and not a solution, so I'm re-opening this perhaps the devs can comment on it.

**Comment by lchreal6** [comment]
+1   I have the same problem
