### ISSUE TITLE
Issue getting the active slide because of duplicated .slick-active class

### ISSUE THREAD

**Issue by sandrina-p** [akiran/react-slick#683]
I'm struggling to get the correct `data-index` of the current active slide (`.slick-active`) because there is always two elements with that class what cause a bug on the last slide.

```
//...
afterChange: function() {
  console.log(document.getElementsByClassName('slick-active')[0].getAttribute('data-index'));
},
//...
```
This works except on last slide that instead of output `3`, it outpus `-1`.

You can see it [here](https://jsfiddle.net/z7rphr7m/1/).

Is there a direct/easy way to always get the correct active slide ?

**Comment by n0umankhan** [comment]
any solution on this ?
