### ISSUE TITLE
Don't slide in slides that haven't loaded yet

### ISSUE THREAD

**Issue by wmertens** [akiran/react-slick#688]
Would it be possible to either:
* check that all images in a new slide have loaded before sliding it into view, or
* provide slides with a callback to call when they are ready?

**Comment by akiran** [comment]
You have to implement custom slide component to meet this requirement
https://github.com/akiran/react-slick/blob/master/examples/CustomSlides.js

**Comment by wmertens** [comment]
But, won't the slider keep showing next images, without waiting for the CustomSlide to complete loading? How can a CustomSlide preload images without being skipped?

**Comment by wmertens** [comment]
Would it be possible to add `preloading` to the API so slides are first loaded with `preload` attribute, rendering off-screen, and they have to call `onReady` when the load completed?

**Comment by zhulduz** [comment]
@wmertens maybe it is not actual anymore :smiley:
There is a library https://github.com/mbrevda/react-image which can preload images before display component
