### ISSUE TITLE
Unique identifiers on buttons (accessibility)

### ISSUE THREAD

**Issue by theovalsand** [akiran/react-slick#689]
Example:
https://jsfiddle.net/wzk976L4/

In the case where more than one carousel would be present on the page at once it introduces accessiblity concerns. Since each there is nothing unique on the buttons for Previous/Next or the Dots to help distinguish the buttons for a non-sighted user. This introduces a issue because good practice is that every link or button text be unique so the action can be distinguished. As it stands the non-sighted user would encounter two Next buttons in the example above, but have no context that they control two different carousels.

Ideally if there was setting that could be passed to give a unique id for the carousel, then this could be added at the end button text.

For example if my first slider carousel had a id of Dog Breeds and another Cat Breeds, then the button could read "Next (Dog Breeds)" or  Dog Breeds Next. And the dots could read Dog Breeds Page 1.  Optionally, if you provided the option to wrap the unique identifier content with a class name around the <span> containing the unique identifier, then the developer could use CSS to hide that text from the sighted user, but leave it there for screen readers to still pick up.

**Comment by akiran** [comment]
You can use custom arrow features for this requirement 
https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js
