### ISSUE TITLE
Reach End of Slideshow Callback

### ISSUE THREAD

**Issue by jennykortina** [akiran/react-slick#692]
Hi,

I need to know when I get to the end of the slider to append more slides.  There is an "edge" callback (which is what I think I need but if there is a dif way to tell when you reach end open to that) in the [slick documentation](http://kenwheeler.github.io/slick/).

Their Definition:
edge
slick, direction
Fires when an edge is overscrolled in non-infinite mode.

Their code:
```
// On edge hit
$('.your-element').on('edge', function(event, slick, direction){
  console.log('edge was hit')
});
```

Is this the correct callback to know when we hit the end of the slideshow, if so how do we get it to work?  If not what can we use to know we are at the end?

Thanks!

**Comment by kiranbabu189** [comment]
is there a pure javascript method to find the end of slide for react-slick

**Comment by chadsteele** [comment]
So?  Is there non jQuery React oriented solution?
