### ISSUE TITLE
Updating State Causes Slider go Back to Initial Slide

### ISSUE THREAD

**Issue by jennykortina** [akiran/react-slick#693]
Whenever I update the state/store (and it changes), the slider returns to the initial slide.  Gist here:

https://gist.github.com/jennykortina/62c807f86e5a8bb50ff392018eb1231f

**Comment by tehviking** [comment]
I'm having the same issue using Redux-UI, anytime I call `this.props.updateUI('currentImageIndex', currentSlide)` it seems to reset to the initial slide about 50% of the time. I'm confused for sure!

**Comment by barnc** [comment]
Also getting this.

**Comment by fr-miura** [comment]
+1

**Comment by ArcQ** [comment]
really annoying issue! quick fix before https://github.com/akiran/react-slick/pull/700 is merged in is to wrap the slider in a component that always checks for shouldComponentUpdate, i have mine returning false since my slider isn't dependent on any parent updates

**Comment by laveesingh** [comment]
Issues related to this have been fixed in previous releases. Please feel free to request reopen if disagree.
