### ISSUE TITLE
inconsistent animation for infinite scroll when lazyload enabled

### ISSUE THREAD

**Issue by dalimian** [akiran/react-slick#698]
normally, in all cases when lazyload is not enabled, clicking next when on last slide will animate "forward" to first slide as if the first slide repeats after last slide.

when lazyload is enabled, however, same action animates backward though all slides in between from last to first.

https://www.screencast.com/t/BtgPNqrU7

both animation styles are ok, but animation style should be a separate config option, independent of lazyload option.

apprears this code block is the cause for this inconsistent behaviour - https://www.screencast.com/t/6YBbG7CXr4H

**Comment by rafaelderolez** [comment]
@akiran any word on this? I a fix for this has been merged before but I am still seeing this behaviour.

**Comment by gkilian** [comment]
This issue looks to be fixed with this commit. https://github.com/akiran/react-slick/commit/7d8eeb5059a9f39931573913332f9785172f5a64#diff-ae7d3bfc927feef9e44923133997daef
