### ISSUE TITLE
Examples page proposal

### ISSUE THREAD

**Issue by kvolkovich-sc** [akiran/react-slick#703]
Hi! =)

![showroom-demo](https://raw.githubusercontent.com/OpusCapitaBES/js-react-showroom-client/93f035a18e6c35de46bfca299a32708ce9e52c1e/docs/demo.gif)

Recently we release this project.

https://github.com/OpusCapitaBES/js-react-showroom-client

It allows to write documentation in markdown and run all docs in sandbox with code examples.
It often useful to have possibility to play with components at web page before use it in project.

Do you interested in adding interactivity to your examples page?)
I can make it and send you pull-request. Of course it can be styled as you wish. :blush:

**Comment by akiran** [comment]
Sorry, We couldn't use it at the moment
