### ISSUE TITLE
Setting fade = true displays only one slide

### ISSUE THREAD

**Issue by jdmswong** [akiran/react-slick#705]
```
const settings = {
  fade: true,
  slidesToShow: 3,
  slidesToScroll: 3,
};
```
```
          <Slider {...settings}>
            {(() => {
              return (new Array(6).fill(null).map((item, i) => {
                return <h3>{i}</h3>;
              }));
            })()}
          </Slider>
```

slider fades but only displays the first slide, changing `fade` to false displays all 3.

[JSFiddle demo](https://jsfiddle.net/20bumb4g/2554/)

**Comment by jdmswong** [comment]
Refreshing this issue... This is a significant bug

**Comment by pgomez89** [comment]
Same bug. @jdmswong Can you fixed it? Thanks!!

**Comment by Morganjackson** [comment]
Has anyone had any success finding a workaround for this?

**Comment by matthax** [comment]
[Recreated in template](https://jsfiddle.net/r6xjy131/) - I'm looking into a workaround, I'll update this if I find anything...

**Comment by czinco** [comment]
Make sure you don't have two of the exact same carousel slides that have the exact same image, it fooled me and made me look into this problem resulting in landing on this page.

**Comment by laveesingh** [comment]
In case of fade=true, slidesToShow has been enforced to 1.

**Comment by jclark-mossio** [comment]
I was able to solve this with a little work around. 
`    $('.slider').slick({
      slidesToShow : 5,
      infinite: true,
      autoplay : false,
    });

    window.setInterval(function(){
      $('.slider .slick-active').removeClass('show-logo');

      setTimeout(function(){
        $('.slider').slick('slickNext');
      }, 500);

      setTimeout(function(){
        $('.slider .slick-active').addClass('show-logo');
      }, 1000);


    }, 5000);

`

`  .slick-active, .slick-slide {
        opacity: 0;
        transition: all 0.4s ease;
        transform: translate(0, 10px);

        &.show-logo {
          opacity: 1;
          transform: translate(0);
        }
      }`

**Comment by AnitaErnszt** [comment]
This is still a bug inn2021, and documentation doesn't even warn about it :(

**Comment by moonbyt3** [comment]
Yup, I'm facing it currently too :D

**Comment by oneknucklehead** [comment]
it's 2023, and this issue still persists. I guess the fade option should be remove from the documentation until it is resolved as it creates a lot of confusion while coding

**Comment by Rahul-Avtrix** [comment]
it's 2024 and this is still an issue, when we use fade= true we cant show more than one slide
