### ISSUE TITLE
No way to add styles on Custom Arrows

### ISSUE THREAD

**Issue by rafaelderolez** [akiran/react-slick#706]
`nextArrow: <button style={{ marginRight: '100px' }}>next btn</button>,`

The styles on the custom arrows are being overwritten by `style: {display: 'block'},` from `src/arrows.js`.

[Jsfiddle here](https://jsfiddle.net/zrbv9mnk/)

**Comment by edencorbin** [comment]
I did not have a problem adding custom style to arrows. Try making a separate component class, heres my funny working test code:

```
import React, { Component } from 'react';
  
class RightNavButton extends React.Component {
  render() {
    const { top, currentSlide, slideCount, ...rest } = this.props
    return <button onClick={this.props.onClick} style={{zIndex: 100, position: 'absolute', width: '3vh', height: '3vh', left: 0, top: 300, background: 'blue'}}>Hey</button>;
  }
}

export default RightNavButton
```

and in my slider options:

```
nextArrow: <RightNavButton />,
```

**Comment by rafaelderolez** [comment]
Ah I hadn't tried using a separate component yet. I'll give that a shot @edencorbin
