### ISSUE TITLE
Not able to swipe at firefox.

### ISSUE THREAD

**Issue by Divyansh1605** [akiran/react-slick#707]
Swipe is Working fine At chrome, but giving trouble when trying to swipe at firefox

**Comment by ArmandoKenneth** [comment]
Any updates on this? Still having this issue.

Even the JsFiddle demo has this problem.
https://jsfiddle.net/kirana/20bumb4g/

**Comment by Divyansh1605** [comment]
nope, this issue still persist.

**Comment by jmoulin-vp** [comment]
the only way I found to fix this is to do a preventDefault on dragstart event

**Comment by laveesingh** [comment]
Commit: 2dc76131e5cc5451c20e18d20f115301dfa57260 should fix this. Changes will be released soon.
