### ISSUE TITLE
React v15.5 warning with React Slick v0.14.7 (React.createClass deprecated)

### ISSUE THREAD

**Issue by cbengtson85** [akiran/react-slick#711]
Warning: Track: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement

The issue is coming from /react-slick/lib/track.js

Will this be updated to use es6 classes?

**Comment by wilbert-abreu** [comment]
PR: #715

**Comment by akiran** [comment]
Fixed in react-slick 0.14.8

**Comment by erasmo-marin** [comment]
Just to make a point because no one will read this on the PR

Migration to es6 classes is required in the future because importing createClass will increase bundle size for people that doesn't use it.
Is it too complicated? since you use mixins and other stuff harder to migrate.
