### ISSUE TITLE
TypeError: null is not an object (evaluating 'elem.getBoundingClientRect')

### ISSUE THREAD

**Issue by arronhunt** [akiran/react-slick#712]
On import, throws that error and fails to work out of the box.

**Comment by alex-di** [comment]
`Cannot read property 'getBoundingClientRect' of null`
seems quite the same

**Comment by nasushkov** [comment]
I have the same issue. It looks like slickList.querySelector('[data-index="0"]') is empty in my case

**Comment by Carlows** [comment]
I'm getting `Cannot read property 'getBoundingClientRect' of null` on my Jest tests and can't seem to be able to get around it

**Comment by andrewmclagan** [comment]
Also seeing this as of 14.5

**Comment by adeelakram696** [comment]
for a time being it doesn't get merged. use 0.12.2 version of react-slick

**Comment by a9901zhy** [comment]
{
   list.length?
   <Slide {...settings}>
     {
       list.map(item =>{
         return 
      })
    }:''
}

**Comment by akiran** [comment]
This issue is fixed in #826

**Comment by Hamrouniasma13** [comment]
how did you fix this issue please ?
