### ISSUE TITLE
Can the open pull requests get some attention?

### ISSUE THREAD

**Issue by mplis** [akiran/react-slick#716]
There are several open pull requests and I think it'd be nice to have some action taken on them.

Some pull requests, like #495, #579, and #509, have received several comments and positive reactions, but haven't gotten any response.

Others, like #560, #582, and #571, have spawned forks of the project (`react-slick-ssr`, `react-slick-with-mobile-in-mind`, and `react-slick-2` respectively) simply because they've been sitting open for several months with no action.

This is an important library and I believe the community deserves to know if these pull requests are ever going to get merged in or not.

**Comment by akiran** [comment]
Yes,  next few weeks I will review PRs and fix important issues

**Comment by aperkaz** [comment]
@akiran any news about the open PR?

**Comment by asimqt** [comment]
@akiran Any updates? I really want this (https://github.com/akiran/react-slick/pull/560) PR to be merged. I am having issues when I use slick in an isomorphic app.

**Comment by edwardaa** [comment]
@akiran Any updates?
