### ISSUE TITLE
error in izomorphic app (

### ISSUE THREAD

**Issue by royroev** [akiran/react-slick#721]
/node_modules/enquire.js/src/MediaQueryDispatch.js:14
    if(!window.matchMedia) {
        ^
ReferenceError: window is not defined

**Comment by Shayac** [comment]
I'm getting the same issue. This was introduced sometime between 0.14.7 and now (0.14.10).

**Comment by eligolding** [comment]
This is because of the new dependency on ensure.js, which cannot be used in node.

**Comment by akiran** [comment]
Please pin react-slick version to 0.14.7 until this is fixed.
I will fix this over weekend

**Comment by Shayac** [comment]
thanx. We're working on a pr here. Should have it done soon.

**Comment by wayweary** [comment]
0.14.7 still depends, need 0.14.5 until fix ;)

**Comment by Shayac** [comment]
in 0.14.7 it was using react-responsive-mixin which wraps the `require(enquire.js)` in a check `if canUseDOM` which is why it worked.

**Comment by Shayac** [comment]
see https://github.com/akiran/react-responsive-mixin/blob/master/index.js#L2

**Comment by royroev** [comment]
Accept changes, please)))
