### ISSUE TITLE
Responsive design is not working on resize the window(smaller to larger) or Change orientation(portrait to landscape).

### ISSUE THREAD

**Issue by abebebiru** [akiran/react-slick#724]
If you resize the window from smaller to larger, the carousel is showing blank white space and it is not rendering more items.
https://jsfiddle.net/abiru/bgygwtgy/

**Comment by AhyoungRyu** [comment]
have same issue..

**Comment by Alexa905** [comment]
the same for me

**Comment by ashkanjj** [comment]
Having the same issue, I guess this library isn't maintained anymore..

**Comment by bharamappa** [comment]
We need to pass the proper breakpoints, then it will work.

**Comment by laveesingh** [comment]
I don't see any such issue. Please refer to [example](https://github.com/akiran/react-slick/blob/master/examples/Responsive.js) for correct usage.

I'm closing the issue for now. If someone disagrees, please feel free to reopen.
