### ISSUE TITLE
module export change from commonjs to es6 is a breaking change.

### ISSUE THREAD

**Issue by eternalsky** [akiran/react-slick#726]
We notice that 7 days ago the package module export way changes.(after ver 0.14.8)
from  `module.exports = Slider` to `export default Slider`. This will cause the package which depend on `react-slick` using `require('react-slick')` fail to work, so this change should be a breaking change which is not expressed in npm package version.  

the babel plugin `add-module-exports` can be used in your build process to have a better compatibility for both commonjs & es6 modules.

**Comment by jonthenerd** [comment]
Agreed. This also causes the community-produced typings file to no longer be valid. NPM Build version should be upped to prevent breaking builds until people choose to go to the higher version.

**Comment by michael-go** [comment]
This change should indeed be released as `1.15.*` , as it's a breaking change, and for us it broke production for few minutes, cause in `package.json` we had `react-slick: "^0.14.6"` :)

anyway, another way to overcome it is to do `require('react-slick').default`
