### ISSUE TITLE
Version 0.14.8: Unknown props `currentSlide`, `slideCount` on <div> tag Warning Back

### ISSUE THREAD

**Issue by wilbert-abreu** [akiran/react-slick#728]
@akiran Seems like this commit #624 was removed from version 0.14.8 and needs to be remerged.

**Comment by wilbert-abreu** [comment]
@akiran Updated to 0.14.11. Seems like the commit was merged back in, but still experiencing this error.

**Comment by tyleraadams** [comment]
i am experiencing the same issue for 0.14.11.

**Comment by edennington** [comment]
I am experiencing this error on 0.14.11 as well.

**Comment by cscottsa** [comment]
@akiran I am experiencing this error as well, please remerge.

**Comment by Dajust** [comment]
It's not an error. It's just a warning. I'm sending a PR to fix this, hope it's accepted ASAP.

**Comment by kjs3** [comment]
I just hit this.

For anyone else slightly confused: 
If you implement your own prev/next arrows react-slick will pass `currentSlide` and `slideCount` props to your custom components. It's on you not to place these properties on tags that shouldn't have them. The following is how I dealt with this.

```javascript
export const CustomArrow = props => {
  // pull off props that don't belong on a <button> tag
  const { currentSlide, slideCount, ...remainingProps } = props

  return (
    <button {...remainingProps}>
      My Btn
    </button>
  )
}
```

**Comment by akiran** [comment]
You have to follow solution mentioned by @kjs3
