### ISSUE TITLE
previous arrow does not go in reverse order

### ISSUE THREAD

**Issue by serendipitist** [akiran/react-slick#729]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

**Comment by gsheppard** [comment]
Looks like it's working to me?

**Comment by janelle-boyd** [comment]
Maybe add "z-index: 10000 !important;" on the element?

**Comment by laveesingh** [comment]
Similar issues have been fixed in previous releases. If someone disagrees, please feel free to reopen the issue.
