### ISSUE TITLE
Tripple item render in 13.3

### ISSUE THREAD

**Issue by super-cache-money** [akiran/react-slick#73]
Even though I'm only passing in a single React Component as a child to `Slick`, the item is trippled.
Here's an example: 

    <Slick >
      <MyComponent/>
    </Slick>

where:

    var MyComponent = React.createClass({
      render: function(){
        return <div> Very simple Component </div>
      }
    });

If I replace `<Slick>` with a `<div>`, `<MyComponent>` is displayed once, perfectly. 
Also, if I replace `<MyComponent/>` with `<div> test </div>`, it works correctly without triplication.

This triplication is accompanied by a glitchy carousel movement.

This is with autoscroll on:

![slick_bug](https://cloud.githubusercontent.com/assets/1463145/8316771/7cfc5a64-19f9-11e5-987e-daa5ea9439b2.gif)

**Comment by vramana** [comment]
Hey, pass down the props sent to your component to the actual slide `div`. That seems to do the job.  
``` javascript
var MyComponent = React.createClass({
  render() {
    return (
      <div {...this.props}><h3>2</h3></div>
    );
  }
});
```

**Comment by vramana** [comment]
Slick actually applies a few props to the slides before they are rendered. Instead of passing down to the actual slide, they are being passed to your custom component which doesn't pass it down further.

If you have any more, feel free to ask

**Comment by super-cache-money** [comment]
Cool, thanks. It should probably be documented in the readme.
