### ISSUE TITLE
this.slider.slickNext() 

### ISSUE THREAD

**Issue by cairnsjoe** [akiran/react-slick#731]
When call this function is there a way to get the slide number that is going to be display or the number of the slide that is currently displayed?  I need to be able to display some text after the function function is executed based on the current slide number.

**Comment by brownsmith** [comment]
You need the `beforeChange` and `afterChange` callback functions: https://github.com/akiran/react-slick/blob/master/examples/SlideChangeHooks.js
They'll give you access to the currentSlide and nextSlide values
