### ISSUE TITLE
[FIXED -PR Waiting ]Moving the slides outside the bounds of the screen throws an error

### ISSUE THREAD

**Issue by silicakes** [akiran/react-slick#736]
in the following bin:
[https://www.webpackbin.com/bins/-KiybDEiWhRa_tKHrapu](https://www.webpackbin.com/bins/-KiybDEiWhRa_tKHrapu)

When the slides are dragged outside the view, 
an error is thrown, instead of restarting the slide position:

![react-slick-touch-issue](https://cloud.githubusercontent.com/assets/1759539/25564059/eaf7af68-2db2-11e7-98b9-4a64eb3b4b3b.gif)

The following PR fixes the issue:
#
[https://github.com/silicakes/react-slick/tree/Out-of-bounds-exception-fix](https://github.com/silicakes/react-slick/tree/Out-of-bounds-exception-fix)

**Comment by tomasdev** [comment]
There are 56 PRs open, @akiran perhaps its time you add collaborators.

**Comment by laveesingh** [comment]
I don't see any such issue, if someone's facing similar to this, please give your configs.

**Comment by laveesingh** [comment]
PR #614 has been considered for fix. Changes will be released soon.

**Comment by silicakes** [comment]
Yay! thanks!:)
