### ISSUE TITLE
Slide only once on safari

### ISSUE THREAD

**Issue by hikkyu** [akiran/react-slick#74]
On safari mac ( 8.0.6 (10600.6.3) ), I can only slide one time after that I can't go back or further.
Works fine the first time with each navigation button (next, back, drag&drop and navigation)

By the way I don't have the slide animation.

No problem on firefox and chrome.

**Comment by vramana** [comment]
@hikkyu I don't have a Mac with me right now. In a few days, I hopefully I'll be able to find one. Can you give an example with which I can reproduce this issue?

**Comment by hikkyu** [comment]
@vramana I reproduce it all the time on your demo page, with all example carousel

**Comment by vramana** [comment]
@hikkyu Are you taking about this link http://webrafter.com/opensource/react-slick ??

**Comment by hikkyu** [comment]
@vramana Yep!

**Comment by vramana** [comment]
@hikkyu A lot things have changed since then.

**Comment by akiran** [comment]
@hikkyu, @vramana  I will test it and try to fix it today

**Comment by akiran** [comment]
@hikkyu I tested the latest version of demos in safari. Its working well.
 http://webrafter.com/opensource/react-slick demos are using old version which had an issue with safari.

To test the latest demos locally
You clone the repo , run npm start and view demos locally at http://localhost:8000

**Comment by hikkyu** [comment]
@vramana @akiran Yes! I just implemented it on my project and it works well. Sorry for the useless issue

**Comment by vramana** [comment]
@hikkyu Its fine. Just happens sometimes. :smile:
