### ISSUE TITLE
How to know the end of slide has reached

### ISSUE THREAD

**Issue by kiranbabu189** [akiran/react-slick#741]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

**Comment by kiranbabu189** [comment]
im trying to integrate it to my react app. Can anyone suggest me a way to find the end of slide has reached?

**Comment by hoschi** [comment]
just switch to finite mode? https://jsfiddle.net/20bumb4g/3192/

**Comment by kiranbabu189** [comment]
i want to call a function on reaching slide end. but thanks i didn't knew this too. is there a way to call a function.

**Comment by hoschi** [comment]
use beforeChange or afterChange hook to check if the param (index of current slide) is less than the count of slides. See example page for that.

**Comment by kiranbabu189** [comment]
Thanks @hoschi . i should have searched deeply.

if anyone require
https://github.com/akiran/react-slick/blob/master/examples/SlideChangeHooks.js

**Comment by laveesingh** [comment]
You can pass a hook with `edgeEvent` prop. This will be triggered once the slider reaches end of the slides and infinite is false.
