### ISSUE TITLE
Jest testing with react: matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by janjuafarooq** [akiran/react-slick#742]
Trying to shallow render a component using Enzyme and I see this error on my component. I see that this issue was "fixed" previously but I am still seeing it on "react-slick": "^0.14.11".  Any suggestions to fix?

 matchMedia not present, legacy browsers require a polyfill
      at new MediaQueryDispatch (node_modules/enquire.js/src/MediaQueryDispatch.js:15:15)
      at Object.<anonymous> (node_modules/enquire.js/src/index.js:2:18)
      at Object.<anonymous> (node_modules/react-slick/lib/slider.js:37:38)
      at Object.<anonymous> (node_modules/react-slick/lib/index.js:3:18)

I am using https://github.com/facebookincubator/create-react-app as my boilerplate

**Comment by andrewdc92** [comment]
did you already add this? https://github.com/akiran/react-slick#test-setup

**Comment by janjuafarooq** [comment]
How can I incorporate this fix for the create-react-app starter kit?

https://github.com/facebookincubator/create-react-app 

I don't have access to a jest command.

**Comment by janjuafarooq** [comment]
I had to create a file setupTests.js and place it inside the src/ folder (src/setupTests.js) and put the following code in:

window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};

This resolved my issue. Might want to update instructions for create-react-app

**Comment by Slebee** [comment]
if you was eject your create-react-app,put that code in /config/polyfills.js

**Comment by astroash** [comment]
@janjuafarooq did you manage to get this working without ejecting your create-react-app?

**Comment by dschinkel** [comment]
nobody using react-slick should have to care anything about Jest tests in here.  This is not something any consumer of react-slick should have to be dependent on.  This is still a major issue which I've posted here: https://github.com/WickyNilliams/enquire.js/issues/169

**Comment by TheGabornator** [comment]
Unfortunately, the above mentioned solution didn't help me, yet I realized something:
Somehow, the setupTest.js is not recognised by Jest the way it's supposed to, according to the [create-react-app guide.](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#testing-components)

  The version (at least) I'm using comes with the following test script.
"scripts": {
    "test": "react-scripts test --env=jsdom --setupTestFrameworkScriptFile=raf/polyfill",
  },

If I remove the --setupTestFrameworkScriptFile=raf/polyfill, and restart the test with "npm test", my setupTests.js will be recognised and the configuration in it becomes valid.

Please let me know if I'm doing it wrong.

**Comment by vTrip** [comment]
@janjuafarooq could you explain why that fix works please :)

**Comment by mustkeom** [comment]
Press ctrl + e in visual code. And search pollyfills.js file. 
Open it and put this code.

window.matchMedia = window.matchMedia || function () {
  return {
    matches: false,
    addListener: function () {},
    removeListener: function () {}
  };
};

You dont need to eject. Polyfills.js file will rescue in this case.

**Comment by igorfelipee** [comment]
If you are use react, you can just import an [match-media-pollyfil ](https://www.npmjs.com/package/match-media)in you App.test.js.

**Comment by leotm** [comment]
Official docs: https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom

**Comment by Miltonjacomini** [comment]
For me fix was almost the same.

Include the file `setupTests.js` in `src` folder.
```
window.matchMedia = window.matchMedia || function() {
    return {
       matches : false,
       addListener : function() {},
       removeListener: function() {}
    };
};
```

But i have include the insert file on Jest call in package.json.
`
"jest": {
//...
"setupFilesAfterEnv": [
    "<rootDir>/src/setupTests.js"
]
`

and then run `npm test` again ... 👍

**Comment by zernabhussain** [comment]
add this piece of code:
```
window.matchMedia =
	window.matchMedia ||
	function() {
		return {
			matches: false,
			addListener: function() {},
			removeListener: function() {}
		};
	};
```
in **jest.setup.js** or **setupTests.js** (you can check the name from **jest.config.js**  
eg.  **setupFiles: ["./jest.setup.js"]** )

**Comment by zernabhussain** [comment]
check this: https://github.com/akiran/react-slick/issues/742#issuecomment-557793922

**Comment by maa-wtag** [comment]
> I had to create a file setupTests.js and place it inside the src/ folder (src/setupTests.js) and put the following code in:
> 
> window.matchMedia = window.matchMedia || function() {
> return {
> matches : false,
> addListener : function() {},
> removeListener: function() {}
> };
> };
> 
> After this I ran npm test again and it resolved my issue (had to stop the watch task and restart it).
> 
> This resolved my issue. Might want to update instructions for create-react-app

where is the src folder? project src? or react-slick src?

**Comment by ioxua** [comment]
For anybody still having this issue: if you're using `react-scripts@4.0.3`, this may help: 

[Source](https://stackoverflow.com/a/66515427)

```js
// $ npm i -D mq-polyfill
// in src/setupTests.ts

import matchMediaPolyfill from 'mq-polyfill'

matchMediaPolyfill(window)

window.resizeTo = function resizeTo(width, height) {
  Object.assign(this, {
    innerWidth: width,
    innerHeight: height,
    outerWidth: width,
    outerHeight: height
  }).dispatchEvent(new this.Event('resize'))
}
```

**Comment by KentuckySato** [comment]
@ioxua Thank you! It works for me! 
My version of react-script is `react-scripts": "^5.0.1` and your solution has solved my problem 🥳

**Comment by sbland** [comment]
The fixes above didn't help for me so I just mocked react-slick in my setupTests.js file.
``` tsx

jest.mock("react-slick", () => ({
  __esModule: true,
  default: ({ children }) => <div data-testid="slick_mock">{children}</div>,
}));
```
