### ISSUE TITLE
Slider rewinding when reaching the end

### ISSUE THREAD

**Issue by sonofabear** [akiran/react-slick#743]
Hello, when using using infinite mode, after the slider reaches the end, instead of continuing to loop, it quickly rewinds back and then continues sliding.

https://jsfiddle.net/f1q9x4Ld/2/

**Comment by SebastianStiehl** [comment]
I also have the same problem if lazyLoad is enabled and i am clicking through the arrows.

https://jsfiddle.net/6bmL4zxs/1/

**Comment by airandfingers** [comment]
Duplicate #698
