### ISSUE TITLE
adaptiveHeight: slider is only as tall as first slide if SlidesToShow is more than 1

### ISSUE THREAD

**Issue by amanda-t** [akiran/react-slick#744]
When SlidesToShow is more than 1 and adaptiveHeight is true, the slider will only be as tall as the first slide in the set of currently active slides. If subsequent slide are taller than the first, they will be cut off.

https://jsfiddle.net/tusinga/d0r9fnzb/

**Comment by rizwan-0** [comment]
We are facing the same issue. Is anyone taking care this one?
