### ISSUE TITLE
Slides are still draggable on mobile - how to prevent?

### ISSUE THREAD

**Issue by raffishquartan** [akiran/react-slick#745]
I have a slick slider that shows only a single slide on screen at once. I would like to disable dragging so that the only way the slide being shown changes either on a timer or when a user clicks a control (e.g. a dot). I have been able to disable dragging in the browser, however I find that I can easily and accidentally drag a slide half off the page on my iPhone, rendering it unreadable.

How do I disable swipeability / draggability on the iPhone as well as in the browser?

I have set up the following jsfiddle to demonstrate the issue and with the relevant code (though jsfiddle isn't very good on mobile...)

https://jsfiddle.net/cfogelberg/j30crdok/

Setting the following settings doesn't seem to have any effect on the iPhone:
      draggable: false,
      swipeToSlide: false,
      touchMove: false,

**Comment by niempi2** [comment]
also set the "swipe"-property to false.

**Comment by raffishquartan** [comment]
Setting swipe: false (and not draggable, swipeToSlide, touchMove) has stopped it being draggable on the iPhone.

**Comment by rozuja** [comment]
Hi lick Good slider. I  added this 
`<script>
jQuery(document).ready(function($){
    jQuery('.slickhome .slick-slider').slick('slickSetOption', {
    accesibility: false,
    draggable: false,
    swipe: false,
    touchMove: false,
    swipeToSlide: false,
  }, true);
 
});
  </script>`

It stopped the drag on PC browser, but It didnt disable the drag on mobile. Im on android with chrome browser.

Any FIX for this. its been a while since I needed to disable drag completely from the site.
