### ISSUE TITLE
Overlapping slick items

### ISSUE THREAD

**Issue by thientran1707** [akiran/react-slick#746]
I am trying to achieve this carousell... How can I adjust react-slick to achieve this? I tried to set the margin of items to negative but the layout breaks and the center item is not in correct position
<img width="944" alt="screen shot 2017-05-07 at 1 05 52 am" src="https://cloud.githubusercontent.com/assets/8632054/25774849/b753992e-32c1-11e7-8dd4-a13ba221c48e.png">

**Comment by bogdan-calapod** [comment]
I'm also trying to do this - I've had some success with using transforms but the spacing is all over the place
