### ISSUE TITLE
What are the plans for supporting React 15.4? 

### ISSUE THREAD

**Issue by smonev** [akiran/react-slick#750]
I am using React 15.4.2 and when I try to install react-slick I get:

> ├── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.1
> ├── UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.0.1

Is there a reason for the hardcoded react 15.0.1 version? If yes, what is the issue with react 15.4.2?

**Comment by akiran** [comment]
15.4 is supported. Need to up package.json
