### ISSUE TITLE
Namespace for class names

### ISSUE THREAD

**Issue by weaintplastic** [akiran/react-slick#751]
Hi @akiran,

we'd like to use react-slick for our project. Apparently we are a little bit concerned about style collisions.

There is no option to set customClasses for the rendered subcomponents and as far as I could read in existing issues you want to stay as close as possible to the original slick API.
I wonder if a `classNamespace` property would still be an option to define a global class prefix that will be prepended to any className created internally.

Please let me know what you think.

Roland

**Comment by akiran** [comment]
You can overrides styles with css using the classnames used in the components

**Comment by weaintplastic** [comment]
Overwriting styles is known to be bad practice. But thanks anyways for the advice.

**Comment by boakenfull** [comment]
👍 custom class namespace would be very useful
