### ISSUE TITLE
Accessibility: Tab through items in the slider

### ISSUE THREAD

**Issue by cmalonzo** [akiran/react-slick#753]
Is there a way to tab through the visible items in the slider when the left/right arrow keys are visible? My ideal tabbing scenario would be that after I tab to focus on the left arrow key, I can tab in the right most item in the slider. I can then tab to each remaining item in the slider until i tab to the right arrow key.

**Comment by garrettdehnketurpin** [comment]
So does react-slick not support tabbing? This is a pretty big thing when it comes to accessibility.

**Comment by antoniojps** [comment]
Any update on this? I notice a lot of issues regarding accessibility.
