### ISSUE TITLE
slick-list height not consistent with server-rendering app

### ISSUE THREAD

**Issue by jpabbuehl** [akiran/react-slick#756]
Hi

I am using react-slick with next.js (a server-rendered app)
When loading it for the first time, I am getting this issue ( I cannot reproduce it with fiddle)
![bug](https://cloud.githubusercontent.com/assets/2730222/26072615/6c75cf0c-39ac-11e7-932c-cb69d7329e45.png)

When looking at the debugger, slick-list height is set to 5 px
After several reloading with f5,  slick-list height is then set to 500 px and the component is correctly displayed
![f5](https://cloud.githubusercontent.com/assets/2730222/26072621/70169092-39ac-11e7-9cd1-aa097439dc04.png)

It looks like it's a responsive issue because as soon as I slightly resize the window, this issue disappears.
Using  .slick-slide { height: auto; } as [here](https://github.com/kenwheeler/slick/issues/771) did not solve this issue for me.

```
import Slider from 'react-slick'
import Vitem from './Vitem';
class verticalCarousel extends React.Component {
  render() {
    const settings = {
      slidesToShow: 3,
      slidesToScroll: 2,
      vertical: true,
      infinite: true,
      arrows: true
    };
    return <Slider {...settings}>
      {this.props.data.map((item, index) =><div data-index={index}><Vitem key={index} title={item.title} img={'static/img/drop.svg'}/></div>)}
    </Slider>
  }
}
```

Any idea ? I spent hours testing all solutions written here but nothing worked for me.
Thank you

**Comment by aperkaz** [comment]
Hello mate, i think it might be something similar to this [#560](https://github.com/akiran/react-slick/pull/560), hope you find this helpful :smile: .

**Comment by laveesingh** [comment]
Such issues have been fixed with the help of resize observer. Please make sure you're using the latest version of react-slick.
