### ISSUE TITLE
overflow-y inside modal

### ISSUE THREAD

**Issue by vugman** [akiran/react-slick#757]
I'm using slick inside a modal where one of the slides has a dropdown menu.
Since overflow for slick-list is set to hidden (makes sense) the dropdown isn't show.

Is there any way to override this behavior without messing up the entire slider?

**Comment by akhayoon** [comment]
@vugman 

Any luck with this problem?

**Comment by gugadev** [comment]
Any solution for this?

**Comment by laveesingh** [comment]
If someone could generate a codesandbox demo for the same, it would be easier to help.

**Comment by vugman** [comment]
Hey @laveesingh,

I've created a [https://codesandbox.io/s/2p0ok14rrr](codesandbox) for this, hope it makes sense.
The scenario is that when there is a custom dropdown menu or day picker inside a slide. 

![screen shot 2018-04-26 at 11 10 23 am](https://user-images.githubusercontent.com/11426508/39293774-742620fc-4942-11e8-9dc7-19864557288f.png)

**Comment by mciszczon** [comment]
@vugman This is a little bit late, but there's no way around it. As per documentation, in overflow in one dimension is set to `hidden`, overflow in the other one cannot be `visible`. What you're looking for is setting `overflow-x: hidden` while `overflow-y: visible`, which will not work.

**Comment by fijisoo** [comment]
we need this improvement!
