### ISSUE TITLE
Not able to destroy slick-slider and re render it

### ISSUE THREAD

**Issue by rohitgoyal7** [akiran/react-slick#761]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

**Comment by rohitgoyal7** [comment]
I am using slick slider for dynamic images where user can add or delete images at run time, but its not working well.

**Comment by fdc-viktor-luft** [comment]
React Basics: simply supply a new key to the Slider... Does this solve your Problem?

**Comment by brovkin** [comment]
> React Basics: simply supply a new key to the Slider... Does this solve your Problem?

It's working! Thx @fdc-viktor-luft

**Comment by f3tusz** [comment]
Hi @brovkin Can you provide code for this solution?

**Comment by hungdev** [comment]
i get same issue

**Comment by brovkin** [comment]
@f3tusz Hi!
I don't remember exactly (it was 2 years ago), but I just added key="{unique value}" to the slider and it worked, try it like that:

```
<Slider key="slider_2">
    ...
</Slider>.
```

**Comment by hungdev** [comment]
@brovkin thank you for your comment. I tried that solution yesterday, but it didn't work. Then now I changed to https://swiperjs.com/react
