### ISSUE TITLE
Getting error using with router

### ISSUE THREAD

**Issue by masquel** [akiran/react-slick#765]
react-slick@0.14.11

https://jsfiddle.net/bu98jbbw/ - this demo display the logic of my component in application, slider component can get page prop on mount from path or on buttons click.
Slider mounts only when pages length > 0

While first render slideCount is equal to null and currentSlide become equal -1 and I'm getting error `Cannot read property 'offsetHeight' of null` because of looking for element with `data-index=-1`

Setting timeout about 100ms helps right now, but it's not a good decision.

**Comment by akiran** [comment]
This issue is fixed in master
