### ISSUE TITLE
lazyLoad don't load after slidesToShow changes.

### ISSUE THREAD

**Issue by aalenliang** [akiran/react-slick#769]
I have a vertical slick, and the height of slick will fit height of window, so when window resize, slick's slideToShow will change.

and I'm using lazyLoad={true}, when slideToShow increase, the additional slide is not rendered.

![screen shot 2017-05-31 at 3 25 29 pm](https://cloud.githubusercontent.com/assets/20056005/26620451/85524d96-4615-11e7-8b98-06050f941f14.png)

the $0 item is what has been rendered, and those active but empty item is what should be rendered but empty.

**Comment by laveesingh** [comment]
All the related issues have been fixed in previous releases.
