### ISSUE TITLE
Is Not Issues, Just Want To Ask About Disable Slide If Only 1 item we have

### ISSUE THREAD

**Issue by prakasa1904** [akiran/react-slick#770]
Like my title, this is not bug or something wrong. I just want to know how to make disable slide effect if we only have 1 item. Thx before

### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

**Comment by Dajust** [comment]
Simply set the infinite option to false.

```
<Slider infinite={isOneItem ? false : true}>
....
</Slider>
```
