### ISSUE TITLE
The default colour for the 'next'and 'prev' button is white. How do I change them? 

### ISSUE THREAD

**Issue by exogenesys** [akiran/react-slick#771]
The default colour for button used for 'next' and 'previous' slides, defined in the class `slick-next:before` and `slick-prev:before` is white.

Why are they white? And how do I change them?

Thanks a lot.

**Comment by brownsmith** [comment]
Are you using CSS modules? If so, you can use the :global prefix to target the .slick-next and .slick-prev selectors `:global(.slick-prev) {...}` etc
