### ISSUE TITLE
LazyLoadList

### ISSUE THREAD

**Issue by tplusrex** [akiran/react-slick#772]
## Cause

When lazy loading galleries the active slide is the only slide that gets rendered. There's no setting to allow slides to preload in advance.

## Effect

The slide div will render when active. In some cases we do not want to wait for the slide to render when active. We want the slide to initially render so by the time that slide is reached no additional render is needed. This makes for a smoother experience if something takes longer to load.

## Proposed Solution

Create a new slick setting property that accepts an array of slide numbers. Load those initial slides and render the other slides normally when lazy load is active.

**Comment by akiran** [comment]
Can you try setting fewer slides initially and latter set lazyLoad and increase the slide count.

Currently we didn't have plans to add extra props to pre-load few slides
