### ISSUE TITLE
Update docs on Custom next/prev arrows to match arrow.js

### ISSUE THREAD

**Issue by Dajust** [akiran/react-slick#779]
The [docs](https://github.com/akiran/react-slick#custom-nextprev-arrows) currently tells the user to "create new React components and set them as the values of nextArrow and prevArrow." But arrows.js uses `React.cloneElement()` to clone and return the passed value, thus expects a _react element_ instead of a component. This gave me hours to debug.

I'll be glad to assist if you need any.

**Comment by akiran** [comment]
Added links for examples in docs
