### ISSUE TITLE
Lazy loading fails to initialize correctly when using react components as slides.

### ISSUE THREAD

**Issue by sbaechler** [akiran/react-slick#78]
I have a slider with about 200 elements. Each element is a react component.
When I have lazyLoad set to true, no slides are loaded. I have to advance the slider first.
The slider initializes and is displayed (if the height of a slide is defined in CSS), but it is empty. The dots appear. When I do a swipe action, the next image is loaded.

Setting 'initialSlide' does not help either.

Autoscroll does not seem to be working either with lazy loading.

When centerMode is set to true, I have to set 'infinite' to false or the slider crashes when going past 0.

**Comment by vramana** [comment]
@sbaechler You probably are not passing down the props into your React component. Can you see the discussion in #73 helps ??

**Comment by sbaechler** [comment]
No, I was using a wrapper div. But even with passing down the props the problem still exists.

**Comment by vramana** [comment]
@sbaechler Can you write an example so the I can reproduce the issue?

**Comment by beepiams** [comment]
+1 on @sbaechler's issue. Finding the triplication of passing props as well (even with https://github.com/akiran/react-slick/issues/73  <div {...this.props}> solution).

**Comment by sean-shilin** [comment]
I got a quick hack to the same issue -> https://github.com/akiran/react-slick/pull/95

**Comment by lauffenp** [comment]
I'm having a similar issue:

Hey, here's an example of the problem I'm having:

    getVidElement: function (vidId) {

    var video = this.props.Annotation[vidId];
 
    var vidElement;
    
  
      vidElement = <Video video={video} />;
 
    return (<div   key ={video.id.objectId} >
        {vidElement}
        </div>);
     },

     render: function () {
           var vidElements = this.getListOfVidIds().map(this.getVidElement);
           var settings = {
           dots: true,
           infinite: true,
           lazyLoad:true,
            arrows:true,
           speed: 500,
          slidesToShow: 3,
          slidesToScroll: 3
    };
     
    return (
      <Slider {...settings} >
        {vidElements}
       
      </Slider>
    );
      }

Even if I pass {...this.props} to both the <Video> and <div> tags, I still can't get anything initialized. It is 'lazyloading' the entire {vidElements} array. When I click the arrows or the dots, everything is loaded.

**Comment by lauffenp** [comment]
Ok, so I removed an unnecessary level of children and it still doesn't work...:

    getListOfVidIds: function () {
    return Object.keys(this.props.Annotation);
     },
    

      getVidElement: function (vidId) {

    var video = this.props.Annotation[vidId];
    

    var vidElement;
    
  
      vidElement = <div 
      onClick = {this.props.handleThumbnailClick.bind(null, this, video)}
           onMouseOver = {this.handleMouseOver}  
             onMouseOut = {this.handleMouseOut} 
             style={videoStyle}
          >
          <h3>{video.description}</h3>
          <h5>{video.hashtags}</h5>
          </div>;
 
    return (<div  key ={video.id.objectId} >
        {vidElement}
        </div>
           );

      },

    
      render: function () {
    

                   
        var vidElements = this.getListOfVidIds().map(this.getVidElement);
          
        var slidesScroll = 3
        if (vidElements.length <4 ){
          slidesScroll = 1  
        }
    var settings = {
    dots: true,
        lazyLoad: true,
      infinite: true,
        arrows:true,
      speed: 500,
      slidesToShow: slidesScroll,
      slidesToScroll: slidesScroll
    };
     
    return (
      <Slider {...settings} >
        {vidElements}
       
      </Slider>
    );
  
     }
    
    });

**Comment by lauffenp** [comment]
I'd really like to resolve this problem in my app. Is there anything further I could do?

**Comment by akiran** [comment]
I will try to fix it soon

**Comment by lusilva** [comment]
Any update on this? I'm also having this issue

**Comment by ewbdaniel** [comment]
I too am having the same issue

**Comment by PatrickWilding** [comment]
Same here. Seeing the same issue.

**Comment by w3jimmy** [comment]
Same here. It's been a while since you posted, I wonder what were your workarounds, guys?

**Comment by jamaljeantobias** [comment]
I still have this same issue

**Comment by laveesingh** [comment]
I think most lazyloading related issues have been fixed. (latest release 0.19.0)
Please refer to this codesandbox example: https://codesandbox.io/s/n9p51n1lo0
If someone still has any problem regarding this, please generate a demo on codesandbox, and feel free to request reopen.
