### ISSUE TITLE
Horizontal stick threshold

### ISSUE THREAD

**Issue by mads-thines** [akiran/react-slick#785]
### Hi!

I've been try to create an horizontal slider to browse tags on touch devices.

Unfortunately the way it sticks is very aggressive and it makes it difficult to slide to the next tags. You have to slide far into the next tag in order for it to stick to it. **See gif below**.

![slick stick](https://user-images.githubusercontent.com/16097850/27582023-bc3f2d18-5b2f-11e7-970b-94275e16f6cd.gif)

#### My slick settings
```js
arrows: false,
infinite: true,
variableWidth: true,
slidesToShow: 1,
slidesToScroll: 1,
swipeToSlide: true,
```

### Question:
Does anyone have a settings, solution or another way to solve this issue?

Thanks!

**Comment by WilliamHolmes** [comment]
maybe try adding `{ ... css-ease: 'ease-in-out', ... }`

**Comment by mads-thines** [comment]
@WilliamHolmes without knowing what this setting does, I would think that it changing how the animation behaves, and what I'm looking for is how the tags sticks.

Nevertheless, thanks for the suggestion, I will try this out and get back to you.

**Comment by mads-thines** [comment]
@WilliamHolmes, sorry I forgot to get back to you. 
This does not solve the issue :)

**Comment by akiran** [comment]
Can you try varying touchThreshold setting.
By default it is 5.  
Try lower and see if it works

**Comment by mads-thines** [comment]
Alright @akiran, I'll try this out.

Thanks!

**Comment by mads-thines** [comment]
I increased the touchThreshold to 100 and it not works perfect.
Thanks for the help @akiran
