### ISSUE TITLE
Module is heavier than nessesary

### ISSUE THREAD

**Issue by radiovisual** [akiran/react-slick#789]
When I inspected the react-slick directory in node_modules, I noticed that the module making it's way into my bundled build has lots of unnecessary files in it:

![image](https://user-images.githubusercontent.com/5614571/27837184-c46b8440-60da-11e7-83c6-8e87473d56b8.png)

Including the tests files, test setup files, docs, examples, etc, making the weight of this module a lot heavier than necessary. 

Either adding this to `package.json`:
```
"files": "dist"
```

Or updating the .npmignore file should do the trick. Happy to send a PR if necessary.

**Comment by akiran** [comment]
Please send PR
