### ISSUE TITLE
ERROR import "slider.js"

### ISSUE THREAD

**Issue by gdr4gon1** [akiran/react-slick#799]
@./~/react-slick/src/slider.js
Module parse failed: ~\node_modules\react-slick\src\slider.js Unexpected token (94:8)
You may need an appropriate loader to handle this file type.
|       // if 'unslick' responsive breakpoint setting used, just return the <Slider> tag nested HTML
|       return (
|         <div>{children}</div>
|       );
|     } else {

**Comment by hhimanshu** [comment]
I see the same issue, what is the resolution?
