### ISSUE TITLE
No support for IE9 transforms

### ISSUE THREAD

**Issue by bdvis** [akiran/react-slick#80]
Noticed an issue where IE9 wasn't correctly changing which slide was selected because `msTransform` wasn't being set in `trackHelper.js`'s `getTrackCSS` function. Not sure if this lib intends to support IE9 or not but thought I'd open an issue anyway. (A `matchMedia` polyfill is required for `< IE 10` which leads me to believe this lib might just be 10+.)

Also, if you could provide instructions on building the project locally that'd be much appreciated, seems like `gulp dist` doesn't totally work quite as expected. It's Friday though, so that could explain it.

Thanks so much for this project, really great! :+1:

**Comment by vramana** [comment]
@bdvis I don't have a windows machine I can't really do much. If your issue is solved by adding `msTransform` in the `getTrackCSS` send a PR, I would be happy to accept it. 

You can run local server for demos using `npm start`.

**Comment by bdvis** [comment]
@vramana will do!

Thanks for the info on `npm start`.
