### ISSUE TITLE
bug: method: update, filepath: src/mixins/helpers.js, line-number: 70

### ISSUE THREAD

**Issue by peterlevel1** [akiran/react-slick#814]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

circumstantance: ajax fetch data, danamically update the data of the slider,
the bug show if you do the pause step

issue: 
filepath: src/mixins/helpers.js, line-number: 70
// pause slider if autoplay is set to false
    if(props.autoplay) {
      this.pause();
    } else {
      this.autoPlay();
    }

----------------------------
you should do this:
    if(props.autoplay) {
      this.autoPlay();
    } else {
     this.pause(); 
    }

**Comment by akiran** [comment]
Fixed it
