### ISSUE TITLE
prevArrow and nextArrow may get rid of the <div> tag

### ISSUE THREAD

**Issue by ycjcl868** [akiran/react-slick#815]
The `nextArrow` and `prevArrow` get rid of the `<div>` tag ,:

the `<div class="slider-action">`  would disappear like this: 
```js
nextArrow={
  <div className="slider-action"><Icon type="right1" /></div>
}
```

It can render like this: 
```js
nextArrow={
  <span><span className="slider-action"><Icon type="right1" /></span></span>
}
```

**Comment by SuEric** [comment]
nextArrow & prevArrow I think just doesn't work... I tried many different html tags and it displays default style arrow

**Comment by akiran** [comment]
Checkout custom arrows example here
https://github.com/akiran/react-slick/blob/master/examples/CustomArrows.js
