### ISSUE TITLE
Is it possible to open image in order to visualisate them one by one in full screen ?

### ISSUE THREAD

**Issue by vickingbg** [akiran/react-slick#816]
Hi,

Your component seems to be very powerful.
Actually I examinate the React components to match with my needs.
I saw that your compoent allow to specified the number of elements to be show in slide as also to put a video link.

Now I would like to understand if it is possible to implement click event over an image for example, which will allow to open the image in full screen and continued to navigate over the image out from the carrousel component ?

Are someone of you already did something like this ?

Thanks for any idea

**Comment by barefootChild** [comment]
I need the same feature of vickingbg

**Comment by akiran** [comment]
Yes, Click on slides work
