### ISSUE TITLE
Cloned, precloned and postcloned classnames for .slick-slide

### ISSUE THREAD

**Issue by RusinovAnton** [akiran/react-slick#818]
Hi, seems like standart jsfiddle is ok for this issue so I'll skip it.

I need to show my slides like regular blocks on print version so I have to hide clonned element then, so I need that classnames to do it with 

```
@media print {
 .slick-slide--cloned {
   display: none;
 }
}
```

Thanks! Sorry if duplicated, just had no time to search more.

**Comment by RusinovAnton** [comment]
Ok, so I've just dig in the code and see [implementation](https://github.com/akiran/react-slick/blob/master/src/track.js#L27) of this feature but it seems like it doesn't work.  
https://jsfiddle.net/kirana/20bumb4g/

**Comment by akiran** [comment]
<img width="511" alt="screen shot 2017-08-23 at 11 03 16 pm" src="https://user-images.githubusercontent.com/3403295/29629667-4ea81922-8857-11e7-9c20-750cd819d4f7.png">

slick-cloned class is added to cloned slides.
Fix for this is in master and it will be released to npm this Sunday
