### ISSUE TITLE
Common Functionality

### ISSUE THREAD

**Issue by devdebonair** [akiran/react-slick#82]
Please excuse my ignorance for I am just getting the hang of react. How exact would one go about moving to the slide if using the arrows is not an option? Due to the nature of React, I believe it wouldn't be fit to call a nextSlide() method. I was thinking of having a currentSlide property that could be passed into React-Slide. My idea is to link the slider to the parameter and manipulate it outside of react-slick. Please let me know if I am on the wrong path.

**Comment by vramana** [comment]
@catalystlive You are absolutely right. Calling external methods on component to change the state is considered an anti-pattern. You should external manipulate the component by only changing the props.

**Comment by catalystlive** [comment]
Which property handles the current page?

**Comment by vramana** [comment]
@catalystlive There is support for paging yet

**Comment by akiran** [comment]
@catalystlive I will try a demo with your use case tomorrow and implement if there is a missing feature

**Comment by catalystlive** [comment]
Thanks for the quick feedback. I am building a comic reader and wanted to be able to paginate by clicking on images and pressing arrow keys. I will try to see about applying those features.

**Comment by vramana** [comment]
> paginate by clicking on images

Do you mean to changing the image upon clicking it? If so, you can achieve this by attaching a `onClick` handler which will change the slider's currentSlide.

**Comment by catalystlive** [comment]
@vramana would you mind showing me a snippet of how to acheive this???

**Comment by akiran** [comment]
We have previous and next methods implemented now
https://github.com/akiran/react-slick/blob/master/examples/PreviousNextMethods.js
