### ISSUE TITLE
.slick-active class incorrectly applied when infinite is true

### ISSUE THREAD

**Issue by nihlton** [akiran/react-slick#820]
DEMO: [jsfiddle](https://jsfiddle.net/3gLkztpk/) 

In this demo, there are 4 slides, with 3 visible at a time.

**opacity: .2** is applied to **.slick-slide**, and **opacity: 1** is applied to **.slick-active**;

Expected: the three visible slides should always be opaque.

Actual: when the slide track wraps (for infinite mode) the cloned items are not set as 'slick-active'

**Comment by akiran** [comment]
This issue is fixed in master

**Comment by nihlton** [comment]
rad.  thanks man :)

**Comment by nihlton** [comment]
Any idea when this change will make it into a release?

**Comment by toiletpatrol** [comment]
@akiran @nihlton guys I think this is still an issue. If you set inactive item's opacity to 0 and active item's opacity to 1 with transition it will blink sometimes
