### ISSUE TITLE
Is this project already abandoned?  

### ISSUE THREAD

**Issue by sidoruk-sv** [akiran/react-slick#824]
Or this lib is too big and buggy to be able to handle all of the problems. 
The last release date is Feb 3, the last author's commit date is May 21.

Maybe it's better to find new fresh and inspired maintainers which can handle all of the exhausting problems. Really seems like there is no alternative for such featured slider for React.
Or even it's time to reorganize concepts and even completely rewrite this project (it will be a huge challenge, because of tons of features presented here)?

**Comment by mikeselander** [comment]
I have been wondering this myself - the core library itself seems relatively stable but there are loads of quirks (most of which even have PRs). I'd be very willing to contribute and help out on a more active basis, but obviously the main maintainer needs to be around to enable anyone else to help out without a fork.

Will be watching this issue closely.

**Comment by nandosangenetto** [comment]
That would be great @mikeselander. I would love to help this project too.

**Comment by zerbfra** [comment]
There are some big issue already fixed in prs... Hope someone forks the repo and continue the development.

**Comment by xwchris** [comment]
I also think it's time to rewrite it'

**Comment by sidoruk-sv** [comment]
@akiran please, we need your decisions on this thread

**Comment by Subha** [comment]
It will be great if someone picks it and fix the PR's. The carousel images are sporadic like the one in the attachment. Hope there is a fix for that .
![screen shot 2017-08-18 at 10 37 28 am](https://user-images.githubusercontent.com/12513265/29463600-4aba9862-8401-11e7-88f5-da7a5fd0cfa9.png)

**Comment by Attimo91** [comment]
@Subha +1 i also need this fix

**Comment by akiran** [comment]
Last couple of months I was busy with projects and could spend time on this project.
I started looking at issues and PR's.

**Comment by sidoruk-sv** [comment]
@akiran if we can help you somehow, or you can publish your milestone plane. Will glad to help with that.

**Comment by akiran** [comment]
Many issues posted in this repo didn't have any code snippets. So It is hard for me replicate the issues. Demos for replicating the issues will be useful.

**Comment by akiran** [comment]
@sidoruk-sv Also testing the existing PR's to make sure it fixes the issues without breaking other features and providing demo for the issue PR is fixing will help me merge the PR's faster

**Comment by Subha** [comment]
Thank you Kiran for getting back :). As mentioned in my previous thread. I could not exactly create the same issue. But there seems to be some bugs. Here is the simple fiddle that I created to recreate the issue.
https://jsfiddle.net/681h7fuj/

1. I am adding the carousel /slider component as part of the menubar which already has some existing styles.

2. The images are of 100% width, with more padding i am able to see the next image in the first slider.

Thank you
Anu
