### ISSUE TITLE
Some features present in slick are missing

### ISSUE THREAD

**Issue by nimishsinghal** [akiran/react-slick#828]
Some following features are not present in react slick
- slickAdd
- slickRemove
- reInitSlick

**Comment by akiran** [comment]
You can implement them easily with react without adding extra functions in this library.
You check this example where number of slides is changed.
https://github.com/akiran/react-slick/blob/master/examples/DynamicSlides.js
You can also use the same approach to add and remove slides.

To reinitialise, just change key on Slider. React will unmount and re-mount the slider.
