### ISSUE TITLE
appendDots feature not working

### ISSUE THREAD

**Issue by sapangshah** [akiran/react-slick#834]
Hi @akiran ,

Can you suggest solution for dot navigation put at top, I don't want to use css.
I found that it has already "appendDots" feature but it is not working in react-slick.

Not working with react-slick - https://jsfiddle.net/20bumb4g/4170/
Working with native library - https://codepen.io/EngCode/pen/BowxNj

Thanks,

**Comment by akiran** [comment]
appendDots and appendArrows functionality is not yet implemented.
PR is welcome

**Comment by paulcredmond** [comment]
@akiran Any updates on this? Is it still not supported? Thanks for your great work.

**Comment by laveesingh** [comment]
This is supported now. Please refer to the [documentation](https://react-slick.neostack.com/docs/api/#appendDots) on this.

**Comment by YossOviedo** [comment]
This doesn't work like the the original slick slider library.

**Comment by caomicc** [comment]
Any updates on making this work like the original library?
