### ISSUE TITLE
direction LTR

### ISSUE THREAD

**Issue by fereshtehaboohamzeh** [akiran/react-slick#839]
if your application is rtl the slider does'nt work properly for this issue you should add  'direction:ltr !important;'
to the  slider wrapper

**Comment by sag1v** [comment]
that won't fix it completely

**Comment by laveesingh** [comment]
We received the pr https://github.com/akiran/react-slick/pull/924 relating to the similar issue. Those changes will be merged shortly. If you think your issue is different, please feel free to reopen it with more details.
