### ISSUE TITLE
 Slider is going to 1st slide if we scroll the page to bottom on iOS

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#84]

**Comment by vramana** [comment]
Hey, this may be similar to #85 I pushed a changed can you check if that solves the issue.

**Comment by akiran** [comment]
Thanks @vramana

**Comment by vramana** [comment]
Hey, Can you release a new version?

**Comment by akiran** [comment]
Yes. I will do it in the evening.

**Comment by akiran** [comment]
released 0.6.4 with this fix

**Comment by akiran** [comment]
This issue still exist on iphone

**Comment by akiran** [comment]
Tested on iphone safari browser.
This is no longer present in latest version (0.6.9)
