### ISSUE TITLE
Refactor inner-slider.js to use a plain ES6 class

### ISSUE THREAD

**Issue by steve-king** [akiran/react-slick#841]
Hi, it would be really nice if this could be refactored in line with the other modules - as the use of `getDefaultProps` and `getInitialState` with the `createReactClass` module causes React to log a lot of warnings into the console - as from what I can see `createReactClass` actually converts to an ES6 class anyway.

In my case, with 4 carousels on the page and having to occasionally re-render them means the console is filled with red, even though everything is currently working as it should.

**Comment by akiran** [comment]
We used create-react-class library to fix the warning.
You shouldn't see these warnings in latest version
