### ISSUE TITLE
Jest error: TypeError: Cannot read property 'getBoundingClientRect' of null 

### ISSUE THREAD

**Issue by skumblue** [akiran/react-slick#845]
Hi, 

When I run Jest in some file with **react-slick**, the console shows me:
`TypeError: Cannot read property 'getBoundingClientRect' of null`

I have the last version _^0.14.11_, and I understand this is fixed... but I still get the error

How can I solve this?

Thanks!

**Comment by akiran** [comment]
Try latest version 0.15

**Comment by skumblue** [comment]
Hi @akiran, installed the latest version **0.15.2**, but now I have other error:

`Cannot find module 'react-slick'`

Look the **react-slick 0.14.11 folder** in my node_modules:
<img width="853" alt="v0 14 11" src="https://user-images.githubusercontent.com/3875593/30003516-88e0cca2-9094-11e7-929c-19e2374a399f.png">

And look the **react-slick 0.15.2 folder** in my node_modules:
<img width="667" alt="v0 15 2" src="https://user-images.githubusercontent.com/3875593/30003519-9cf987d8-9094-11e7-8d98-b6038f52c3d9.png">

How can I solve this?

**Comment by akiran** [comment]
Can you try 0.15.3 version

**Comment by skumblue** [comment]
@akiran 

Now show me other error when I run *Jest*:

Invariant Violation: getNodeFromInstance: Invalid argument.

<img width="897" alt="screen shot 2017-09-03 at 11 14 43 am" src="https://user-images.githubusercontent.com/3875593/30003758-e508be0a-9098-11e7-8edb-8ef5f079dc12.png">

**Comment by akiran** [comment]
We use jest to run tests in this library.
You can checkout the setup we have.

**Comment by skumblue** [comment]
Perfect!

My new code based on your [code example](https://github.com/akiran/react-slick/blob/master/examples/__tests__/SimpleSlider.test.js) is running perfectly. I must use `mount` from enzyme instead `renderer.create` to snapshot test.

Thanks!
