### ISSUE TITLE
Vertical mode issue with count of elements

### ISSUE THREAD

**Issue by DonikaV** [akiran/react-slick#847]
Same problem in your demo
http://neostack.com/opensource/react-slick

so if we click to the latest element (dot) we see half of 5th block and the latest sixth never will be appear....
In my situation, i can`t see two last elements of 10
```
const settings = {
			speed: 500,
			dots: false,
			slidesToShow: 6,
			slidesToScroll: 2,
			vertical: true,
			infinite: false,
			verticalSwiping: true,
			swipeToSlide: true,
			nextArrow: <NextArrow/>,
			prevArrow: <PrevArrow/>,
		};
```

**Comment by Alkasih** [comment]
Why no answer?

**Comment by laveesingh** [comment]
The issue doesn't exist anymore. Please make sure you're using the latest version of react-slick.
