### ISSUE TITLE
Slider goes to first slider when changing route with react-router

### ISSUE THREAD

**Issue by cport1** [akiran/react-slick#85]
I am changing the route in the afterChange method, but when doing so it sometimes jumps to the 1st slide.

 render() {
        var self = this;
        function goTo(event){
            self.context.router.replaceWith(pages[event].path);
        }
        var settings = {
            dots: false,
            infinite: true,
            arrows: true,
            speed: 500,
            slidesToShow: 1,
            slidesToScroll: 1,
            afterChange: function(event){
                goTo(event);
            }
        };

**Comment by vramana** [comment]
@cport1 Hey, think I know there the issue may be coming from. Can you remove these lines https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L54-L56  from your react-slick in your node_modules and tell what happens ?

**Comment by cport1** [comment]
That totally fixed it.

**Comment by neculaionutni** [comment]
> Hey, think I know there the issue may be coming from. Can you remove these lines https://github.com/akiran/react-slick/blob/master/src/inner-slider.jsx#L54-L56 from your react-slick in your node_modules and tell what happens ?

@vramana 
I have the same problem, but the link you provided is now broken. Can you please tell me what are the lines that should be removed? And is that safe to do? Isn't there another solution? Thanks.

**Comment by neculaionutni** [comment]
@cport1  that may fix it for when you change between routes, but if you refresh the route the slick will break.

**Comment by cport1** [comment]
@neculaionutni you're commenting on something from over two years ago
