### ISSUE TITLE
bug with responsive mode and lazyLoad

### ISSUE THREAD

**Issue by otdelnovp** [akiran/react-slick#850]
I create carusel with this parameters:
https://jsfiddle.net/otdelnov/2z7vatgt/1/
var settings = {
infinite: true,
lazyLoad: true,
responsive: [{
    breakpoint: 990,
    settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        dots: true
    }
},{
    breakpoint: 10000,
    settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        dots: false
    }
}]
};

When i open page in vertical ipad i have 1 slide
But when i rotate ipad to horizontal i need 2 slide, but second slide is empty and not load.
I think lazyLoad not worked when i change page width.

And second problem with Infinity and lazyLoad. When i open page and click to Left button Carusel flasing and not working.
And when i click to Right and go to last slide, next click to Right button not move me to Clone first slide on the right, but carusel very fast moving to first slide on left.

And i need parameter to disabled create Cloned slide, becose i have many warning in console that key dublicate

PS: My slides have iframe video and any text or buttons.

**Comment by laveesingh** [comment]
I've examined the issue, and I'm reopening it and will set appropriate priority. Thanks!

**Comment by laveesingh** [comment]
fixed: d6d5e92629869a0969d4af507ec598376189b91f
