### ISSUE TITLE
Fade property messes up onClick actions on slides

### ISSUE THREAD

**Issue by sergioavazquez** [akiran/react-slick#852]
I'm using react-slick as the main slideshow and carousels on my site. Whenever fade property is off, everything works fine but when set to true, onClick functions get mixed up.

To recreate on fiddle, open js console, navigate slides and click on them. The behavior I get on my site is similar, instead of executing always the last slides's action it executes the previous slide's action.

Regardless, the key factor here is that if fade is set to false everything magically works just fine.

* Issue -> [jsfiddle](https://jsfiddle.net/20bumb4g/4372/)

**Comment by nicotroia** [comment]
Same issue here. It seems like in "fade" mode, the hidden slides are actually on top of the current one which is causing pointer issues. I hacked my css to add `.slick-active { z-index: 999; }` as a workaround to fix input bugs

**Comment by laveesingh** [comment]
to be fixed by: #853
