### ISSUE TITLE
height calculate error when set vertical to true

### ISSUE THREAD

**Issue by zhaojunb** [akiran/react-slick#855]
I noticed the slider height is calculated as follow: slidesToShow * (first slider item height). 
When items in slider have different height, it goes wrong. 

For a slider which has 4 items, each height is 200px 400px  200px and 400px, when sliderToShow equals to 2, the slider height depends on the first item height, if first item is 200px, then slider height is sliderToShow * 200px = 2 * 200px = 400px. It's apperently not expected. The corrent height should equals to the sum of each item at front, which is 200px + 400px = 600px. Otherwise, there should be a prop that we could set slider height manuely.

**Comment by shanejones** [comment]
Also getting this issue.

Works fine when vertical is set to false though

**Comment by laveesingh** [comment]
Please make sure that you're using the latest version of react-slick. Similar problems have been fixed with resize-observer in recent releases. Please feel free to request reopen if disagree.
