### ISSUE TITLE
React v16 support

### ISSUE THREAD

**Issue by stefensuhat** [akiran/react-slick#868]
warning "react-slick@0.15.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
warning "react-slick@0.15.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".

Thanks

**Comment by teux** [comment]
And also I see:
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

**Comment by pencilcheck** [comment]
getting weird error like `Error in ./ReactMount Module not found: Error: Can't resolve 'react/lib/React' in '/project/node_modules/react-slick/node_modules/react-dom/lib'`

**Comment by jonricaurte** [comment]
mixins are no longer supported:

https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L17

also should migrate away from createReactClass:

https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L16

**Comment by danjumamilhaus** [comment]
When installing from npm, the version is `"version": "0.15.4"` but the peerDependancies in the package.json don't list React\ReactDOM 16:

```
"peerDependencies": {
    "react": "^0.14.0 || ^15.0.1",
    "react-dom": "^0.14.0 || ^15.0.1"
  },
```

Is this a known issue yet?

**Comment by screendriver** [comment]
That's what this issue is about here.

**Comment by ankitduseja** [comment]
@akiran Any idea when it will be updated on npm?

**Comment by tony99nyr** [comment]
@akiran ping.  Please run a `npm version patch && npm publish`

**Comment by tony99nyr** [comment]
Tried to do the publish myself without success :frowning_face: 

```bash
npm ERR! You do not have permission to publish "react-slick". Are you logged in as the correct user? : react-slick
```

**Comment by hdwatts** [comment]
Bump!

**Comment by superbiche** [comment]
I've made a fork by necessity, to use React 16 in our next release.  
A quick and dirty fork, but at least my sliders work and I have no error.  

Tests are broken as [enzyme isn't compatible with React 16 yet](https://github.com/airbnb/enzyme/issues/1106)

It's available here: https://github.com/mygooder/react-slick.  
Also published on npm: `npm i @mygooder/react-slick --save`  

Let me know if this helps someone and eventually if we should start contributing this fork (as the original project seems still), so I publish it unscoped and update the README.  We're using it in production today and we won't be switching soon.

**Comment by savbace** [comment]
@superbiche enzyme works with React 16 though require some [efforts](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md).

**Comment by superbiche** [comment]
@savbace you're right! I'm adding this to my todo. Thanks for the link.

**Comment by akiran** [comment]
Made a new release with react 16 dependency support. 
Can you test it

**Comment by dschinkel** [comment]
can this be merged into a release, we had to use this fix in order to use react-slick in react 16 and we have to add a hack to our package.json until this is merged into the official release
`"react-slick": "git://github.com/mygooder/react-slick"`

would like to get rid of that.

**Comment by superbiche** [comment]
@akiran I confirm this is working in production with React 16. Many thanks !

**For people using my fork, I strongly advice you to switch back to the original repo**. We currently have no other plans than contributing here, so I guess this repo will move much more often than my fork.

@akiran are you looking for co-maintainers? Let me know if you do.
Best 💋
