### ISSUE TITLE
JAWS 18 : tabindex=-1 makes it verbose. 

### ISSUE THREAD

**Issue by srinivasvenigalla** [akiran/react-slick#869]
### Guidlines for posting new issue
having that tabindex=-1 makes JAWS read the contents twice for the buttons in the panel. Can you please make it configurable?

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

![image](https://user-images.githubusercontent.com/32373683/30989356-6e1102ee-a46b-11e7-9470-21d34c2e3faa.png)

**Comment by srinivasvenigalla** [comment]
Alternatively, you can also add aria-label="" to the same element to fix this issue.

**Comment by laveesingh** [comment]
Similar is the behaviour reflected by [slick](http://kenwheeler.github.io/slick/).
