### ISSUE TITLE
Flex layout version

### ISSUE THREAD

**Issue by angus-c** [akiran/react-slick#87]
My content is expecting to be rendered in a flex container, but since div.slide-slide is display:block, div.myContent always renders with zero height.

```
  div.slick-initialized slick-slider
    div.slick-list
      div.slick-track
        div.slick-slide slick-cloned
        div.slick-slide slick-active <------- display:block
          div.myContent <------- expects display:flex parent
        div.slick-slide
          div.myContent
        div.slick-slide
          div.myContent

```

I forked react-slick and tried to change it to flex layout - but got into a snag with div.slick-track, which I was unable to get to function properly within flex layout.

Any suggestions for how to do this? - thanks!

**Comment by vramana** [comment]
Can't you wrap your div.myContent in a div with display:flex? Or is that you would prefer not to have extra div's?

Even I wanted to change the css to an entirely flexbox layout. Using float seems too much of a hack to me. I ran into wierd errors when I was trying to implement vertical scrolling. Also some of the code inside react-slide is dirty because of the hacky nature of floats used to render the slides. I am working on other things right now. You are interested to solve this. I'll surely help you with any problems you got.

**Comment by angus-c** [comment]
Thanks for the response. 

I don't want to specify a size on div.myContent or a wrapper - I just want it to fill the available space. And div.slick-slide has no explicit size, so I can't just do height:100% on the wrapper.

I may do a PR if I get time.

**Comment by akiran** [comment]
Demo for react slick slider inside flexbox container
https://jsfiddle.net/kirana/wabv7wLj/

**Comment by iDVB** [comment]
No one else stilling having issues getting slick to run inside of a flex'd element?

**Comment by iam-peekay** [comment]
@iDVB @akiran I'm not able to get this to work properly :/
I followed the JSFiddle example but no luck

**Comment by pradeepgill007** [comment]
* {
  min-height: 0;
  min-width: 0;
}

**Comment by pradeepgill007** [comment]
`* {
  min-height: 0;
  min-width: 0;
}`

**Comment by Robert-Queeney** [comment]
<div class="slide-cont" tabindex="-1" style="width: 100%; display: inline-block;">

  .slide-cont{
    width: 100vw; 
    display: flex; 
    justify-content: center; 
  }

@vramana , was having the same problem and tried your solution of wrapping my content in an extra div with a display of flex, and it overwrote the styling to inline-block.  Is flexbox possible?

**Comment by Robert-Queeney** [comment]
@vramana, sorry it cut off my previous message.   Here is what renders after I wrap my content in the div with a display: flex 

.slide-cont{
width: 100vw;
display: flex;
justify-content: center;
}

<div class="slide-cont" tabindex="-1" style="width: 100%; display: inline-block;">
