### ISSUE TITLE
fullscreen mode

### ISSUE THREAD

**Issue by watzak** [akiran/react-slick#870]
Hello guys!

Thanx for your library! But what I am missing is a **fullscreen mode**! Is there a possibility to do that anyway? Maybe I haven't seen it in the examples/documenation although I have checked them!

Thanx in advance for your feedback

Cheers watzak

**Comment by watzak** [comment]
Here is a solution for fullscreen mode, what I have implemented =>
https://github.com/akiran/react-slick/pull/893

**Comment by laveesingh** [comment]
We would love to have features like this in future. But currently, our prime goal is to be similar to and not to deviate from slick library. For now, I'm closing this, but once we are close enough to our goal, we'd definitely wanna have features like this.

**Comment by watzak** [comment]
Hello @laveesingh

Is it possible to include 2 methods to your api! Variables still exist in your code!

Would be following methods:
`getDirection = () =>  this.innerSlider.getDirection();

  isAnimated = () => this.innerSlider.isAnimated();`

Thanx in advance for your feedback!

Cheers watzak

PS: Code still exist, but don't know if it's wanted for merging?
