### ISSUE TITLE
Cannot fix matchMedia issue for Jest tests as I cannot overwrite create-react-app Jest scripts in package.json

### ISSUE THREAD

**Issue by ameliejyc** [akiran/react-slick#876]
Having had the same "matchMedia not present, legacy browsers require a polyfill" issue that many others have had (#523 #93) I am not able to fix the issue by adding in a test-setup file and jest script as indicated by @akiran and shown [here](https://github.com/akiran/react-slick#test-setup).

Instead, my terminal gives the following error to do with create-react-app:

> Out of the box, Create React App only supports overriding these Jest options:
• collectCoverageFrom
• coverageReporters
• coverageThreshold
• snapshotSerializers.
These options in your package.json Jest configuration are not currently supported by Create React App:
• setupFiles
If you wish to override other Jest options, you need to eject from the default setup. You can do so by running npm run eject but remember that this is a one-way operation. You may also file an issue with Create React App to discuss supporting more options out of the box. 

Ejecting creates a whole heap of other problems so I'm keen not to do this. Has anyone else come across and gotten around this issue?

**Comment by Slyke** [comment]
I'm also having this issue. I tried to add in the setupTests.js file, but it did not fix the issue.

**Comment by ameliejyc** [comment]
I ended up fixing the issue by adding this extra line into my setupTests.js file: 
(check out this issue [here](https://github.com/facebook/jest/issues/4545))

```
global.requestAnimationFrame = callback => setTimeout(callback, 0);
```
No ejection necessary! 🌸

**Comment by justwright** [comment]
This line in my src/setupTests.js file did the trick for me for this particular issue

`window.matchMedia = window.matchMedia || function() { return { matches : false, addListener : function() {}, removeListener: function() {} }; };`

**Comment by dschinkel** [comment]
nobody using react-slick should have to care anything about Jest tests in here.  This is not something any consumer of react-slick should have to be dependent on.  This is still a major issue which I've posted here: https://github.com/WickyNilliams/enquire.js/issues/169

**Comment by kopax** [comment]
@justwright without ejecting, how do you plus `src/setupTest.js`?

**Comment by leotm** [comment]
[This](https://github.com/akiran/react-slick/issues/742#issuecomment-460281987) may work (the official Jest way)
