### ISSUE TITLE
playground doesn't work

### ISSUE THREAD

**Issue by khoshbin** [akiran/react-slick#878]
Hi
 https://jsfiddle.net/kirana/20bumb4g/ doesn't work
 it seems that react-slick is not working in bootstrap v4 too

**Comment by test27c** [comment]
Demo is working fine using http , rather than https

**Comment by SeabassNg** [comment]
"Mixed Content: The page at 'https://jsfiddle.net/kirana/20bumb4g/' was loaded over HTTPS, but requested an insecure script 'http://reactjs.org/js/jsfiddle-integration-babel.js'. This request has been blocked; the content must be served over HTTPS."

**Comment by siakaramalegos** [comment]
I have this same problem. I'd like to try out this tool, but the jsfiddle is requesting some resources over http so Chrome and other browsers are blocking it.

**Comment by akiran** [comment]
We moved playground from jsfiddle to codesandbox 
https://codesandbox.io/s/zzloxr09mp
