### ISSUE TITLE
Demo broken on Safari desktop?

### ISSUE THREAD

**Issue by ranyefet** [akiran/react-slick#88]
Hi,

I've just tried the [demo](http://webrafter.com/opensource/react-slick) on Safari desktop.
I'm able to click on the right arrow once and it works, but after that it's stop working and the left button also do nothing.

I'm running Safari on Mac: Version 8.0.7 (10600.7.12)
On Chrome it seems to work fine.

Is it just me? a bug?

Thanks!

**Comment by akiran** [comment]
Demos on the website are old version.
recent version of code didn't have bugs on safari.

website need to be updated
