### ISSUE TITLE
React-slick vanishes when a using page is translated

### ISSUE THREAD

**Issue by mghazanfar** [akiran/react-slick#880]
React-slick works perfectly for 'english' but when page is translated to some right hand language like arabic or urdu, it shows no card.
I have resolved the issue by wrapping the react-slick carousel in a div and giving this div 'direction:ltr'. I think there must be a prop for this property also. Even there is a prop 'rtl' which does not work for this issue.
Thank you!!

**Comment by sag1v** [comment]
@mghazanfar I'm facing the same issue.
Why did you close the issue then if it wasn't fix?

**Comment by mghazanfar** [comment]
Because I got my own fix =D

**Comment by sag1v** [comment]
@mghazanfar yeah i've tried this solution but its not fully working. there is a problem with the transform translate calculation as well. its only showing one item, even if there are more items to display.
I advice you to re-check your project ;)

**Comment by mghazanfar** [comment]
I'll see for sure

**Comment by sag1v** [comment]
Great. consider re-open this issue so there is no reason for me to open a new one.
@akiran do you know about this?

**Comment by laveesingh** [comment]
@sag1v I'm reopening this issue to give it a check. Could you share your thoughts or any experience on this issue?

**Comment by loanlaux** [comment]
Can confirm — I have the same bug here. Carousel works fine when browsing my page with English set as the browser language, but breaks with Hebrew or Arabic.

**Comment by votsa** [comment]
Confirm. The same for me. Just want to watch for updates

**Comment by laveesingh** [comment]
Can you regenerate it on codesandbox, because I'm trying it on my machine, and it's working fine without the issue. Please feel free to request reopen the issue.

**Comment by laveesingh** [comment]
I'm able to successfully translate the page without breaking anything. If someone is still facing the issue, please generate a demo on codesandbox and feel free to request reopen.

**Comment by sag1v** [comment]
@laveesingh see [my comment](https://github.com/akiran/react-slick/issues/952#issuecomment-368426095) on #952

**Comment by nilam-jadhav-maf** [comment]
@mhdkashif07 is your issue resolved? if yes how?

**Comment by mhdkashif07** [comment]
> [@mhdkashif07](https://github.com/mhdkashif07) is your issue resolved? if yes how?

was not able to fix that issue, also not working on that project anymore, so I have not touched it again
