### ISSUE TITLE
demo repo, where is it?

### ISSUE THREAD

**Issue by vinicri** [akiran/react-slick#885]
here can I find the repo of the demo link? 

http://neostack.com/opensource/react-slick

I want to check how webpack is configured there regarding the css import.

**Comment by gsheppard** [comment]
It's explained in the documentation.

Running demos: https://github.com/akiran/react-slick#development
Demos folder: https://github.com/akiran/react-slick/tree/master/examples
Demo App: https://github.com/akiran/react-slick/blob/master/docs/demos.jsx
