### ISSUE TITLE
in autoplay mode, the color of dot which is clicked would not be recovered after slided to next dot automatically

### ISSUE THREAD

**Issue by kingwinchan** [akiran/react-slick#886]
### Guidlines for posting new issue
In autoplay mode, the color of dot which is clicked would not be recovered after slided to next dot automatically. By that I mean, If any dot is clicked, after autoplay time is over, the next silde would be showed and the prev dot still remains chosen color.

**Comment by laveesingh** [comment]
Turns out it was not a bug. It just shows that the dot is focused. If you click somewhere else, the dot loses focus and the colour fades.
