### ISSUE TITLE
Can't slide when clicking dots

### ISSUE THREAD

**Issue by sergejr** [akiran/react-slick#888]
I can't slide the slider when clicking a Dot. The Dot shos when it's active - but the onClick handler doesn't work.

Any Idea?

File looks like this: 
https://jsfiddle.net/20bumb4g/4815/

**Comment by laveesingh** [comment]
This could be an issue with older versions. Newer versions of react-slick don't have any related probelms.

**Comment by astinaam** [comment]
Using the latest version available now, this problem persists. But when I use custom dot class other than 'slick-dots', it wroks

**Comment by amitmall87** [comment]
there is pseudo element (:before and :after) on dot element (li), remove that by css, and will work fine:
`.slick-dots li:before,.slick-dots li:after{display:none}`
