### ISSUE TITLE
what happened with the dist file

### ISSUE THREAD

**Issue by MarshallChen** [akiran/react-slick#89]
``` javascript 
	var _mixinsEventHandlers = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"./mixins/event-handlers\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));

	var _mixinsEventHandlers2 = _interopRequireDefault(_mixinsEventHandlers);

	var _mixinsHelpers = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"./mixins/helpers\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
```

it cause problem when I use it, and yes from `npm install react-slick`. In the package.json file the main field are "./lib" but it doesn't exist in npm modules nor in repo, so I changed it to "./dist/react-slick.js" and what the error message is `error given was: Error: Cannot find module "./mixins/event-handlers"`

**Comment by akiran** [comment]
I just installed latest version of react-slick and lib folder is present.
lib folder is auto generated during npm publish.  lib folder contained jsx to js transformed files 

lib folder will not be present in repo , but it will be present on npm installed package

**Comment by MarshallChen** [comment]
Thats my fault, Thanks!

**Comment by gus4no** [comment]
this is happening to me too with `bower install` @MarshallChen how did you fixed it?

**Comment by akiran** [comment]
@gus4no  Fixed this in 0.6.6  Can you test it

**Comment by gus4no** [comment]
@akiran you're awesome man! it all works now! thanks a lot! I'm fairly new to react but I hope I can contribute to this! thanks a lot!

**Comment by akiran** [comment]
@gus4no You are welcome
