### ISSUE TITLE
slickAdd behavior for including slides at begining

### ISSUE THREAD

**Issue by cccaballero** [akiran/react-slick#894]
Following DynamicSlides.js example we can easily include new slides, but how can we include new slides at begining and keep the user in the current slide?

**Comment by MarkEhr** [comment]
Hi, cccaballero. I've got a similar problem and what I have done is to call the method slickGoTo inside the componentDidUpdate of the component that renders the slider. This has worked for me with one exception, which I believe is a bug. 
If you have the last slide selected and remove one slide, the method won't work and the first slide will become the selected one, no matter which one you try to select with slickGoTo.

**Comment by cccaballero** [comment]
Thanks @MarkEhr, I have managed to make it work, fortunately I don't need to remove elements, so the bug is not affecting me right now.

**Comment by laveesingh** [comment]
You can use slickGoTo method along with managing a state for the slides list in the wrapper.
