### ISSUE TITLE
[Bug] lazyLoad touch move

### ISSUE THREAD

**Issue by kozlikov** [akiran/react-slick#897]
If you move the pictures to the last, then the last picture does not show.
I tested myself locally and here: http://neostack.com/opensource/react-slick

![93yb258734y gif](https://user-images.githubusercontent.com/13614707/32138145-d0677418-bc36-11e7-9691-9793c2dda186.gif)

**Comment by laveesingh** [comment]
That problem has already been solved. Please let me know if you have different opinion.
