### ISSUE TITLE
React slick dynamic not working with first element

### ISSUE THREAD

**Issue by lionel95200x** [akiran/react-slick#898]
Hello,

I have a button who delete the current item display in my slider (Item active is stored in redux)

<button onClick={e => this.deleteListing(e)}>{text.labels.BUTTON_NO}</button>

deleteListing() {
    const { listingActive } = this.props
    this.props.deleteListing(listingActive)
  }

//------- Slider -----
Here is my slider with settings :

<Slider ref='slider' {...settings}>
                {items.map(item => (
                    this.displayItem(item)
                ))}
</Slider>

const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    afterChange: (index) => {
        const itemActive = store.getState().item[index].id
        store.dispatch(updateItemActive(idActive))
    },
}

When i delete all elements other than first all works, the methods afterChange is called and the item active is setCorrectly

But when i delete the first element, the afterChange is notCalled and the slider can't delete the newCurrent element

Do you have any suggestion ?

Thanks

**Comment by laveesingh** [comment]
That sounds like a bit complex situation, could you create a codesandbox demo for the same?
