### ISSUE TITLE
Is this project already abandoned? v2.0

### ISSUE THREAD

**Issue by sh-a-v** [akiran/react-slick#903]
v1.0 #824 

> Maybe it's better to find new fresh and inspired maintainers which can handle all of the exhausting problems.

**Comment by sh-a-v** [comment]
@akiran can you comment?

**Comment by izzappel** [comment]
There are so many open PRs and a lot of other people who would love to help out and spend some time and energy in this project. @akiran would be nice if you could at least comment it.

**Comment by MartinN3** [comment]
@akiran Could we reopen maintainers discussion?

> Maybe it's better to find new fresh and inspired maintainers which can handle all of the exhausting problems.
