### ISSUE TITLE
Swiping vertically cause carousal to scroll horizontally

### ISSUE THREAD

**Issue by GeniusIdeas** [akiran/react-slick#906]
Hello,

First of all Slick carousal works like a charm. One issue i was having is when swiping vertically in carousal cause to scroll horizontally. Please help!!

**Comment by romainwn** [comment]
Could you provide some code so we can try to look what is wrong ?

**Comment by laveesingh** [comment]
If you're still facing this issue, please create a demo on codesandbox.

**Comment by deepika1223** [comment]
Try this: 
 const settings = {
      dots: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      vertical: true,
      verticalSwiping: true,
      swipeToSlide: true,
      beforeChange: function(currentSlide, nextSlide) {
       //DO NOTHING
      },
      afterChange: function(currentSlide) {
       //DO NOTHING
      }
    };
