### ISSUE TITLE
Slick transform

### ISSUE THREAD

**Issue by GeniusIdeas** [akiran/react-slick#907]
Hello,

I think the original slick slider have the option to disable transform with useTransform property. Could you please let me know if react slick offers that?

**Comment by Seb33300** [comment]
I am encountering the same issue. It seems that this option doesn't work.
Any solution?

**Comment by GeniusIdeas** [comment]
I think feel like it may be a feature need to add to slick. But i made it work around to disable with CSS.

**Comment by conor909** [comment]
A fade option would be handy for presentations

**Comment by GeniusIdeas** [comment]
Right, there is still transform property enabled.  Need to disabled transform by css like transform: none !important.

**Comment by redhotkid123** [comment]
The transform property is also causing the items in the slider to be right aligned. 

https://codesandbox.io/s/0x0mv9y1q0

**Comment by laveesingh** [comment]
This feature has been taken into account and will be implemented pretty soon. Please follow: #1050
