### ISSUE TITLE
main entry on bower.json points to a non-existent file

### ISSUE THREAD

**Issue by jeongsd** [akiran/react-slick#91]
Hi I'm using https://github.com/ck86/main-bower-files to generate file list for gulp.
But in react-slick's bower.json file, the "main" entry points to "index.js" file which does not exist.

Could you please fix bower.json's main entry to point to "dist/react-slick.js"? Thank you

**Comment by vramana** [comment]
@akiran I have fixed this issue. But probably you have to retag with the version. I'll leave that to you.

**Comment by akiran** [comment]
Thanks @vramana .

Created a 0.6.5 release tag
