### ISSUE TITLE
Dots enforcing `display: block`

### ISSUE THREAD

**Issue by Yurickh** [akiran/react-slick#910]
Hello, I'm having an issue while styling the Dots component.

Inside `src/dots.js:55`, you're inlining a `display: block` in the dots collection.
There's absolutely no way to disable this behaviour from outside, so trying to use, for example, a `display: flex` from css is useless, since inline styles always gets precedence.

One could work around this by using `!important` in her styles, but this isn't a good practice at all.

**Comment by laveesingh** [comment]
Another prop called `appendDots` has been added, and I think that's what you are looking for.
