### ISSUE TITLE
How to make hidden slides untabbable?

### ISSUE THREAD

**Issue by Michaeljdu2010** [akiran/react-slick#912]
Hey there, thanks for the react-slick.  We're making our site WCAG AA compliant for legal reasons, and one of the ask is to have hidden items be untabbable.  Currently slick-slider seems to break this, as items which are off screen in the beginning (namely those with data-index = -1 or lower, which are the cloned items to make scrolling left smoother) are tabbable.  Is there a way to make these untabbable?  Thank you

**Comment by laveesingh** [comment]
Recently, all the slides (including clones, original, hidden, shown) have been made untabbable (a behavior that slick reflects). These changes will be released pretty soon.
