### ISSUE TITLE
infinite + lazyLoad fails to render slide [-1] content

### ISSUE THREAD

**Issue by benpetty** [akiran/react-slick#914]
JS Fiddle:
http://jsfiddle.net/benpetty/k2yc66ec/

When infinite and lazyLoad are both set to true, initial dragging/swiping from slide [0] to slide [-1] does not render slide [-1] content.

It does work if using arrow navigation or if navigating to it from 0, 1, 2, 3 etc.

**Comment by lionel95200x** [comment]
Same problem, have you found solution ?

**Comment by laveesingh** [comment]
infinite + lazyLoad issues have been solved in 0.18.0 and 0.19.0 releases.
