### ISSUE TITLE
Please do not remove the slickGoTo prop!

### ISSUE THREAD

**Issue by ooloth** [akiran/react-slick#915]
I've managed to get Slick's `asNavFor` functionality working between two react-slick sliders. However, this functionality relies on the `slickGoTo` prop (I pass the index of the nav slider to the main slider's `slickGoTo` prop, which creates the nav functionality).

However, in the console, I see the following warning:
`react-slick deprecation warning: slickGoTo prop is deprecated and it will be removed in next release. Use slickGoTo method instead`

Unfortunately, the `slickGoTo` method does not work for coordinating the indexes of two separate sliders that are rendered in different `render()` methods. (In my case, the two sliders are each separate great-grandchildren of the parent component, so `this.refs.main-slider-grandparent.slickGoTo()` doesn't work).

Please do not deprecate the `slickGoTo` property. It works well for simulating `asNavFor`.

**Comment by akiran** [comment]
asNavFor feature will be implemented

**Comment by laveesingh** [comment]
asNavFor has been implemented and will be released soon.
