### ISSUE TITLE
bug: in vertical mode, slides with different height will get an error transform-Y value, see codepen demo

### ISSUE THREAD

**Issue by 2999** [akiran/react-slick#917]
### as the title

* it is dependencies by [antd.Carousel](https://ant.design/components/carousel/), but maybe it has a bug:

* [codepen demo show the bug](https://codepen.io/quanyun/pen/qVxEmW)

![snip20171120_3](https://user-images.githubusercontent.com/1653891/33015527-bdd78fbe-cdb0-11e7-95c2-b0bd828e77c7.png)

**Comment by laveesingh** [comment]
Can you please regenerate the issue with react-slick library only, and not the and-design library? If you do, please feel free to open this issue along with https://github.com/akiran/react-slick/issues/918 and https://github.com/akiran/react-slick/pull/919.
