### ISSUE TITLE
typeError in react-a11y check

### ISSUE THREAD

**Issue by pieded** [akiran/react-slick#92]
if you set `dots: true` then it throws
`Uncaught TypeError: Cannot read property 'children' of undefined`
traceable to
/lib/dots.js:40

**Comment by Wgil** [comment]
Hi,

Can you still reproduce this issue?

I created a hello world app and included the react-a11y package with the basic config but no error received.

Maybe you can share how to reproduce it.

**Comment by laveesingh** [comment]
The issue doesn't exist anymore. Please feel free to request reopen if you disagree.
