### ISSUE TITLE
RTL not working

### ISSUE THREAD

**Issue by rmtngh** [akiran/react-slick#926]
RTL is not working
Here is the fiddle:
[jsFiddle](https://jsfiddle.net/20bumb4g/5181/)

by adding `direction:ltr!important` to the container it will at least show the items but swipe move in wrong direction.

**Comment by ignocide** [comment]
remove 
> dir="rtl"
div.container

I fixed about wrong direction problem 
and send a pull-request, at 11/25

**Comment by rmtngh** [comment]
@ignocide Thanks, somewhere in docs I read it must be added, anyway I tried removing that too, finally I ended up using this, looks more reliable:
[react-id-swiper](https://github.com/kidjp85/react-id-swiper)

**Comment by harishekhar** [comment]
Even for me, I thought this bug is already fixed in new version 0.15.0 but it is still there.

**Comment by laveesingh** [comment]
We received a pr https://github.com/akiran/react-slick/pull/924 fixing similar issues. These changes will be merged shortly. If you think your issue is different, please feel free to reopen the issue
