### ISSUE TITLE
Update of react peer dependencies not reflected in node_modules

### ISSUE THREAD

**Issue by nickspiel** [akiran/react-slick#927]
I can see that the peer dependencies of react and react dom have been updated to support version 16: https://github.com/akiran/react-slick/blob/458da86a5ead079cc4d6365c680ac5eb2cfc8f2c/package.json#L80

However a fresh install of 0.15.4 still complains:
```
"react-slick@0.15.4" has unmet peer dependency "react@^0.14.0 || ^15.0.1".
"react-slick@0.15.4" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.1".
```

When I dive into the node modules folder the package.json does not reflect the changes listed in the link above (peer deps don't support 16).

**Comment by akiran** [comment]
Released a new version with React 16 dependency support 
can you test it

**Comment by nickspiel** [comment]
Tested - all good at version 0.16.0
