### ISSUE TITLE
Enquire js errors out becuase matchMedia not present

### ISSUE THREAD

**Issue by trodrigu** [akiran/react-slick#93]
My error is `matchMedia not present, legacy browsers require a polyfill`
I am running my tests with jest.

**Comment by trodrigu** [comment]
It's specifically happening in the react-responsive-mixin

**Comment by vramana** [comment]
What is the browser that you are targeting?

**Comment by trodrigu** [comment]
Jest ships with jsdom.

**Comment by trodrigu** [comment]
![screen shot 2015-08-03 at 20 12 40](https://cloud.githubusercontent.com/assets/7085664/9052413/047eef6e-3a1c-11e5-98aa-bc250a8a68e4.png)

**Comment by trodrigu** [comment]
Just a snippet from the jest jQuery tutorial at https://facebook.github.io/jest/docs/tutorial-jquery.html

**Comment by vramana** [comment]
I am sorry. But what exactly is the issue here? You are not able to test the slick component in jest, is that correct?

**Comment by trodrigu** [comment]
Correct.  These are the settings for the component.

      var settings = {
      autoplay: true,
      dots: false,
      infinite: true,
      speed: 500,
      rtl: false,
      pauseOnHover: true,/*not working*/
      responsive: [
        {
          breakpoint: 479,
          settings: {
            slidesToScroll: 1,
            slidesToShow: 1
          }
        },
        {
          breakpoint: 767,
          settings: {
            slidesToScroll: 1,
            slidesToShow: 1
          }
        },
        {
          breakpoint: 991,
          settings: {
            slidesToScroll: 1,
            slidesToShow: 6
          }
        },
        {
          breakpoint: 1200,
          settings: {
            slidesToScroll: 1,
            slidesToShow: 6
          }
        },
        {
          breakpoint: 2840,
          settings: {
            slidesToScroll: 1,
            slidesToShow: 6
          }
        }
      ]

**Comment by trodrigu** [comment]
The issue is that enquire js not seeing matchMedia, which is under the react-responsive-mixin.

**Comment by trodrigu** [comment]
Full error is
`Error: /Users/thomas/Sites/design-2-1/server/isomorphic/components/TrendingSlider.js: /Users/thomas/Sites/design-2-1/node_modules/react-slick/lib/index.js: /Users/thomas/Sites/design-2-1/node_modules/react-slick/lib/slider.js: /Users/thomas/Sites/design-2-1/node_modules/react-slick/node_modules/react-responsive-mixin/index.js: /Users/thomas/Sites/design-2-1/node_modules/react-slick/node_modules/react-responsive-mixin/node_modules/enquire.js/dist/enquire.js: matchMedia not present, legacy browsers require a polyfill`

**Comment by trodrigu** [comment]
I found that stubbing it out was the solution because the browser is headless.
[This](https://github.com/WickyNilliams/enquire.js/issues/82) is where I found the answer.  Thanks.

**Comment by fadeojo** [comment]
@trodrigu please where does the stub go? Testcase or component?

**Comment by akiran** [comment]
@fadeojo you should add below jest config in package.json and add test-setup.js file
 https://github.com/akiran/react-slick/blob/master/package.json#L74-L76

https://github.com/akiran/react-slick/blob/master/test-setup.js

**Comment by fadeojo** [comment]
@akiran Thanks, I got it working.

**Comment by yyynnn** [comment]
@akiran Running into the same problem while building to static bundle using "react-static-webpack-plugin". What can be done? While in dev everything works fine.

**Comment by renoiser** [comment]
I have the same problem with react-static-webpack-plugin, @yyynnn did you find a solution?

**Comment by browne0** [comment]
I'm having the same problem @yyynnn how did you resolve this? WOuld love to hear from you @akiran on what to do when building :)

Thanks!
