### ISSUE TITLE
Default arrow image shows for Custom prev/next arrow buttons..

### ISSUE THREAD

**Issue by sanjeevdalvi** [akiran/react-slick#930]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

Hi,

If I use my custom React component which uses icon and pass as prevArrow, nextArrow property, the default arrow image still shows behind my icon image.......ideally the default arrow image you are using should not be shown for custom components....

**Comment by laveesingh** [comment]
I tried doing that and I didn't get anything like that. 
This is what I used:
```
    const prevArrow = <img src='http://www.creativehunt.co/wp-content/uploads/2016/02/Previous-300x300.png' />
    const nextArrow = <img src='http://www.creativehunt.co/wp-content/uploads/2016/02/Next-300x300.png' />
    const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1,
      prevArrow,
      nextArrow
    };
```
And I got very much expected results.
