### ISSUE TITLE
lazyLoad and slidesToScroll/slidesToShow breaks infinite scrolling

### ISSUE THREAD

**Issue by jtl3d** [akiran/react-slick#931]
Demo of issue: http://jsfiddle.net/u93xo1e2/1/

As you can see in the demo, when lazyLoad is set to true, the infinite scroll feature does not work like it should. In the demo, I have 10 slides and show 4 and slide 4 at a time. When it shows the last two slides, the next button should move forward to slides 1-4 but instead goes backward to slides 2-6.

I assume this is a bug but let me know if I'm missing a setting.

**Comment by pbpraveen1988** [comment]
@jtl3d same issue i do have., did you find any solution on this ?

**Comment by jtl3d** [comment]
No... I ended up abandoning lazy load in my case.

**Comment by laveesingh** [comment]
This has been fixed already.
