### ISSUE TITLE
In RTL, Paging stays LTR

### ISSUE THREAD

**Issue by YoniH** [akiran/react-slick#935]
My settings object includes:
```
{
  rtl: true,
  slidesToShow: 4,
  slidesToScroll: 4,
}
```

Now, say I have 9 items. I expect to see 3 pages:
Right: 4 items
Middle: 4 items
Left: 1 item

But what I actually see is 4 items on the right page, then when I click the middle dot, it slides only one item, then when I click the left dot it slides 4 items.
So it looks like internally the pages are set as though it's still ltr:
Right: 1 items
Middle: 4 items
Left: 4 items

It looks like a bug. Is it?

**Comment by laveesingh** [comment]
Thank you @YoniH  for your concern. But this behaviour is the expected behaviour in cases where (totalNoOfSlides % slidesToShow != 0) and not just in the rtl: true case. Please feel free to reopen the issue if you disagree or have more to suggest.

**Comment by zanusilker** [comment]
What is totalNoOfSlides?
