### ISSUE TITLE
Suggestion: Default values in docs

### ISSUE THREAD

**Issue by JikkuJose** [akiran/react-slick#939]
It would be great to provide default value in docs

**Comment by akiran** [comment]
@JikkuJose Can you open a PR with this change?

**Comment by JikkuJose** [comment]
Sure, can you give me some pointer to where I can find the default values?

**Comment by ChuckPierce** [comment]
@JikkuJose default props can be found here: https://github.com/akiran/react-slick/blob/master/src/default-props.js

**Comment by JikkuJose** [comment]
Thanks, just submitted a PR!

**Comment by akiran** [comment]
Merged it
