### ISSUE TITLE
How to support horizontal linear sliding instead of switching?

### ISSUE THREAD

**Issue by hyy1115** [akiran/react-slick#945]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

I want the horizontal slider to be linear and have an inertial motion, but it looks like you only see the paging in your document.

What can I do to support a horizontal linear slide?

This is my configuration option

```javascript
let settings = {
            dots: false,
            infinite: false,
            arrows: false,
            speed: 500,
            slidesToShow: 1,
            slidesToScroll: 1,
            vertical: false
        }
```

**Comment by pbpraveen1988** [comment]
Same issue we are also facing ? any solution for this ?

**Comment by mvpspl619** [comment]
@pbpraveen1988 @hyy1115
I believe this should help:

```
.slick-slider .slick-track {
    transition: transform 0.3s;
}
```

**Comment by hyy1115** [comment]
@mvpspl619 It's late. I've switched to Swiper.
