### ISSUE TITLE
I need slickGoTo method hardly in project. What is the other way around for that ?

### ISSUE THREAD

**Issue by gowthambalashanmugam** [akiran/react-slick#947]
### Guidlines for posting new issue

* Please replicate your issue with this [jsfiddle](https://jsfiddle.net/kirana/20bumb4g/) and provide a link to it along with the issue description

**Comment by aperkaz** [comment]
Hi @gowthambalashanmugam,
A fix has been laying aroung for more than a year now https://github.com/akiran/react-slick/pull/579, but surprisinly hasnt been merged yet...

**Comment by akiran** [comment]
You can use slickGoTo method
https://github.com/akiran/react-slick/blob/master/examples/SlickGoTo.js

**Comment by gowthambalashanmugam** [comment]
@akiran. But combination of slickGoTo and slidesToScroll is not working. Is there any solution for that ? please advice me on #3352

**Comment by gowthambalashanmugam** [comment]
Please have a look on https://github.com/kenwheeler/slick/issues/3352
