### ISSUE TITLE
strict scroll angle in v 0.15.0

### ISSUE THREAD

**Issue by stubar** [akiran/react-slick#948]
Hi 
We have recently upgraded to 0.15.0 and have found that the angle of swipe required to move the slider is very strict, to the point where most swipes don't work.  In 0.14.0 45 degree swipes work easily.  We've be able to get by by rolling back to 0.14.0 or deleting this part
```
    if (!this.props.verticalSwiping && !this.state.swiping && verticalSwipeLength > 4) {
      this.setState({
        scrolling: true
      });
      return;
    }
```
from swipeMove.  Are there any better ways to get back the old behaviour?

**Comment by laveesingh** [comment]
If verticalSwipeLength is greater than 4 units, it is declared as a vertical scroll that's why horizontal scrolling doesn't work. I don't think it has to do anything with angles. Although now this verticalSwipeLength has been increased to 10, so that should improve the experience.
