### ISSUE TITLE
Issues rendering arrows

### ISSUE THREAD

**Issue by Magneticmagnum** [akiran/react-slick#951]
Latest doesn't render arrows for me:

Demo: https://codesandbox.io/s/11k31p2zj

I see other people reporting the same issue, but have closed them without posting a solution.

**Comment by saurishkar** [comment]
@Magneticmagnum It looks like that the background color of the arrows are white, hence they are not visible.
Just add
 ```
button.slick-arrow.slick-prev {
    background-color: black;
}
```
and you will see the previous button on the view.

**Comment by akiran** [comment]
Its a styling issue
using this styles in your codesandbox shows the arrows
```
const styles = {
  fontFamily: "sans-serif",
  textAlign: "center",
  background: "#ccc",
  padding: '50px'
};
```
