### ISSUE TITLE
Content moves to next row if the lazyload is true for bulk records.

### ISSUE THREAD

**Issue by pbpraveen1988** [akiran/react-slick#953]
Hello @akiran ,

Issue is that, if we set the `lazyload` to true and slide element is near about 100 , after few scrolls elements is coming in next row. Below are the settings which i used
`  var settings = {
            dots: false,
            infinite: false,
             speed: 500,
           centerMode: false,
            variableWidth: true,
            slidesToScroll: 3,
            slidesToShow: 10,
        }`

Also has the same issue mentioned in #931.

Any Solution ?

**Comment by laveesingh** [comment]
I'm not getting any such problem as for now. We did some improvements to trackWidth, and I'm assuming we fixed it. Please feel free to reopen if you disagree.
