### ISSUE TITLE
Pre and post clone count

### ISSUE THREAD

**Issue by simonasdev** [akiran/react-slick#956]
I have discovered that there is no way to configure how many clones are render pre and post real slides. For my use case I am using `variableWidth`, `centerMode` and `infinite`, so when showing the first slide, only 2 pre clones are rendered before it (because `slidesToShow + 1 === 2`), as seen here https://jsfiddle.net/2m703gbr/5/. This leads to the fact that there is bunch of whitespace from the left side of the container until the first pre clone (indicated in the fiddle by a red background).
When looking through the source code I have found that I can increase the number of clones by setting `slidesToShow` to a higher number, but then that number of real slides are set as active, so there is no way to distinguish the actually active slide, because `slidesToShow` number of slides have `.slick-active` class.
Ideally, I should be able to specify number of pre/post clones to render, so there is no whitespace in the container. Seems to me that this new prop shouldn't affect anything else and undefined prop value could fall back to current behaviour.
Or is there a way to achieve my desired result without a new prop?

**Comment by akiran** [comment]
pre and post clones are internal implementation details.
That can't be configured.

If there aren't enough clones in a particular mode, it could be bug and it need to be fixed.
You are welcome to open a PR with the fix
