### ISSUE TITLE
Render carousel in component not yet displayed 

### ISSUE THREAD

**Issue by gigaga** [akiran/react-slick#957]
Hi, 

Firstly, thanks for your work! 
If I try to render a carousel in a parent component not yet displayed (bootstrap collapse for example). In this case, the width computed is 0 and when carousel's parent is displayed, the carousel is still incorrect.

**Comment by akiran** [comment]
Can you give code snippet for the issue ?

**Comment by danvernon** [comment]
@akiran @gigaga also have this issue!

**Comment by gigaga** [comment]
@akiran 
Of course: http://jsfiddle.net/w7oh18Lk/6/
In this case, carousel is rendered in a parent not yet visible. When I click on button to display carousel, we can see that the width of slick-track element is incorrect (not computed) :(

**Comment by laveesingh** [comment]
jsfiddle does not work fine with this, if you could regenerate it with codesandbox, please feel free to reopen this.

**Comment by gigaga** [comment]
Why close? I can reproduce it with codesandbox...

**Comment by laveesingh** [comment]
Please provide the link to the demo...

**Comment by gigaga** [comment]
Thanks.
codesandbox link: https://codesandbox.io/s/03jyjy47ln

**Comment by laveesingh** [comment]
Please take a look at this example demo: https://codesandbox.io/s/x26z0lxlpp
I'm using the same old css as with the rest of example demos, and it works as expected.
Please let me know if you have different opinion.

**Comment by gigaga** [comment]
I have the following error :
"Could not find dependency: 'react-collapse'"

**Comment by laveesingh** [comment]
I've already added this dependency, but anyway you can just add the dependency from the left bar.
Or you should be able to access this url: https://x26z0lxlpp.codesandbox.io/

**Comment by gigaga** [comment]
@laveesingh Thanks for that.
In fact, when collapse is managed by React code, there is no problem (render method is reexecuted), but when collapse is managed outside React (in my case by Bootstrap's jQuery), render method is not reexecuted and width/height computed are incorrect.

**Comment by laveesingh** [comment]
I'm not sure if letting jQuery temper with your react components is a good idea. (I get that you're using jquery bootstrap and not react bootstrap). If you're doing so, you have to somehow force React to reconsider updates whenever external events are done. In your case, you could attach an event listener to track your jQuery update, and then force your react component to update by managing some state in your component.

**Comment by laveesingh** [comment]
Also, refer to #1010 if that can help you somehow.

**Comment by gigaga** [comment]
Thx!
