### ISSUE TITLE
Still Does Not Work in React 16 - IS THIS PROJECT IS DEAD?

### ISSUE THREAD

**Issue by dschinkel** [akiran/react-slick#958]
We tried the carousel in React 15 and it works fine.  It still does not work in React 16.  When will this be resolved?  After trying it in a React 16 project it doesn't work.
  
I've gotten no responses to my last two issues so I'm concluding basically that the project as dead coupled with the fact that it's still not working with React 16 and there seems to be no replies from @akiran on any of the new issues it looks like.   Maybe this project should just be closed, we don't have a roadmap, and no responses from @akiran?  Is this dead?   People have asked for this to work in React 16 but doesn't look like there's much going on in here.
  
I don't have time to contribute, so maybe I'll look for another carousel.

**Comment by akiran** [comment]
It already works with react 16.
Have you tried latest version of react-slick ?

**Comment by dschinkel** [comment]
yes and it's not working. We tested this in our react 16 project

<Slider>
        <div><h3>1</h3></div>
        <div><h3>2</h3></div>
        <div><h3>3</h3></div>
        <div><h3>4</h3></div>
        <div><h3>5</h3></div>
        <div><h3>6</h3></div>
      </Slider>

**Comment by dschinkel** [comment]
Please reopen this and don't close things before it's resolved

**Comment by dschinkel** [comment]
The problem was that we had a web project using React v15 and then we import a shared React project of ours that the web also uses.  Well that shared project was the project I upgraded from React v15 to v16.  But you can't run 2 versions of react in the same project so that was causing the `Unable to find node on an unmounted component error`.  I think your component is probably fine, we're upgrading our web project to 16 and I'll report back.

**Comment by dschinkel** [comment]
There's still a problem.  Even though react-slick runs, when I run my mocha tests that excercise code using react-slick I'm still getting this error:

`matchMedia not present, legacy browsers require a polyfill`

**Comment by dschinkel** [comment]
Related

https://github.com/akiran/react-slick/issues/955
https://github.com/akiran/react-slick/issues/645 - October!

**Comment by dschinkel** [comment]
We should not have to add this for YOUR module in OUR projects:

Test Setup
If you try to run tests with jest in a project that uses react-slick, you may run into this error

matchMedia not present, legacy browsers require a polyfill
To fix this issue add below snippet in test-setup.js

window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};

**Comment by dschinkel** [comment]
@akiran I'd like to contribute to your readme and add more info to the section on this fake that will help people who are not using Jest.  Can I do a PR?

**Comment by laveesingh** [comment]
@dschinkel please do, we'd love to merge favourable changes.
