### ISSUE TITLE
slider malfunctions for last item

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#963]
Try these settings with 9 items, the slider gets stuck once for the last element.
```javascript
    const settings = {
      className: 'center',
      centerMode: true,
      infinite: true,
      centerPadding: '60px',
      slidesToShow: 3,
      speed: 500,
      slidesToScroll: 2
    };```

**Comment by magicspon** [comment]
I've got a similar issue:
https://codesandbox.io/s/7mmmly0rv1

last slide does not fully transform into the available area

**Comment by laveesingh** [comment]
That issue is solved way back.

**Comment by magicspon** [comment]
yup... my bad... t'was a flex box issue...

cheers

**Comment by hoangtuan438** [comment]
> That issue is solved way back.

How do you resolve that? I got the same issue. I'm so appreciate if you help me to pass this isse
