### ISSUE TITLE
Infinte slider reset glitch

### ISSUE THREAD

**Issue by BrentonWatt** [akiran/react-slick#966]
It seems that having infinite set to true causes a bug to occur in which after reaching the end of the slides it does not smoothly continue over to a clone but rather glitches back to the first element. The cloned elements are visible but it does not flow over to them. My settings are as follows:

`const settings = {
      dots: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2000,
      pauseOnHover: true,
};`

**Comment by akiran** [comment]
@laveesingh I noticed this issue in Multiple items example in this repo as well.
Can you prioritise this issue

**Comment by akiran** [comment]
Similar issue is reported here as well
https://github.com/akiran/react-slick/issues/557

**Comment by denvasden** [comment]
Looks loke I've got the same issue.

**Comment by laveesingh** [comment]
I am not able to reproduce this anymore. Maybe it got fixed around 8feb5cd. 
If someone is still able to regenerate it, please feel free to suggest reopening the issue.

**Comment by JackBlakeston** [comment]
Hi, I'm currently still getting this bug
