### ISSUE TITLE
Lazy loading wrapping animation is different from other modes

### ISSUE THREAD

**Issue by akiran** [akiran/react-slick#969]
In the lazy load demo, If we click on the next button after last slide is reached, all slides are scrolled left to reach first slide. In other modes, it scrolls one slide right to reach first slide.

@laveesingh  Can you compare the wrapping animation of the library in lazy load with jQuery version

**Comment by laveesingh** [comment]
Yeah, I'll try and check that against the jQuery equivalent.

**Comment by laveesingh** [comment]
fixed
