### ISSUE TITLE
Flex width positive feedback.

### ISSUE THREAD

**Issue by lapanoid** [akiran/react-slick#97]
I encountered some bug while using react-slick with flex boxes.

```
<div style={{display:'flex'}}>
<div style={{display:'flex', flexGrow:1}}>
<Slider {...settings}>
            {caruselItems}
          </Slider>
</div>
<div style={{display:'flex', flexGrow:1}}>
@@@
</div>
</div>
```

First of all that does not fit into screen and if we try to rezise it width grows to infinity. I think that flexboxes and react-slick both dynamically calculate its sizes so it create positive feedback.
Maybe there is some common way to deal with that as there are other react components that dynamically calculate their sizes, so there should be a way to use them with flex boxes, but unfortunatelly I don't know it =(

By the way thanks for this awesome project, best react carusel I have found so far!

**Comment by jeffcatania** [comment]
I am experiencing this same issue.  Any work around found?

**Comment by nslobodchuk** [comment]
+1
I encountered an issue when placing the Slider into a flex with horizontal flow. Didn't find a workaround.

**Comment by nabilfreeman** [comment]
I also had this bug. So brutal.

**Comment by akiran** [comment]
Solution to this problem is mentioned in
https://github.com/kenwheeler/slick/issues/982

its working with the css fix mention in above link. Check the demo
https://jsfiddle.net/kirana/wabv7wLj/
