### ISSUE TITLE
Change autoplay from `false` to `true` not work automatically

### ISSUE THREAD

**Issue by youngBrain1893** [akiran/react-slick#970]
when `props.slickGoTo` didn't change, `initial-state` will not call the `mixins/helpers.update` function, so the `autoPlay` will not work automatically.

https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L99

**Comment by akiran** [comment]
If you are trying to use pause and play slides, you can slickPause and slickPlay methods
https://github.com/akiran/react-slick/blob/master/examples/AutoPlayMethods.js

**Comment by Ram-SR** [comment]
Guys, what is the answer for the question? How to make autoplay work?
