### ISSUE TITLE
Basic fiddle mixed content browser error

### ISSUE THREAD

**Issue by uccio83** [akiran/react-slick#972]
Your basic [fiddle](https://jsfiddle.net/kirana/20bumb4g/) doesn't work anymore.

Chrome error: 
`Mixed Content: The page at 'https://jsfiddle.net/kirana/20bumb4g/' was loaded over HTTPS, but requested an insecure script 'http://reactjs.org/js/jsfiddle-integration-babel.js'. This request has been blocked; the content must be served over HTTPS.`

I tried on Firefox too.

**Comment by laveesingh** [comment]
Okay, we got the issue. We'll soon shift to [Code Sandbox](https://codesandbox.io/) from JSFiddle.

**Comment by laveesingh** [comment]
The demo playground has been updated and will be merged to master very soon.
