### ISSUE TITLE
Lazyload not working with dymamic slides

### ISSUE THREAD

**Issue by uccio83** [akiran/react-slick#973]
I have a Slider with slides rendered from a property array. 
The property is updated asynchronously by a chain of action->reducer->change-redux-state. 

Unfortunately if I activate the option lazyLoad (which is really useful to avoid loading many images at once), the Slider won't increase the number of rendered slides when the state change (when slides are added), resulting in a wrong set of rendered slides. 

I tried to reproduce the problem in a [jsfiddle](http://jsfiddle.net/vdxLqtb8/1/) but I found different problems:  
- every time I add a slide, the slide is actually added but the slider rendering got buggy

The fiddle is different from my application because it is a strong simplification and it uses component state instead of redux, but I hope it is representative enough to help solve my problem. 
Or maybe I'm even trying to use the slick library in a wrong way...

Every help is appreciated.

**Comment by laveesingh** [comment]
solved: d6d5e92629869a0969d4af507ec598376189b91f
