### ISSUE TITLE
Slides disappear as soon as browser resizes in Firefox

### ISSUE THREAD

**Issue by k-mada** [akiran/react-slick#977]
In Firefox, when I resize my browser using the react-slick slider, the slides suddenly disappear. I have replicated the issue here:

https://jsfiddle.net/1ub8pcyL/

I inspected the slider elements, and it looks like when I resize, the inline style on the div with class "slick-track" the translate3d attribute goes crazy with its values. on Firefox, the first value inside translate3d jumps to a crazy value. This doesn't happen for me in Chrome.

`<div class="slick-track" style="opacity: 1; transform: translate3d(-17895600px, 0px, 0px); width: 89478000px;">`

**Comment by laveesingh** [comment]
I tried it in the Firefox, I didn't encounter any such issue. Maybe this is happening just in jsfiddle resizing. Could you try and regenerate it without jsfiddle? If you do, please feel free to reopen the issue.
