### ISSUE TITLE
Is it possible to use a scrollbar with this library?

### ISSUE THREAD

**Issue by scolacur** [akiran/react-slick#978]
I'm trying to display a scrollbar at the bottom of the slider for mobile users in lieu of dots or arrows, to let them know where they are.

If I add 'overflow-x: scroll' to the .slick-list element, a scrollbar appears but there is a lot of extra whitespace at the end of the scrollable area. I was unable to get the fiddle working, but you can replicate this behavior by adding the CSS to any of the examples on http://neostack.com/opensource/react-slick.

I'm not sure why, if infiniteMode is turned off, this extra white space is necessary. Anyone know a way around it?

Possibly related: Looking at trackHelper.js, why is line 27 identical to line 23?

**Comment by laveesingh** [comment]
`.slick-track` element is the one that needs to be scrolled. You can take advantage of that and tweak a bit in your css with that, you might get desired results.
