### ISSUE TITLE
Demo doesn't seem to work on mobile browsers (iOS Chrome and Safari)

### ISSUE THREAD

**Issue by dptoot** [akiran/react-slick#98]
Great port so far!   Really looking forward to using it.

I want to ask about mobile support.  I see in the road map that a swipe and swipeToSlide boolean are road mapped.  Any idea on priority.  I ask as it seems swiping on the Demo page works initially but then causes the carousel to immediately deactivate and is no longer functional.  I thought  it may just be an issue with swiping but it seems the same occurs using the touch controls except in that scenario there isn't even an animation before the cease of function?  

Any ideas or tips?

**Comment by vramana** [comment]
Which demo are you talking about? The online one is too old. Try running it locally.

**Comment by dptoot** [comment]
That's great news!  Would it be a good idea to update the demo with current functionality?  I would hate for people to bypass this component based on false premises.

**Comment by vramana** [comment]
If I get time this weekend, I'll try to put the latest demo using Github Pages.

**Comment by dptoot** [comment]
Sounds great!  Thanks again for the work thus far.
