### ISSUE TITLE
Is it possible to track wether it was a swipe left or a swipe right?

### ISSUE THREAD

**Issue by generalpaulinski** [akiran/react-slick#984]
Is it possible to track wether it was a swipe left or a swipe right?

**Comment by laveesingh** [comment]
Yes, that is possible. That's how the swipeToSlide option works.

**Comment by generalpaulinski** [comment]
thanks for closing. your answer doesn't help me at all!

**Comment by laveesingh** [comment]
@generalpaulinski please refer to [this](https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js#L294-L320) portion of [helpers.js](https://github.com/akiran/react-slick/blob/master/src/mixins/helpers.js)
