### ISSUE TITLE
In case of fade=true, swiping/dragging shows weird behaviour

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#986]
Note: The track is not expected to be swipeable when the fade is true. Also, **probably** multiple items option should be disabled in case of fade.

**Comment by laveesingh** [comment]
fixed by: 611bf6d647c7b3f54179be6e877c295d872c60ba and 9015037ca1155fbfd36220c706368b2c659b9665

**Comment by thuctonhuyen** [comment]
I just migrated from react owl carousel to react-slick. In react owl carousel, the slide can be swappable and draggable when the fade is set to true. Will you support this? Any helps would be greatly appreciated.
