### ISSUE TITLE
`centerMode` doesn't work when `variableWidth` and `lazyLoad` are true

### ISSUE THREAD

**Issue by richardasaurus** [akiran/react-slick#99]
With this config:

```
  dots: false,
  infinite: true,
  speed: 500,
  arrows: true,
  autoplay: false,
  autoplaySpeed: 0,
  slidesToShow: 1,
  slidesToScroll: 1,
  centerMode: true,
  centerPadding: '5px',
  initialSlide: 1,
  touchMove: true,
  lazyLoad: true,
  useCSS: true,
  variableWidth: true
```

 centerMode doesn't work, is there a fix coming for this? Thanks

**Comment by vramana** [comment]
variableWidth is broken completely. It needs a rewrite. I don't have the time currently.

**Comment by richardasaurus** [comment]
Is there an previous release where it does work?

**Comment by vramana** [comment]
No. I don't think so. Centering was broken in previous releases.

**Comment by richardasaurus** [comment]
![http://www.meriahnichols.com/wp-content/uploads/2014/05/picard-ears.jpg](http://www.meriahnichols.com/wp-content/uploads/2014/05/picard-ears.jpg)
AH..the readme should probable contain some notes on what actually works so people don't use non-working features.

**Comment by vramana** [comment]
variableWidth is the only thing that has the issue. I didn't want to remove it. So, I kind of left it unchanged. Rest of them works properly expect for a few safari edge cases with touch events.

**Comment by richardasaurus** [comment]
Sure, but I've spent a bunch of time debugging other areas when the issue was in fact `react-slick`, if there was a note in the readme that could have been avoided :+1:

**Comment by frg** [comment]
Bump for variableWidth fix.

**Comment by Eschon** [comment]
Are there any updates on this?
I use `variableWidth` and it kind of works, the only problem I have is that it always tries to center the active image.

The only way I found to display the active image on the left is to set `infinite` to `false`
