### ISSUE TITLE
sliding happens unexpectedly in case of infinite uneven-set case

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#994]
![uneven-set-infinite-test](https://user-images.githubusercontent.com/8917978/35561355-05a2b352-05d6-11e8-863a-a4a806fa9a2b.gif)

**Comment by yenly** [comment]
Is there any fix or work around to this bug?

**Comment by laveesingh** [comment]
We'll be looking into it now, I'm sure we'll have a fix soon.

**Comment by laveesingh** [comment]
fixed!
