### ISSUE TITLE
slickPause doesn't work

### ISSUE THREAD

**Issue by msalsas** [akiran/react-slick#995]
I'm trying to use the new feature `slickPause`. However it doesn't work.
Before this feature I was changing an `autoPlay` state variable, so that the `autoplay` prop change to false when the slider has to pause.

    // this.state.autoPlay is true by default 
    pauseSlider() {
        this.setState({autoPlay: false});
    }

    ...

    render() {
        const {autoPlay} = this.state;
        const settings = {
            autoplaySpeed: 5000,
            className: 'swiper-wrapper',
            infinite: true,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: false,
            autoplay: autoPlay,
            pauseOnHover: false,
            initialSlide: 1,
            beforeChange: this.beforeChangeSlide,
            afterChange: this.afterChangeSlide
        };

        ...
    }

but the problem was that `autoPlay` to false made to slide one more time (because the `autoPlayTimer` was not cleared). Now, I expect the timer to be cleared when calling `slickPause()`, but it seems to do nothing, as it works the same way as not calling it. I've tried several ways:

### Keeping the above example and calling `this.slider.slickPause()` from `componentDidUpdate()`:

    componentDidUpdate(prevProps, prevState) {
        const {autoPlay} = this.state;
        if (!autoPlay && prevState.autoPlay) {
            this.slider.slickPause();
        }
        // also tried calling `this.slider.slickPlay()` when `autoPlay && !prevState.autoPlay`
    }

### The same as above (with `componentDidUpdate`) but keeping `autoplay` prop to true:

    render() {
        const {autoPlay} = this.state;
        const settings = {
            autoplaySpeed: 5000,
            className: 'swiper-wrapper',
            infinite: true,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: false,
            autoplay: true, // ***
            pauseOnHover: false,
            initialSlide: 1,
            beforeChange: this.beforeChangeSlide,
            afterChange: this.afterChangeSlide
        };

        ...
    }

In this way, it just doesn't stop sliding.

### Calling `this.slider.slickPause()` instead of change state

    pauseSlider() {
        this.slider.slickPause();
    }

Although I need to change the state also for other functionality so actually I change the state:

    pauseSlider() {
        this.slider.slickPause();
        this.setState({foo: 'bar'});
    }

Am I doing something wrong or is it a bug?

**Comment by akiran** [comment]
Its working . you can check this example
https://github.com/akiran/react-slick/blob/master/examples/AutoPlayMethods.js

**Comment by msalsas** [comment]
I thinks that it's because of the changing state. Look at [this example](https://codesandbox.io/s/0ov91n8mql). If you press the button, you will be redirected to slide 3 and the slider should pause. However, after 5 seconds the slider goes to slide 0 before pausing. Also, if you swipe a few slides forward and wait, instead of pressing the button, you will see a weird behaviour, the slides change within different times.

**Comment by akiran** [comment]
@laveesingh We need to clear autoplayTimers when autoPlay is set to false

**Comment by laveesingh** [comment]
I tried replicating it and I found the problem. The `autoplay` prop was available in `props` instead of `this.props` in update mixin. Fixed that, fixed the issue. 817cd797b04e158a70ada4b2f1ea9c2dc98aab9a

The following snippet works for me:
```
import React, { Component } from 'react'
import Slider from '../src/slider'

export default class SimpleSlider extends Component {

  constructor(props) {
    super(props)
    this.state = {
      autoplay: false
    }
  }

  render() {
    const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplaySpeed: 500,
      autoplay: this.state.autoplay
    };
    return (
      <div>
        <h2> Single Item</h2>
        <div>
          <button onClick={() => this.setState({ autoplay: !this.state.autoplay })}> {this.state.autoplay ? 'Playing' : 'Paused' } </button>
        </div>
        <Slider {...settings}>
          <div><h3>1</h3></div>
          <div><h3>2</h3></div>
          <div><h3>3</h3></div>
          <div><h3>4</h3></div>
          <div><h3>5</h3></div>
          <div><h3>6</h3></div>
        </Slider>
      </div>
    );
  }
}
```

**Comment by msalsas** [comment]
@laveesingh Please, look at my [previous comment](https://github.com/akiran/react-slick/issues/995#issuecomment-367307643). It's happening exactly the same with `0.19.0` version.

**Comment by msalsas** [comment]
@akiran @laveesingh Could you reopen the issue?

**Comment by laveesingh** [comment]
@msalsas I long as I remember, slickPause is working perfectly fine. Could you take a look at this [example](https://react-slick.neostack.com/docs/example/auto-play-methods).

**Comment by msalsas** [comment]
@laveesingh Your example works right. Please, look at [this example](https://codesandbox.io/s/0ov91n8mql). If you press the button, you will be redirected to slide 3 and the slider should pause. However, after 5 seconds the slider goes to slide 0 before pausing. Also, if you swipe a few slides forward and wait, instead of pressing the button, you will see a weird behaviour, the slides change within different times.

**Comment by msalsas** [comment]
@laveesingh In your example, you're also changing the state in beforeChange/afterChange hooks (changeUpdateCount/changeSlider). Regarding the second point, I've also tried calling first `slickGoTo` before `slickPause` with the same result. You can check it out by editing the code of the "codesandbox" link.

**Comment by laveesingh** [comment]
@msalsas the point of the example was to see how we're using another wrapper component to use setState in beforeChange hook. I'll try to find another way to the same.
Anyway, what you're trying to achieve can be achieved as follows:
```javascript
<button onClick={() => {
  this.slickGoTo(3)
  setTimeout(this.slickPause, 0)
}}>
 goto slide 3 and pause
</button>
```
I figured two consecutive methods won't work because updates from the first take a bit of time and the second method won't take effect while first is still in progress. I'll look more into it to find something that'd make these methods work without setTimeout.

**Comment by varrant** [comment]
SlickPause doesn't work , it is ok?

**Comment by msalsas** [comment]
@laveesingh I've tried using a timeout and wrapping the `Slider` but neither worked. I've finally disabled `autoplay`, added a `setInterval` with a `slickNext` call in `componentDidMount` and called `clearInterval` when I want to stop the auto-play. I'd  say that you have a bit of mess with timers, because any of the children components of `Slide` could change its state, and timers shouldn't be updated.

**Comment by laveesingh** [comment]
@msalsas Finally, I've managed to solved issues related to autoplay/pause by managing another state in InnerSlider component. Commits like: 466e026, 877c465 and bb5de6a solve the problem.
These changes are currently in dev branch and will be released soon.
