### ISSUE TITLE
Animation is not applied on slickToGo function

### ISSUE THREAD

**Issue by tamnvt** [akiran/react-slick#997]
The function slickToGo is work correctly but there is no animation effects on this. Please help me to check.

**Comment by laveesingh** [comment]
The issue has been taken into consideration, I'll make sure to find out what can be done. Thanks!

**Comment by laveesingh** [comment]
Please check SlickGoTo [example](https://github.com/akiran/react-slick/blob/dev/examples/SlickGoTo.js) from dev branch(will be merged to master soon).
Let me know if you have any queries.
