### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by yzgc** [akiran/react-slick#998]
After reference to `import xx form 'react-slick'`. After modifying the code，webpack Automatic compilation have a problem. Cannot read property 'apply' of undefined, why?????

**Comment by laveesingh** [comment]
Could you please provide the whole snippet or link to the snippet that you're using?

**Comment by yzgc** [comment]
react-router config + webpack :
`export const routes = {
  path: '/',
  getComponent(nextState,cb){
    require.ensure([],require=>{
      cb(null,require('../views/home/App'));
    },'app')
  },
  indexRoute: {
  getComponent(nextState,cb){
    require.ensure([],require=>{
      cb(null,require('../views/home/Home'));
    },'home')
  }
},`
reference  react-slick
`import Slider from 'react-slick'`

If you don't introduce react-slick, compilation will not make a mistake，The component that the error directly causes the routing match is null

**Comment by akiran** [comment]
We can't invest time in reproducing this issue at the moment
Can you provide a repo replicating this issue and re-open it
