### ISSUE TITLE
Problem with one image

### ISSUE THREAD

**Issue by guilima** [akiran/react-slick#999]
In the v0.17.1 when the slick-carousel has only one image the clones aren't generated if `infinite: true`
[CodeSandBox - Example](https://codesandbox.io/s/mm79xmrv1j)

**Comment by hardensky** [comment]
same problem

**Comment by laveesingh** [comment]
The issue has been fixed in dev branch, and will soon be reflected in master. Should be included in 0.18 release hopefully.
